import type { MigrationInterface, QueryRunner } from 'typeorm';

export class AddNodeJsQuestions1773962300000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const questions = [
      // ── Module 1: Node.js Core & Event Loop ──
      { id: 'd4000001-0000-4000-8001-000000000001', moduleId: 'd4000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What is the event loop in Node.js?', choices: ['A loop that processes all synchronous code', 'A mechanism that allows Node.js to perform non-blocking I/O by offloading operations to the OS and processing callbacks when complete', 'A while loop that keeps the process alive', 'A thread pool for parallel execution'], answer: '1', tags: ['event-loop'], explanation: 'The event loop is the core of Node.js\'s concurrency model. It continuously checks if the call stack is empty, then picks callbacks from the event queue and pushes them onto the stack to execute.', docs: 'https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick' } },
      { id: 'd4000001-0000-4000-8001-000000000002', moduleId: 'd4000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What is the difference between process.nextTick() and setImmediate()?', choices: ['They are identical', 'process.nextTick() fires before I/O callbacks in the current iteration; setImmediate() fires in the check phase after I/O', 'setImmediate() is synchronous', 'process.nextTick() is deprecated'], answer: '1', tags: ['event-loop', 'nextTick', 'setImmediate'], explanation: 'process.nextTick() runs callbacks before the event loop continues to the next phase — even before I/O. setImmediate() runs in the check phase after I/O callbacks. nextTick can starve the event loop if recursive.', docs: 'https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick' } },
      { id: 'd4000001-0000-4000-8001-000000000003', moduleId: 'd4000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What is libuv\'s role in Node.js?', choices: ['It provides the V8 JavaScript engine', 'It provides the cross-platform async I/O library including the event loop, thread pool, and OS async API integration', 'It handles HTTP parsing', 'It manages npm packages'], answer: '1', tags: ['libuv', 'internals'], explanation: 'libuv is the C library that powers Node.js\'s event loop, async I/O, timers, and thread pool (for file I/O, DNS, crypto). It abstracts platform differences (epoll on Linux, kqueue on macOS, IOCP on Windows).', docs: 'https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick' } },
      { id: 'd4000001-0000-4000-8001-000000000004', moduleId: 'd4000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What are microtasks in Node.js event loop?', choices: ['Tasks run in a separate thread', 'Callbacks scheduled by Promise.then() and process.nextTick() that run between event loop phases', 'Low-priority background tasks', 'HTTP micro-requests'], answer: '1', tags: ['event-loop', 'microtasks'], explanation: 'Microtasks (Promise .then callbacks, process.nextTick) run after each task completes, before the event loop proceeds to the next phase. They have higher priority than macrotasks (setTimeout, setImmediate).', docs: 'https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick' } },
      { id: 'd4000001-0000-4000-8001-000000000005', moduleId: 'd4000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'In what order do these execute: setTimeout(fn, 0), Promise.resolve().then(fn), process.nextTick(fn)?', choices: ['setTimeout → Promise → nextTick', 'nextTick → Promise → setTimeout', 'Promise → nextTick → setTimeout', 'They run in order of registration'], answer: '1', tags: ['event-loop', 'execution-order'], explanation: 'Order: 1) process.nextTick (highest priority microtask). 2) Promise.then (microtask). 3) setTimeout (macrotask in timer phase). nextTick queue drains completely before Promises; then macrotasks run.', docs: 'https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick' } },
      { id: 'd4000001-0000-4000-8001-000000000006', moduleId: 'd4000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is the Node.js thread pool (libuv) used for?', choices: ['Running all JavaScript code', 'Handling blocking operations: file I/O, DNS lookups, crypto, zlib compression — offloaded from the main thread', 'Running timers', 'Network I/O'], answer: '1', tags: ['thread-pool', 'libuv'], explanation: 'Network I/O uses OS async APIs (no threads needed). Blocking operations like fs.readFile, dns.lookup, crypto.pbkdf2 use libuv\'s thread pool (default 4 threads, configurable via UV_THREADPOOL_SIZE).', docs: 'https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick' } },
      { id: 'd4000001-0000-4000-8001-000000000007', moduleId: 'd4000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'What does "non-blocking I/O" mean in Node.js?', choices: ['I/O never fails', 'I/O operations are initiated and Node.js continues executing other code while waiting for the OS to complete them', 'I/O runs faster than blocking', 'I/O cannot be cancelled'], answer: '1', tags: ['non-blocking', 'io'], explanation: 'Non-blocking I/O: Node starts an I/O operation, registers a callback, and immediately returns. The event loop handles other work. When the OS completes the I/O, the callback is queued for execution.', docs: 'https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick' } },
      { id: 'd4000001-0000-4000-8001-000000000008', moduleId: 'd4000000-0000-4000-8000-000000000001', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which of the following event loop phases process callbacks? (select all that apply)', choices: ['timers (setTimeout/setInterval)', 'poll (I/O callbacks)', 'check (setImmediate)', 'nextTick queue'], answer: '[0,1,2]', tags: ['event-loop', 'phases'], explanation: 'Event loop phases: timers, pending callbacks, idle/prepare, poll (I/O), check (setImmediate), close callbacks. nextTick is a microtask queue processed between phases — not a phase itself.', docs: 'https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick' } },
      { id: 'd4000001-0000-4000-8001-000000000009', moduleId: 'd4000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'What happens when you do a CPU-intensive synchronous operation in Node.js?', choices: ['Node spawns a new thread automatically', 'The event loop is blocked — no I/O callbacks, no timers fire until the operation completes', 'It runs in the thread pool', 'Node.js pauses and resumes'], answer: '1', tags: ['event-loop', 'blocking', 'cpu'], explanation: 'JavaScript runs on a single thread. Synchronous CPU work (like sorting 10M items) blocks the event loop entirely — no other requests can be handled until it completes. Use Worker Threads for CPU-bound work.', docs: 'https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick' } },
      { id: 'd4000001-0000-4000-8001-000000000010', moduleId: 'd4000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'What is the default size of libuv\'s thread pool and how can you change it?', choices: ['2 threads; UV_THREADPOOL_SIZE=n', '4 threads; UV_THREADPOOL_SIZE=n environment variable (max 1024)', '8 threads; --threads CLI flag', '1 thread; not configurable'], answer: '1', tags: ['thread-pool', 'configuration'], explanation: 'Default thread pool size: 4. Set UV_THREADPOOL_SIZE=8 (before Node.js starts) to increase. Maximum is 1024. Increasing helps when many concurrent fs/crypto/dns operations are used.', docs: 'https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick' } },
      { id: 'd4000001-0000-4000-8001-000000000011', moduleId: 'd4000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'What is "starvation" of the event loop and how can process.nextTick cause it?', choices: ['Running out of memory', 'Recursively calling process.nextTick() fills the nextTick queue infinitely, preventing the event loop from ever proceeding to I/O or timers', 'Too many setImmediate calls', 'Too many Promise rejections'], answer: '1', tags: ['event-loop', 'nextTick', 'starvation'], explanation: 'process.nextTick callbacks run before any I/O. If a nextTick callback schedules another nextTick, the event loop never advances — starving I/O callbacks and timers. setImmediate does not have this problem.', docs: 'https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick' } },
      { id: 'd4000001-0000-4000-8001-000000000012', moduleId: 'd4000000-0000-4000-8000-000000000001', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which statements about V8 and Node.js are true? (select all that apply)', choices: ['V8 compiles JavaScript to machine code via JIT', 'V8 provides the garbage collector', 'V8 handles async I/O', 'Node.js adds APIs on top of V8 (fs, http, etc.)'], answer: '[0,1,3]', tags: ['v8', 'nodejs'], explanation: 'V8: JIT compiles JS, manages memory/GC. Node.js wraps V8 and adds: event loop (libuv), file system (fs), networking (http/net), crypto, etc. V8 does not handle async I/O — that\'s libuv\'s job.', docs: 'https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick' } },

      // ── Module 2: CommonJS & ESM ──
      { id: 'd4000002-0000-4000-8001-000000000001', moduleId: 'd4000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What is the difference between require() and import in Node.js?', choices: ['They are identical', 'require() is CommonJS (synchronous, dynamic); import is ESM (static, hoisted, supports tree-shaking)', 'require() is faster always', 'import is only for browsers'], answer: '1', tags: ['commonjs', 'esm'], explanation: 'require() (CJS): synchronous, can be used anywhere in code, dynamic. import (ESM): statically analyzed, hoisted, tree-shakeable, supports top-level await. Both are supported in Node.js.', docs: 'https://nodejs.org/api/modules.html' } },
      { id: 'd4000002-0000-4000-8001-000000000002', moduleId: 'd4000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'How do you enable ES modules in a Node.js project?', choices: ['Use --esm flag', 'Set "type": "module" in package.json or use .mjs extension', 'Use require("esm")', 'ES modules are enabled by default'], answer: '1', tags: ['esm', 'package-json'], explanation: '"type": "module" in package.json makes all .js files treated as ESM. Alternatively, use .mjs extension for ES modules and .cjs for CommonJS. Both can coexist in a project.', docs: 'https://nodejs.org/api/modules.html' } },
      { id: 'd4000002-0000-4000-8001-000000000003', moduleId: 'd4000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What is module.exports in CommonJS?', choices: ['The module\'s file path', 'The object that is returned when another module requires() this module', 'The module\'s metadata', 'The module\'s dependencies'], answer: '1', tags: ['commonjs', 'module-exports'], explanation: 'module.exports is the value returned by require(). By default it\'s an empty object. Assign anything to module.exports — function, class, or object — to export it. exports is a reference to module.exports initially.', docs: 'https://nodejs.org/api/modules.html' } },
      { id: 'd4000002-0000-4000-8001-000000000004', moduleId: 'd4000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What is top-level await in ESM Node.js?', choices: ['Using await inside async functions', 'Using await directly at the module top level without wrapping in async function — only valid in ES modules', 'Using await in CommonJS', 'A polyfill for older Node.js'], answer: '1', tags: ['esm', 'top-level-await'], explanation: 'Top-level await (Node.js 14.8+, ESM only) allows await at the module root: const data = await fetchConfig(). The module pauses until resolved before dependents can import it.', docs: 'https://nodejs.org/en/learn/asynchronous-work/javascript-asynchronous-programming-and-callbacks' } },
      { id: 'd4000002-0000-4000-8001-000000000005', moduleId: 'd4000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'What are circular dependencies in Node.js and what problem do they cause?', choices: ['Two modules importing each other — may result in partially-loaded empty objects when one module is not yet fully initialized', 'A runtime crash always', 'Only a problem in ESM', 'Only affect performance'], answer: '0', tags: ['commonjs', 'circular-dependencies'], explanation: 'Circular: A requires B, B requires A. When A loads B and B requires A, A is only partially initialized. The part of A loaded before the circular require is available; the rest is undefined — causing subtle bugs.', docs: 'https://nodejs.org/api/modules.html' } },
      { id: 'd4000002-0000-4000-8001-000000000006', moduleId: 'd4000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'How do you create a dual CJS/ESM package (supports both require() and import)?', choices: ['Use two separate packages', 'Use "exports" field in package.json with "require" and "import" conditions pointing to different entry files', 'Use a Babel transform', 'Use .mjs files only'], answer: '1', tags: ['esm', 'dual-package', 'exports'], explanation: 'package.json "exports": { ".": { "import": "./dist/index.mjs", "require": "./dist/index.cjs" } } creates a dual package. Build tools (tsup, rollup) can generate both formats from a single source.', docs: 'https://nodejs.org/api/modules.html' } },
      { id: 'd4000002-0000-4000-8001-000000000007', moduleId: 'd4000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'What does the "exports" field in package.json do?', choices: ['Lists npm dependencies', 'Defines the public API of the package — which files can be imported and under what conditions', 'Sets the entry point only', 'Replaces the "main" field completely'], answer: '1', tags: ['package-json', 'exports'], explanation: '"exports" controls which files are importable from outside the package. It supports conditions (import/require/browser/node), subpath exports, and blocks access to internal files not listed.', docs: 'https://nodejs.org/api/modules.html' } },
      { id: 'd4000002-0000-4000-8001-000000000008', moduleId: 'd4000000-0000-4000-8000-000000000002', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which are differences between CJS and ESM in Node.js? (select all that apply)', choices: ['ESM is statically analyzable; CJS is dynamic', 'ESM supports tree-shaking; CJS does not', 'CJS has __dirname and __filename; ESM uses import.meta.url', 'ESM require() syntax works the same as CJS'], answer: '[0,1,2]', tags: ['commonjs', 'esm', 'differences'], explanation: 'ESM is statically analyzed (tree-shakeable), CJS is dynamic. ESM uses import.meta.url instead of __dirname. ESM does NOT use require() — that syntax is CJS only (use import instead).', docs: 'https://nodejs.org/api/modules.html' } },
      { id: 'd4000002-0000-4000-8001-000000000009', moduleId: 'd4000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'In ESM, how do you get the equivalent of __dirname?', choices: ['global.__dirname', 'import.meta.dirname (Node 21.2+) or path.dirname(fileURLToPath(import.meta.url))', 'process.cwd()', '__filename'], answer: '1', tags: ['esm', '__dirname'], explanation: 'ESM does not have __dirname. Use: import { fileURLToPath } from "url"; import { dirname } from "path"; const __dirname = dirname(fileURLToPath(import.meta.url)). Node 21.2+ adds import.meta.dirname directly.', docs: 'https://nodejs.org/api/modules.html' } },
      { id: 'd4000002-0000-4000-8001-000000000010', moduleId: 'd4000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'What is module caching in Node.js CommonJS?', choices: ['Modules are compiled once and cached in require.cache — subsequent require() calls return the cached export without re-executing', 'Files are cached on disk', 'Module results are stored in Redis', 'Only built-in modules are cached'], answer: '0', tags: ['commonjs', 'caching'], explanation: 'Node.js caches loaded modules in require.cache. The module code runs only once; subsequent require() calls return the same exported object. Delete require.cache[key] to force re-load (rarely needed).', docs: 'https://nodejs.org/api/modules.html' } },
      { id: 'd4000002-0000-4000-8001-000000000011', moduleId: 'd4000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'Can you use require() in an ES module file in Node.js?', choices: ['Yes, always', 'No by default — ESM files cannot use require(). Use createRequire from "module" to create a require function if needed', 'Yes with --allow-require flag', 'Only for built-in modules'], answer: '1', tags: ['esm', 'require', 'interop'], explanation: 'ESM files (type:module or .mjs) cannot use require() directly. import.meta.url provides the module URL. Use createRequire(import.meta.url) to create a CJS-compatible require function for loading CJS modules.', docs: 'https://nodejs.org/api/modules.html' } },
      { id: 'd4000002-0000-4000-8001-000000000012', moduleId: 'd4000000-0000-4000-8000-000000000002', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which of the following are available in ESM but NOT CJS Node.js? (select all that apply)', choices: ['import.meta.url', 'Top-level await', 'Static import analysis', '__dirname'], answer: '[0,1,2]', tags: ['esm', 'features'], explanation: 'ESM-only: import.meta.url (module URL), top-level await, static imports (tree-shakeable). __dirname is CJS-only. ESM gets the equivalent via path.dirname(fileURLToPath(import.meta.url)).', docs: 'https://nodejs.org/api/modules.html' } },

      // ── Module 3: File System & Streams ──
      { id: 'd4000003-0000-4000-8001-000000000001', moduleId: 'd4000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What is the difference between fs.readFile and fs.createReadStream?', choices: ['They are identical', 'readFile loads the entire file into memory; createReadStream reads it in chunks, suitable for large files', 'createReadStream is synchronous', 'readFile only works with text files'], answer: '1', tags: ['fs', 'streams'], explanation: 'readFile loads all bytes into memory at once — fine for small files, problematic for large ones. createReadStream reads in chunks (default 64KB), keeping memory usage constant regardless of file size.', docs: 'https://nodejs.org/api/fs.html' } },
      { id: 'd4000003-0000-4000-8001-000000000002', moduleId: 'd4000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What is backpressure in Node.js streams?', choices: ['Memory pressure from large files', 'When a writable stream cannot consume data fast enough, the readable stream must pause to avoid buffer overflow', 'A security mechanism', 'CPU pressure from stream processing'], answer: '1', tags: ['streams', 'backpressure'], explanation: 'Backpressure: readable.pipe(writable) handles it automatically. Manual handling: check writable.write() return value — false means buffer is full. Listen to "drain" event before writing more.', docs: 'https://nodejs.org/api/fs.html' } },
      { id: 'd4000003-0000-4000-8001-000000000003', moduleId: 'd4000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What does fs/promises API provide compared to the callback-based fs API?', choices: ['Faster file operations', 'Promise-based versions of all fs functions that work with async/await', 'Only works with streams', 'It is a completely different module'], answer: '1', tags: ['fs', 'promises'], explanation: 'import { readFile, writeFile } from "fs/promises" provides Promise-returning versions of all fs operations. Use with async/await instead of callbacks. Same functionality, cleaner code.', docs: 'https://nodejs.org/api/fs.html' } },
      { id: 'd4000003-0000-4000-8001-000000000004', moduleId: 'd4000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What is a Transform stream in Node.js?', choices: ['A stream that transforms the OS', 'A duplex stream that reads input, transforms it, and outputs the result — e.g., compression, encryption', 'A stream that moves files', 'A unidirectional stream'], answer: '1', tags: ['streams', 'transform'], explanation: 'Transform streams implement both Readable and Writable. Data flows in, gets modified, and flows out. Examples: zlib.createGzip() (compress), crypto.createCipher() (encrypt), CSV parsing.', docs: 'https://nodejs.org/api/fs.html' } },
      { id: 'd4000003-0000-4000-8001-000000000005', moduleId: 'd4000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'What is the pipeline() function in Node.js streams?', choices: ['A CI/CD pipeline', 'stream.pipeline(source, ...transforms, destination, callback) that pipes streams together and handles error/cleanup automatically', 'An alternative to require()', 'A way to connect databases'], answer: '1', tags: ['streams', 'pipeline'], explanation: 'pipeline() from "stream" (or stream/promises for async) chains streams and properly handles errors and cleanup in all cases — unlike pipe() which can leak resources on error.', docs: 'https://nodejs.org/api/fs.html' } },
      { id: 'd4000003-0000-4000-8001-000000000006', moduleId: 'd4000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is the difference between Buffer and Uint8Array in Node.js?', choices: ['They are unrelated', 'Buffer extends Uint8Array with additional Node.js-specific methods (toString, copy, etc.) and is the standard for binary data in Node.js', 'Uint8Array is faster', 'Buffer is deprecated'], answer: '1', tags: ['buffer', 'binary'], explanation: 'Buffer is a subclass of Uint8Array. It adds Node.js-specific methods like toString(encoding), copy(), concat(), and slice(). Modern Node.js APIs accept both types; prefer Buffer for Node.js code.', docs: 'https://nodejs.org/api/fs.html' } },
      { id: 'd4000003-0000-4000-8001-000000000007', moduleId: 'd4000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'What does fs.watch() do compared to fs.watchFile()?', choices: ['They are identical', 'fs.watch() uses OS-level inotify/FSEvents (efficient, event-driven); fs.watchFile() polls the file stat (less efficient, more portable)', 'fs.watchFile() is newer', 'fs.watch() is synchronous'], answer: '1', tags: ['fs', 'watch'], explanation: 'fs.watch() uses OS file-watching events — very efficient. fs.watchFile() polls using stat() at an interval — more portable but higher CPU cost. fs.watch() is preferred; libraries like chokidar wrap both for reliability.', docs: 'https://nodejs.org/api/fs.html' } },
      { id: 'd4000003-0000-4000-8001-000000000008', moduleId: 'd4000000-0000-4000-8000-000000000003', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which stream types exist in Node.js? (select all that apply)', choices: ['Readable', 'Writable', 'Duplex', 'Transform'], answer: '[0,1,2,3]', tags: ['streams', 'types'], explanation: 'Node.js streams: Readable (produce data), Writable (consume data), Duplex (both read and write independently, like TCP socket), Transform (read-modify-write, like compression).', docs: 'https://nodejs.org/api/fs.html' } },
      { id: 'd4000003-0000-4000-8001-000000000009', moduleId: 'd4000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'What is the highWaterMark option in Node.js streams?', choices: ['Maximum file size', 'The buffer threshold (in bytes for binary, objects for object mode) above which the stream signals backpressure', 'The CPU high water mark', 'A stream timeout'], answer: '1', tags: ['streams', 'highWaterMark'], explanation: 'highWaterMark defines the buffer size. Readable: stop reading from source when buffered bytes exceed it. Writable: write() returns false when internal buffer exceeds it — triggering backpressure.', docs: 'https://nodejs.org/api/fs.html' } },
      { id: 'd4000003-0000-4000-8001-000000000010', moduleId: 'd4000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'How do you convert a Node.js stream to an async iterable?', choices: ['stream.toIterable()', 'Streams implement the async iterable protocol — use for await...of (stream)', 'promisify(stream)', 'stream.on("data") with async callback'], answer: '1', tags: ['streams', 'async-iterator'], explanation: 'Node.js readable streams implement the AsyncIterable protocol. Use: for await (const chunk of readableStream) { ... }. This is the modern clean API for consuming streams.', docs: 'https://nodejs.org/api/fs.html' } },
      { id: 'd4000003-0000-4000-8001-000000000011', moduleId: 'd4000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'How do you implement a custom Transform stream?', choices: ['Extend Transform and implement _read()', 'Extend Transform and implement _transform(chunk, encoding, callback) and optionally _flush(callback)', 'Implement a ReadableStream factory', 'Use stream.Writable with piping'], answer: '1', tags: ['streams', 'transform', 'custom'], explanation: '_transform(chunk, encoding, callback) processes each chunk. Call callback(null, transformedChunk) or this.push(transformedChunk); callback(). _flush(callback) is called when the source ends to emit any buffered output.', docs: 'https://nodejs.org/api/fs.html' } },
      { id: 'd4000003-0000-4000-8001-000000000012', moduleId: 'd4000000-0000-4000-8000-000000000003', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which are advantages of streaming over buffering for large files? (select all that apply)', choices: ['Constant memory usage regardless of file size', 'Faster time-to-first-byte (starts processing before full file loads)', 'Supports backpressure', 'Always faster total throughput'], answer: '[0,1,2]', tags: ['streams', 'advantages'], explanation: 'Streams: constant memory (no OOM for large files), lower latency (process first chunk immediately), backpressure support. Total throughput is not always faster — buffering can be faster for small files due to overhead.', docs: 'https://nodejs.org/api/fs.html' } },

      // ── Module 4: Async Patterns ──
      { id: 'd4000004-0000-4000-8001-000000000001', moduleId: 'd4000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What is "callback hell" in Node.js?', choices: ['Too many event listeners', 'Deeply nested callbacks making code hard to read and maintain — also called "pyramid of doom"', 'Memory leaks from callbacks', 'Infinite callback loops'], answer: '1', tags: ['callbacks', 'async'], explanation: 'Callback hell: fs.readFile(file, (err, data) => { db.query(data, (err, result) => { http.post(result, (err) => { ... }) }) }). Solutions: Promises, async/await, or libraries like async.js.', docs: 'https://nodejs.org/en/learn/asynchronous-work/javascript-asynchronous-programming-and-callbacks' } },
      { id: 'd4000004-0000-4000-8001-000000000002', moduleId: 'd4000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What does Promise.all() do?', choices: ['Runs promises sequentially', 'Runs all promises concurrently and resolves with an array of all results when all resolve, or rejects immediately if any reject', 'Returns the first resolved promise', 'Ignores rejections'], answer: '1', tags: ['promises', 'Promise.all'], explanation: 'Promise.all([p1, p2, p3]) runs concurrently. Resolves with [r1, r2, r3] when all succeed. Rejects with the first rejection reason immediately — "fail fast".', docs: 'https://nodejs.org/en/learn/asynchronous-work/javascript-asynchronous-programming-and-callbacks' } },
      { id: 'd4000004-0000-4000-8001-000000000003', moduleId: 'd4000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What is util.promisify() used for?', choices: ['Converting promises to callbacks', 'Converting Node.js callback-style functions (err-first) into Promise-returning functions', 'Creating new Promises', 'Debugging async code'], answer: '1', tags: ['promisify', 'callbacks'], explanation: 'util.promisify(fn) wraps a callback-style function: const readFile = promisify(fs.readFile); const data = await readFile("file.txt"). Works with standard error-first callbacks.', docs: 'https://nodejs.org/en/learn/asynchronous-work/javascript-asynchronous-programming-and-callbacks' } },
      { id: 'd4000004-0000-4000-8001-000000000004', moduleId: 'd4000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What is the difference between Promise.allSettled() and Promise.all()?', choices: ['No difference', 'allSettled() waits for all promises to complete (fulfilled or rejected) and never short-circuits; all() rejects immediately on first rejection', 'allSettled() is faster', 'all() handles rejections silently'], answer: '1', tags: ['promises', 'Promise.allSettled'], explanation: 'Promise.all() fails fast on first rejection. Promise.allSettled() waits for all — returns [{status:"fulfilled",value}, {status:"rejected",reason}]. Use allSettled() when you want all results regardless of failures.', docs: 'https://nodejs.org/en/learn/asynchronous-work/javascript-asynchronous-programming-and-callbacks' } },
      { id: 'd4000004-0000-4000-8001-000000000005', moduleId: 'd4000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'What is Promise.race() and when is it useful?', choices: ['Cancels slower promises', 'Resolves/rejects with the first promise to settle — useful for timeouts: Promise.race([fetch(url), timeout(5000)])', 'Runs promises in race condition', 'Returns a random promise'], answer: '1', tags: ['promises', 'Promise.race', 'timeout'], explanation: 'Promise.race([p, timeout]) creates a timeout pattern: if the fetch doesn\'t resolve within 5s, the timeout promise rejects first. The "winner" determines the race result.', docs: 'https://nodejs.org/en/learn/asynchronous-work/javascript-asynchronous-programming-and-callbacks' } },
      { id: 'd4000004-0000-4000-8001-000000000006', moduleId: 'd4000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is an async generator in Node.js?', choices: ['A Generator that is asynchronous', 'An async function* that yields values asynchronously — consumed with for await...of', 'A Promise that generates values', 'A stream alternative'], answer: '1', tags: ['async-generator', 'iterators'], explanation: 'async function* gen() { yield await fetch(url1); yield await fetch(url2); } for await (const data of gen()) { ... }. Useful for lazy async sequences — paginated APIs, file line-by-line reading.', docs: 'https://nodejs.org/en/learn/asynchronous-work/javascript-asynchronous-programming-and-callbacks' } },
      { id: 'd4000004-0000-4000-8001-000000000007', moduleId: 'd4000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'What is the difference between Promise.any() and Promise.race()?', choices: ['They are identical', 'any() resolves with the first fulfilled promise (ignoring rejections); race() resolves/rejects with the first settled promise regardless of outcome', 'any() is deprecated', 'race() ignores rejections'], answer: '1', tags: ['promises', 'Promise.any'], explanation: 'Promise.any() resolves with first success, only rejects if ALL reject (AggregateError). Promise.race() resolves or rejects with whichever settles first — including rejections.', docs: 'https://nodejs.org/en/learn/asynchronous-work/javascript-asynchronous-programming-and-callbacks' } },
      { id: 'd4000004-0000-4000-8001-000000000008', moduleId: 'd4000000-0000-4000-8000-000000000004', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which Promise combinators are available in modern Node.js? (select all that apply)', choices: ['Promise.all()', 'Promise.allSettled()', 'Promise.race()', 'Promise.any()'], answer: '[0,1,2,3]', tags: ['promises', 'combinators'], explanation: 'All four are standard: all() (fail-fast concurrency), allSettled() (wait all), race() (first settled), any() (first fulfilled). Know their differences for real-world use cases.', docs: 'https://nodejs.org/en/learn/asynchronous-work/javascript-asynchronous-programming-and-callbacks' } },
      { id: 'd4000004-0000-4000-8001-000000000009', moduleId: 'd4000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'How do you run async tasks with a concurrency limit in Node.js?', choices: ['Promise.all() with a limit parameter', 'Manually batch with chunks of Promise.all() or use libraries like p-limit', 'Node.js handles this automatically', 'Set UV_THREADPOOL_SIZE'], answer: '1', tags: ['async', 'concurrency', 'rate-limiting'], explanation: 'p-limit(5) creates a limiter: const limit = pLimit(5); await Promise.all(urls.map(url => limit(() => fetch(url)))). Or batch: process chunks of N with sequential Promise.all().', docs: 'https://nodejs.org/en/learn/asynchronous-work/javascript-asynchronous-programming-and-callbacks' } },
      { id: 'd4000004-0000-4000-8001-000000000010', moduleId: 'd4000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'What is an unhandled Promise rejection and how do you handle it globally?', choices: ['Use try/catch', 'Listen to process.on("unhandledRejection", handler) to catch Promise rejections without .catch()', 'Use --unhandled-rejections=throw', 'Both process.on and --unhandled-rejections are valid'], answer: '3', tags: ['promises', 'error-handling', 'unhandledRejection'], explanation: 'Both are valid: process.on("unhandledRejection", (reason, promise) => { ... }) for programmatic handling. --unhandled-rejections=throw (default in Node 15+) makes unhandled rejections crash the process.', docs: 'https://nodejs.org/en/learn/asynchronous-work/javascript-asynchronous-programming-and-callbacks' } },
      { id: 'd4000004-0000-4000-8001-000000000011', moduleId: 'd4000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'How does async/await differ from .then() chains in terms of error handling?', choices: ['They are identical', 'async/await uses try/catch which catches both synchronous and async errors; .then chains need .catch() at the end', 'async/await is slower', '.then() chains are safer'], answer: '1', tags: ['async-await', 'error-handling'], explanation: 'try/catch with await catches both sync throws and async rejections uniformly. .then().catch() only catches Promise rejections. async/await code is also more readable and debuggable.', docs: 'https://nodejs.org/en/learn/asynchronous-work/javascript-asynchronous-programming-and-callbacks' } },
      { id: 'd4000004-0000-4000-8001-000000000012', moduleId: 'd4000000-0000-4000-8000-000000000004', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which of the following are valid patterns for sequential async execution? (select all that apply)', choices: ['for...of loop with await', 'await in a for loop', 'Array.reduce with Promises', 'Promise.all() (runs concurrently, not sequentially)'], answer: '[0,1,2]', tags: ['async', 'sequential'], explanation: 'Sequential: for...of with await, for loop with await, reduce((promise, item) => promise.then(() => process(item)), Promise.resolve()). Promise.all() is concurrent — not sequential.', docs: 'https://nodejs.org/en/learn/asynchronous-work/javascript-asynchronous-programming-and-callbacks' } },

      // ── Module 5: HTTP & REST with Express ──
      { id: 'd4000005-0000-4000-8001-000000000001', moduleId: 'd4000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What is middleware in Express.js?', choices: ['A database adapter', 'A function with (req, res, next) signature that processes requests in a pipeline, calling next() to pass to the next middleware', 'An authentication module', 'A routing mechanism'], answer: '1', tags: ['express', 'middleware'], explanation: 'Express middleware: (req, res, next) => { process(req); next(); }. Chain multiple middleware. If next() is not called, the request is "stuck". Error middleware has 4 params: (err, req, res, next).', docs: 'https://expressjs.com/en/starter/hello-world.html' } },
      { id: 'd4000005-0000-4000-8001-000000000002', moduleId: 'd4000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What HTTP status code should a successful POST that creates a resource return?', choices: ['200 OK', '201 Created', '204 No Content', '202 Accepted'], answer: '1', tags: ['http', 'rest', 'status-codes'], explanation: '201 Created: resource was created. Return it with a Location header. 200 OK: general success. 204 No Content: success with no body (DELETE/PUT). 202 Accepted: async processing started.', docs: 'https://expressjs.com/en/starter/hello-world.html' } },
      { id: 'd4000005-0000-4000-8001-000000000003', moduleId: 'd4000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'How do you parse JSON request bodies in Express?', choices: ['bodyParser.json()', 'express.json() middleware', 'req.json()', 'JSON.parse(req.body)'], answer: '1', tags: ['express', 'body-parsing'], explanation: 'app.use(express.json()) adds body parsing middleware. express.json() is built into Express 4.16+. It sets req.body to the parsed JSON object.', docs: 'https://expressjs.com/en/starter/hello-world.html' } },
      { id: 'd4000005-0000-4000-8001-000000000004', moduleId: 'd4000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What is the difference between app.use() and app.get() in Express?', choices: ['They are identical', 'app.use() matches any HTTP method and any path prefix; app.get() matches only GET requests at a specific path', 'app.use() is for static files only', 'app.get() is deprecated'], answer: '1', tags: ['express', 'routing'], explanation: 'app.use("/api", router) matches all HTTP methods for paths starting with /api. app.get("/users", handler) only matches GET /users exactly.', docs: 'https://expressjs.com/en/starter/hello-world.html' } },
      { id: 'd4000005-0000-4000-8001-000000000005', moduleId: 'd4000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'How do you handle async errors in Express 5 vs Express 4?', choices: ['Same in both', 'Express 5: async middleware errors are automatically passed to error handlers; Express 4: you must manually call next(err) in catch blocks', 'Express 4 is async by default', 'Express 5 removes error middleware'], answer: '1', tags: ['express', 'async', 'error-handling'], explanation: 'Express 4: async errors must be caught and passed: async (req, res, next) => { try { ... } catch(e) { next(e) } }. Express 5 auto-propagates rejected promises, eliminating try/catch boilerplate.', docs: 'https://expressjs.com/en/starter/hello-world.html' } },
      { id: 'd4000005-0000-4000-8001-000000000006', moduleId: 'd4000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is the purpose of Express Router?', choices: ['To handle HTTP routing at OS level', 'To create modular, mountable route handlers that can be mounted on an Express app at a specific path', 'To cache routes', 'To validate request paths'], answer: '1', tags: ['express', 'router'], explanation: 'express.Router() creates a mini Express app. Define routes on it, then app.use("/api/users", userRouter). Enables modular code organization — separate router files per resource.', docs: 'https://expressjs.com/en/starter/hello-world.html' } },
      { id: 'd4000005-0000-4000-8001-000000000007', moduleId: 'd4000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'What does CORS stand for and why is it needed?', choices: ['Cross-Origin Resource Security', 'Cross-Origin Resource Sharing — a browser security policy that restricts cross-origin HTTP requests, requiring server headers to allow them', 'Content-Origin Resource Server', 'Cross-Origin Request Security'], answer: '1', tags: ['cors', 'security'], explanation: 'Browsers block cross-origin requests by default (Same-Origin Policy). CORS headers (Access-Control-Allow-Origin, etc.) on the server tell browsers to allow specific origins. Use the cors npm package in Express.', docs: 'https://expressjs.com/en/starter/hello-world.html' } },
      { id: 'd4000005-0000-4000-8001-000000000008', moduleId: 'd4000000-0000-4000-8000-000000000005', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which of the following are RESTful API best practices? (select all that apply)', choices: ['Use nouns for resource paths (/users, /posts)', 'Use HTTP verbs (GET, POST, PUT, DELETE) for operations', 'Return appropriate HTTP status codes', 'Put all operations in POST requests'], answer: '[0,1,2]', tags: ['rest', 'best-practices'], explanation: 'REST best practices: noun-based resource URLs, HTTP verbs for actions (GET=read, POST=create, PUT=update, DELETE=delete), appropriate status codes. Using only POST for all operations violates REST principles.', docs: 'https://expressjs.com/en/starter/hello-world.html' } },
      { id: 'd4000005-0000-4000-8001-000000000009', moduleId: 'd4000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'How do you implement rate limiting in an Express API?', choices: ['Manually count requests in memory', 'Use express-rate-limit middleware with Redis store for distributed limiting', 'Use Node.js cluster', 'Use a load balancer only'], answer: '1', tags: ['express', 'rate-limiting'], explanation: 'express-rate-limit: const limiter = rateLimit({ windowMs: 15*60*1000, max: 100 }); app.use(limiter). For distributed systems, use a Redis store (rate-limit-redis) to share state across instances.', docs: 'https://expressjs.com/en/starter/hello-world.html' } },
      { id: 'd4000005-0000-4000-8001-000000000010', moduleId: 'd4000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'What is request validation and what library is commonly used with Express?', choices: ['Validating the HTTP version', 'Checking that req.body/params/query match expected schemas — zod or joi are popular libraries', 'Validating SSL certificates', 'Checking Content-Type headers'], answer: '1', tags: ['express', 'validation'], explanation: 'Validate incoming data with zod (TypeScript-first) or joi: const schema = z.object({ name: z.string() }); const result = schema.safeParse(req.body). Use middleware to validate consistently across routes.', docs: 'https://expressjs.com/en/starter/hello-world.html' } },
      { id: 'd4000005-0000-4000-8001-000000000011', moduleId: 'd4000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'What is the helmet middleware package for Express?', choices: ['A headless browser for testing', 'Sets secure HTTP response headers (Content-Security-Policy, X-Frame-Options, etc.) to protect against common web vulnerabilities', 'Provides HTTPS support', 'A request logging middleware'], answer: '1', tags: ['express', 'security', 'helmet'], explanation: 'helmet() sets: Content-Security-Policy, X-DNS-Prefetch-Control, X-Frame-Options, Strict-Transport-Security, X-Content-Type-Options, etc. A single app.use(helmet()) adds ~14 security headers.', docs: 'https://expressjs.com/en/starter/hello-world.html' } },
      { id: 'd4000005-0000-4000-8001-000000000012', moduleId: 'd4000000-0000-4000-8000-000000000005', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which of the following are valid Express error handling patterns? (select all that apply)', choices: ['4-parameter error middleware: (err, req, res, next) => { ... }', 'try/catch with next(err) in async handlers (Express 4)', 'Global process.on("uncaughtException") only', 'Automatic async error propagation in Express 5'], answer: '[0,1,3]', tags: ['express', 'error-handling'], explanation: 'Express error handling: 4-param middleware (must be last), try/catch with next(err) in Express 4, auto-propagation in Express 5. process.on("uncaughtException") is for truly unhandled errors — not Express errors.', docs: 'https://expressjs.com/en/starter/hello-world.html' } },
    ];

    for (const q of questions) {
      await queryRunner.query(
        `INSERT INTO "qcm_question" ("id", "moduleId", "type", "difficulty", "sortOrder", "data")
         VALUES ($1, $2, $3, $4, $5, $6)
         ON CONFLICT ("id") DO NOTHING`,
        [q.id, q.moduleId, q.type, q.difficulty, q.sortOrder, q.data]
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const ids: string[] = [];
    for (let m = 1; m <= 5; m++) {
      for (let q = 1; q <= 12; q++) {
        ids.push(`d400000${m}-0000-4000-8001-${String(q).padStart(12, '0')}`);
      }
    }
    await queryRunner.query(`DELETE FROM "qcm_question" WHERE "id" = ANY($1)`, [ids]);
  }
}
