import type { MigrationInterface, QueryRunner } from 'typeorm';

export class AddAngular19Questions1773962000000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const questions = [
      // ── Module 1: Standalone Components & the Angular CLI ──
      { id: 'a1000001-0000-4000-8001-000000000001', moduleId: 'a1000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What decorator marks an Angular component as standalone?', choices: ['@NgModule({ standalone: true })', '@Component({ standalone: true })', '@Standalone()', '@Injectable({ standalone: true })'], answer: '1', tags: ['standalone', 'components'], explanation: 'Setting standalone: true in @Component makes the component self-contained — it no longer needs to be declared in an NgModule. This is the default recommended approach in Angular 19.', docs: 'https://angular.dev/guide/components/importing' } },
      { id: 'a1000001-0000-4000-8001-000000000002', moduleId: 'a1000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'Which CLI command generates a new standalone Angular 19 application?', choices: ['ng new my-app', 'ng new my-app --no-modules', 'ng new my-app --standalone', 'ng generate app my-app'], answer: '0', tags: ['cli', 'standalone'], explanation: 'As of Angular 17+, ng new my-app generates a standalone application by default — no AppModule is created. The --standalone flag is no longer needed because standalone is the default.', docs: 'https://angular.dev/tools/cli/setup-local' } },
      { id: 'a1000001-0000-4000-8001-000000000003', moduleId: 'a1000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'In a standalone Angular app, where do you bootstrap the root component?', choices: ['In AppModule\'s bootstrap array', 'In main.ts using bootstrapApplication()', 'In index.html using <app-root>', 'In angular.json under "bootstrap"'], answer: '1', tags: ['standalone', 'bootstrap'], explanation: 'bootstrapApplication(AppComponent, appConfig) in main.ts replaces the old NgModule bootstrap. appConfig holds providers that were previously in AppModule.', docs: 'https://angular.dev/reference/configs/app-config' } },
      { id: 'a1000001-0000-4000-8001-000000000004', moduleId: 'a1000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What build tool does Angular 19 use by default instead of Webpack?', choices: ['Vite', 'Rollup', 'esbuild (via the Angular application builder)', 'Parcel'], answer: '2', tags: ['cli', 'build', 'esbuild'], explanation: 'Angular 17+ adopted esbuild as the default bundler via the @angular-devkit/build-angular:application builder, giving significantly faster build times compared to the legacy Webpack-based builder.', docs: 'https://angular.dev/tools/cli/build' } },
      { id: 'a1000001-0000-4000-8001-000000000005', moduleId: 'a1000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'How do you import a standalone component into another standalone component?', choices: ['Add it to the declarations array', 'Add it to the imports array of @Component', 'Use forwardRef() inside the constructor', 'Register it in AppModule'], answer: '1', tags: ['standalone', 'imports'], explanation: 'Standalone components use the imports array directly inside @Component to declare their dependencies (other components, directives, pipes). There is no declarations array for standalone components.', docs: 'https://angular.dev/guide/components/importing' } },
      { id: 'a1000001-0000-4000-8001-000000000006', moduleId: 'a1000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is the purpose of the provideRouter() function in a standalone Angular app?', choices: ['It creates a new Router instance', 'It replaces RouterModule.forRoot() when configuring routing in bootstrapApplication()', 'It generates route files automatically', 'It wraps all routes in a lazy-loaded module'], answer: '1', tags: ['routing', 'standalone', 'providers'], explanation: 'provideRouter(routes) is the standalone-compatible alternative to importing RouterModule.forRoot(). It is passed in the providers array of bootstrapApplication() or appConfig.', docs: 'https://angular.dev/api/router/provideRouter' } },
      { id: 'a1000001-0000-4000-8001-000000000007', moduleId: 'a1000000-0000-4000-8000-000000000001', type: 'multiple', difficulty: 'medium', sortOrder: 6, data: { question: 'Which of the following are valid ways to provide a service in a standalone Angular 19 app? (select all that apply)', choices: ['@Injectable({ providedIn: \'root\' })', 'providers array in bootstrapApplication()', 'providers array in @Component', 'declarations array in @Component'], answer: '[0,1,2]', tags: ['di', 'providers', 'standalone'], explanation: 'Services can be provided at root level with providedIn: \'root\', at app level in bootstrapApplication providers, or scoped to a component via the component\'s own providers array. The declarations array is not for services.', docs: 'https://angular.dev/guide/di/dependency-injection' } },
      { id: 'a1000001-0000-4000-8001-000000000008', moduleId: 'a1000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 7, data: { question: 'What does the ng generate component --inline-template CLI flag do?', choices: ['Generates the component without a CSS file', 'Generates the component with the template inside the @Component decorator instead of a separate .html file', 'Generates a standalone component', 'Generates a component with no constructor'], answer: '1', tags: ['cli', 'components'], explanation: '--inline-template (or -t) puts the template string directly in the templateUrl equivalent inside the decorator, avoiding a separate .html file. Useful for small components.', docs: 'https://angular.dev/tools/cli/schematics' } },
      { id: 'a1000001-0000-4000-8001-000000000009', moduleId: 'a1000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'When migrating a legacy NgModule-based app to standalone in Angular 19, which schematic helps automate the migration?', choices: ['ng update @angular/core --migrate-only standalone', 'ng generate @angular/core:standalone', 'ng migrate standalone --all', 'ng add @angular/standalone'], answer: '1', tags: ['migration', 'standalone', 'schematics'], explanation: 'The ng generate @angular/core:standalone schematic automates the conversion of components/directives/pipes to standalone and can also remove unnecessary NgModules in subsequent runs.', docs: 'https://angular.dev/reference/migrations/standalone' } },
      { id: 'a1000001-0000-4000-8001-000000000010', moduleId: 'a1000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'What is the role of ApplicationConfig in a standalone Angular 19 app?', choices: ['It defines environment variables for the build', 'It provides the root injector configuration (providers) passed to bootstrapApplication()', 'It configures the HTTP interceptors only', 'It replaces angular.json for build settings'], answer: '1', tags: ['standalone', 'config', 'providers'], explanation: 'ApplicationConfig is a typed interface for the configuration object ({ providers: [...] }) passed as the second argument to bootstrapApplication(). It centralises all root-level providers previously held by AppModule.', docs: 'https://angular.dev/reference/configs/app-config' } },
      { id: 'a1000001-0000-4000-8001-000000000011', moduleId: 'a1000000-0000-4000-8000-000000000001', type: 'multiple', difficulty: 'hard', sortOrder: 10, data: { question: 'Which of the following statements about standalone components are TRUE in Angular 19? (select all that apply)', choices: ['They can still be imported into NgModules', 'They cannot use dependency injection', 'They use the imports array instead of declarations', 'They are the default when using ng new'], answer: '[0,2,3]', tags: ['standalone', 'components'], explanation: 'Standalone components CAN be imported into NgModules for backward compatibility. They fully support DI. They use imports[] for their dependencies and are the default since Angular 17.', docs: 'https://angular.dev/guide/components/importing' } },
      { id: 'a1000001-0000-4000-8001-000000000012', moduleId: 'a1000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 11, data: { question: 'What is the purpose of importProvidersFrom() in a standalone Angular app?', choices: ['It lazily imports components', 'It converts NgModule providers to standalone-compatible providers for use in bootstrapApplication()', 'It imports CSS from external libraries', 'It wraps a component in a module boundary'], answer: '1', tags: ['standalone', 'providers', 'migration'], explanation: 'importProvidersFrom(SomeModule) extracts the providers from an NgModule so they can be used in the standalone providers array. Useful when migrating libraries that still use NgModules.', docs: 'https://angular.dev/api/core/importProvidersFrom' } },

      // ── Module 2: Signals & Reactivity ──
      { id: 'a1000002-0000-4000-8001-000000000001', moduleId: 'a1000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'How do you create a writable signal in Angular 19?', choices: ['new Signal(0)', 'signal(0)', 'createSignal(0)', 'ref(0)'], answer: '1', tags: ['signals'], explanation: 'signal(initialValue) from @angular/core creates a WritableSignal. You read its value by calling it as a function: count() and update it with count.set(1) or count.update(v => v + 1).', docs: 'https://angular.dev/guide/signals' } },
      { id: 'a1000002-0000-4000-8001-000000000002', moduleId: 'a1000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'How do you derive a read-only value from one or more signals?', choices: ['effect()', 'computed()', 'derived()', 'watch()'], answer: '1', tags: ['signals', 'computed'], explanation: 'computed(() => expression) creates a memoized, lazily-evaluated signal that automatically updates when its signal dependencies change. It is read-only — you cannot call .set() on it.', docs: 'https://angular.dev/guide/signals#computed-signals' } },
      { id: 'a1000002-0000-4000-8001-000000000003', moduleId: 'a1000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What is the purpose of effect() in Angular signals?', choices: ['To create a new signal', 'To run a side-effect whenever its signal dependencies change', 'To memoize a computed value', 'To subscribe to an Observable'], answer: '1', tags: ['signals', 'effect'], explanation: 'effect(() => { ... }) schedules a reactive side-effect that re-runs whenever any signal read inside it changes. It is not for deriving values — use computed() for that.', docs: 'https://angular.dev/guide/signals#effects' } },
      { id: 'a1000002-0000-4000-8001-000000000004', moduleId: 'a1000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'How do you declare a component input as a signal in Angular 19?', choices: ['@Input() name = signal(\'\')', 'input<string>()', 'signalInput()', '@SignalInput() name!: string'], answer: '1', tags: ['signals', 'input'], explanation: 'input<T>() and input.required<T>() from @angular/core declare signal-based inputs. The value is read as a signal: this.name() inside the component, replacing the older @Input() decorator.', docs: 'https://angular.dev/guide/signals/inputs' } },
      { id: 'a1000002-0000-4000-8001-000000000005', moduleId: 'a1000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'What does signal.update() do compared to signal.set()?', choices: ['update() accepts a new value directly; set() uses a function', 'update() accepts a function that receives the current value; set() accepts a new value directly', 'update() is asynchronous; set() is synchronous', 'They are identical'], answer: '1', tags: ['signals'], explanation: 'set(value) replaces the signal value directly. update(fn) takes a pure function receiving the current value and returning the new one — useful for increment patterns: count.update(v => v + 1).', docs: 'https://angular.dev/guide/signals#writable-signals' } },
      { id: 'a1000002-0000-4000-8001-000000000006', moduleId: 'a1000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is linkedSignal() introduced in Angular 19?', choices: ['A signal that links two components together', 'A writable signal whose default value is derived from other signals and resets when dependencies change', 'An alias for computed()', 'A signal factory for creating multiple signals at once'], answer: '1', tags: ['signals', 'linkedSignal'], explanation: 'linkedSignal({ source, computation }) creates a writable signal whose initial/reset value is derived from source signals. When source changes, the signal resets. Unlike computed(), it remains writable.', docs: 'https://angular.dev/guide/signals/linked-signal' } },
      { id: 'a1000002-0000-4000-8001-000000000007', moduleId: 'a1000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'What does the resource() API in Angular 19 provide?', choices: ['A way to load CSS resources lazily', 'An async signal-based primitive for data fetching that exposes value, status, and error signals', 'A replacement for HttpClient', 'A caching layer for computed signals'], answer: '1', tags: ['signals', 'resource'], explanation: 'resource({ request, loader }) creates an async resource tied to signals. It exposes .value(), .status(), .error(), and .isLoading() signals, enabling reactive async data fetching without RxJS.', docs: 'https://angular.dev/guide/signals/resource' } },
      { id: 'a1000002-0000-4000-8001-000000000008', moduleId: 'a1000000-0000-4000-8000-000000000002', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which of the following are true about computed() signals? (select all that apply)', choices: ['They are lazily evaluated', 'They are read-only', 'They can call .set() to update their value', 'They automatically track signal dependencies'], answer: '[0,1,3]', tags: ['signals', 'computed'], explanation: 'computed() signals are lazy (only recalculated when read after a dependency changes) and read-only. They cannot be set manually. They automatically track any signal accessed during their computation function.', docs: 'https://angular.dev/guide/signals#computed-signals' } },
      { id: 'a1000002-0000-4000-8001-000000000009', moduleId: 'a1000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'How do you declare a two-way bindable signal input in Angular 19?', choices: ['@TwoWayInput()', 'model()', 'signal() with [(ngModel)]', 'input() with output()'], answer: '1', tags: ['signals', 'model', 'two-way-binding'], explanation: 'model() creates a ModelSignal which supports two-way binding via [(name)] syntax. It combines an input signal and an output EventEmitter (nameChange) automatically.', docs: 'https://angular.dev/guide/signals/model' } },
      { id: 'a1000002-0000-4000-8001-000000000010', moduleId: 'a1000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'What happens if you write to a signal inside a computed() function?', choices: ['The signal is updated but the computed is not re-evaluated', 'Angular throws a runtime error — signal writes inside computed() are not allowed', 'The computed value is cleared', 'Angular silently ignores the write'], answer: '1', tags: ['signals', 'computed'], explanation: 'Writing to a signal inside computed() is forbidden and throws an error. computed() must be a pure derivation. Side-effects and mutations should be performed inside effect() or event handlers.', docs: 'https://angular.dev/guide/signals#computed-signals' } },
      { id: 'a1000002-0000-4000-8001-000000000011', moduleId: 'a1000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'How do you convert an RxJS Observable into a signal in Angular 19?', choices: ['signal.from(observable$)', 'toSignal(observable$)', 'observable$.toSignal()', 'fromObservable(observable$)'], answer: '1', tags: ['signals', 'rxjs', 'interop'], explanation: 'toSignal(observable$) from @angular/core/rxjs-interop wraps an Observable in a signal. The signal updates synchronously with each emitted value. An initialValue option can be provided to avoid undefined.', docs: 'https://angular.dev/guide/rxjs-interop' } },
      { id: 'a1000002-0000-4000-8001-000000000012', moduleId: 'a1000000-0000-4000-8000-000000000002', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which of the following are valid ways to use output() in Angular 19 signal-based APIs? (select all that apply)', choices: ['output<string>()', 'output()', 'outputFromObservable(obs$)', '@Output() myEvent = new EventEmitter()'], answer: '[0,1,2,3]', tags: ['signals', 'output'], explanation: 'output() and output<T>() create typed signal-based outputs. outputFromObservable() wraps an Observable as an output. The classic @Output() EventEmitter still works and is valid. All four are valid in Angular 19.', docs: 'https://angular.dev/guide/signals/outputs' } },

      // ── Module 3: New Template Control Flow ──
      { id: 'a1000003-0000-4000-8001-000000000001', moduleId: 'a1000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'Which syntax replaces *ngIf in Angular 17+ template control flow?', choices: ['#if', '@if', '<ng-if>', '{#if}'], answer: '1', tags: ['control-flow', 'template'], explanation: '@if (condition) { ... } @else { ... } is the new built-in control flow syntax. It is more readable, supports @else if branches, and does not require importing NgIf.', docs: 'https://angular.dev/guide/templates/control-flow' } },
      { id: 'a1000003-0000-4000-8001-000000000002', moduleId: 'a1000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What replaces *ngFor in the new Angular control flow?', choices: ['@forEach', '@repeat', '@for', '@loop'], answer: '2', tags: ['control-flow', 'for'], explanation: '@for (item of items; track item.id) { ... } replaces *ngFor. The track expression is mandatory and replaces trackBy. It improves reconciliation performance.', docs: 'https://angular.dev/guide/templates/control-flow#for-block' } },
      { id: 'a1000003-0000-4000-8001-000000000003', moduleId: 'a1000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'In the new @for block, what is the purpose of track?', choices: ['It adds CSS tracking classes to elements', 'It identifies each item uniquely to optimise DOM reconciliation', 'It enables animations on list items', 'It is optional metadata for debugging'], answer: '1', tags: ['control-flow', 'for', 'track'], explanation: 'track is mandatory in @for and works like trackBy in *ngFor. It tells Angular how to identify items to minimise DOM mutations when the list changes. Use a unique property like item.id.', docs: 'https://angular.dev/guide/templates/control-flow#for-block' } },
      { id: 'a1000003-0000-4000-8001-000000000004', moduleId: 'a1000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What replaces [ngSwitch] in the new Angular control flow?', choices: ['@switch / @case / @default', '@match / @when', '#switch', '@select'], answer: '0', tags: ['control-flow', 'switch'], explanation: '@switch (expr) { @case (val) { ... } @default { ... } } replaces the verbose [ngSwitch] / *ngSwitchCase combination. It is more concise and does not require importing NgSwitch.', docs: 'https://angular.dev/guide/templates/control-flow#switch-block' } },
      { id: 'a1000003-0000-4000-8001-000000000005', moduleId: 'a1000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'How do you expose the loop index in the new @for block?', choices: ['(item, index) of items', '; let i = $index', 'track $index', '; index as i'], answer: '1', tags: ['control-flow', 'for'], explanation: '@for supports contextual variables via ; let varName = $variable. Available variables include $index, $count, $first, $last, $even, $odd.', docs: 'https://angular.dev/guide/templates/control-flow#for-block' } },
      { id: 'a1000003-0000-4000-8001-000000000006', moduleId: 'a1000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What block renders when a @for list is empty?', choices: ['@empty', '@else', '@fallback', '@default'], answer: '0', tags: ['control-flow', 'for', 'empty'], explanation: '@for (item of items; track item.id) { ... } @empty { <p>No items</p> } — the @empty block renders automatically when the items collection is empty, replacing the previous workaround of *ngIf with empty checks.', docs: 'https://angular.dev/guide/templates/control-flow#for-block' } },
      { id: 'a1000003-0000-4000-8001-000000000007', moduleId: 'a1000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'What CLI command migrates existing *ngIf/*ngFor/*ngSwitch to the new control flow syntax?', choices: ['ng update --control-flow', 'ng generate @angular/core:control-flow', 'ng migrate control-flow', 'ng add @angular/new-syntax'], answer: '1', tags: ['control-flow', 'migration', 'cli'], explanation: 'ng generate @angular/core:control-flow runs the Angular schematic that automatically converts structural directives to the new built-in @if / @for / @switch syntax across the entire project.', docs: 'https://angular.dev/reference/migrations/control-flow' } },
      { id: 'a1000003-0000-4000-8001-000000000008', moduleId: 'a1000000-0000-4000-8000-000000000003', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which contextual variables are available inside an @for block? (select all that apply)', choices: ['$index', '$first', '$last', '$key'], answer: '[0,1,2]', tags: ['control-flow', 'for'], explanation: '@for exposes $index, $count, $first, $last, $even, $odd. There is no $key variable — that belongs to other frameworks. Use ; let i = $index to access them.', docs: 'https://angular.dev/guide/templates/control-flow#for-block' } },
      { id: 'a1000003-0000-4000-8001-000000000009', moduleId: 'a1000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'What is the key performance difference between the new @for and the old *ngFor?', choices: ['@for supports async pipes natively', '@for uses a more efficient diffing algorithm internally, and the mandatory track removes the need for a separate trackBy function', '@for renders items in parallel', '@for is compiled to native browser loops'], answer: '1', tags: ['control-flow', 'for', 'performance'], explanation: 'The new @for built-in block uses an improved reconciliation algorithm and makes track mandatory (equivalent to trackBy) inline, resulting in up to 90% faster re-renders for large lists compared to *ngFor.', docs: 'https://angular.dev/guide/templates/control-flow' } },
      { id: 'a1000003-0000-4000-8001-000000000010', moduleId: 'a1000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'Can the new @if / @for / @switch blocks be used inside NgModule-based components?', choices: ['No, they only work in standalone components', 'Yes, they work in any Angular 17+ component regardless of whether it is standalone or in an NgModule', 'Only after importing ControlFlowModule', 'Only in components using OnPush change detection'], answer: '1', tags: ['control-flow', 'ngmodule'], explanation: 'The new control flow syntax is a compiler feature, not a directive — it works in all Angular 17+ templates, whether standalone or NgModule-based, without any import.', docs: 'https://angular.dev/guide/templates/control-flow' } },
      { id: 'a1000003-0000-4000-8001-000000000011', moduleId: 'a1000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'In the new @if block, how do you alias the truthy expression result to a template variable?', choices: ['@if (user$ | async; let user)', '@if (user(); as user)', '@if (user()) { as u }', '@if (getUser(); let u)'], answer: '1', tags: ['control-flow', 'if', 'alias'], explanation: '@if (expr; as varName) { ... } captures the truthy result as varName inside the block, similar to *ngIf="obs$ | async as val". This avoids re-evaluating the expression.', docs: 'https://angular.dev/guide/templates/control-flow' } },
      { id: 'a1000003-0000-4000-8001-000000000012', moduleId: 'a1000000-0000-4000-8000-000000000003', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which of the following are advantages of the new built-in control flow over structural directives? (select all that apply)', choices: ['No need to import NgIf / NgFor / NgSwitch', 'Better type narrowing in @if blocks', 'Mandatory track for @for improves performance', 'They support native async/await inside the block'], answer: '[0,1,2]', tags: ['control-flow', 'advantages'], explanation: 'The built-in blocks do not require any import, provide improved TypeScript type narrowing (e.g., after @if the type is narrowed), and enforce track for lists. They do not support native async/await — use async pipe or signals for async data.', docs: 'https://angular.dev/guide/templates/control-flow' } },

      // ── Module 4: Deferrable Views & Performance ──
      { id: 'a1000004-0000-4000-8001-000000000001', moduleId: 'a1000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What is the purpose of the @defer block in Angular?', choices: ['To delay API calls', 'To lazily load a chunk of the template (and its dependencies) only when a trigger condition is met', 'To defer change detection', 'To postpone form validation'], answer: '1', tags: ['defer', 'performance'], explanation: '@defer lazy-loads the template block and all its standalone component/directive/pipe dependencies. The dependencies are code-split into a separate JS chunk downloaded only when needed.', docs: 'https://angular.dev/guide/templates/defer' } },
      { id: 'a1000004-0000-4000-8001-000000000002', moduleId: 'a1000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'Which block renders while the @defer chunk is being downloaded?', choices: ['@fallback', '@loading', '@pending', '@skeleton'], answer: '1', tags: ['defer', 'loading'], explanation: '@loading { ... } renders while the lazy chunk is being fetched. It supports minimum and after parameters to avoid loading flash: @loading (minimum 500ms; after 100ms) { ... }.', docs: 'https://angular.dev/guide/templates/defer#loading-block' } },
      { id: 'a1000004-0000-4000-8001-000000000003', moduleId: 'a1000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'Which block renders before the @defer block has started loading?', choices: ['@loading', '@placeholder', '@idle', '@waiting'], answer: '1', tags: ['defer', 'placeholder'], explanation: '@placeholder renders immediately as a cheap substitute before the lazy chunk starts downloading. Unlike @loading, it is shown before the fetch begins.', docs: 'https://angular.dev/guide/templates/defer#placeholder-block' } },
      { id: 'a1000004-0000-4000-8001-000000000004', moduleId: 'a1000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'Which @defer trigger loads the block when the browser is idle?', choices: ['on viewport', 'on idle', 'on hover', 'on timer(0)'], answer: '1', tags: ['defer', 'triggers'], explanation: 'on idle uses requestIdleCallback to load the chunk when the browser has no higher-priority work. It is the default trigger when none is specified.', docs: 'https://angular.dev/guide/templates/defer#on-idle' } },
      { id: 'a1000004-0000-4000-8001-000000000005', moduleId: 'a1000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'What does the "on viewport" @defer trigger do?', choices: ['Loads the chunk when the component is scrolled into the visible viewport using IntersectionObserver', 'Loads when the viewport is resized', 'Loads when the user has a large viewport', 'Loads when the entire page is in view'], answer: '0', tags: ['defer', 'triggers', 'viewport'], explanation: 'on viewport defers loading until an element (by default the @placeholder) enters the viewport. An optional template reference variable can target a specific element: on viewport(triggerRef).', docs: 'https://angular.dev/guide/templates/defer#on-viewport' } },
      { id: 'a1000004-0000-4000-8001-000000000006', moduleId: 'a1000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'How do you prefetch a @defer block without rendering it yet?', choices: ['@defer (prefetch on idle)', '@defer (on idle; prefetch on hover)', 'prefetch @defer', '@defer (preload on hover)'], answer: '1', tags: ['defer', 'prefetch'], explanation: 'The prefetch trigger is separate from the render trigger: @defer (on interaction; prefetch on idle) means start downloading on idle but only render when the user interacts.', docs: 'https://angular.dev/guide/templates/defer#prefetching' } },
      { id: 'a1000004-0000-4000-8001-000000000007', moduleId: 'a1000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'What is incremental hydration in Angular 19?', choices: ['Hydrating one component at a time during SSR', 'Selectively hydrating parts of an SSR-rendered page using @defer triggers instead of hydrating the full app at once', 'A polyfill for older browsers', 'A way to hydrate animations incrementally'], answer: '1', tags: ['hydration', 'ssr', 'defer'], explanation: 'Incremental hydration (stable in Angular 19) lets you annotate SSR-rendered sections with @defer triggers (e.g., on viewport) so Angular only downloads and hydrates that component tree when the trigger fires.', docs: 'https://angular.dev/guide/incremental-hydration' } },
      { id: 'a1000004-0000-4000-8001-000000000008', moduleId: 'a1000000-0000-4000-8000-000000000004', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which of the following are valid @defer triggers in Angular 19? (select all that apply)', choices: ['on idle', 'on viewport', 'on hover', 'on scroll'], answer: '[0,1,2]', tags: ['defer', 'triggers'], explanation: 'Valid built-in triggers are: on idle, on viewport, on interaction, on hover, on immediate, on timer(). There is no built-in "on scroll" trigger. You can use when (condition) for custom signal-based triggers.', docs: 'https://angular.dev/guide/templates/defer#triggers' } },
      { id: 'a1000004-0000-4000-8001-000000000009', moduleId: 'a1000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'What constraint applies to components used inside a @defer block?', choices: ['They must be decorated with @Deferrable()', 'They must be standalone — non-standalone components cannot be deferred', 'They cannot use dependency injection', 'They must have OnPush change detection'], answer: '1', tags: ['defer', 'standalone'], explanation: 'Only standalone components, directives, and pipes can be lazily loaded by @defer. NgModule-declared components cannot be deferred because they lack independent code-splitting boundaries.', docs: 'https://angular.dev/guide/templates/defer' } },
      { id: 'a1000004-0000-4000-8001-000000000010', moduleId: 'a1000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'How does the @error block differ from @placeholder in @defer?', choices: ['@error renders if the lazy chunk download fails; @placeholder renders before loading starts', '@error renders during loading; @placeholder renders on success', 'They are interchangeable', '@error is for HTTP errors; @placeholder is for component errors'], answer: '0', tags: ['defer', 'error'], explanation: '@placeholder renders before the fetch begins (initial cheap UI). @error renders if the lazy chunk fails to load (network error, etc.). Both are optional companion blocks for @defer.', docs: 'https://angular.dev/guide/templates/defer#error-block' } },
      { id: 'a1000004-0000-4000-8001-000000000011', moduleId: 'a1000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'How do you use a signal-based condition as a @defer trigger?', choices: ['on signal(mySignal)', 'when mySignal()', 'if mySignal()', 'trigger(mySignal)'], answer: '1', tags: ['defer', 'signals', 'when'], explanation: 'when (expression) accepts any truthy expression, including signal reads: @defer (when isLoggedIn()) { ... }. The block loads as soon as the expression becomes truthy.', docs: 'https://angular.dev/guide/templates/defer#when-condition' } },
      { id: 'a1000004-0000-4000-8001-000000000012', moduleId: 'a1000000-0000-4000-8000-000000000004', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which of the following are performance benefits of using @defer blocks? (select all that apply)', choices: ['Reduces initial bundle size by code-splitting lazy sections', 'Delays hydration of SSR content until needed', 'Eliminates all JavaScript for deferred components permanently', 'Reduces Largest Contentful Paint by prioritising visible content'], answer: '[0,1,3]', tags: ['defer', 'performance'], explanation: '@defer reduces initial bundle size (code splitting), enables incremental hydration (delayed hydration), and improves LCP by only loading critical content first. The deferred JS is still downloaded eventually — it is not eliminated.', docs: 'https://angular.dev/guide/templates/defer' } },

      // ── Module 5: Dependency Injection & inject() ──
      { id: 'a1000005-0000-4000-8001-000000000001', moduleId: 'a1000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What does the inject() function replace in Angular 19?', choices: ['The @NgModule decorator', 'Constructor-based dependency injection', 'The HttpClient service', 'The Router service'], answer: '1', tags: ['di', 'inject'], explanation: 'inject(Token) can be used in the injection context (field initializer, constructor, factory function) to inject dependencies without declaring them as constructor parameters. It enables cleaner functional DI.', docs: 'https://angular.dev/api/core/inject' } },
      { id: 'a1000005-0000-4000-8001-000000000002', moduleId: 'a1000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What decorator marks a class as injectable in Angular?', choices: ['@Injectable()', '@Service()', '@Provide()', '@Inject()'], answer: '0', tags: ['di', 'injectable'], explanation: '@Injectable() marks a class as a candidate for DI. providedIn: \'root\' makes it a singleton available app-wide without needing to add it to any providers array.', docs: 'https://angular.dev/api/core/Injectable' } },
      { id: 'a1000005-0000-4000-8001-000000000003', moduleId: 'a1000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What is an injection token used for in Angular?', choices: ['To authenticate API requests', 'To provide and inject non-class values (strings, objects, configs) into the DI system', 'To mark a class as singleton', 'To create lazy-loaded providers'], answer: '1', tags: ['di', 'injection-token'], explanation: 'InjectionToken<T> creates a typed DI token for non-class values. Example: const API_URL = new InjectionToken<string>(\'API_URL\'). You then use inject(API_URL) to retrieve it.', docs: 'https://angular.dev/api/core/InjectionToken' } },
      { id: 'a1000005-0000-4000-8001-000000000004', moduleId: 'a1000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What does providedIn: "root" mean on an @Injectable?', choices: ['The service is only available in the root component', 'The service is tree-shakeable and provided as a singleton in the root injector', 'The service must be manually added to AppModule', 'The service is eagerly loaded at startup'], answer: '1', tags: ['di', 'injectable', 'singleton'], explanation: 'providedIn: \'root\' registers the service in the root injector lazily. If no component injects it, it is tree-shaken from the bundle. It is the recommended default for services.', docs: 'https://angular.dev/guide/di/dependency-injection' } },
      { id: 'a1000005-0000-4000-8001-000000000005', moduleId: 'a1000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'How do you create a functional route guard in Angular 19?', choices: ['Implement CanActivate interface', 'Return a function from @Injectable', 'Use inject() inside a plain function: (route, state) => inject(AuthService).isLoggedIn()', 'Use @Guard() decorator'], answer: '2', tags: ['di', 'guards', 'functional'], explanation: 'Functional guards are plain functions that use inject() inside them. They return true/false/UrlTree/Observable. Example: export const authGuard: CanActivateFn = () => inject(AuthService).isLoggedIn();', docs: 'https://angular.dev/api/router/CanActivateFn' } },
      { id: 'a1000005-0000-4000-8001-000000000006', moduleId: 'a1000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is an environment injector in Angular?', choices: ['An injector only available in development mode', 'An injector that exists outside of the component tree, enabling DI in non-component contexts', 'The root injector alias', 'An injector for environment variable tokens'], answer: '1', tags: ['di', 'environment-injector'], explanation: 'EnvironmentInjector exists outside the component hierarchy. runInInjectionContext(environmentInjector, fn) lets you use inject() inside non-component code like interceptors, guards, and factory functions.', docs: 'https://angular.dev/api/core/EnvironmentInjector' } },
      { id: 'a1000005-0000-4000-8001-000000000007', moduleId: 'a1000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'What is the difference between providedIn: "root" and providing a service in a component\'s providers array?', choices: ['No difference — both create singletons', 'providedIn: "root" creates a single app-wide instance; component providers create a new instance scoped to that component subtree', 'Component providers are not tree-shakeable', 'providedIn: "root" is deprecated in Angular 19'], answer: '1', tags: ['di', 'scopes'], explanation: 'When provided in a component, a new service instance is created for that component and its descendants. This enables component-level isolation. Root-provided services share one instance across the entire app.', docs: 'https://angular.dev/guide/di/hierarchical-dependency-injection' } },
      { id: 'a1000005-0000-4000-8001-000000000008', moduleId: 'a1000000-0000-4000-8000-000000000005', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'In which contexts is inject() valid in Angular 19? (select all that apply)', choices: ['Class field initializers', 'Constructor body', 'Factory functions in useFactory providers', 'Regular functions called outside Angular\'s injection context'], answer: '[0,1,2]', tags: ['di', 'inject'], explanation: 'inject() is valid in injection contexts: field initializers, constructor body, and factory functions. Calling it in a random function outside Angular\'s injection context throws a runtime error.', docs: 'https://angular.dev/api/core/inject' } },
      { id: 'a1000005-0000-4000-8001-000000000009', moduleId: 'a1000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'What is the useExisting provider option used for?', choices: ['To create a new instance of an existing class', 'To create an alias — makes one token resolve to the same instance as another already-registered token', 'To provide a factory function', 'To forward-reference a class not yet defined'], answer: '1', tags: ['di', 'providers', 'useExisting'], explanation: 'useExisting creates a token alias: { provide: Logger, useExisting: ConsoleLogger }. Both tokens resolve to the same ConsoleLogger instance, unlike useClass which would create a second instance.', docs: 'https://angular.dev/guide/di/dependency-injection-providers' } },
      { id: 'a1000005-0000-4000-8001-000000000010', moduleId: 'a1000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'What does @Optional() do when combined with inject() in Angular 19?', choices: ['inject(Token, { optional: true })', '@Optional() inject(Token)', 'inject(Token) ?? null', 'injectOptional(Token)'], answer: '0', tags: ['di', 'optional'], explanation: 'inject(Token, { optional: true }) returns null if the token is not provided, instead of throwing. This is the inject()-based equivalent of the @Optional() constructor parameter decorator.', docs: 'https://angular.dev/api/core/inject' } },
      { id: 'a1000005-0000-4000-8001-000000000011', moduleId: 'a1000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'How do you create a functional HTTP interceptor in Angular 19?', choices: ['Implement HttpInterceptor interface', 'Use withInterceptors([interceptorFn]) in provideHttpClient()', 'Add it to AppModule imports', 'Use @Interceptor() decorator'], answer: '1', tags: ['di', 'interceptors', 'http'], explanation: 'Functional interceptors are HttpInterceptorFn: (req, next) => next(req). They are registered via provideHttpClient(withInterceptors([myInterceptor])). They use inject() for dependencies.', docs: 'https://angular.dev/api/common/http/withInterceptors' } },
      { id: 'a1000005-0000-4000-8001-000000000012', moduleId: 'a1000000-0000-4000-8000-000000000005', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which useFactory features are available in Angular 19 DI? (select all that apply)', choices: ['deps array to inject other tokens', 'Returning a Promise for async providers', 'Returning a signal', 'Accessing the current injector with inject()'], answer: '[0,3]', tags: ['di', 'useFactory'], explanation: 'useFactory supports a deps array for injecting tokens and inject() is valid inside factory functions. Angular DI does not natively support async providers (Promise) — you need APP_INITIALIZER for that. Signals are values, not a provider feature.', docs: 'https://angular.dev/guide/di/dependency-injection-providers' } },
    ];

    for (const q of questions) {
      await queryRunner.query(
        `INSERT INTO "qcm_question" ("id", "moduleId", "type", "difficulty", "sortOrder", "data")
         VALUES ($1, $2, $3, $4, $5, $6)
         ON CONFLICT ("id") DO NOTHING`,
        [q.id, q.moduleId, q.type, q.difficulty, q.sortOrder, q.data]
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const ids: string[] = [];
    for (let m = 1; m <= 5; m++) {
      for (let q = 1; q <= 12; q++) {
        ids.push(`a100000${m}-0000-4000-8001-${String(q).padStart(12, '0')}`);
      }
    }
    await queryRunner.query(`DELETE FROM "qcm_question" WHERE "id" = ANY($1)`, [ids]);
  }
}
