import type { MigrationInterface, QueryRunner } from 'typeorm';

export class AddNestJsQuestions2_1773962401000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const questions = [
      // ── Module 8: Microservices ──
      { id: 'e5000008-0000-4000-8001-000000000001', moduleId: 'e5000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What is a NestJS Microservice and how does it differ from an HTTP app?', choices: ['Only a naming difference', 'A microservice uses a transport layer (TCP, Redis, Kafka, NATS) instead of HTTP — communicates via messages/events, not REST requests', 'A microservice is smaller code-wise', 'Microservices cannot use controllers'], answer: '1', tags: ['nestjs', 'microservices'], explanation: 'NestFactory.createMicroservice(AppModule, { transport: Transport.TCP, options: { port: 3001 } }). Uses @MessagePattern() handlers instead of @Get()/@Post(). Enables event-driven distributed architectures.' } },
      { id: 'e5000008-0000-4000-8001-000000000002', moduleId: 'e5000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What is the difference between @MessagePattern() and @EventPattern() in NestJS microservices?', choices: ['They are identical', '@MessagePattern handles request-response (expects a reply); @EventPattern handles fire-and-forget events (no reply expected)', '@EventPattern is for HTTP', '@MessagePattern is asynchronous only'], answer: '1', tags: ['nestjs', 'microservices', 'messaging'], explanation: '@MessagePattern("get_user"): client awaits reply. @EventPattern("user_created"): client sends and forgets. Use MessagePattern for queries, EventPattern for domain events.' } },
      { id: 'e5000008-0000-4000-8001-000000000003', moduleId: 'e5000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What transports does NestJS microservices support?', choices: ['Only TCP', 'TCP, Redis, NATS, RabbitMQ, Kafka, gRPC, and MQTT built-in', 'Only HTTP-based transports', 'Only Redis and Kafka'], answer: '1', tags: ['nestjs', 'microservices', 'transport'], explanation: 'NestJS supports: TCP (simple), Redis Pub/Sub, NATS, RabbitMQ (AMQP), Kafka, gRPC, MQTT. Choose based on requirements: Kafka for event streaming, gRPC for high-perf RPC, Redis for simple pub/sub.' } },
      { id: 'e5000008-0000-4000-8001-000000000004', moduleId: 'e5000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'How does a NestJS hybrid app work?', choices: ['A mix of Angular and NestJS', 'An application that listens on both HTTP (REST/GraphQL) and a microservice transport simultaneously', 'A multi-tenant app', 'An app with multiple databases'], answer: '1', tags: ['nestjs', 'hybrid-app', 'microservices'], explanation: 'app.connectMicroservice(microserviceOptions); await app.startAllMicroservices(); await app.listen(3000). Same app handles REST requests and microservice messages concurrently.' } },
      { id: 'e5000008-0000-4000-8001-000000000005', moduleId: 'e5000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'What is ClientProxy in NestJS microservices?', choices: ['A proxy server', 'A service for sending messages/events TO microservices from another service — obtained via @InjectClient() or ClientsModule', 'A database proxy', 'An HTTP client'], answer: '1', tags: ['nestjs', 'microservices', 'client-proxy'], explanation: 'this.client.send("pattern", data) returns Observable (request-response). this.client.emit("event", data) fires an event. ClientsModule.register([{ name: "SERVICE", transport: Transport.TCP }]).' } },
      { id: 'e5000008-0000-4000-8001-000000000006', moduleId: 'e5000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is the Saga pattern in microservices and how does NestJS support it?', choices: ['A story-based testing pattern', 'A sequence of local transactions with compensating transactions on failure — NestJS supports via @nestjs/cqrs with sagas using RxJS streams', 'A database transaction type', 'A NestJS-specific pattern'], answer: '1', tags: ['nestjs', 'saga', 'microservices', 'cqrs'], explanation: '@Saga() orderSagas = (events$: Observable<any>) => events$.pipe(ofType(OrderCreatedEvent), map(() => new ReserveInventoryCommand())). Orchestrates distributed transactions via events.' } },
      { id: 'e5000008-0000-4000-8001-000000000007', moduleId: 'e5000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'How do you handle errors in NestJS microservices?', choices: ['Errors are ignored', 'Throw RpcException in handlers — it serializes to the transport and is re-thrown as RpcException on the caller side', 'Use HttpException', 'Errors crash the microservice'], answer: '1', tags: ['nestjs', 'microservices', 'error-handling'], explanation: 'throw new RpcException({ message: "Not found", status: 404 }). On client: catchError(err => { throw new RpcException(err); }). Add RPC exception filter for consistent error transformation.' } },
      { id: 'e5000008-0000-4000-8001-000000000008', moduleId: 'e5000000-0000-4000-8000-000000000008', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which are advantages of microservices architecture? (select all that apply)', choices: ['Independent deployment per service', 'Technology diversity (different stacks per service)', 'Fault isolation', 'Simpler development overhead vs monolith'], answer: '[0,1,2]', tags: ['microservices', 'architecture'], explanation: 'Microservices advantages: independent deploy/scale, polyglot (use the right tool), fault isolation. Disadvantages: network latency, distributed tracing complexity, more operational overhead than monolith.' } },
      { id: 'e5000008-0000-4000-8001-000000000009', moduleId: 'e5000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'What is CQRS and how does @nestjs/cqrs implement it?', choices: ['A caching pattern', 'Command Query Responsibility Segregation — separate read and write operations. @nestjs/cqrs provides CommandBus, QueryBus, EventBus with handlers', 'A microservice transport', 'A database pattern'], answer: '1', tags: ['nestjs', 'cqrs'], explanation: 'commandBus.execute(new CreateUserCommand(dto)) → CreateUserHandler. queryBus.execute(new GetUserQuery(id)) → GetUserHandler. eventBus.publish(new UserCreatedEvent(user)) → multiple handlers. Separates concerns for complex domains.' } },
      { id: 'e5000008-0000-4000-8001-000000000010', moduleId: 'e5000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'What is the Outbox Pattern in microservices and why is it needed?', choices: ['An email outbox', 'Ensures atomicity between DB writes and event publishing — save event to DB in same transaction, then publish from DB (not from memory)', 'A message queue pattern', 'A retry pattern'], answer: '1', tags: ['microservices', 'outbox-pattern', 'eventual-consistency'], explanation: 'Problem: save order + publish event. If publish fails after save, event is lost. Outbox: save order + outbox record in one transaction. Separate process reads outbox and publishes. Guarantees at-least-once delivery.' } },
      { id: 'e5000008-0000-4000-8001-000000000011', moduleId: 'e5000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'How do you implement distributed tracing in NestJS microservices?', choices: ['Add console.log everywhere', 'Use OpenTelemetry with @opentelemetry/sdk-node — propagates trace context (W3C TraceContext) across service boundaries automatically', 'Use unique request IDs only', 'PM2 handles distributed tracing'], answer: '1', tags: ['nestjs', 'tracing', 'opentelemetry'], explanation: 'OpenTelemetry auto-instrumentation: instruments HTTP, gRPC, Kafka. Each service propagates traceparent header. Traces visualized in Jaeger/Zipkin — see the full request journey across services.' } },
      { id: 'e5000008-0000-4000-8001-000000000012', moduleId: 'e5000000-0000-4000-8000-000000000008', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which patterns help with resilience in NestJS microservices? (select all that apply)', choices: ['Circuit Breaker (fail fast when downstream is down)', 'Retry with exponential backoff', 'Timeout for slow services', 'Ignoring errors from downstream services'], answer: '[0,1,2]', tags: ['microservices', 'resilience'], explanation: 'Resilience patterns: Circuit Breaker (open circuit after N failures, fast-fail instead of waiting), Retry with backoff (transient failures), Timeout (prevent slow services from blocking). Use @nestjs/terminus for health checks.' } },

      // ── Module 9: Testing ──
      { id: 'e5000009-0000-4000-8001-000000000001', moduleId: 'e5000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What is Test.createTestingModule() used for?', choices: ['Generating test files', 'Creates a testing-specific NestJS module with injected mock providers for unit/integration testing services/controllers', 'Running database tests', 'A Jest wrapper'], answer: '1', tags: ['nestjs', 'testing', 'test-module'], explanation: 'const module = await Test.createTestingModule({ imports: [], controllers: [UsersController], providers: [UsersService, { provide: Repo, useValue: mockRepo }] }).compile().' } },
      { id: 'e5000009-0000-4000-8001-000000000002', moduleId: 'e5000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'How do you test a NestJS controller?', choices: ['Only integration tests work for controllers', 'Use Test.createTestingModule with controller + mocked service, then call controller methods directly', 'Use supertest only', 'Mock the HTTP server'], answer: '1', tags: ['nestjs', 'testing', 'controller'], explanation: 'controller = module.get(UsersController); service = module.get(UsersService); jest.spyOn(service, "findAll").mockResolvedValue([user]); expect(await controller.findAll()).toEqual([user]).' } },
      { id: 'e5000009-0000-4000-8001-000000000003', moduleId: 'e5000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'How do you write an end-to-end test in NestJS?', choices: ['Use Postman', 'Use supertest with a real test app: request(app.getHttpServer()).get("/users").expect(200)', 'Unit test all layers', 'Use a browser for E2E'], answer: '1', tags: ['nestjs', 'testing', 'e2e'], explanation: 'e2e test: create real app, seed test DB, use supertest. jest.config e2e: testRegex: ".e2e-spec.ts". beforeAll: init app. afterAll: close app and cleanup DB.' } },
      { id: 'e5000009-0000-4000-8001-000000000004', moduleId: 'e5000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What is the getRepositoryToken() function used for in NestJS tests?', choices: ['Gets a JWT token for tests', 'Returns the injection token for a TypeORM repository — used with useValue to provide a mock repository in tests', 'Generates database tokens', 'Creates test users'], answer: '1', tags: ['nestjs', 'testing', 'typeorm'], explanation: '{ provide: getRepositoryToken(User), useValue: mockUsersRepository }. This matches the token that @InjectRepository(User) expects, allowing you to inject the mock.' } },
      { id: 'e5000009-0000-4000-8001-000000000005', moduleId: 'e5000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'How do you mock a guard in NestJS E2E tests?', choices: ['Guards cannot be mocked', 'Override the guard with useValue: { canActivate: () => true } to bypass authentication in tests', 'Add @SkipAuth() to all test routes', 'Disable guards globally'], answer: '1', tags: ['nestjs', 'testing', 'guards'], explanation: 'moduleRef.overrideGuard(AuthGuard).useValue({ canActivate: () => true }). Or override globally: app.overrideGuard(JwtAuthGuard).useValue({ canActivate: (ctx) => { /* mock user on request */ return true; } }).' } },
      { id: 'e5000009-0000-4000-8001-000000000006', moduleId: 'e5000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is the jest.spyOn() method used for in NestJS unit tests?', choices: ['Watching file changes', 'Creates a spy on a method — records calls, can mock implementation while preserving the original method', 'Monitoring HTTP requests', 'A performance profiler'], answer: '1', tags: ['nestjs', 'testing', 'jest', 'spy'], explanation: 'jest.spyOn(service, "findOne").mockResolvedValue(user). Tracks: expect(service.findOne).toHaveBeenCalledWith(id). Restore original: jest.spyOn(service, "findOne").mockRestore().' } },
      { id: 'e5000009-0000-4000-8001-000000000007', moduleId: 'e5000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'How do you test NestJS guards in isolation?', choices: ['Only test via E2E', 'Instantiate the guard directly, create a mock ExecutionContext, and call canActivate(context)', 'Guards are untestable', 'Use only integration tests'], answer: '1', tags: ['nestjs', 'testing', 'guards'], explanation: 'const guard = new AuthGuard(mockJwtService); const context = createMock<ExecutionContext>(); context.switchToHttp.mockReturnValue({ getRequest: () => ({ headers: { authorization: "Bearer token" } }) }); expect(guard.canActivate(context)).resolves.toBe(true).' } },
      { id: 'e5000009-0000-4000-8001-000000000008', moduleId: 'e5000000-0000-4000-8000-000000000009', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which are valid testing strategies for NestJS applications? (select all that apply)', choices: ['Unit tests for services with mocked dependencies', 'Integration tests with real database (test container)', 'E2E tests with supertest', 'Only E2E tests are reliable'], answer: '[0,1,2]', tags: ['nestjs', 'testing', 'strategies'], explanation: 'All three are needed: unit tests (fast, isolated), integration tests (real DB with docker-compose/testcontainers), E2E tests (full HTTP flow). They serve different purposes in the testing pyramid.' } },
      { id: 'e5000009-0000-4000-8001-000000000009', moduleId: 'e5000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'How do you use Testcontainers with NestJS for database integration tests?', choices: ['Mock all database calls', 'Start a real PostgreSQL container in beforeAll, configure TypeORM to connect to it, run migrations, then test', 'Use SQLite for integration tests', 'Testcontainers are not supported'], answer: '1', tags: ['nestjs', 'testing', 'testcontainers', 'database'], explanation: 'const container = await new PostgreSqlContainer().start(); TypeOrmModule with container.getConnectionUri(). Runs real queries against real Postgres. teardown: await container.stop().' } },
      { id: 'e5000009-0000-4000-8001-000000000010', moduleId: 'e5000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'How do you test NestJS interceptors?', choices: ['Only via E2E tests', 'Instantiate interceptor, create CallHandler mock returning Observable, call intercept() and subscribe to the result', 'Interceptors cannot be unit tested', 'Test via controller unit tests'], answer: '1', tags: ['nestjs', 'testing', 'interceptor'], explanation: 'const next: CallHandler = { handle: () => of(mockData) }. interceptor.intercept(mockContext, next).pipe(toArray()).subscribe(result => expect(result[0]).toEqual(expected)).' } },
      { id: 'e5000009-0000-4000-8001-000000000011', moduleId: 'e5000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'What is the @nestjs/testing createMock utility and how does it help?', choices: ['It mocks the entire NestJS framework', 'Creates a type-safe automatic mock of any class with all methods stubbed as jest.fn() — reduces mock boilerplate', 'Creates API mocks', 'Only mocks HTTP services'], answer: '1', tags: ['nestjs', 'testing', 'mock'], explanation: '@golevelup/ts-jest createMock<UsersService>() creates a mock with all methods as jest.fn(). More ergonomic than manually creating { findOne: jest.fn(), create: jest.fn(), ... }.' } },
      { id: 'e5000009-0000-4000-8001-000000000012', moduleId: 'e5000000-0000-4000-8000-000000000009', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which practices improve NestJS test reliability? (select all that apply)', choices: ['Isolate tests — no shared state between tests', 'Use beforeEach to reset mocks: jest.clearAllMocks()', 'Test error paths, not just happy paths', 'Use the same database for all environments'], answer: '[0,1,2]', tags: ['nestjs', 'testing', 'best-practices'], explanation: 'Reliable tests: isolation (each test starts fresh), reset mocks (clearAllMocks in beforeEach), test error cases (rejection, 404, validation errors). Never share test DB with dev/prod.' } },

      // ── Module 10: GraphQL ──
      { id: 'e5000010-0000-4000-8001-000000000001', moduleId: 'e5000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What are the two approaches to build a GraphQL API in NestJS?', choices: ['REST and GraphQL', 'Code-first (decorators generate schema) and Schema-first (SDL defines schema, generates TypeScript types)', 'Frontend-first and Backend-first', 'TypeScript-first and JavaScript-first'], answer: '1', tags: ['nestjs', 'graphql'], explanation: 'Code-first: @ObjectType(), @Resolver(), @Query(), @Mutation() — TypeScript defines the schema. Schema-first: .graphql SDL file defines schema, NestJS generates TS types from it.' } },
      { id: 'e5000010-0000-4000-8001-000000000002', moduleId: 'e5000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What is a Resolver in NestJS GraphQL?', choices: ['A dependency injector', 'A class decorated with @Resolver() that handles GraphQL queries, mutations, and subscriptions for a type', 'An HTTP route handler', 'A type definition'], answer: '1', tags: ['nestjs', 'graphql', 'resolver'], explanation: '@Resolver(() => User) class UsersResolver { @Query(() => User) async user(@Args("id") id: string) { return this.usersService.findOne(id); } }. Similar to @Controller but for GraphQL.' } },
      { id: 'e5000010-0000-4000-8001-000000000003', moduleId: 'e5000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What is the N+1 problem in GraphQL and how does DataLoader solve it?', choices: ['Fetching N extra fields', 'For N parent objects, N child queries are made (N+1 total) — DataLoader batches multiple calls in a tick into one query', 'A GraphQL version issue', 'A subscription problem'], answer: '1', tags: ['nestjs', 'graphql', 'dataloader', 'n+1'], explanation: 'posts { author { name } } → 1 query for posts + N queries for authors. DataLoader: batch all authorIds in a tick, fetch in ONE query. @nestjs/dataloader makes this injectable.' } },
      { id: 'e5000010-0000-4000-8001-000000000004', moduleId: 'e5000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What is GraphQL subscription in NestJS?', choices: ['A payment subscription', 'A real-time feature using WebSockets that pushes data to clients when events occur — implemented with @Subscription() decorator', 'An HTTP polling mechanism', 'A GraphQL schema version'], answer: '1', tags: ['nestjs', 'graphql', 'subscription'], explanation: '@Subscription(() => User) userCreated() { return this.pubSub.asyncIterator("userCreated"); }. Server pushes updates to subscribing clients via WebSocket. Use PubSub from graphql-subscriptions.' } },
      { id: 'e5000010-0000-4000-8001-000000000005', moduleId: 'e5000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'How do you protect a GraphQL resolver with authentication in NestJS?', choices: ['GraphQL cannot use guards', '@UseGuards(JwtAuthGuard) on the resolver class or individual query/mutation methods', 'Use middleware only', 'Add auth in schema definition'], answer: '1', tags: ['nestjs', 'graphql', 'guard', 'authentication'], explanation: '@UseGuards(JwtAuthGuard) works on GraphQL resolvers too — ExecutionContext handles GQL context. Access user: @CurrentUser() user: User from context.req.user.' } },
      { id: 'e5000010-0000-4000-8001-000000000006', moduleId: 'e5000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is the GraphQL context in NestJS and how do you access the current user?', choices: ['The GraphQL schema context', 'The context object passed to all resolvers — in NestJS, context.req contains the Express request with the authenticated user', 'A caching context', 'A subscription context'], answer: '1', tags: ['nestjs', 'graphql', 'context'], explanation: 'GraphQLModule.forRoot({ context: ({ req }) => ({ req }) }). In resolver: @Context() ctx: { req: Request }. Or use @CurrentUser() decorator that reads from context.req.user.' } },
      { id: 'e5000010-0000-4000-8001-000000000007', moduleId: 'e5000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'What is field resolver in NestJS GraphQL and when is it used?', choices: ['Resolver for a specific field type', '@ResolveField() decorator on a method in a Resolver that computes a specific field of an object type — useful for nested relations', 'A computed property', 'A database computed column'], answer: '1', tags: ['nestjs', 'graphql', 'resolve-field'], explanation: '@ResolveField("posts", () => [Post]) async posts(@Parent() user: User) { return this.postsService.findByUser(user.id); }. Runs only when "posts" field is requested. Use with DataLoader to batch.' } },
      { id: 'e5000010-0000-4000-8001-000000000008', moduleId: 'e5000000-0000-4000-8000-000000000010', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which are advantages of GraphQL over REST? (select all that apply)', choices: ['No over-fetching (request only needed fields)', 'Single endpoint for all operations', 'Strongly typed schema as contract', 'Easier caching than REST'], answer: '[0,1,2]', tags: ['graphql', 'rest', 'comparison'], explanation: 'GraphQL advantages: no over/under-fetching, single endpoint (/graphql), schema as contract (codegen). Caching is harder (POST requests, complex keys). REST has simpler HTTP caching.' } },
      { id: 'e5000010-0000-4000-8001-000000000009', moduleId: 'e5000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'What is query complexity analysis in GraphQL and why is it needed?', choices: ['Analyzing query performance', 'Preventing deeply nested or expensive queries from DoS-ing the server by assigning costs to fields and rejecting queries exceeding a limit', 'A code quality check', 'Query caching'], answer: '1', tags: ['nestjs', 'graphql', 'security', 'complexity'], explanation: 'Without limits: { users { posts { comments { author { posts { ... } } } } } } can generate thousands of DB queries. graphql-query-complexity computes field costs, rejects if > maxComplexity.' } },
      { id: 'e5000010-0000-4000-8001-000000000010', moduleId: 'e5000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'What is Apollo Federation in NestJS and what problem does it solve?', choices: ['Apollo Server configuration', 'A specification for composing multiple GraphQL services into a single supergraph — enables GraphQL microservices with a unified schema', 'A caching solution', 'A NestJS-specific GraphQL format'], answer: '1', tags: ['nestjs', 'graphql', 'federation', 'microservices'], explanation: '@nestjs/apollo supports Federation. Each service owns its types. Gateway composes them into one schema. Service A extends User type from Service B. Clients query one endpoint; gateway routes to services.' } },
      { id: 'e5000010-0000-4000-8001-000000000011', moduleId: 'e5000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'How do you implement cursor-based pagination in NestJS GraphQL?', choices: ['Use skip/limit only', 'Return Connection type with edges (node + cursor) and pageInfo (hasNextPage, endCursor) — query with first: N, after: cursor', 'GraphQL pagination is not standard', 'Use page number always'], answer: '1', tags: ['nestjs', 'graphql', 'pagination', 'cursor'], explanation: 'Relay cursor pagination: query(first: 10, after: "cursor") returns { edges: [{ node, cursor }], pageInfo: { hasNextPage, endCursor } }. Stable under insertions. @nestjs/graphql provides Connection types.' } },
      { id: 'e5000010-0000-4000-8001-000000000012', moduleId: 'e5000000-0000-4000-8000-000000000010', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which GraphQL security practices should be implemented? (select all that apply)', choices: ['Query depth limiting', 'Query complexity analysis', 'Field-level authorization', 'Disable introspection in production'], answer: '[0,1,2,3]', tags: ['nestjs', 'graphql', 'security'], explanation: 'GraphQL security: depth limiting (prevent deeply nested queries), complexity (prevent expensive queries), field-level auth (hide sensitive fields per role), disable introspection (hide schema from attackers in production).' } },

      // ── Module 11: WebSockets ──
      { id: 'e5000011-0000-4000-8001-000000000001', moduleId: 'e5000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'How do you create a WebSocket Gateway in NestJS?', choices: ['Use @Controller() with websocket option', 'Create a class with @WebSocketGateway() decorator that handles WebSocket events with @SubscribeMessage()', 'Configure in module only', 'Use @UseWebSockets() on a service'], answer: '1', tags: ['nestjs', 'websocket', 'gateway'], explanation: '@WebSocketGateway(80, { namespace: "/chat" }) class ChatGateway { @SubscribeMessage("message") handleMessage(client: Socket, payload) { this.server.emit("message", payload); } }' } },
      { id: 'e5000011-0000-4000-8001-000000000002', moduleId: 'e5000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What is the @WebSocketServer() decorator in NestJS?', choices: ['Configures the server port', 'Injects the native WebSocket server instance (socket.io Server or ws.Server) into the gateway property', 'Creates a new server', 'Starts the WebSocket server'], answer: '1', tags: ['nestjs', 'websocket', 'server'], explanation: '@WebSocketServer() server: Server. Access to emit to all clients: this.server.emit("event", data). Or to a room: this.server.to("room").emit("event", data).' } },
      { id: 'e5000011-0000-4000-8001-000000000003', moduleId: 'e5000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What is the difference between socket.io and ws adapters in NestJS?', choices: ['No difference', 'socket.io adds rooms, namespaces, auto-reconnect, fallback transports; ws is a lightweight pure WebSocket without extras', 'ws is faster always', 'socket.io is deprecated'], answer: '1', tags: ['nestjs', 'websocket', 'socket.io', 'ws'], explanation: 'socket.io: rooms, namespaces, broadcasting, HTTP long-poll fallback, auto-reconnect. ws: raw WebSocket, lighter, faster but fewer features. NestJS uses socket.io by default; switch with WsAdapter.' } },
      { id: 'e5000011-0000-4000-8001-000000000004', moduleId: 'e5000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What lifecycle hooks are available in NestJS WebSocket Gateways?', choices: ['Only onMessage', 'OnGatewayInit (afterInit), OnGatewayConnection (handleConnection), OnGatewayDisconnect (handleDisconnect)', 'Same as HTTP lifecycle', 'ngOnInit'], answer: '1', tags: ['nestjs', 'websocket', 'lifecycle'], explanation: 'Implement interfaces: OnGatewayInit.afterInit(server), OnGatewayConnection.handleConnection(client), OnGatewayDisconnect.handleDisconnect(client). Handle auth on connection, cleanup on disconnect.' } },
      { id: 'e5000011-0000-4000-8001-000000000005', moduleId: 'e5000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'How do you authenticate WebSocket connections in NestJS?', choices: ['WebSockets cannot be authenticated', 'Validate JWT in handleConnection() hook or via WsGuard in SubscribeMessage handlers', 'Use HTTP session cookies only', 'Authentication is automatic'], answer: '1', tags: ['nestjs', 'websocket', 'authentication'], explanation: 'handleConnection(client): const token = client.handshake.auth.token; try { const user = jwt.verify(token, secret); client.data.user = user; } catch { client.disconnect(); }. Or implement WsGuard.' } },
      { id: 'e5000011-0000-4000-8001-000000000006', moduleId: 'e5000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'How do you use rooms in socket.io with NestJS for private messaging?', choices: ['Rooms are not supported', 'client.join(roomId) adds client to room; this.server.to(roomId).emit("message", data) sends to room members only', 'Use separate namespaces', 'Private messages via direct socket'], answer: '1', tags: ['nestjs', 'websocket', 'socket.io', 'rooms'], explanation: 'Each socket has unique ID (client.id). For direct message: this.server.to(targetSocketId).emit(). For group chat: await client.join(roomId). Leave: client.leave(roomId).' } },
      { id: 'e5000011-0000-4000-8001-000000000007', moduleId: 'e5000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'How do WebSocket guards differ from HTTP guards in NestJS?', choices: ['No difference', 'WsGuard uses WsArgumentsHost instead of HttpArgumentsHost to access WebSocket-specific context (client, data)', 'WsGuards block all connections', 'Guards cannot be used with WebSockets'], answer: '1', tags: ['nestjs', 'websocket', 'guard'], explanation: 'canActivate(context: ExecutionContext): context.switchToWs().getClient() returns socket client. context.switchToWs().getData() returns message data. Check client.data.user (set in handleConnection).' } },
      { id: 'e5000011-0000-4000-8001-000000000008', moduleId: 'e5000000-0000-4000-8000-000000000011', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which are valid use cases for WebSockets in NestJS? (select all that apply)', choices: ['Real-time chat', 'Live notifications', 'Collaborative document editing', 'Static file serving'], answer: '[0,1,2]', tags: ['nestjs', 'websocket', 'use-cases'], explanation: 'WebSockets: bi-directional, low-latency. Perfect for chat, live notifications (stock prices, alerts), collaborative apps (Google Docs-like). Static files should use HTTP/CDN — no need for persistent connections.' } },
      { id: 'e5000011-0000-4000-8001-000000000009', moduleId: 'e5000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'How do you scale WebSocket servers across multiple NestJS instances?', choices: ['WebSockets cannot be scaled', 'Use socket.io Redis adapter (@socket.io/redis-adapter) to broadcast events across all instances', 'Use round-robin load balancing only', 'Use sticky sessions only'], answer: '1', tags: ['nestjs', 'websocket', 'scaling', 'redis'], explanation: 'With multiple instances, client A on instance 1 cannot message client B on instance 2 by default. Redis adapter: all instances subscribe to Redis pub/sub — events broadcast to all instances.' } },
      { id: 'e5000011-0000-4000-8001-000000000010', moduleId: 'e5000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'How do you emit WebSocket events from a NestJS HTTP controller?', choices: ['Cannot mix HTTP and WebSocket', 'Inject the Gateway or a shared EventsService into the HTTP controller; call gateway.server.emit() from it', 'Use a shared Redis channel', 'Use HTTP Server-Sent Events instead'], answer: '1', tags: ['nestjs', 'websocket', 'http-to-ws'], explanation: 'Inject ChatGateway into HttpController (or use a shared service). this.chatGateway.server.emit("notification", data). Since Gateway is @Injectable() singleton, this works seamlessly.' } },
      { id: 'e5000011-0000-4000-8001-000000000011', moduleId: 'e5000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'What is the WsAdapter and why might you switch from socket.io to ws?', choices: ['A migration tool', 'app.useWebSocketAdapter(new WsAdapter(app)) switches to raw WebSocket (ws library) — lighter, faster, no socket.io protocol overhead', 'A compatibility adapter', 'Required for Fastify'], answer: '1', tags: ['nestjs', 'websocket', 'ws-adapter'], explanation: 'WsAdapter uses the ws library instead of socket.io. Pros: lighter, standard WebSocket protocol (any client), faster. Cons: no rooms, no namespaces, no auto-reconnect, no fallback. Use when clients are non-browser.' } },
      { id: 'e5000011-0000-4000-8001-000000000012', moduleId: 'e5000000-0000-4000-8000-000000000011', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which challenges are specific to WebSocket production deployments? (select all that apply)', choices: ['Load balancer sticky sessions or Redis adapter required', 'Memory management for long-lived connections', 'Handling reconnection on server restart', 'WebSockets only work on port 80'], answer: '[0,1,2]', tags: ['nestjs', 'websocket', 'production'], explanation: 'WebSocket production challenges: stickiness (client must reconnect to same instance) or Redis adapter, memory (thousands of open connections), graceful reconnection handling after deploy. No restriction to port 80.' } },
    ];

    for (const q of questions) {
      await queryRunner.query(
        `INSERT INTO "qcm_question" ("id", "moduleId", "type", "difficulty", "sortOrder", "data")
         VALUES ($1, $2, $3, $4, $5, $6)
         ON CONFLICT ("id") DO NOTHING`,
        [q.id, q.moduleId, q.type, q.difficulty, q.sortOrder, q.data]
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const ids: string[] = [];
    for (let m = 8; m <= 11; m++) {
      for (let q = 1; q <= 12; q++) {
        ids.push(`e500000${m}-0000-4000-8001-${String(q).padStart(12, '0')}`);
      }
    }
    await queryRunner.query(`DELETE FROM "qcm_question" WHERE "id" = ANY($1)`, [ids]);
  }
}
