import type { MigrationInterface, QueryRunner } from 'typeorm';

export class AddAlgorithmesQuestions1773962100000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const questions = [
      // ── Module 1: Data Structures ──
      { id: 'b2000001-0000-4000-8001-000000000001', moduleId: 'b2000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What is the time complexity of accessing an element by index in an array?', choices: ['O(n)', 'O(log n)', 'O(1)', 'O(n²)'], answer: '2', tags: ['arrays', 'complexity'], explanation: 'Arrays store elements in contiguous memory. Index-based access computes the memory address directly (base + index × size), making it O(1) — constant time regardless of array length.', docs: 'https://en.wikipedia.org/wiki/Data_structure' } },
      { id: 'b2000001-0000-4000-8001-000000000002', moduleId: 'b2000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What data structure follows the LIFO (Last In, First Out) principle?', choices: ['Queue', 'Stack', 'Linked List', 'Heap'], answer: '1', tags: ['stack', 'lifo'], explanation: 'A Stack removes elements in reverse order of insertion. Think of a stack of plates — you can only add/remove from the top. Operations: push (add) and pop (remove) are both O(1).', docs: 'https://en.wikipedia.org/wiki/Data_structure' } },
      { id: 'b2000001-0000-4000-8001-000000000003', moduleId: 'b2000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What is the average time complexity of lookup in a hash map?', choices: ['O(n)', 'O(log n)', 'O(1)', 'O(n log n)'], answer: '2', tags: ['hash-map', 'complexity'], explanation: 'Hash maps compute a hash of the key to find the bucket. Average case is O(1). Worst case is O(n) due to hash collisions, but good hash functions minimize this.', docs: 'https://en.wikipedia.org/wiki/Data_structure' } },
      { id: 'b2000001-0000-4000-8001-000000000004', moduleId: 'b2000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What is a singly linked list?', choices: ['A list with random access', 'A sequence of nodes where each node holds a value and a pointer to the next node', 'A doubly-connected graph', 'An array with gaps'], answer: '1', tags: ['linked-list'], explanation: 'In a singly linked list each node stores data and a next pointer. Traversal is O(n). Insertion/deletion at head is O(1). No random access — you must traverse to reach index i.', docs: 'https://en.wikipedia.org/wiki/Data_structure' } },
      { id: 'b2000001-0000-4000-8001-000000000005', moduleId: 'b2000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'What is the difference between a stack and a queue?', choices: ['A stack uses FIFO; a queue uses LIFO', 'A stack uses LIFO; a queue uses FIFO', 'They are the same structure', 'A stack is sorted; a queue is not'], answer: '1', tags: ['stack', 'queue'], explanation: 'Stack = LIFO (Last In First Out): push/pop at the same end. Queue = FIFO (First In First Out): enqueue at back, dequeue at front. Both have O(1) add/remove with proper implementation.', docs: 'https://en.wikipedia.org/wiki/Data_structure' } },
      { id: 'b2000001-0000-4000-8001-000000000006', moduleId: 'b2000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What property defines a binary search tree (BST)?', choices: ['Every node has exactly two children', 'Left child < parent < right child for every node', 'The tree is always balanced', 'All leaves are at the same depth'], answer: '1', tags: ['bst', 'trees'], explanation: 'BST invariant: for any node N, all values in its left subtree are less than N, and all in its right are greater. This enables O(log n) average search, insert, and delete (O(n) worst if unbalanced).', docs: 'https://en.wikipedia.org/wiki/Data_structure' } },
      { id: 'b2000001-0000-4000-8001-000000000007', moduleId: 'b2000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'What is a min-heap?', choices: ['A tree where the root is the maximum element', 'A complete binary tree where each node is smaller than or equal to its children', 'A sorted array', 'A balanced BST'], answer: '1', tags: ['heap', 'priority-queue'], explanation: 'A min-heap is a complete binary tree with the heap property: parent ≤ children. The minimum element is always at the root. Extract-min and insert are O(log n). Used to implement priority queues.', docs: 'https://en.wikipedia.org/wiki/Data_structure' } },
      { id: 'b2000001-0000-4000-8001-000000000008', moduleId: 'b2000000-0000-4000-8000-000000000001', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which data structures provide O(1) average insertion at the front? (select all that apply)', choices: ['Linked List (prepend)', 'Array (unshift)', 'Deque (double-ended queue)', 'Hash Map'], answer: '[0,2]', tags: ['complexity', 'insertion'], explanation: 'Linked list prepend is O(1) — just update head pointer. Deque prepend is O(1) with a doubly linked list implementation. Array unshift is O(n) because all elements shift. Hash map insertion is by key, not position.', docs: 'https://en.wikipedia.org/wiki/Data_structure' } },
      { id: 'b2000001-0000-4000-8001-000000000009', moduleId: 'b2000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'What is the time complexity of inserting into a balanced BST (e.g., AVL tree)?', choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], answer: '1', tags: ['bst', 'avl', 'complexity'], explanation: 'A balanced BST maintains height O(log n) through rotations. Insertion finds the position in O(log n) and may perform O(log n) rotations to rebalance. Total: O(log n).', docs: 'https://en.wikipedia.org/wiki/Data_structure' } },
      { id: 'b2000001-0000-4000-8001-000000000010', moduleId: 'b2000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'What is the space complexity of a hash map storing n key-value pairs?', choices: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], answer: '2', tags: ['hash-map', 'space-complexity'], explanation: 'A hash map requires O(n) space to store n entries plus the underlying array of buckets (typically O(n) capacity). Space complexity is O(n) where n is the number of stored elements.', docs: 'https://en.wikipedia.org/wiki/Data_structure' } },
      { id: 'b2000001-0000-4000-8001-000000000011', moduleId: 'b2000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'In a trie (prefix tree), what is the time complexity of searching for a word of length k?', choices: ['O(n) where n is number of words', 'O(k)', 'O(k log n)', 'O(1)'], answer: '1', tags: ['trie', 'complexity'], explanation: 'A trie search follows one edge per character. For a word of length k, exactly k nodes are visited — O(k). This is independent of the number of words stored, making tries very efficient for prefix lookups.', docs: 'https://en.wikipedia.org/wiki/Data_structure' } },
      { id: 'b2000001-0000-4000-8001-000000000012', moduleId: 'b2000000-0000-4000-8000-000000000001', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which graph representations are commonly used? (select all that apply)', choices: ['Adjacency Matrix', 'Adjacency List', 'Edge List', 'Incidence Matrix'], answer: '[0,1,2]', tags: ['graphs', 'representation'], explanation: 'Common graph representations: Adjacency Matrix (O(V²) space, O(1) edge lookup), Adjacency List (O(V+E) space, efficient for sparse graphs), Edge List (simple list of edges). Incidence Matrix is less common in algorithm courses.', docs: 'https://en.wikipedia.org/wiki/Data_structure' } },

      // ── Module 2: Sorting & Searching ──
      { id: 'b2000002-0000-4000-8001-000000000001', moduleId: 'b2000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What is the time complexity of binary search?', choices: ['O(n)', 'O(log n)', 'O(1)', 'O(n log n)'], answer: '1', tags: ['binary-search', 'complexity'], explanation: 'Binary search halves the search space on each step. After k steps, n/2^k = 1, so k = log₂(n). Requires a sorted array. O(log n) time, O(1) space iteratively.', docs: 'https://en.wikipedia.org/wiki/Sorting_algorithm' } },
      { id: 'b2000002-0000-4000-8001-000000000002', moduleId: 'b2000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What is the average time complexity of quicksort?', choices: ['O(n²)', 'O(n log n)', 'O(n)', 'O(log n)'], answer: '1', tags: ['quicksort', 'complexity'], explanation: 'Quicksort average case: O(n log n). Each partition step is O(n). With good pivot selection, we get O(log n) levels of recursion. Worst case (sorted array, bad pivot): O(n²).', docs: 'https://en.wikipedia.org/wiki/Sorting_algorithm' } },
      { id: 'b2000002-0000-4000-8001-000000000003', moduleId: 'b2000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'Which sorting algorithm is stable and has O(n log n) guaranteed time complexity?', choices: ['Quicksort', 'Heapsort', 'Merge sort', 'Selection sort'], answer: '2', tags: ['merge-sort', 'stable-sort'], explanation: 'Merge sort is stable (equal elements maintain relative order) and always O(n log n). Quicksort and heapsort are not stable. Selection sort is O(n²). Merge sort uses O(n) extra space.', docs: 'https://en.wikipedia.org/wiki/Sorting_algorithm' } },
      { id: 'b2000002-0000-4000-8001-000000000004', moduleId: 'b2000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What condition must be met to apply binary search?', choices: ['The array must be sorted', 'The array must have no duplicates', 'The array must be a power of 2 in length', 'The array must be stored in a hash map'], answer: '0', tags: ['binary-search', 'prerequisites'], explanation: 'Binary search requires the input array to be sorted. It compares the target with the midpoint and eliminates half the search space. On an unsorted array, binary search produces incorrect results.', docs: 'https://en.wikipedia.org/wiki/Sorting_algorithm' } },
      { id: 'b2000002-0000-4000-8001-000000000005', moduleId: 'b2000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'What is the worst-case time complexity of quicksort and when does it occur?', choices: ['O(n log n) — always', 'O(n²) — when the pivot is always the smallest or largest element', 'O(n²) — when the array has no duplicates', 'O(log n) — when the array is sorted'], answer: '1', tags: ['quicksort', 'worst-case'], explanation: 'Quicksort degrades to O(n²) when partitioning is maximally unbalanced — e.g., always picking the first element as pivot on a sorted array. Randomised pivot selection avoids this in practice.', docs: 'https://en.wikipedia.org/wiki/Sorting_algorithm' } },
      { id: 'b2000002-0000-4000-8001-000000000006', moduleId: 'b2000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is counting sort and when is it most efficient?', choices: ['A comparison-based sort with O(n log n)', 'A non-comparison sort that counts occurrences; efficient when the value range k is small relative to n', 'A sort using hash maps', 'A parallel sorting algorithm'], answer: '1', tags: ['counting-sort', 'non-comparison'], explanation: 'Counting sort counts how many times each value appears, then reconstructs the sorted array. Time: O(n + k) where k is the value range. Ideal when k << n (e.g., sorting ages 0-120 in a list of millions).', docs: 'https://en.wikipedia.org/wiki/Sorting_algorithm' } },
      { id: 'b2000002-0000-4000-8001-000000000007', moduleId: 'b2000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'How does heap sort achieve O(n log n) time complexity?', choices: ['It uses merge sort internally', 'It builds a max-heap in O(n), then repeatedly extracts the max in O(log n) — n times', 'It uses binary search during sorting', 'It partitions like quicksort but always picks the median'], answer: '1', tags: ['heap-sort', 'complexity'], explanation: 'Heapsort: 1) Build max-heap: O(n). 2) Extract max n times: each extraction is O(log n) heapify. Total: O(n log n). In-place with O(1) extra space, but not stable.', docs: 'https://en.wikipedia.org/wiki/Sorting_algorithm' } },
      { id: 'b2000002-0000-4000-8001-000000000008', moduleId: 'b2000000-0000-4000-8000-000000000002', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which of the following sorting algorithms are O(n log n) in the average case? (select all that apply)', choices: ['Merge sort', 'Quicksort', 'Bubble sort', 'Heap sort'], answer: '[0,1,3]', tags: ['sorting', 'complexity'], explanation: 'Merge sort: O(n log n) always. Quicksort: O(n log n) average. Heapsort: O(n log n) always. Bubble sort: O(n²) average and worst case.', docs: 'https://en.wikipedia.org/wiki/Sorting_algorithm' } },
      { id: 'b2000002-0000-4000-8001-000000000009', moduleId: 'b2000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'What is the lower bound for comparison-based sorting algorithms?', choices: ['O(n)', 'O(n log n)', 'O(log n)', 'O(n²)'], answer: '1', tags: ['sorting', 'lower-bound', 'theory'], explanation: 'Any comparison-based sort must make at least Ω(n log n) comparisons in the worst case — proven via decision tree argument (n! possible orderings require log₂(n!) = Ω(n log n) comparisons).', docs: 'https://en.wikipedia.org/wiki/Sorting_algorithm' } },
      { id: 'b2000002-0000-4000-8001-000000000010', moduleId: 'b2000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'How does the two-pointer technique optimize searching in a sorted array?', choices: ['It uses two binary searches', 'It places one pointer at each end and moves them inward based on comparisons, achieving O(n) instead of O(n²)', 'It sorts the array twice', 'It applies divide and conquer'], answer: '1', tags: ['two-pointer', 'searching'], explanation: 'Two-pointer: left=0, right=n-1. Compare arr[left]+arr[right] with target. If too large, right--. If too small, left++. Solves two-sum in sorted array in O(n) time vs O(n²) brute force.', docs: 'https://en.wikipedia.org/wiki/Sorting_algorithm' } },
      { id: 'b2000002-0000-4000-8001-000000000011', moduleId: 'b2000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'What is the time complexity of finding the kth smallest element using a min-heap approach?', choices: ['O(n)', 'O(n + k log n)', 'O(k log n)', 'O(n log k)'], answer: '1', tags: ['heap', 'kth-element'], explanation: 'Build min-heap: O(n). Extract min k times: O(k log n). Total: O(n + k log n). Alternative: maintain max-heap of size k while scanning — O(n log k). The QuickSelect algorithm achieves O(n) average.', docs: 'https://en.wikipedia.org/wiki/Sorting_algorithm' } },
      { id: 'b2000002-0000-4000-8001-000000000012', moduleId: 'b2000000-0000-4000-8000-000000000002', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which sorting algorithms sort in-place (O(1) extra space)? (select all that apply)', choices: ['Quicksort', 'Heap sort', 'Merge sort', 'Insertion sort'], answer: '[0,1,3]', tags: ['sorting', 'in-place', 'space'], explanation: 'In-place (O(1) extra space): quicksort (recursive stack O(log n) but array is in-place), heapsort, insertion sort, selection sort, bubble sort. Merge sort requires O(n) auxiliary space for merging.', docs: 'https://en.wikipedia.org/wiki/Sorting_algorithm' } },

      // ── Module 3: Recursion & Backtracking ──
      { id: 'b2000003-0000-4000-8001-000000000001', moduleId: 'b2000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What are the two essential components of a recursive function?', choices: ['A loop and a condition', 'A base case and a recursive case', 'A stack and a queue', 'An input and an output'], answer: '1', tags: ['recursion', 'base-case'], explanation: 'Every recursive function needs: 1) A base case that terminates recursion without a self-call. 2) A recursive case that calls itself with a smaller/simpler input, progressing toward the base case.', docs: 'https://en.wikipedia.org/wiki/Backtracking' } },
      { id: 'b2000003-0000-4000-8001-000000000002', moduleId: 'b2000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What is the space complexity of a recursive function with depth d?', choices: ['O(1)', 'O(d)', 'O(2^d)', 'O(d²)'], answer: '1', tags: ['recursion', 'space-complexity', 'call-stack'], explanation: 'Each recursive call adds a stack frame. With recursion depth d, the call stack holds d frames simultaneously. Space complexity is O(d) — this is why deep recursion can cause stack overflow.', docs: 'https://en.wikipedia.org/wiki/Backtracking' } },
      { id: 'b2000003-0000-4000-8001-000000000003', moduleId: 'b2000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What is memoization?', choices: ['Sorting results for faster access', 'Caching the results of function calls so that repeated calls with the same arguments return the cached result', 'A type of dynamic programming bottom-up approach', 'Storing intermediate values in a heap'], answer: '1', tags: ['memoization', 'optimization'], explanation: 'Memoization is top-down dynamic programming: store computed results in a cache (map/array). When the function is called again with the same inputs, return the cached value instead of recomputing.', docs: 'https://en.wikipedia.org/wiki/Backtracking' } },
      { id: 'b2000003-0000-4000-8001-000000000004', moduleId: 'b2000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What is backtracking?', choices: ['A recursive technique that builds candidates incrementally and abandons a candidate as soon as it violates constraints', 'Iterating through all permutations with nested loops', 'A sorting algorithm', 'Reversing a linked list recursively'], answer: '0', tags: ['backtracking'], explanation: 'Backtracking explores candidates by making choices, and when a partial solution violates constraints or cannot lead to a valid solution, it "backtracks" — undoes the last choice and tries another.', docs: 'https://en.wikipedia.org/wiki/Backtracking' } },
      { id: 'b2000003-0000-4000-8001-000000000005', moduleId: 'b2000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'What is the time complexity of computing Fibonacci(n) naively (without memoization)?', choices: ['O(n)', 'O(n log n)', 'O(2^n)', 'O(n²)'], answer: '2', tags: ['recursion', 'fibonacci', 'complexity'], explanation: 'Naive Fibonacci makes two recursive calls: fib(n-1) and fib(n-2). The call tree has ~2^n nodes. With memoization, it becomes O(n). With tabulation (DP), O(n) time and O(1) space.', docs: 'https://en.wikipedia.org/wiki/Backtracking' } },
      { id: 'b2000003-0000-4000-8001-000000000006', moduleId: 'b2000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is tail recursion and why does it matter?', choices: ['Recursion where the base case is at the bottom', 'Recursion where the recursive call is the last operation in the function, enabling compiler optimization to reuse the stack frame', 'Recursion that calls itself in a loop', 'Recursion with no base case'], answer: '1', tags: ['recursion', 'tail-recursion', 'optimization'], explanation: 'In tail recursion, the recursive call is the last thing the function does. Compilers can optimize this to a loop (tail call optimization), reducing stack space from O(n) to O(1). JavaScript supports TCO in strict mode.', docs: 'https://en.wikipedia.org/wiki/Backtracking' } },
      { id: 'b2000003-0000-4000-8001-000000000007', moduleId: 'b2000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'In the N-Queens problem, what backtracking optimization prunes the search space?', choices: ['Only checking the first n/2 columns', 'Checking if placing a queen is safe (no row/column/diagonal conflicts) before recursing', 'Sorting queens by value', 'Using a hash map for O(1) lookups'], answer: '1', tags: ['backtracking', 'n-queens', 'pruning'], explanation: 'Before placing a queen, check if it conflicts with any already-placed queen (same row, column, or diagonal). If so, skip — don\'t recurse. This pruning dramatically reduces the search space from n! to manageable.', docs: 'https://en.wikipedia.org/wiki/Backtracking' } },
      { id: 'b2000003-0000-4000-8001-000000000008', moduleId: 'b2000000-0000-4000-8000-000000000003', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which problems are classically solved with backtracking? (select all that apply)', choices: ['N-Queens', 'Sudoku solver', 'Generating all permutations', 'Binary search'], answer: '[0,1,2]', tags: ['backtracking', 'problems'], explanation: 'N-Queens, Sudoku, and permutation/combination generation are classic backtracking problems — they explore a decision tree and prune invalid branches. Binary search is a different paradigm.', docs: 'https://en.wikipedia.org/wiki/Backtracking' } },
      { id: 'b2000003-0000-4000-8001-000000000009', moduleId: 'b2000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'How do you convert a recursive DFS to an iterative one?', choices: ['Use a queue instead of recursion', 'Use an explicit stack to simulate the call stack', 'Use memoization', 'Use tail call optimization'], answer: '1', tags: ['recursion', 'dfs', 'iterative'], explanation: 'Replace the call stack with an explicit stack data structure. Push the initial node, then loop: pop a node, process it, push its children. This avoids stack overflow for deep graphs and is often more memory-efficient.', docs: 'https://en.wikipedia.org/wiki/Backtracking' } },
      { id: 'b2000003-0000-4000-8001-000000000010', moduleId: 'b2000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'What is the time complexity of generating all subsets of a set of n elements?', choices: ['O(n)', 'O(n²)', 'O(2^n)', 'O(n!)'], answer: '2', tags: ['recursion', 'subsets', 'complexity'], explanation: 'A set of n elements has 2^n subsets (each element is either included or not). Generating all subsets requires O(2^n) time. Backtracking generates them by making include/exclude choices at each step.', docs: 'https://en.wikipedia.org/wiki/Backtracking' } },
      { id: 'b2000003-0000-4000-8001-000000000011', moduleId: 'b2000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'What is the time complexity of generating all permutations of n elements?', choices: ['O(2^n)', 'O(n²)', 'O(n!)', 'O(n log n)'], answer: '2', tags: ['recursion', 'permutations', 'complexity'], explanation: 'There are n! permutations of n elements. Generating all requires O(n × n!) time (n! permutations, each of length n to copy). The backtracking tree has n! leaves.', docs: 'https://en.wikipedia.org/wiki/Backtracking' } },
      { id: 'b2000003-0000-4000-8001-000000000012', moduleId: 'b2000000-0000-4000-8000-000000000003', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which techniques can reduce exponential recursion to polynomial time? (select all that apply)', choices: ['Memoization (top-down DP)', 'Tabulation (bottom-up DP)', 'Greedy pruning in backtracking', 'Using a larger stack size'], answer: '[0,1,2]', tags: ['optimization', 'memoization', 'dp'], explanation: 'Memoization and tabulation both convert overlapping subproblems from exponential to polynomial. Greedy pruning in backtracking reduces constants but cannot change exponential worst-case. A larger stack does not help complexity.', docs: 'https://en.wikipedia.org/wiki/Backtracking' } },

      // ── Module 4: Dynamic Programming ──
      { id: 'b2000004-0000-4000-8001-000000000001', moduleId: 'b2000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What are the two key properties a problem must have for dynamic programming to apply?', choices: ['Greedy choice and local optimum', 'Overlapping subproblems and optimal substructure', 'Recursion and sorting', 'Graph structure and BFS'], answer: '1', tags: ['dp', 'fundamentals'], explanation: 'Overlapping subproblems: the same subproblem is solved multiple times. Optimal substructure: optimal solution contains optimal solutions to subproblems. Both are required for DP to be beneficial.', docs: 'https://en.wikipedia.org/wiki/Dynamic_programming' } },
      { id: 'b2000004-0000-4000-8001-000000000002', moduleId: 'b2000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What is the difference between top-down and bottom-up DP?', choices: ['Top-down is faster; bottom-up is easier', 'Top-down (memoization) starts from the problem and caches recursively; bottom-up (tabulation) builds from base cases up', 'Top-down uses arrays; bottom-up uses hash maps', 'They always produce different results'], answer: '1', tags: ['dp', 'top-down', 'bottom-up'], explanation: 'Top-down: recursive + memo cache. Easy to code, only solves needed subproblems. Bottom-up: iterative, fills DP table from smallest subproblems up. Often faster in practice (no recursion overhead).', docs: 'https://en.wikipedia.org/wiki/Dynamic_programming' } },
      { id: 'b2000004-0000-4000-8001-000000000003', moduleId: 'b2000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What is the time complexity of the 0/1 knapsack problem with DP?', choices: ['O(n²)', 'O(n × W) where W is the capacity', 'O(2^n)', 'O(n log n)'], answer: '1', tags: ['dp', 'knapsack'], explanation: 'The DP table has n rows (items) and W+1 columns (capacities). Each cell is filled in O(1). Total: O(n × W). Note: this is pseudo-polynomial (depends on W, not just n).', docs: 'https://en.wikipedia.org/wiki/Dynamic_programming' } },
      { id: 'b2000004-0000-4000-8001-000000000004', moduleId: 'b2000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What is the Longest Common Subsequence (LCS) problem?', choices: ['Finding the longest sorted subarray', 'Finding the longest subsequence present in both strings (not necessarily contiguous)', 'Finding common elements in two arrays', 'Finding the longest palindrome'], answer: '1', tags: ['dp', 'lcs'], explanation: 'LCS finds the longest sequence of characters appearing in the same relative order in both strings, but not necessarily contiguously. DP solution: O(m×n) time and space, where m, n are string lengths.', docs: 'https://en.wikipedia.org/wiki/Dynamic_programming' } },
      { id: 'b2000004-0000-4000-8001-000000000005', moduleId: 'b2000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'What is the recurrence for the coin change problem (minimum coins to make amount)?', choices: ['dp[i] = dp[i-1] + 1', 'dp[i] = min(dp[i - coin] + 1) for each coin ≤ i', 'dp[i] = dp[i/2] + 1', 'dp[i] = dp[i-1] × coin'], answer: '1', tags: ['dp', 'coin-change'], explanation: 'dp[i] = min coins to make amount i. For each coin c ≤ i: dp[i] = min(dp[i], dp[i-c] + 1). Base: dp[0] = 0. Time: O(amount × coins). Space: O(amount).', docs: 'https://en.wikipedia.org/wiki/Dynamic_programming' } },
      { id: 'b2000004-0000-4000-8001-000000000006', moduleId: 'b2000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is the optimal substructure of the shortest path problem (Bellman-Ford / Dijkstra)?', choices: ['The shortest path between any two nodes is always unique', 'Any subpath of a shortest path is itself a shortest path between its endpoints', 'Shortest paths never contain cycles', 'All edge weights must be positive'], answer: '1', tags: ['dp', 'shortest-path', 'optimal-substructure'], explanation: 'Optimal substructure for shortest paths: if P is a shortest path from u to v, then for any intermediate node w on P, the subpaths u→w and w→v are also shortest paths. This enables DP-based algorithms.', docs: 'https://en.wikipedia.org/wiki/Dynamic_programming' } },
      { id: 'b2000004-0000-4000-8001-000000000007', moduleId: 'b2000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'How can space complexity of a 2D DP table sometimes be optimized to O(n)?', choices: ['Using binary indexing', 'If each row depends only on the previous row, use two 1D arrays (current and previous) instead of the full 2D table', 'Using hashing rows', 'Using bit manipulation'], answer: '1', tags: ['dp', 'space-optimization'], explanation: 'When dp[i][j] depends only on dp[i-1][...], keep only two 1D arrays. Further, if it depends only on dp[i][j-1] and dp[i-1][j], a single 1D array updated in the right order suffices — O(n) space.', docs: 'https://en.wikipedia.org/wiki/Dynamic_programming' } },
      { id: 'b2000004-0000-4000-8001-000000000008', moduleId: 'b2000000-0000-4000-8000-000000000004', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which of the following are classic DP problems? (select all that apply)', choices: ['Longest Increasing Subsequence', 'Edit Distance', 'Matrix Chain Multiplication', 'Dijkstra\'s algorithm'], answer: '[0,1,2]', tags: ['dp', 'classic-problems'], explanation: 'LIS, Edit Distance, and Matrix Chain Multiplication are classic DP problems. Dijkstra\'s algorithm uses a greedy approach (priority queue), not DP — though shortest path has optimal substructure, Dijkstra is greedy.', docs: 'https://en.wikipedia.org/wiki/Dynamic_programming' } },
      { id: 'b2000004-0000-4000-8001-000000000009', moduleId: 'b2000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'What is the time complexity of the Edit Distance (Levenshtein) algorithm?', choices: ['O(n + m)', 'O(n × m)', 'O(n log m)', 'O(2^(n+m))'], answer: '1', tags: ['dp', 'edit-distance', 'complexity'], explanation: 'Edit Distance fills an (n+1) × (m+1) DP table where n, m are string lengths. Each cell: O(1). Total: O(n × m). Space: O(n × m), reducible to O(min(n,m)) with the rolling array trick.', docs: 'https://en.wikipedia.org/wiki/Dynamic_programming' } },
      { id: 'b2000004-0000-4000-8001-000000000010', moduleId: 'b2000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'What is interval DP and give an example?', choices: ['DP over a range [i,j] where subproblems are smaller intervals; e.g., Matrix Chain Multiplication or Burst Balloons', 'DP with index intervals in time scheduling', 'Solving DP problems in O(n) using sliding window', 'DP for interval trees'], answer: '0', tags: ['dp', 'interval-dp'], explanation: 'Interval DP: define dp[i][j] as the solution for subarray [i..j]. Fill by increasing interval length. Matrix Chain Multiplication: dp[i][j] = min cost to multiply matrices i..j. Burst Balloons is another example.', docs: 'https://en.wikipedia.org/wiki/Dynamic_programming' } },
      { id: 'b2000004-0000-4000-8001-000000000011', moduleId: 'b2000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'What is the time complexity of the Longest Increasing Subsequence with binary search optimization?', choices: ['O(n²)', 'O(n log n)', 'O(n)', 'O(n²log n)'], answer: '1', tags: ['dp', 'lis', 'binary-search'], explanation: 'Naive LIS DP is O(n²). The patience sorting optimization maintains a "tails" array and uses binary search to find the correct position, achieving O(n log n) while using O(n) space.', docs: 'https://en.wikipedia.org/wiki/Dynamic_programming' } },
      { id: 'b2000004-0000-4000-8001-000000000012', moduleId: 'b2000000-0000-4000-8000-000000000004', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which of the following statements about DP are true? (select all that apply)', choices: ['DP always requires exponential space', 'Tabulation (bottom-up) avoids recursion overhead', 'Memoization only solves needed subproblems', 'All greedy problems can be solved with DP but not vice versa'], answer: '[1,2,3]', tags: ['dp', 'theory'], explanation: 'DP does NOT always require exponential space — many problems use O(n) or O(n²). Tabulation avoids function call overhead. Memoization only computes required subproblems. All greedy problems are subsets of DP-solvable problems.', docs: 'https://en.wikipedia.org/wiki/Dynamic_programming' } },

      // ── Module 5: Graph Algorithms ──
      { id: 'b2000005-0000-4000-8001-000000000001', moduleId: 'b2000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What data structure does BFS use internally?', choices: ['Stack', 'Queue', 'Priority Queue', 'Heap'], answer: '1', tags: ['bfs', 'graph'], explanation: 'BFS uses a queue (FIFO). Start: enqueue source. Loop: dequeue a node, visit it, enqueue unvisited neighbors. This explores nodes level by level, guaranteeing shortest path in unweighted graphs.', docs: 'https://en.wikipedia.org/wiki/Graph_traversal' } },
      { id: 'b2000005-0000-4000-8001-000000000002', moduleId: 'b2000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What data structure does DFS use internally?', choices: ['Queue', 'Stack (or recursion)', 'Hash Map', 'Priority Queue'], answer: '1', tags: ['dfs', 'graph'], explanation: 'DFS uses a stack — either an explicit stack or the call stack via recursion. It explores as deep as possible before backtracking. Time: O(V+E). Used for topological sort, cycle detection, connected components.', docs: 'https://en.wikipedia.org/wiki/Graph_traversal' } },
      { id: 'b2000005-0000-4000-8001-000000000003', moduleId: 'b2000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What is the time complexity of Dijkstra\'s algorithm with a min-heap?', choices: ['O(V²)', 'O((V + E) log V)', 'O(E log E)', 'O(V log E)'], answer: '1', tags: ['dijkstra', 'complexity'], explanation: 'With a binary min-heap: each vertex extraction is O(log V), done V times = O(V log V). Each edge relaxation is O(log V), done E times = O(E log V). Total: O((V + E) log V).', docs: 'https://en.wikipedia.org/wiki/Graph_traversal' } },
      { id: 'b2000005-0000-4000-8001-000000000004', moduleId: 'b2000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What is topological sorting and when is it applicable?', choices: ['Sorting graph nodes alphabetically', 'Linear ordering of vertices such that for every edge u→v, u comes before v; applicable only to DAGs', 'Finding shortest path in a DAG', 'Sorting edges by weight'], answer: '1', tags: ['topological-sort', 'dag'], explanation: 'Topological sort orders nodes of a Directed Acyclic Graph (DAG) so dependencies come first. Used for task scheduling, build systems, course prerequisites. Impossible if the graph has cycles.', docs: 'https://en.wikipedia.org/wiki/Graph_traversal' } },
      { id: 'b2000005-0000-4000-8001-000000000005', moduleId: 'b2000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'Why can\'t Dijkstra\'s algorithm handle negative edge weights?', choices: ['It uses a min-heap which cannot store negatives', 'A visited node might need to be updated again when a negative edge creates a shorter path, but Dijkstra never revisits nodes', 'It only works on undirected graphs', 'Negative weights cause infinite loops'], answer: '1', tags: ['dijkstra', 'negative-weights'], explanation: 'Dijkstra\'s greedy assumption: once a node is settled, its shortest distance is final. A negative edge to an already-settled node could improve its distance, violating this. Use Bellman-Ford for negative weights.', docs: 'https://en.wikipedia.org/wiki/Graph_traversal' } },
      { id: 'b2000005-0000-4000-8001-000000000006', moduleId: 'b2000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is Union-Find (Disjoint Set Union) used for?', choices: ['Finding shortest paths', 'Efficiently tracking connected components and detecting cycles; supports union() and find() operations', 'Topological sorting', 'Minimum spanning tree only'], answer: '1', tags: ['union-find', 'dsu'], explanation: 'Union-Find groups elements into disjoint sets. find(x) returns the set representative. union(x,y) merges sets. With path compression and union by rank, both operations are O(α(n)) ≈ O(1) amortized. Used in Kruskal\'s MST and cycle detection.', docs: 'https://en.wikipedia.org/wiki/Graph_traversal' } },
      { id: 'b2000005-0000-4000-8001-000000000007', moduleId: 'b2000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'What is the difference between Prim\'s and Kruskal\'s algorithms for MST?', choices: ['Prim\'s is for directed graphs; Kruskal\'s for undirected', 'Prim\'s grows the MST from a starting vertex greedily; Kruskal\'s sorts all edges by weight and adds them if they don\'t create a cycle', 'Prim\'s uses DFS; Kruskal\'s uses BFS', 'They produce different MSTs'], answer: '1', tags: ['mst', 'prims', 'kruskals'], explanation: 'Prim\'s: start from a node, greedily add the cheapest edge connecting the tree to a new node. O((V+E) log V) with heap. Kruskal\'s: sort edges, add each if it joins two different components (Union-Find). O(E log E).', docs: 'https://en.wikipedia.org/wiki/Graph_traversal' } },
      { id: 'b2000005-0000-4000-8001-000000000008', moduleId: 'b2000000-0000-4000-8000-000000000005', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which algorithms can detect cycles in a graph? (select all that apply)', choices: ['DFS with a "visiting" / "visited" state', 'Union-Find', 'BFS with parent tracking', 'Topological sort (cycle exists if not all nodes are processed)'], answer: '[0,1,2,3]', tags: ['cycle-detection', 'graph'], explanation: 'All four detect cycles: DFS uses grey/white/black coloring. Union-Find detects when two nodes are already in the same component. BFS detects when a non-parent neighbor is already visited. Topo sort fails if in-degree never reaches 0.', docs: 'https://en.wikipedia.org/wiki/Graph_traversal' } },
      { id: 'b2000005-0000-4000-8001-000000000009', moduleId: 'b2000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'What is the time complexity of Bellman-Ford algorithm?', choices: ['O(V log V)', 'O(V × E)', 'O(E log V)', 'O(V²)'], answer: '1', tags: ['bellman-ford', 'complexity'], explanation: 'Bellman-Ford relaxes all E edges V-1 times (V-1 iterations needed to find shortest paths of at most V-1 hops). Time: O(V×E). A Vth pass that still relaxes indicates a negative cycle.', docs: 'https://en.wikipedia.org/wiki/Graph_traversal' } },
      { id: 'b2000005-0000-4000-8001-000000000010', moduleId: 'b2000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'What is Floyd-Warshall used for and what is its time complexity?', choices: ['Single-source shortest path: O(V log V)', 'All-pairs shortest paths: O(V³)', 'Minimum spanning tree: O(E log E)', 'Cycle detection: O(V + E)'], answer: '1', tags: ['floyd-warshall', 'all-pairs', 'complexity'], explanation: 'Floyd-Warshall computes shortest paths between all pairs of vertices. dp[i][j][k] = shortest path from i to j using only vertices {1..k}. Three nested loops = O(V³). Handles negative weights but not negative cycles.', docs: 'https://en.wikipedia.org/wiki/Graph_traversal' } },
      { id: 'b2000005-0000-4000-8001-000000000011', moduleId: 'b2000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'What is Kosaraju\'s algorithm used for?', choices: ['Finding minimum spanning tree', 'Finding all Strongly Connected Components (SCCs) in a directed graph in O(V+E)', 'Finding shortest path with negative edges', 'Finding the diameter of a graph'], answer: '1', tags: ['scc', 'kosaraju', 'graph'], explanation: 'Kosaraju\'s: 1) DFS on original graph, push nodes to stack in finish order. 2) Transpose graph. 3) DFS in stack order on transposed graph — each DFS tree is an SCC. Total: O(V+E).', docs: 'https://en.wikipedia.org/wiki/Graph_traversal' } },
      { id: 'b2000005-0000-4000-8001-000000000012', moduleId: 'b2000000-0000-4000-8000-000000000005', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which of the following are true about BFS vs DFS? (select all that apply)', choices: ['BFS finds shortest path in unweighted graphs', 'DFS uses less memory than BFS for wide graphs', 'DFS is better for detecting cycles', 'BFS cannot be used on directed graphs'], answer: '[0,1,2]', tags: ['bfs', 'dfs', 'comparison'], explanation: 'BFS guarantees shortest path in unweighted graphs. DFS uses O(depth) memory vs BFS O(width) — better for wide trees. DFS cycle detection is standard. BFS works fine on directed graphs too.', docs: 'https://en.wikipedia.org/wiki/Graph_traversal' } },
    ];

    for (const q of questions) {
      await queryRunner.query(
        `INSERT INTO "qcm_question" ("id", "moduleId", "type", "difficulty", "sortOrder", "data")
         VALUES ($1, $2, $3, $4, $5, $6)
         ON CONFLICT ("id") DO NOTHING`,
        [q.id, q.moduleId, q.type, q.difficulty, q.sortOrder, q.data]
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const ids: string[] = [];
    for (let m = 1; m <= 5; m++) {
      for (let q = 1; q <= 12; q++) {
        ids.push(`b200000${m}-0000-4000-8001-${String(q).padStart(12, '0')}`);
      }
    }
    await queryRunner.query(`DELETE FROM "qcm_question" WHERE "id" = ANY($1)`, [ids]);
  }
}
