import type { MigrationInterface, QueryRunner } from 'typeorm';

export class AddAngular19Questions2_1773962001000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const questions = [
      // ── Module 6: Routing & Lazy Loading ──
      { id: 'a1000006-0000-4000-8001-000000000001', moduleId: 'a1000000-0000-4000-8000-000000000006', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'How do you lazily load a standalone component in Angular 19 routing?', choices: ['loadChildren: () => import(\'./my.component\')', 'loadComponent: () => import(\'./my.component\').then(m => m.MyComponent)', 'lazy: true in the route config', 'RouterModule.forChild([...])'], answer: '1', tags: ['routing', 'lazy-loading'], explanation: 'loadComponent is the standalone equivalent of loadChildren for single components. It code-splits the component into a separate chunk loaded on navigation.', docs: 'https://angular.dev/guide/routing/common-router-tasks#lazy-loading' } },
      { id: 'a1000006-0000-4000-8001-000000000002', moduleId: 'a1000000-0000-4000-8000-000000000006', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'Which function configures routing in a standalone Angular 19 app?', choices: ['RouterModule.forRoot(routes)', 'provideRouter(routes)', 'withRouter(routes)', 'configureRouter(routes)'], answer: '1', tags: ['routing', 'standalone'], explanation: 'provideRouter(routes) is passed to bootstrapApplication providers (or appConfig). It replaces RouterModule.forRoot() in standalone apps and supports functional feature flags like withComponentInputBinding().', docs: 'https://angular.dev/api/router/provideRouter' } },
      { id: 'a1000006-0000-4000-8001-000000000003', moduleId: 'a1000000-0000-4000-8000-000000000006', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What does withComponentInputBinding() do in Angular routing?', choices: ['Enables two-way binding in templates', 'Automatically binds route parameters, query params, and data to @Input() / input() properties of the routed component', 'Creates a binding between the router and the store', 'Allows binding events to router events'], answer: '1', tags: ['routing', 'inputs', 'withComponentInputBinding'], explanation: 'withComponentInputBinding() (passed to provideRouter) makes route params, query params, and static data automatically flow into the component\'s inputs — no need to inject ActivatedRoute manually.', docs: 'https://angular.dev/api/router/withComponentInputBinding' } },
      { id: 'a1000006-0000-4000-8001-000000000004', moduleId: 'a1000000-0000-4000-8000-000000000006', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'How do you read the current route state as a signal in Angular 19?', choices: ['inject(ActivatedRoute).params', 'inject(Router).currentRoute()', 'toSignal(inject(ActivatedRoute).params)', 'routeSignal()'], answer: '2', tags: ['routing', 'signals'], explanation: 'ActivatedRoute still exposes Observables. Wrap them with toSignal() from @angular/core/rxjs-interop to use route data reactively as signals.', docs: 'https://angular.dev/guide/rxjs-interop' } },
      { id: 'a1000006-0000-4000-8001-000000000005', moduleId: 'a1000000-0000-4000-8000-000000000006', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'How do you write a functional CanActivate guard in Angular 19?', choices: ['class MyGuard implements CanActivate { canActivate() { ... } }', 'export const myGuard: CanActivateFn = (route, state) => inject(AuthService).check()', 'function myGuard() { return true; }', '@Guard() export class MyGuard { }'], answer: '1', tags: ['routing', 'guards', 'functional'], explanation: 'A CanActivateFn is a plain function taking (ActivatedRouteSnapshot, RouterStateSnapshot) that returns boolean | UrlTree | Observable/Promise thereof. inject() is valid inside it.', docs: 'https://angular.dev/api/router/CanActivateFn' } },
      { id: 'a1000006-0000-4000-8001-000000000006', moduleId: 'a1000000-0000-4000-8000-000000000006', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is the Router.navigate() return value in Angular 19?', choices: ['void', 'boolean', 'Promise<boolean>', 'Observable<boolean>'], answer: '2', tags: ['routing', 'navigate'], explanation: 'Router.navigate() and Router.navigateByUrl() return Promise<boolean> — true if navigation succeeded, false if it was cancelled by a guard or redirected.', docs: 'https://angular.dev/api/router/Router#navigate' } },
      { id: 'a1000006-0000-4000-8001-000000000007', moduleId: 'a1000000-0000-4000-8000-000000000006', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'How do you preload all lazy routes in Angular?', choices: ['withPreloading(AllModules)', 'withPreloading(PreloadAllModules)', 'preloadAll: true in provideRouter', 'RouterModule.forRoot(routes, { preloadingStrategy: NoPreloading })'], answer: '1', tags: ['routing', 'preloading'], explanation: 'withPreloading(PreloadAllModules) passed to provideRouter enables eager background loading of all lazy chunks after the initial navigation, improving subsequent navigations.', docs: 'https://angular.dev/api/router/withPreloading' } },
      { id: 'a1000006-0000-4000-8001-000000000008', moduleId: 'a1000000-0000-4000-8000-000000000006', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which router features are available via withXxx() helpers in Angular 19? (select all that apply)', choices: ['withComponentInputBinding()', 'withViewTransitions()', 'withPreloading()', 'withDebugTracing()'], answer: '[0,1,2,3]', tags: ['routing', 'features'], explanation: 'Angular\'s functional router features include withComponentInputBinding(), withViewTransitions(), withPreloading(), withDebugTracing(), withHashLocation(), withEnabledBlockingInitialNavigation() and more.', docs: 'https://angular.dev/api/router/provideRouter' } },
      { id: 'a1000006-0000-4000-8001-000000000009', moduleId: 'a1000000-0000-4000-8000-000000000006', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'What is a Router resolver and how is it written functionally in Angular 19?', choices: ['A class implementing Resolve<T>', 'A ResolveFn<T> arrow function using inject() to prefetch data before the route activates', 'An async guard', 'A component lifecycle hook'], answer: '1', tags: ['routing', 'resolver', 'functional'], explanation: 'ResolveFn<T> is a function (route, state) => T | Observable<T> | Promise<T>. It runs before the route component activates and makes the resolved value available via ActivatedRoute.data or component inputs (with withComponentInputBinding).', docs: 'https://angular.dev/api/router/ResolveFn' } },
      { id: 'a1000006-0000-4000-8001-000000000010', moduleId: 'a1000000-0000-4000-8000-000000000006', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'How do you enable View Transitions API with Angular Router 19?', choices: ['withViewTransitions() in provideRouter()', 'viewTransitions: true in RouterModule.forRoot', 'import { ViewTransitionsModule }', 'router.enableViewTransitions()'], answer: '0', tags: ['routing', 'view-transitions'], explanation: 'withViewTransitions() enables browser View Transitions API integration so Angular uses document.startViewTransition() during navigations. Optional onViewTransitionCreated callback allows fine-grained control.', docs: 'https://angular.dev/api/router/withViewTransitions' } },
      { id: 'a1000006-0000-4000-8001-000000000011', moduleId: 'a1000000-0000-4000-8000-000000000006', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'What does the CanMatch guard do differently from CanActivate?', choices: ['It is identical to CanActivate', 'It prevents the route from being matched at all — if false, Angular tries the next matching route instead of blocking navigation', 'It runs after the component is loaded', 'It only works with lazy-loaded routes'], answer: '1', tags: ['routing', 'guards', 'canmatch'], explanation: 'CanMatch prevents route matching entirely. If it returns false, Angular skips that route and tries the next one in the config. CanActivate blocks activation but the route was already matched.', docs: 'https://angular.dev/api/router/CanMatchFn' } },
      { id: 'a1000006-0000-4000-8001-000000000012', moduleId: 'a1000000-0000-4000-8000-000000000006', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which of the following are ways to navigate programmatically in Angular 19? (select all that apply)', choices: ['inject(Router).navigate(["/path"])', 'inject(Router).navigateByUrl("/path")', '[routerLink]="/path"', 'inject(Location).go("/path")'], answer: '[0,1,3]', tags: ['routing', 'navigation'], explanation: 'Programmatic navigation: Router.navigate(), Router.navigateByUrl(), and Location.go(). [routerLink] is a template directive, not programmatic navigation.', docs: 'https://angular.dev/api/router/Router' } },

      // ── Module 7: Reactive Forms & Typed Forms ──
      { id: 'a1000007-0000-4000-8001-000000000001', moduleId: 'a1000000-0000-4000-8000-000000000007', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What type does FormControl have in Angular\'s typed forms?', choices: ['FormControl<any>', 'FormControl<T | null>', 'FormControl<string>', 'UntypedFormControl'], answer: '1', tags: ['forms', 'typed-forms'], explanation: 'FormControl<T> is generically typed. By default it includes null because reset() sets the value to null. Use FormControl<T> with nonNullable: true or NonNullableFormBuilder to exclude null.', docs: 'https://angular.dev/guide/forms/typed-forms' } },
      { id: 'a1000007-0000-4000-8001-000000000002', moduleId: 'a1000000-0000-4000-8000-000000000007', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'How do you create a non-nullable FormControl in Angular?', choices: ['new FormControl<string>(\'\')', 'new FormControl(\'\')', 'new FormControl(\'\', { nonNullable: true })', 'new RequiredFormControl(\'\')'], answer: '2', tags: ['forms', 'typed-forms', 'nonNullable'], explanation: '{ nonNullable: true } in the options makes the control\'s type T instead of T | null. reset() will restore the initial value instead of null. NonNullableFormBuilder also creates non-nullable controls by default.', docs: 'https://angular.dev/guide/forms/typed-forms#non-nullable-controls' } },
      { id: 'a1000007-0000-4000-8001-000000000003', moduleId: 'a1000000-0000-4000-8000-000000000007', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What is the difference between FormGroup.value and FormGroup.getRawValue()?', choices: ['They are identical', 'value excludes disabled control values; getRawValue() includes all values including disabled', 'getRawValue() validates before returning', 'value returns a signal; getRawValue() returns a plain object'], answer: '1', tags: ['forms', 'formgroup'], explanation: 'value omits disabled controls. getRawValue() returns values for all controls regardless of disabled state. Use getRawValue() when you need the complete form value.', docs: 'https://angular.dev/api/forms/FormGroup#getRawValue' } },
      { id: 'a1000007-0000-4000-8001-000000000004', moduleId: 'a1000000-0000-4000-8000-000000000007', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'Which Angular validator checks that a control value matches a pattern?', choices: ['Validators.required', 'Validators.pattern()', 'Validators.regex()', 'Validators.match()'], answer: '1', tags: ['forms', 'validators'], explanation: 'Validators.pattern(regex | string) returns a validator function that checks the control value against the regular expression. It is available as a static method on the Validators class.', docs: 'https://angular.dev/api/forms/Validators#pattern' } },
      { id: 'a1000007-0000-4000-8001-000000000005', moduleId: 'a1000000-0000-4000-8000-000000000007', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'How do you add a cross-field validator to a FormGroup in Angular?', choices: ['Pass it as the third argument to the FormControl', 'Pass it to the validators option of the FormGroup itself', 'Use Validators.crossField()', 'Add it to the template with [validator]'], answer: '1', tags: ['forms', 'validators', 'cross-field'], explanation: 'Cross-field validators are passed to the FormGroup\'s validators option: new FormGroup({...}, { validators: passwordMatchValidator }). They receive the group and can access any control\'s value.', docs: 'https://angular.dev/guide/forms/form-validation#cross-field-validation' } },
      { id: 'a1000007-0000-4000-8001-000000000006', moduleId: 'a1000000-0000-4000-8000-000000000007', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is NonNullableFormBuilder in Angular?', choices: ['A form builder that throws on null values', 'A FormBuilder variant where all created controls are non-nullable by default', 'A stricter version that validates required', 'A builder for template-driven forms'], answer: '1', tags: ['forms', 'form-builder', 'nonNullable'], explanation: 'inject(NonNullableFormBuilder) creates a builder where all controls have nonNullable: true by default. This avoids writing { nonNullable: true } for every control when null is never needed.', docs: 'https://angular.dev/api/forms/NonNullableFormBuilder' } },
      { id: 'a1000007-0000-4000-8001-000000000007', moduleId: 'a1000000-0000-4000-8000-000000000007', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'How do you subscribe to value changes on a specific FormControl?', choices: ['control.onChange(fn)', 'control.valueChanges.subscribe(fn)', 'control.on("change", fn)', 'effect(() => control.value)'], answer: '1', tags: ['forms', 'reactive'], explanation: 'Every AbstractControl exposes valueChanges (Observable<T>) and statusChanges (Observable<string>) that emit on every change. Use toSignal(control.valueChanges) to integrate with signals.', docs: 'https://angular.dev/api/forms/AbstractControl#valueChanges' } },
      { id: 'a1000007-0000-4000-8001-000000000008', moduleId: 'a1000000-0000-4000-8000-000000000007', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which of the following are built-in Angular validators? (select all that apply)', choices: ['Validators.required', 'Validators.minLength()', 'Validators.email', 'Validators.unique()'], answer: '[0,1,2]', tags: ['forms', 'validators'], explanation: 'Built-in validators: required, requiredTrue, email, min, max, minLength, maxLength, pattern, nullValidator. There is no built-in Validators.unique() — that must be a custom async validator.', docs: 'https://angular.dev/api/forms/Validators' } },
      { id: 'a1000007-0000-4000-8001-000000000009', moduleId: 'a1000000-0000-4000-8000-000000000007', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'How do you create an async validator in Angular reactive forms?', choices: ['Validators.async(fn)', 'A function returning Observable<ValidationErrors | null> or Promise<ValidationErrors | null>', 'AsyncValidator class with validate()', 'Adding async: true to the validator options'], answer: '1', tags: ['forms', 'async-validator'], explanation: 'An AsyncValidatorFn receives an AbstractControl and returns Observable<ValidationErrors | null> or Promise. Register it as the third argument to FormControl: new FormControl(\'\', [], [myAsyncValidator]).', docs: 'https://angular.dev/guide/forms/form-validation#async-validation' } },
      { id: 'a1000007-0000-4000-8001-000000000010', moduleId: 'a1000000-0000-4000-8000-000000000007', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'What is the purpose of FormArray in Angular reactive forms?', choices: ['To group heterogeneous controls', 'To manage a dynamic list of controls where controls can be added or removed at runtime', 'To validate array values', 'To create read-only form fields'], answer: '1', tags: ['forms', 'form-array'], explanation: 'FormArray manages an ordered list of controls. Use push(), removeAt(), and insert() to dynamically manage controls. Typed as FormArray<FormControl<T>> in Angular\'s typed forms.', docs: 'https://angular.dev/api/forms/FormArray' } },
      { id: 'a1000007-0000-4000-8001-000000000011', moduleId: 'a1000000-0000-4000-8000-000000000007', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'How do you use signal-based form state observation in Angular 19?', choices: ['new SignalFormControl()', 'toSignal(control.valueChanges, { initialValue: control.value })', 'control.asSignal()', 'signalForm()'], answer: '1', tags: ['forms', 'signals'], explanation: 'Wrap control.valueChanges with toSignal(..., { initialValue: control.value }) to get a signal that stays in sync with the form control. This bridges reactive forms with Angular\'s signal system.', docs: 'https://angular.dev/guide/rxjs-interop' } },
      { id: 'a1000007-0000-4000-8001-000000000012', moduleId: 'a1000000-0000-4000-8000-000000000007', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'What are the AbstractControl status values in Angular? (select all that apply)', choices: ['VALID', 'INVALID', 'PENDING', 'DISABLED'], answer: '[0,1,2,3]', tags: ['forms', 'status'], explanation: 'AbstractControl.status can be VALID, INVALID, PENDING (async validation in progress), or DISABLED. Check control.valid, control.invalid, control.pending, control.disabled as boolean shortcuts.', docs: 'https://angular.dev/api/forms/AbstractControl#status' } },

      // ── Module 8: HttpClient & Server Communication ──
      { id: 'a1000008-0000-4000-8001-000000000001', moduleId: 'a1000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'How do you provide HttpClient in a standalone Angular 19 app?', choices: ['imports: [HttpClientModule]', 'provideHttpClient()', 'providers: [HttpClient]', 'HttpModule.forRoot()'], answer: '1', tags: ['http', 'standalone'], explanation: 'provideHttpClient() is passed to bootstrapApplication providers or appConfig. It replaces HttpClientModule for standalone apps and supports optional feature flags like withFetch() and withInterceptors().', docs: 'https://angular.dev/api/common/http/provideHttpClient' } },
      { id: 'a1000008-0000-4000-8001-000000000002', moduleId: 'a1000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What does withFetch() do when passed to provideHttpClient()?', choices: ['Enables HTTP/2 fetch protocol', 'Uses the native browser fetch() API as the underlying transport instead of XMLHttpRequest', 'Caches all responses', 'Enables streaming responses'], answer: '1', tags: ['http', 'fetch'], explanation: 'withFetch() switches HttpClient\'s transport from XHR to the native fetch() API. This is required when using Angular SSR in Node.js 18+ which has native fetch, and provides better streaming support.', docs: 'https://angular.dev/api/common/http/withFetch' } },
      { id: 'a1000008-0000-4000-8001-000000000003', moduleId: 'a1000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What does HttpClient.get<T>() return?', choices: ['T', 'Promise<T>', 'Observable<T>', 'Signal<T>'], answer: '2', tags: ['http', 'observables'], explanation: 'HttpClient methods return cold Observables. The request is only sent when you subscribe (or use async pipe / toSignal). The generic type parameter types the response body.', docs: 'https://angular.dev/guide/http/making-requests' } },
      { id: 'a1000008-0000-4000-8001-000000000004', moduleId: 'a1000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'How do you add headers to an HttpClient request?', choices: ['httpClient.get(url, headers)', 'httpClient.get(url, { headers: new HttpHeaders({ ... }) })', 'httpClient.setHeaders({ ... })', 'By modifying the global fetch headers'], answer: '1', tags: ['http', 'headers'], explanation: 'Pass an options object with a headers property: { headers: new HttpHeaders({ \'Authorization\': \'Bearer token\' }) }. Headers can also be added globally via functional interceptors.', docs: 'https://angular.dev/guide/http/making-requests#adding-request-headers' } },
      { id: 'a1000008-0000-4000-8001-000000000005', moduleId: 'a1000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'How do you write a functional HTTP interceptor in Angular 19?', choices: ['class MyInterceptor implements HttpInterceptor', '(req: HttpRequest<unknown>, next: HttpHandlerFn) => next(req)', 'app.use((req, res) => next(req))', '@Interceptor() class MyInterceptor'], answer: '1', tags: ['http', 'interceptors', 'functional'], explanation: 'An HttpInterceptorFn is (req: HttpRequest<unknown>, next: HttpHandlerFn) => Observable<HttpEvent<unknown>>. Register with withInterceptors([myFn]) in provideHttpClient().', docs: 'https://angular.dev/guide/http/interceptors' } },
      { id: 'a1000008-0000-4000-8001-000000000006', moduleId: 'a1000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'How do you add a query parameter to an HttpClient request?', choices: ['httpClient.get(url + \'?key=value\')', '{ params: new HttpParams().set(\'key\', \'value\') }', '{ query: { key: \'value\' } }', '{ searchParams: new URLSearchParams() }'], answer: '1', tags: ['http', 'params'], explanation: 'Pass { params: new HttpParams().set(\'key\', \'val\') } or use { params: { key: \'val\' } } shorthand in the options object. HttpParams is immutable — chaining .set() returns a new instance.', docs: 'https://angular.dev/guide/http/making-requests#adding-request-parameters' } },
      { id: 'a1000008-0000-4000-8001-000000000007', moduleId: 'a1000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'What RxJS operator is typically used to handle HTTP errors?', choices: ['catchError()', 'handleError()', 'onError()', 'retry()'], answer: '0', tags: ['http', 'error-handling', 'rxjs'], explanation: 'catchError(err => { ... }) from RxJS is used in pipe() after an HTTP call to handle errors gracefully — returning a fallback observable or rethrowing. Often combined with retry() for transient failures.', docs: 'https://angular.dev/guide/http/making-requests#handling-request-failure' } },
      { id: 'a1000008-0000-4000-8001-000000000008', moduleId: 'a1000000-0000-4000-8000-000000000008', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which of the following HTTP response types can be requested with Angular\'s HttpClient? (select all that apply)', choices: ['json (default)', 'text', 'blob', 'arraybuffer'], answer: '[0,1,2,3]', tags: ['http', 'response-types'], explanation: 'HttpClient supports responseType: \'json\' (default), \'text\', \'blob\', and \'arraybuffer\'. Pass as { responseType: \'blob\' } in the options to get binary responses for file downloads.', docs: 'https://angular.dev/guide/http/making-requests' } },
      { id: 'a1000008-0000-4000-8001-000000000009', moduleId: 'a1000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'How do you use HttpClient inside a signal-based resource() in Angular 19?', choices: ['resource({ loader: () => firstValueFrom(http.get<T>(url)) })', 'httpResource(url)', 'signalHttp.get(url)', 'resource({ loader: () => http.get<T>(url) })'], answer: '0', tags: ['http', 'signals', 'resource'], explanation: 'resource() expects the loader to return a Promise. Use firstValueFrom() from RxJS to convert the HttpClient Observable to a Promise: resource({ request: id, loader: ({ request }) => firstValueFrom(http.get<T>(`/api/${request}`)) }).', docs: 'https://angular.dev/guide/signals/resource' } },
      { id: 'a1000008-0000-4000-8001-000000000010', moduleId: 'a1000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'How do you clone and modify an HttpRequest inside an interceptor?', choices: ['req.headers.set()', 'req.clone({ headers: req.headers.set(\'key\', \'val\') })', 'Object.assign(req, { headers: ... })', 'new HttpRequest(req, { ... })'], answer: '1', tags: ['http', 'interceptors'], explanation: 'HttpRequest is immutable. Use req.clone({ ... }) to create a modified copy. The clone inherits all properties and overrides only what you specify. Then pass the clone to next(cloned).', docs: 'https://angular.dev/guide/http/interceptors' } },
      { id: 'a1000008-0000-4000-8001-000000000011', moduleId: 'a1000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'What is HttpContext and how is it used in Angular 19?', choices: ['A class for storing global HTTP state', 'A per-request map used to pass arbitrary data to interceptors via HttpContextToken', 'A cache for HTTP responses', 'A replacement for HttpHeaders'], answer: '1', tags: ['http', 'context', 'interceptors'], explanation: 'HttpContextToken<T> creates a typed key. Set on a request: { context: new HttpContext().set(MY_TOKEN, value) }. Read in interceptor: req.context.get(MY_TOKEN). Useful for opt-in interceptor behaviour like skipping auth.', docs: 'https://angular.dev/guide/http/interceptors#passing-metadata-to-interceptors' } },
      { id: 'a1000008-0000-4000-8001-000000000012', moduleId: 'a1000000-0000-4000-8000-000000000008', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which options can be passed to provideHttpClient() in Angular 19? (select all that apply)', choices: ['withFetch()', 'withInterceptors([])', 'withRequestsMadeViaParent()', 'withNoXsrfProtection()'], answer: '[0,1,2,3]', tags: ['http', 'providers'], explanation: 'All four are valid: withFetch() (use fetch API), withInterceptors() (functional interceptors), withRequestsMadeViaParent() (hierarchical HTTP), withNoXsrfProtection() (disable CSRF headers).', docs: 'https://angular.dev/api/common/http/provideHttpClient' } },

      // ── Module 9: Change Detection & Zoneless ──
      { id: 'a1000009-0000-4000-8001-000000000001', moduleId: 'a1000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What does ChangeDetectionStrategy.OnPush do?', choices: ['Disables change detection permanently', 'Limits change detection to run only when an @Input reference changes, an event fires, or markForCheck() is called', 'Pushes change detection to the parent', 'Enables zone-free components'], answer: '1', tags: ['change-detection', 'onpush'], explanation: 'OnPush makes Angular skip a component during change detection unless: a bound @Input reference changes, a DOM event fires inside it, markForCheck()/detectChanges() is called, or an async pipe resolves.', docs: 'https://angular.dev/api/core/ChangeDetectionStrategy' } },
      { id: 'a1000009-0000-4000-8001-000000000002', moduleId: 'a1000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What is Zone.js\'s role in traditional Angular apps?', choices: ['It provides HTTP interceptors', 'It monkey-patches async APIs (setTimeout, Promise, fetch) to notify Angular when to run change detection', 'It manages component lifecycle', 'It is Angular\'s module system'], answer: '1', tags: ['zone', 'change-detection'], explanation: 'Zone.js patches browser async APIs and triggers Angular\'s change detection after each async operation. It is what makes Angular automatically update the UI after async events without manual notification.', docs: 'https://angular.dev/guide/change-detection' } },
      { id: 'a1000009-0000-4000-8001-000000000003', moduleId: 'a1000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'How do you enable experimental zoneless change detection in Angular 19?', choices: ['zone: false in angular.json', 'provideExperimentalZonelessChangeDetection() in providers', 'ChangeDetectorRef.detach()', 'Remove zone.js from polyfills'], answer: '1', tags: ['zoneless', 'change-detection'], explanation: 'provideExperimentalZonelessChangeDetection() (passing in bootstrapApplication providers) enables zoneless mode. Angular then relies on signals, markForCheck(), and async pipe to schedule updates — no Zone.js needed.', docs: 'https://angular.dev/guide/experimental/zoneless' } },
      { id: 'a1000009-0000-4000-8001-000000000004', moduleId: 'a1000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What is ChangeDetectorRef.markForCheck() used for?', choices: ['To force re-render of all components', 'To mark an OnPush component and its ancestors as needing change detection on the next cycle', 'To trigger detectChanges() immediately', 'To enable change detection on a detached view'], answer: '1', tags: ['change-detection', 'markForCheck'], explanation: 'markForCheck() marks the component tree from the current component up to root as dirty, so it will be checked in the next change detection cycle. Used with OnPush when state changes occur outside Angular events.', docs: 'https://angular.dev/api/core/ChangeDetectorRef' } },
      { id: 'a1000009-0000-4000-8001-000000000005', moduleId: 'a1000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'How do signals automatically trigger change detection in Angular 19?', choices: ['By calling Zone.js notifyAngular()', 'Angular schedules a change detection check when a signal value changes, without Zone.js', 'Signals use NgZone.run() internally', 'By dispatching a custom DOM event'], answer: '1', tags: ['signals', 'change-detection', 'zoneless'], explanation: 'When a signal used in a template changes, Angular\'s signal graph schedules a targeted check for that component. In zoneless mode, this is the primary mechanism driving UI updates — no Zone.js patch needed.', docs: 'https://angular.dev/guide/signals' } },
      { id: 'a1000009-0000-4000-8001-000000000006', moduleId: 'a1000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is the difference between detectChanges() and markForCheck()?', choices: ['They are the same', 'detectChanges() synchronously runs change detection for this component and its children; markForCheck() schedules the component for the next global CD cycle', 'markForCheck() is for zoneless; detectChanges() is for Zone.js', 'detectChanges() only works with Default strategy'], answer: '1', tags: ['change-detection', 'cdr'], explanation: 'detectChanges() runs immediately and synchronously. markForCheck() only marks the view dirty to be checked in the next scheduled cycle. detectChanges() is preferred for one-off forced updates; markForCheck() for async data.', docs: 'https://angular.dev/api/core/ChangeDetectorRef' } },
      { id: 'a1000009-0000-4000-8001-000000000007', moduleId: 'a1000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'What benefit does zoneless Angular provide over Zone.js-based apps?', choices: ['Unlimited components', 'Smaller bundle size (removes zone.js ~50KB), faster startup, and predictable change detection driven by signals', 'Automatic lazy loading', 'Native SSR without hydration'], answer: '1', tags: ['zoneless', 'performance'], explanation: 'Removing Zone.js saves ~50KB, eliminates unpredictable "change detection on every async event" behaviour, and makes debugging easier. The app relies on signals and explicit scheduling for updates.', docs: 'https://angular.dev/guide/experimental/zoneless' } },
      { id: 'a1000009-0000-4000-8001-000000000008', moduleId: 'a1000000-0000-4000-8000-000000000009', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which of the following trigger change detection in an OnPush component? (select all that apply)', choices: ['An @Input reference changes', 'A signal used in the template changes', 'markForCheck() is called', 'A setTimeout fires inside the component (with Zone.js)'], answer: '[0,1,2,3]', tags: ['change-detection', 'onpush'], explanation: 'All four trigger OnPush CD: input reference change, signal update, markForCheck(), or async event patched by Zone.js. Without Zone.js, setTimeout would NOT trigger CD unless signals or markForCheck are used.', docs: 'https://angular.dev/guide/change-detection' } },
      { id: 'a1000009-0000-4000-8001-000000000009', moduleId: 'a1000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'What does ChangeDetectorRef.detach() do?', choices: ['Removes the component from the DOM', 'Detaches the component\'s change detector so it is never checked automatically until reattach() is called', 'Disables all inputs on the component', 'Destroys the component'], answer: '1', tags: ['change-detection', 'detach'], explanation: 'detach() removes the view from the change detection tree. detectChanges() can still be called manually for on-demand updates. reattach() re-connects it. Useful for high-frequency data or manual rendering control.', docs: 'https://angular.dev/api/core/ChangeDetectorRef' } },
      { id: 'a1000009-0000-4000-8001-000000000010', moduleId: 'a1000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'How do you run code outside Angular\'s zone to avoid triggering change detection?', choices: ['NgZone.runOutside(() => {})', 'inject(NgZone).runOutsideAngular(() => {})', 'zone.skip(() => {})', 'ChangeDetectorRef.runOutside(() => {})'], answer: '1', tags: ['zone', 'performance'], explanation: 'inject(NgZone).runOutsideAngular(fn) executes code (e.g., setInterval for animations) without triggering Angular\'s change detection. Re-enter Angular\'s zone with ngZone.run(() => {}) when you need to update the UI.', docs: 'https://angular.dev/api/core/NgZone#runOutsideAngular' } },
      { id: 'a1000009-0000-4000-8001-000000000011', moduleId: 'a1000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'In Angular 19 zoneless mode, what drives change detection for async operations (like HTTP responses)?', choices: ['Zone.js patches', 'Signals updated by the async operation, or explicit markForCheck() / detectChanges() calls', 'Automatic polling every 16ms', 'Service workers'], answer: '1', tags: ['zoneless', 'signals', 'change-detection'], explanation: 'In zoneless mode, Angular does not know about async operations by default. You must use signals (e.g., toSignal(http.get(...))), update a signal in the subscription, or call markForCheck() after async operations.', docs: 'https://angular.dev/guide/experimental/zoneless' } },
      { id: 'a1000009-0000-4000-8001-000000000012', moduleId: 'a1000000-0000-4000-8000-000000000009', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which of the following are prerequisites for fully zoneless Angular apps in production? (select all that apply)', choices: ['Remove zone.js from polyfills in angular.json', 'Use signals or explicit scheduling for all async state updates', 'Use provideExperimentalZonelessChangeDetection()', 'Set all components to OnPush'], answer: '[0,1,2]', tags: ['zoneless', 'setup'], explanation: 'For zoneless: remove zone.js from polyfills, add provideExperimentalZonelessChangeDetection(), and ensure all async state flows through signals or markForCheck(). OnPush is recommended but not strictly required.', docs: 'https://angular.dev/guide/experimental/zoneless' } },

      // ── Module 10: SSR, Hydration & Angular Universal ──
      { id: 'a1000010-0000-4000-8001-000000000001', moduleId: 'a1000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'How do you add SSR to an existing Angular 19 standalone app?', choices: ['ng add universal', 'ng add @angular/ssr', 'npm install @angular/platform-server', 'ng generate ssr'], answer: '1', tags: ['ssr', 'angular-universal'], explanation: 'ng add @angular/ssr sets up Angular SSR (previously called Angular Universal) including server.ts, hydration, and the necessary build configuration for Angular 19.', docs: 'https://angular.dev/guide/ssr' } },
      { id: 'a1000010-0000-4000-8001-000000000002', moduleId: 'a1000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What does provideClientHydration() enable in Angular 19?', choices: ['Client-side authentication', 'Reuses SSR-rendered DOM instead of destroying and re-rendering it, preventing content flicker during hydration', 'Provides HTTP client on the browser', 'Enables lazy hydration of all components'], answer: '1', tags: ['ssr', 'hydration'], explanation: 'Without provideClientHydration(), Angular destroys the SSR HTML and re-renders from scratch. With it, Angular reuses server-rendered DOM, updating only what changed — improving LCP and avoiding flicker.', docs: 'https://angular.dev/guide/hydration' } },
      { id: 'a1000010-0000-4000-8001-000000000003', moduleId: 'a1000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'How do you detect if code is running on the server or browser in Angular SSR?', choices: ['process.env.PLATFORM', 'inject(PLATFORM_ID) and isPlatformBrowser()', 'window !== undefined', 'Angular.isServer()'], answer: '1', tags: ['ssr', 'platform'], explanation: 'isPlatformBrowser(inject(PLATFORM_ID)) returns true on the browser. isPlatformServer() for server. Use this to guard browser-only APIs (window, localStorage) from running during SSR.', docs: 'https://angular.dev/api/common/isPlatformBrowser' } },
      { id: 'a1000010-0000-4000-8001-000000000004', moduleId: 'a1000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What is event replay in Angular 19 hydration?', choices: ['Replaying HTTP requests on the client', 'Capturing user events that occur before hydration completes and replaying them once hydration finishes', 'Re-running SSR on the server after first paint', 'Replaying route navigation history'], answer: '1', tags: ['ssr', 'hydration', 'event-replay'], explanation: 'Event replay (stable in Angular 19) records user interactions (clicks, inputs) that happen while hydration is in progress and replays them on the fully hydrated components. Enable with withEventReplay() in provideClientHydration().', docs: 'https://angular.dev/guide/hydration#event-replay' } },
      { id: 'a1000010-0000-4000-8001-000000000005', moduleId: 'a1000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'What is the purpose of TransferState in Angular SSR?', choices: ['To transfer component state between routes', 'To serialize server-fetched data into the HTML so the client can reuse it without re-fetching', 'To transfer session cookies to the client', 'To cache component templates on the server'], answer: '1', tags: ['ssr', 'transfer-state'], explanation: 'TransferState serializes data fetched on the server into the HTML response. On the client, it reads the data synchronously, preventing duplicate HTTP calls during hydration.', docs: 'https://angular.dev/api/core/TransferState' } },
      { id: 'a1000010-0000-4000-8001-000000000006', moduleId: 'a1000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is incremental hydration in Angular 19?', choices: ['Hydrating one component at a time in a waterfall', 'Using @defer triggers to hydrate specific parts of the SSR page lazily instead of the entire app at once', 'Progressive enhancement of older browsers', 'Hydration that runs incrementally in the background'], answer: '1', tags: ['ssr', 'hydration', 'incremental'], explanation: 'Incremental hydration (stable Angular 19) uses @defer blocks to annotate sections of the SSR page. Only those sections are hydrated when their @defer trigger fires (e.g., on viewport), deferring JS cost for off-screen content.', docs: 'https://angular.dev/guide/incremental-hydration' } },
      { id: 'a1000010-0000-4000-8001-000000000007', moduleId: 'a1000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'What causes a hydration mismatch error in Angular?', choices: ['Using lazy-loaded routes', 'The server-rendered HTML structure differs from what Angular renders on the client', 'Using async pipes', 'Having more than 100 components'], answer: '1', tags: ['ssr', 'hydration', 'errors'], explanation: 'Hydration mismatches occur when server and client render different DOM. Common causes: Date.now(), Math.random(), browser-only code running on server, or non-deterministic rendering.', docs: 'https://angular.dev/errors/NG0500' } },
      { id: 'a1000010-0000-4000-8001-000000000008', moduleId: 'a1000000-0000-4000-8000-000000000010', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which of the following improve Angular SSR performance in Angular 19? (select all that apply)', choices: ['provideClientHydration() to reuse server DOM', 'withEventReplay() to not block on hydration', 'Incremental hydration with @defer', 'Removing all async pipes'], answer: '[0,1,2]', tags: ['ssr', 'performance'], explanation: 'provideClientHydration() avoids full re-render, withEventReplay() makes the app interactive before full hydration, and incremental @defer hydration reduces JS parsing cost. Removing async pipes does not help SSR.', docs: 'https://angular.dev/guide/hydration' } },
      { id: 'a1000010-0000-4000-8001-000000000009', moduleId: 'a1000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'What is the ngSkipHydration attribute used for in Angular 19?', choices: ['To skip a component during SSR rendering', 'To tell Angular to skip hydration for a specific component and re-render it fresh on the client', 'To skip lazy loading for a component', 'To disable change detection during hydration'], answer: '1', tags: ['ssr', 'hydration', 'skip'], explanation: 'Adding ngSkipHydration to a component\'s host element opts it out of hydration — Angular destroys and re-renders it on the client. Useful for third-party components with known DOM manipulation issues.', docs: 'https://angular.dev/guide/hydration#skipping-hydration' } },
      { id: 'a1000010-0000-4000-8001-000000000010', moduleId: 'a1000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'How do you prerender specific routes in Angular 19 SSR?', choices: ['prerender: true in angular.json routes', '"prerender": { "routes": ["/", "/about"] } in angular.json server configuration', 'ng generate prerender', 'APP_ROUTES token with prerender: true'], answer: '1', tags: ['ssr', 'prerender'], explanation: 'In angular.json, the server builder supports a "prerender" option with "routes" array to statically generate HTML for specific routes at build time. This is ideal for mostly-static content.', docs: 'https://angular.dev/guide/prerendering' } },
      { id: 'a1000010-0000-4000-8001-000000000011', moduleId: 'a1000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'What HTTP server does Angular 19\'s built-in SSR use by default?', choices: ['Apache', 'Nginx', 'Express via @angular/ssr/node', 'Fastify'], answer: '2', tags: ['ssr', 'server'], explanation: '@angular/ssr integrates with Node.js via @angular/ssr/node which exports AngularNodeAppEngine for use with Express or other Node.js HTTP frameworks. You configure the server in server.ts.', docs: 'https://angular.dev/guide/ssr' } },
      { id: 'a1000010-0000-4000-8001-000000000012', moduleId: 'a1000000-0000-4000-8000-000000000010', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which of the following are valid withXxx() options for provideClientHydration() in Angular 19? (select all that apply)', choices: ['withEventReplay()', 'withIncrementalHydration()', 'withNoDomReuse()', 'withHttpTransferCache()'], answer: '[0,1,3]', tags: ['ssr', 'hydration', 'options'], explanation: 'provideClientHydration() supports withEventReplay() (replay events during hydration), withIncrementalHydration() (enable @defer-based hydration), and withHttpTransferCache() (transfer HTTP state). withNoDomReuse() is not a real option.', docs: 'https://angular.dev/api/platform-browser/provideClientHydration' } },

      // ── Module 11: State Management with NgRx & Signals ──
      { id: 'a1000011-0000-4000-8001-000000000001', moduleId: 'a1000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What is NgRx SignalStore?', choices: ['A Redux-based global store using signals', 'A lightweight, composable state management solution built natively on Angular signals, introduced in NgRx 17+', 'A replacement for RxJS Subject', 'An NgModule-based state container'], answer: '1', tags: ['ngrx', 'signal-store'], explanation: 'NgRx SignalStore (@ngrx/signals) is a standalone, signal-first store built on Angular signals. It uses withState(), withComputed(), withMethods(), and withHooks() features instead of actions/reducers/effects.', docs: 'https://ngrx.io/guide/signals/signal-store' } },
      { id: 'a1000011-0000-4000-8001-000000000002', moduleId: 'a1000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'In NgRx classic (component store), what does createAction() do?', choices: ['Dispatches an action immediately', 'Creates a typed action creator function used with the store', 'Creates a reducer', 'Creates a selector'], answer: '1', tags: ['ngrx', 'actions'], explanation: 'createAction(\'[Source] Event\', props<{ payload: T }>()) returns an action creator function. Calling it returns an action object dispatched via store.dispatch().', docs: 'https://ngrx.io/guide/store/actions' } },
      { id: 'a1000011-0000-4000-8001-000000000003', moduleId: 'a1000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What does createFeature() do in NgRx?', choices: ['Creates a lazy-loaded module', 'Creates a self-contained state slice with a reducer and auto-generated selectors', 'Creates an NgRx effect', 'Creates a signal from a store slice'], answer: '1', tags: ['ngrx', 'feature'], explanation: 'createFeature({ name, reducer }) auto-generates a feature reducer and typed selectors for each top-level state property. It replaces the verbose StoreModule.forFeature() + manual selector boilerplate.', docs: 'https://ngrx.io/guide/store/feature-creators' } },
      { id: 'a1000011-0000-4000-8001-000000000004', moduleId: 'a1000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What is the purpose of NgRx Effects?', choices: ['To update component templates', 'To handle side-effects (e.g., HTTP calls) triggered by actions and dispatch new actions in response', 'To compute derived state', 'To replace reducers'], answer: '1', tags: ['ngrx', 'effects'], explanation: 'NgRx Effects listen to dispatched actions, perform side-effects (API calls, etc.), and dispatch new actions (success/failure). They use RxJS operators and are registered with provideEffects([]).', docs: 'https://ngrx.io/guide/effects' } },
      { id: 'a1000011-0000-4000-8001-000000000005', moduleId: 'a1000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'How do you read state as a signal from NgRx SignalStore?', choices: ['store.state$.toSignal()', 'store.myStateSlice() — state properties are exposed as signals directly', 'toSignal(store.select(selector))', 'store.asSignal()'], answer: '1', tags: ['ngrx', 'signal-store', 'signals'], explanation: 'NgRx SignalStore exposes each state property as a signal. Given withState({ count: 0 }), the store provides store.count() as a signal. No selector or toSignal() wrapper needed.', docs: 'https://ngrx.io/guide/signals/signal-store' } },
      { id: 'a1000011-0000-4000-8001-000000000006', moduleId: 'a1000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is patchState() in NgRx SignalStore?', choices: ['Dispatches a NgRx action', 'A method to partially update store state immutably inside withMethods()', 'A selector factory', 'A lifecycle hook'], answer: '1', tags: ['ngrx', 'signal-store', 'patchState'], explanation: 'patchState(store, { key: value }) shallowly merges the partial update into store state. It is the primary way to mutate state inside withMethods() service functions in SignalStore.', docs: 'https://ngrx.io/guide/signals/signal-store#updating-state' } },
      { id: 'a1000011-0000-4000-8001-000000000007', moduleId: 'a1000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'How do you select a slice of NgRx classic store state as a signal in Angular 19?', choices: ['toSignal(inject(Store).select(mySelector))', 'inject(Store).asSignal(mySelector)', 'inject(Store).signalSelect(mySelector)', 'selectAsSignal(mySelector)'], answer: '0', tags: ['ngrx', 'store', 'signals'], explanation: 'toSignal(store.select(mySelector)) wraps the Observable selector in a signal. This bridges classic NgRx with Angular\'s signal system for use in computed() or template signal reads.', docs: 'https://angular.dev/guide/rxjs-interop' } },
      { id: 'a1000011-0000-4000-8001-000000000008', moduleId: 'a1000000-0000-4000-8000-000000000011', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which features can be composed into an NgRx SignalStore? (select all that apply)', choices: ['withState()', 'withComputed()', 'withMethods()', 'withHooks()'], answer: '[0,1,2,3]', tags: ['ngrx', 'signal-store'], explanation: 'NgRx SignalStore is built from composable features: withState() (initial state), withComputed() (derived signals), withMethods() (state updaters and async operations), withHooks() (lifecycle: onInit, onDestroy).', docs: 'https://ngrx.io/guide/signals/signal-store' } },
      { id: 'a1000011-0000-4000-8001-000000000009', moduleId: 'a1000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'What is the difference between NgRx Store and NgRx SignalStore?', choices: ['They are identical', 'NgRx Store uses Redux pattern (actions/reducers/effects/selectors) with Observables; SignalStore is signal-first with no actions, using withState/withMethods composables', 'SignalStore is deprecated', 'NgRx Store is only for global state; SignalStore only for local state'], answer: '1', tags: ['ngrx', 'store', 'signal-store'], explanation: 'NgRx Store follows strict Redux with immutable actions/reducers/selectors/effects. SignalStore is opinionated differently — signal-based, no actions required, composable API. Both can coexist. SignalStore is great for local/feature state.', docs: 'https://ngrx.io/guide/signals/signal-store' } },
      { id: 'a1000011-0000-4000-8001-000000000010', moduleId: 'a1000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'How do you create a custom SignalStore feature (plugin)?', choices: ['Extend SignalStoreFeature class', 'signalStoreFeature() factory function', 'createFeature() from @ngrx/store', '@StoreFeature() decorator'], answer: '1', tags: ['ngrx', 'signal-store', 'custom-feature'], explanation: 'signalStoreFeature() creates reusable, composable store extensions. Example: a withLogger() feature that logs all state changes. It can accept type constraints to require specific state shape.', docs: 'https://ngrx.io/guide/signals/signal-store-features' } },
      { id: 'a1000011-0000-4000-8001-000000000011', moduleId: 'a1000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'What does withEntities() from @ngrx/signals/entities provide?', choices: ['Generic CRUD HTTP operations', 'A normalized entity collection (id map + ids array) with pre-built updaters like setAllEntities(), addEntity(), removeEntity()', 'A replacement for NgRx EntityAdapter', 'Automatic pagination signals'], answer: '1', tags: ['ngrx', 'signal-store', 'entities'], explanation: 'withEntities<T>() adds an entity dictionary and ids array to the store, plus helpers: setAllEntities, setEntity, addEntity, updateEntity, removeEntity, selectEntityById — similar to @ngrx/entity but signal-native.', docs: 'https://ngrx.io/guide/signals/entities' } },
      { id: 'a1000011-0000-4000-8001-000000000012', moduleId: 'a1000000-0000-4000-8000-000000000011', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which of the following are true about NgRx Effects in Angular 19? (select all that apply)', choices: ['They use createEffect() factory', 'They can be registered with provideEffects()', 'They can use functional effects with createEffect(() => inject(Actions)...)', 'They replace reducers'], answer: '[0,1,2]', tags: ['ngrx', 'effects'], explanation: 'NgRx effects use createEffect() with { dispatch: true/false }. They are registered with provideEffects([MyEffects]). The functional style uses inject() inside createEffect. Effects do NOT replace reducers — they complement them.', docs: 'https://ngrx.io/guide/effects' } },
    ];

    for (const q of questions) {
      await queryRunner.query(
        `INSERT INTO "qcm_question" ("id", "moduleId", "type", "difficulty", "sortOrder", "data")
         VALUES ($1, $2, $3, $4, $5, $6)
         ON CONFLICT ("id") DO NOTHING`,
        [q.id, q.moduleId, q.type, q.difficulty, q.sortOrder, q.data]
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const ids: string[] = [];
    for (let m = 6; m <= 11; m++) {
      for (let q = 1; q <= 12; q++) {
        ids.push(`a100000${m}-0000-4000-8001-${String(q).padStart(12, '0')}`);
      }
    }
    await queryRunner.query(`DELETE FROM "qcm_question" WHERE "id" = ANY($1)`, [ids]);
  }
}
