import type { MigrationInterface, QueryRunner } from 'typeorm';

export class AddSqlQuestions2_1773962501000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const questions = [
      // ── Module 9: PostgreSQL Advanced Features ──
      { id: 'f6000009-0000-4000-8001-000000000001', moduleId: 'f6000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What is a PostgreSQL schema and how does it differ from a database?', choices: ['They are the same', 'A schema is a namespace within a database — one DB can have multiple schemas (public, auth, analytics) to organize tables', 'A schema is a table definition only', 'Schemas replace databases in PostgreSQL'], answer: '1', tags: ['postgresql', 'schema'], explanation: 'PostgreSQL: database > schema > table. Default schema: "public". CREATE SCHEMA auth; CREATE TABLE auth.users (...). The search_path variable determines which schemas are searched by default.' } },
      { id: 'f6000009-0000-4000-8001-000000000002', moduleId: 'f6000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What is Row-Level Security (RLS) in PostgreSQL?', choices: ['Encrypting rows', 'A security feature where policies control which rows users can see or modify — enables multi-tenant data isolation at the database level', 'A row-locking mechanism', 'A column-level permission'], answer: '1', tags: ['postgresql', 'rls', 'security'], explanation: 'ALTER TABLE orders ENABLE ROW LEVEL SECURITY; CREATE POLICY user_owns_order ON orders FOR SELECT USING (user_id = current_setting("app.user_id")::uuid). Each user only sees their rows.' } },
      { id: 'f6000009-0000-4000-8001-000000000003', moduleId: 'f6000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What is the PostgreSQL ARRAY type?', choices: ['A collection of tables', 'A column that stores an array of values of any type — supports indexing with GIN and operators like @> (contains), && (overlap)', 'A JSON array', 'An ordered set of rows'], answer: '1', tags: ['postgresql', 'array'], explanation: 'CREATE TABLE tags (id serial, tag_names TEXT[]). INSERT ... VALUES (ARRAY["nodejs", "typescript"]). WHERE "react" = ANY(tag_names). GIN index for fast containment queries.' } },
      { id: 'f6000009-0000-4000-8001-000000000004', moduleId: 'f6000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What is a PostgreSQL sequence?', choices: ['An ordered query', 'A database object that generates unique sequential integer values — used for auto-increment primary keys (SERIAL/BIGSERIAL)', 'A sorted index', 'A time-ordered table'], answer: '1', tags: ['postgresql', 'sequence'], explanation: 'CREATE SEQUENCE user_id_seq START 1 INCREMENT 1. NEXTVAL("user_id_seq") gets the next value. SERIAL is syntactic sugar: creates a sequence and sets it as DEFAULT. GENERATED ALWAYS AS IDENTITY is the modern equivalent.' } },
      { id: 'f6000009-0000-4000-8001-000000000005', moduleId: 'f6000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'What is full-text search in PostgreSQL?', choices: ['LIKE with wildcards', 'Built-in text search using tsvector (indexed text) and tsquery (search query) with ranking and linguistic processing', 'ILIKE case-insensitive search', 'A text column index'], answer: '1', tags: ['postgresql', 'full-text-search', 'tsvector'], explanation: 'to_tsvector("english", "The quick brown fox") @@ to_tsquery("quick & fox"). GIN index on tsvector. ts_rank() for relevance scoring. Supports stemming, stop words, phrase search.' } },
      { id: 'f6000009-0000-4000-8001-000000000006', moduleId: 'f6000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is GENERATED ALWAYS AS IDENTITY in PostgreSQL?', choices: ['A generated column with expression', 'The SQL standard way to auto-generate unique integer IDs — replaces SERIAL, provides more control and explicit generation', 'A UUID generator', 'A computed column'], answer: '1', tags: ['postgresql', 'identity-column'], explanation: 'id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY. GENERATED ALWAYS prevents manual INSERT (use BY DEFAULT to allow). Standard SQL (not PostgreSQL-only like SERIAL). Preferred over SERIAL in modern PostgreSQL.' } },
      { id: 'f6000009-0000-4000-8001-000000000007', moduleId: 'f6000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'What is the UPSERT (INSERT ON CONFLICT) syntax in PostgreSQL?', choices: ['UPDATE + INSERT in two statements', 'INSERT INTO ... ON CONFLICT (column) DO UPDATE SET ... — atomically inserts or updates if a conflict occurs', 'A MERGE statement', 'A trigger-based insert'], answer: '1', tags: ['postgresql', 'upsert', 'on-conflict'], explanation: 'INSERT INTO users (id, name) VALUES (1, "Alice") ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name. EXCLUDED refers to the values that were attempted to be inserted. Atomic — no race condition.' } },
      { id: 'f6000009-0000-4000-8001-000000000008', moduleId: 'f6000000-0000-4000-8000-000000000009', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which PostgreSQL extensions are commonly used? (select all that apply)', choices: ['uuid-ossp (UUID generation)', 'pg_trgm (trigram similarity search)', 'PostGIS (geographic data)', 'pgcrypto (encryption functions)'], answer: '[0,1,2,3]', tags: ['postgresql', 'extensions'], explanation: 'Popular extensions: uuid-ossp (gen_random_uuid()), pg_trgm (LIKE with GIN index, similarity()), PostGIS (geographic data, ST_Distance), pgcrypto (encryption, crypt()). Enabled with CREATE EXTENSION.' } },
      { id: 'f6000009-0000-4000-8001-000000000009', moduleId: 'f6000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'What is logical replication in PostgreSQL?', choices: ['A backup method', 'Replication at the row/logical level using a publication/subscription model — can replicate specific tables, enable live migrations, feed downstream consumers', 'A streaming replication type', 'A foreign data wrapper'], answer: '1', tags: ['postgresql', 'logical-replication', 'replication'], explanation: 'CREATE PUBLICATION my_pub FOR TABLE orders. Subscriber: CREATE SUBSCRIPTION ... CONNECTION "..." PUBLICATION my_pub. Row-level, table-selective. Used for CDC (Change Data Capture), cross-version upgrades.' } },
      { id: 'f6000009-0000-4000-8001-000000000010', moduleId: 'f6000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'What is pg_trgm and when do you use it?', choices: ['A trigonometric math extension', 'Trigram-based similarity extension — enables fast LIKE/ILIKE queries with GIN index and fuzzy string matching with similarity()', 'A performance tuning extension', 'A spatial index extension'], answer: '1', tags: ['postgresql', 'pg_trgm', 'full-text-search'], explanation: 'CREATE INDEX ON products USING GIN(name gin_trgm_ops). SELECT * FROM products WHERE name ILIKE "%laptop%" — uses GIN index (normally impossible for % prefix). similarity("apple", "aplpe") → 0.5 for fuzzy match.' } },
      { id: 'f6000009-0000-4000-8001-000000000011', moduleId: 'f6000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'What is the difference between streaming replication and logical replication?', choices: ['Same technology', 'Streaming: physical WAL-level byte copy (entire DB, same major version). Logical: row-level change stream (select tables, cross-version, CDC)', 'Streaming is logical', 'Logical replication is older'], answer: '1', tags: ['postgresql', 'replication'], explanation: 'Streaming replication: binary WAL, exact copy, high-availability standby. Logical: row-level, supports cross-version (14→15 migration), selective tables, external consumers (Debezium, Kafka). Both can coexist.' } },
      { id: 'f6000009-0000-4000-8001-000000000012', moduleId: 'f6000000-0000-4000-8000-000000000009', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which PostgreSQL features support high availability? (select all that apply)', choices: ['Streaming replication (primary-standby)', 'pg_basebackup for base backups', 'WAL archiving for point-in-time recovery', 'Connection pooling with PgBouncer'], answer: '[0,1,2]', tags: ['postgresql', 'high-availability', 'backup'], explanation: 'HA stack: streaming replication (standby replicas), pg_basebackup (initial replica setup, backups), WAL archiving (PITR). PgBouncer is connection pooling — important for performance but not directly HA.' } },

      // ── Module 10: Database Design Patterns ──
      { id: 'f6000010-0000-4000-8001-000000000001', moduleId: 'f6000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What is the Repository Pattern in the context of databases?', choices: ['A Git repository', 'An abstraction layer that encapsulates database access logic, providing a collection-like interface for domain objects', 'A database backup pattern', 'A query template'], answer: '1', tags: ['patterns', 'repository-pattern'], explanation: 'UserRepository: findById(id), findByEmail(email), save(user), delete(id). Hides SQL/ORM details from domain layer. Makes testing easy (mock the repository). Separates concerns.' } },
      { id: 'f6000010-0000-4000-8001-000000000002', moduleId: 'f6000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What is the Unit of Work pattern?', choices: ['Measuring database performance', 'Tracks objects modified during a business transaction and coordinates writing changes to the database as a single unit', 'A database transaction', 'An ORM pattern only'], answer: '1', tags: ['patterns', 'unit-of-work'], explanation: 'UoW groups related changes: mark user as modified, create order, update inventory — then commit once. TypeORM\'s EntityManager/DataSource implements UoW. Ensures all-or-nothing data consistency.' } },
      { id: 'f6000010-0000-4000-8001-000000000003', moduleId: 'f6000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What is an audit trail in database design?', choices: ['A performance log', 'Recording who made what changes and when — typically a separate audit table or built-in columns (created_by, updated_at, etc.)', 'A database transaction log', 'A test trace'], answer: '1', tags: ['patterns', 'audit-trail'], explanation: 'Audit tables: INSERT INTO user_audit SELECT "UPDATE", OLD.*, NOW(), current_user FROM trigger. Columns: created_at, updated_at, created_by, updated_by. Temporal tables provide this automatically.' } },
      { id: 'f6000010-0000-4000-8001-000000000004', moduleId: 'f6000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What is database sharding?', choices: ['Encrypting database data', 'Horizontally partitioning data across multiple database instances — each shard holds a subset, enabling horizontal scaling beyond a single server', 'Indexing very large tables', 'A backup strategy'], answer: '1', tags: ['patterns', 'sharding', 'scaling'], explanation: 'Sharding by user_id: users 1-1M on shard 1, 1M-2M on shard 2. Trade-offs: no cross-shard JOINs, complex routing, resharding is painful. Use when vertical scaling and caching are insufficient.' } },
      { id: 'f6000010-0000-4000-8001-000000000005', moduleId: 'f6000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'What is Event Sourcing and how does it differ from traditional state storage?', choices: ['Storing events in a timeline', 'Instead of storing current state, store all events that led to the state — current state is derived by replaying events', 'An audit log pattern', 'A backup strategy'], answer: '1', tags: ['patterns', 'event-sourcing'], explanation: 'Traditional: store current state. Event sourcing: store [UserRegistered, EmailChanged, OrderPlaced...]. Reconstruct state by replaying. Benefits: audit trail, time travel, event replay. Complex to implement.' } },
      { id: 'f6000010-0000-4000-8001-000000000006', moduleId: 'f6000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is CQRS (Command Query Responsibility Segregation) at the database level?', choices: ['A query optimization pattern', 'Separate read and write models — write side normalizes data into write tables; read side may use denormalized read models or replicas for fast queries', 'A caching pattern', 'A replication strategy'], answer: '1', tags: ['patterns', 'cqrs', 'read-write-split'], explanation: 'CQRS DB: commands write to normalized primary DB. Queries read from a denormalized read replica or separate read model. Enables independent scaling of reads/writes. Often paired with Event Sourcing.' } },
      { id: 'f6000010-0000-4000-8001-000000000007', moduleId: 'f6000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'What is the Outbox Pattern for reliable event publishing?', choices: ['A database inbox/outbox', 'Write domain data and an event to the outbox table in the SAME transaction — a separate process publishes from outbox to message broker', 'A trigger pattern', 'An async queue pattern'], answer: '1', tags: ['patterns', 'outbox-pattern', 'eventual-consistency'], explanation: 'Problem: save order + publish event — non-atomic. Solution: save order + outbox row in one transaction. Poller reads outbox, publishes to Kafka, marks as published. Guarantees at-least-once delivery.' } },
      { id: 'f6000010-0000-4000-8001-000000000008', moduleId: 'f6000000-0000-4000-8000-000000000010', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which are valid strategies for multi-tenancy in SQL databases? (select all that apply)', choices: ['Separate database per tenant', 'Separate schema per tenant', 'Shared tables with tenant_id column + RLS', 'All tenant data in same row'], answer: '[0,1,2]', tags: ['patterns', 'multi-tenancy'], explanation: 'Multi-tenancy: separate DB (full isolation, expensive), separate schema (good isolation, manageable), shared table + tenant_id with RLS (efficient, good for many small tenants). Choice depends on isolation needs and scale.' } },
      { id: 'f6000010-0000-4000-8001-000000000009', moduleId: 'f6000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'What is the Saga Pattern for distributed transactions?', choices: ['A story-based test pattern', 'A sequence of local transactions where each step publishes an event triggering the next, with compensating transactions on failure — no distributed 2PC', 'A microservices communication protocol', 'A database two-phase commit'], answer: '1', tags: ['patterns', 'saga', 'distributed-transactions'], explanation: 'Order saga: CreateOrder → ReserveInventory → ChargePayment → ConfirmOrder. If payment fails: trigger compensating: ReleaseInventory → CancelOrder. Choreography (events) or Orchestration (central coordinator).' } },
      { id: 'f6000010-0000-4000-8001-000000000010', moduleId: 'f6000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'What is the CAP theorem and how does it apply to distributed databases?', choices: ['Consistency, Availability, Persistence', 'Consistency, Availability, Partition tolerance — a distributed system can only guarantee 2 of the 3 simultaneously', 'Cache, API, Performance theorem', 'A replication theorem'], answer: '1', tags: ['patterns', 'cap-theorem', 'distributed-systems'], explanation: 'CAP: Consistency (all nodes see same data), Availability (every request gets a response), Partition tolerance (system works despite network partition). SQL databases choose CP or CA; most choose CP (PostgreSQL).' } },
      { id: 'f6000010-0000-4000-8001-000000000011', moduleId: 'f6000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'What is Change Data Capture (CDC) and common implementations?', choices: ['A database backup method', 'Capturing every INSERT/UPDATE/DELETE as a stream of events — implemented via WAL (Debezium), triggers, or temporal tables', 'A data migration tool', 'A query caching pattern'], answer: '1', tags: ['patterns', 'cdc', 'debezium'], explanation: 'CDC streams DB changes to Kafka/Kinesis. Debezium reads PostgreSQL WAL, publishes each row change as an event. Used for: cache invalidation, search indexing, analytics pipelines, data synchronization.' } },
      { id: 'f6000010-0000-4000-8001-000000000012', moduleId: 'f6000000-0000-4000-8000-000000000010', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which are signs you should consider moving from SQL to a different database? (select all that apply)', choices: ['Document-heavy data with varying schemas (consider MongoDB/DynamoDB)', 'Graph relationships with deep traversal (consider Neo4j)', 'High-throughput time-series data (consider InfluxDB/TimescaleDB)', 'Standard relational data with JOINs'], answer: '[0,1,2]', tags: ['database-selection', 'sql', 'nosql'], explanation: 'SQL alternatives: document DB for schema-less documents, graph DB for relationship traversal, time-series DB for metrics. Standard relational data with JOINs is exactly what SQL excels at — no need to switch.' } },
    ];

    for (const q of questions) {
      await queryRunner.query(
        `INSERT INTO "qcm_question" ("id", "moduleId", "type", "difficulty", "sortOrder", "data")
         VALUES ($1, $2, $3, $4, $5, $6)
         ON CONFLICT ("id") DO NOTHING`,
        [q.id, q.moduleId, q.type, q.difficulty, q.sortOrder, q.data]
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const ids: string[] = [];
    for (const m of [9, 10]) {
      for (let q = 1; q <= 12; q++) {
        ids.push(`f600000${m}-0000-4000-8001-${String(q).padStart(12, '0')}`);
      }
    }
    await queryRunner.query(`DELETE FROM "qcm_question" WHERE "id" = ANY($1)`, [ids]);
  }
}
