import type { MigrationInterface, QueryRunner } from 'typeorm';

export class AddSqlQuestions1773962500000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const questions = [
      // ── Module 1: SQL Fundamentals ──
      { id: 'f6000001-0000-4000-8001-000000000001', moduleId: 'f6000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What does SQL stand for?', choices: ['Sequential Query Language', 'Structured Query Language', 'Simple Query Language', 'Standard Query Language'], answer: '1', tags: ['sql', 'basics'], explanation: 'SQL (Structured Query Language) is the standard language for managing and querying relational databases. Defined by ANSI/ISO standards, with database-specific extensions (T-SQL, PL/pgSQL).' } },
      { id: 'f6000001-0000-4000-8001-000000000002', moduleId: 'f6000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What is the difference between DDL, DML, and DCL in SQL?', choices: ['Different SQL dialects', 'DDL (CREATE/ALTER/DROP) defines schema; DML (SELECT/INSERT/UPDATE/DELETE) manipulates data; DCL (GRANT/REVOKE) controls access', 'DDL is for data; DML is for schema', 'Only DML is standard'], answer: '1', tags: ['sql', 'ddl', 'dml', 'dcl'], explanation: 'DDL: Data Definition Language — structure. DML: Data Manipulation Language — data CRUD. DCL: Data Control Language — permissions. Also: TCL (COMMIT/ROLLBACK) for transaction control.' } },
      { id: 'f6000001-0000-4000-8001-000000000003', moduleId: 'f6000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What is a PRIMARY KEY constraint?', choices: ['A key that can be null', 'A column or set of columns that uniquely identifies each row in a table — must be NOT NULL and unique', 'A foreign key reference', 'An auto-increment column'], answer: '1', tags: ['sql', 'primary-key', 'constraints'], explanation: 'PRIMARY KEY = UNIQUE + NOT NULL. Each table should have one. Creates a clustered index automatically in most databases. Can be single column or composite (multiple columns).' } },
      { id: 'f6000001-0000-4000-8001-000000000004', moduleId: 'f6000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What does SELECT DISTINCT do?', choices: ['Selects all rows', 'Returns only unique rows, removing duplicate values from the result set', 'Selects random rows', 'Filters NULL values'], answer: '1', tags: ['sql', 'select', 'distinct'], explanation: 'SELECT DISTINCT city FROM users returns each city only once. With multiple columns: SELECT DISTINCT country, city — the combination must be unique. Can be slow on large tables without indexes.' } },
      { id: 'f6000001-0000-4000-8001-000000000005', moduleId: 'f6000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'What is the difference between WHERE and HAVING in SQL?', choices: ['No difference', 'WHERE filters rows BEFORE grouping; HAVING filters groups AFTER GROUP BY — HAVING can use aggregate functions', 'WHERE is for joins; HAVING is for filters', 'HAVING replaces WHERE in modern SQL'], answer: '1', tags: ['sql', 'where', 'having', 'group-by'], explanation: 'WHERE country = "US" filters before aggregation. HAVING COUNT(*) > 5 filters after GROUP BY. You cannot use aggregate functions in WHERE. Both can be used in the same query.' } },
      { id: 'f6000001-0000-4000-8001-000000000006', moduleId: 'f6000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is a NULL value in SQL and how do you properly compare it?', choices: ['NULL equals empty string', 'NULL represents unknown/missing — cannot use = for comparison; use IS NULL or IS NOT NULL', 'NULL equals 0', 'NULL comparison works with ='], answer: '1', tags: ['sql', 'null'], explanation: 'NULL = NULL is NULL (not TRUE). Use WHERE column IS NULL. COALESCE(column, default) returns default if null. NULL in arithmetic = NULL. NULL in boolean = unknown (tri-valued logic).' } },
      { id: 'f6000001-0000-4000-8001-000000000007', moduleId: 'f6000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'What is the order of SQL clause execution?', choices: ['SELECT → FROM → WHERE → GROUP BY → HAVING → ORDER BY', 'FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY → LIMIT', 'WHERE → FROM → SELECT → ORDER BY', 'They can be in any order'], answer: '1', tags: ['sql', 'execution-order'], explanation: 'Logical processing order: FROM/JOINs → WHERE → GROUP BY → HAVING → SELECT → DISTINCT → ORDER BY → LIMIT/OFFSET. This is why you cannot use SELECT aliases in WHERE (not yet defined).' } },
      { id: 'f6000001-0000-4000-8001-000000000008', moduleId: 'f6000000-0000-4000-8000-000000000001', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which are valid aggregate functions in SQL? (select all that apply)', choices: ['COUNT()', 'SUM()', 'AVG()', 'UPPER()'], answer: '[0,1,2]', tags: ['sql', 'aggregate-functions'], explanation: 'Aggregate functions: COUNT, SUM, AVG, MIN, MAX. They operate on groups of rows and return a single value. UPPER() is a scalar string function, not an aggregate.' } },
      { id: 'f6000001-0000-4000-8001-000000000009', moduleId: 'f6000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'What is a CTE (Common Table Expression) and when is it used?', choices: ['A table alias', 'A named temporary result set defined with WITH clause — improves readability, enables recursion, and can replace subqueries', 'A permanent view', 'A database procedure'], answer: '1', tags: ['sql', 'cte', 'with'], explanation: 'WITH cte AS (SELECT ...) SELECT * FROM cte. Benefits: readable (name complex subqueries), reusable in the same query. Recursive CTE: WITH RECURSIVE traverses trees/graphs.' } },
      { id: 'f6000001-0000-4000-8001-000000000010', moduleId: 'f6000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'What is a recursive CTE and what is it used for?', choices: ['A CTE with a loop', 'WITH RECURSIVE cte AS (base_case UNION ALL recursive_step WHERE stop_condition) — traverses hierarchical data like org charts or file trees', 'A CTE that calls a stored procedure', 'A CTE with multiple WITH clauses'], answer: '1', tags: ['sql', 'recursive-cte'], explanation: 'WITH RECURSIVE org AS (SELECT * FROM employees WHERE manager_id IS NULL UNION ALL SELECT e.* FROM employees e JOIN org ON e.manager_id = org.id) SELECT * FROM org. Traverses entire tree.' } },
      { id: 'f6000001-0000-4000-8001-000000000011', moduleId: 'f6000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'What is the difference between UNION and UNION ALL?', choices: ['No difference', 'UNION removes duplicate rows (slower); UNION ALL keeps all rows including duplicates (faster)', 'UNION ALL is older', 'UNION works across databases'], answer: '1', tags: ['sql', 'union'], explanation: 'UNION: sorts and deduplicates — extra cost. UNION ALL: simple concatenation, no dedup — faster. Use UNION ALL when duplicates are acceptable or impossible (mutually exclusive queries).' } },
      { id: 'f6000001-0000-4000-8001-000000000012', moduleId: 'f6000000-0000-4000-8000-000000000001', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which SQL set operations are supported in PostgreSQL? (select all that apply)', choices: ['UNION / UNION ALL', 'INTERSECT', 'EXCEPT', 'MINUS'], answer: '[0,1,2]', tags: ['sql', 'set-operations'], explanation: 'PostgreSQL supports UNION, INTERSECT, EXCEPT. MINUS is Oracle-specific equivalent of EXCEPT. INTERSECT returns rows in both queries. EXCEPT returns rows in first but not second.' } },

      // ── Module 2: Joins ──
      { id: 'f6000002-0000-4000-8001-000000000001', moduleId: 'f6000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What is an INNER JOIN?', choices: ['Joins all rows', 'Returns only rows that have matching values in both tables', 'Returns all rows from left table', 'A faster version of outer join'], answer: '1', tags: ['sql', 'join', 'inner-join'], explanation: 'INNER JOIN (or just JOIN): SELECT * FROM orders o INNER JOIN customers c ON o.customer_id = c.id — returns only orders that have a matching customer. Unmatched rows are excluded.' } },
      { id: 'f6000002-0000-4000-8001-000000000002', moduleId: 'f6000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What is a LEFT (OUTER) JOIN?', choices: ['Returns only left table rows', 'Returns all rows from the left table plus matching rows from the right table — non-matching right rows have NULL', 'Returns only matched rows from left', 'Same as INNER JOIN'], answer: '1', tags: ['sql', 'join', 'left-join'], explanation: 'LEFT JOIN: all left rows, plus right matches. Unmatched left rows have NULL for right columns. Find users without orders: SELECT u.* FROM users u LEFT JOIN orders o ON u.id = o.user_id WHERE o.id IS NULL.' } },
      { id: 'f6000002-0000-4000-8001-000000000003', moduleId: 'f6000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What is a FULL OUTER JOIN?', choices: ['Joins all columns', 'Returns all rows from both tables — NULL fills where there is no match on either side', 'Only returns matched rows', 'Not supported in PostgreSQL'], answer: '1', tags: ['sql', 'join', 'full-outer-join'], explanation: 'FULL OUTER JOIN combines LEFT and RIGHT JOIN results. Rows with no match on either side have NULLs for the other table\'s columns. Useful for finding unmatched rows in both tables.' } },
      { id: 'f6000002-0000-4000-8001-000000000004', moduleId: 'f6000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What is a CROSS JOIN?', choices: ['A join across databases', 'Returns the Cartesian product — every row from the left table paired with every row from the right table (M×N rows)', 'A join without conditions', 'A random join'], answer: '1', tags: ['sql', 'join', 'cross-join'], explanation: 'CROSS JOIN: 100 rows × 50 rows = 5000 rows. No ON clause. Use cases: generate combinations (e.g., all sizes × all colors). Usually accidental if you forget the ON clause in an implicit join.' } },
      { id: 'f6000002-0000-4000-8001-000000000005', moduleId: 'f6000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'What is a self-join and when is it useful?', choices: ['Joining a table to itself with two aliases — useful for hierarchical data like employee-manager relationships', 'Joining two identical tables', 'A performance optimization', 'A recursive query'], answer: '0', tags: ['sql', 'self-join'], explanation: 'SELECT e.name, m.name AS manager FROM employees e LEFT JOIN employees m ON e.manager_id = m.id. The same table joined with two different aliases to query relationships within the table.' } },
      { id: 'f6000002-0000-4000-8001-000000000006', moduleId: 'f6000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is a LATERAL join in PostgreSQL?', choices: ['A left join alternative', 'A join where the right side can reference columns from the left side — like a correlated subquery but returning multiple rows', 'A join with LIMIT', 'A cross join variant'], answer: '1', tags: ['sql', 'lateral-join', 'postgresql'], explanation: 'LATERAL: SELECT u.*, recent.* FROM users u, LATERAL (SELECT * FROM orders WHERE user_id = u.id ORDER BY created_at DESC LIMIT 3) recent. Right side can reference u.id from the left.' } },
      { id: 'f6000002-0000-4000-8001-000000000007', moduleId: 'f6000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'What is the difference between ON and USING in JOIN?', choices: ['They are identical', 'ON specifies arbitrary join condition; USING (column) is shorthand when both tables have the same column name', 'USING is only for MySQL', 'ON is deprecated'], answer: '1', tags: ['sql', 'join', 'on', 'using'], explanation: 'JOIN ... ON a.user_id = b.user_id. JOIN ... USING (user_id) — shorthand when column names match. With USING, the result has only one instance of the column (not two).' } },
      { id: 'f6000002-0000-4000-8001-000000000008', moduleId: 'f6000000-0000-4000-8000-000000000002', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which are valid approaches to find rows with no match (orphans)? (select all that apply)', choices: ['LEFT JOIN ... WHERE right_id IS NULL', 'NOT EXISTS (SELECT 1 FROM other WHERE ...)', 'NOT IN (SELECT id FROM other)', 'Using EXCEPT set operation'], answer: '[0,1,2,3]', tags: ['sql', 'join', 'anti-join'], explanation: 'All four find orphans: LEFT JOIN null check (anti-join), NOT EXISTS (stops on first match), NOT IN (careful with NULLs — avoids if other has NULLs), EXCEPT. LEFT JOIN null check is often fastest.' } },
      { id: 'f6000002-0000-4000-8001-000000000009', moduleId: 'f6000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'How does the query optimizer choose join order?', choices: ['Joins in the order written', 'The optimizer estimates row counts and costs, choosing the join order that minimizes total work — influenced by table statistics', 'Alphabetical order', 'Smallest table first always'], answer: '1', tags: ['sql', 'query-optimizer', 'join-order'], explanation: 'PostgreSQL planner uses statistics (pg_statistics) to estimate cardinality. Chooses hash join, merge join, or nested loop based on row counts and available indexes. EXPLAIN ANALYZE shows the chosen plan.' } },
      { id: 'f6000002-0000-4000-8001-000000000010', moduleId: 'f6000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'What is the difference between Hash Join, Merge Join, and Nested Loop Join?', choices: ['Only performance differs', 'Nested Loop: O(N×M) per inner row scan; Hash Join: hash small table, probe with large (good for large unsorted); Merge Join: sort both then merge (good for sorted/indexed)', 'Only available in specific databases', 'Optimizer never uses nested loop'], answer: '1', tags: ['sql', 'join-algorithms', 'query-plan'], explanation: 'Nested Loop: for each outer row, scan inner — O(N×M), good with indexes. Hash Join: build hash table from small table, probe with large — good for large joins. Merge Join: both sides sorted — efficient for sorted data.' } },
      { id: 'f6000002-0000-4000-8001-000000000011', moduleId: 'f6000000-0000-4000-8000-000000000002', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'What is a non-equi join?', choices: ['A join without ON clause', 'A join using non-equality conditions like <, >, BETWEEN, or ≠ in the ON clause', 'A join across schemas', 'A join with NULL columns'], answer: '1', tags: ['sql', 'non-equi-join'], explanation: 'JOIN salary_ranges sr ON e.salary BETWEEN sr.min AND sr.max. Or self-join: JOIN employees e2 ON e1.salary < e2.salary (rank calculation). Often requires special attention for performance.' } },
      { id: 'f6000002-0000-4000-8001-000000000012', moduleId: 'f6000000-0000-4000-8000-000000000002', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which factors affect join performance? (select all that apply)', choices: ['Indexes on join columns', 'Table statistics (for query planner)', 'Column data types (matching types avoid casts)', 'Number of SELECT columns'], answer: '[0,1,2]', tags: ['sql', 'join-performance'], explanation: 'Join performance: indexes on join columns (hash/nested loop use them), accurate statistics (good plan), matching data types (avoid implicit casts that prevent index use). Number of SELECT columns rarely affects join cost.' } },

      // ── Module 3: Indexes ──
      { id: 'f6000003-0000-4000-8001-000000000001', moduleId: 'f6000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What is a database index and what problem does it solve?', choices: ['A table constraint', 'A data structure (B-tree by default) that speeds up data retrieval by avoiding full table scans — at the cost of extra storage and write overhead', 'A backup mechanism', 'A query cache'], answer: '1', tags: ['sql', 'index', 'performance'], explanation: 'Index = book index. Without: scan all rows (O(N)). With: B-tree traversal (O(log N)). Trade-off: faster SELECTs, slower INSERT/UPDATE/DELETE (maintain index). Use for frequently queried columns.' } },
      { id: 'f6000003-0000-4000-8001-000000000002', moduleId: 'f6000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What is the difference between a clustered and a non-clustered index?', choices: ['Speed only', 'Clustered: data rows physically ordered by the index key (one per table). Non-clustered: separate structure with pointers to data rows (multiple allowed)', 'Clustered indexes are slower', 'Non-clustered require more storage'], answer: '1', tags: ['sql', 'index', 'clustered'], explanation: 'PostgreSQL: heap (table) + index separately — no traditional clustered index, but CLUSTER command reorders the table. MySQL InnoDB: primary key = clustered index (data in key order).' } },
      { id: 'f6000003-0000-4000-8001-000000000003', moduleId: 'f6000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What is a composite (multi-column) index?', choices: ['An index on multiple tables', 'An index on multiple columns — effective for queries filtering on the leftmost columns', 'A partial index', 'Multiple indexes combined'], answer: '1', tags: ['sql', 'composite-index'], explanation: 'CREATE INDEX idx ON orders(user_id, status). Supports queries on (user_id), (user_id, status), but NOT (status) alone. The "leftmost prefix rule" — first column must be in the WHERE clause.' } },
      { id: 'f6000003-0000-4000-8001-000000000004', moduleId: 'f6000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What is a partial index in PostgreSQL?', choices: ['An index covering part of a column', 'An index with a WHERE clause — only indexes rows matching the condition, smaller and faster for specific query patterns', 'An incomplete index', 'An index on a subset of columns'], answer: '1', tags: ['sql', 'partial-index', 'postgresql'], explanation: 'CREATE INDEX idx_active ON users(email) WHERE active = true. Only indexes active users — much smaller than full index if most users are inactive. Useful for queries always filtering on a condition.' } },
      { id: 'f6000003-0000-4000-8001-000000000005', moduleId: 'f6000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'What is an index-only scan in PostgreSQL?', choices: ['A scan without indexes', 'A query answered entirely from the index without accessing heap rows — requires all selected columns in the index (covering index)', 'A sequential scan with index hint', 'Only for primary key queries'], answer: '1', tags: ['sql', 'index-only-scan', 'covering-index'], explanation: 'CREATE INDEX idx ON orders(user_id, status, created_at). SELECT status, created_at FROM orders WHERE user_id = 1 — all needed columns are in the index, no heap access needed. Very fast.' } },
      { id: 'f6000003-0000-4000-8001-000000000006', moduleId: 'f6000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'When does an index NOT get used by the query planner?', choices: ['Always used if it exists', 'When the table is small, selectivity is low, the query uses functions on indexed column (LOWER(name)), or cost estimate favors seq scan', 'Only when FORCE INDEX is not used', 'Indexes always reduce query time'], answer: '1', tags: ['sql', 'index', 'query-planner'], explanation: 'Index not used: small tables (seq scan faster), low selectivity (WHERE active=true on 95% active users), functions on column (LOWER(email) = $1 — use functional index instead), type mismatch.' } },
      { id: 'f6000003-0000-4000-8001-000000000007', moduleId: 'f6000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'What is a GIN index in PostgreSQL and what is it used for?', choices: ['A synonym for B-tree', 'Generalized Inverted Index — indexes elements within composite types: arrays, JSONB, full-text search vectors', 'A geographic index', 'A unique index variant'], answer: '1', tags: ['sql', 'gin-index', 'postgresql', 'jsonb'], explanation: 'GIN: CREATE INDEX ON articles USING GIN(to_tsvector("english", body)) for full-text search. CREATE INDEX ON products USING GIN(attributes) for JSONB. Supports @>, ?, ?| operators.' } },
      { id: 'f6000003-0000-4000-8001-000000000008', moduleId: 'f6000000-0000-4000-8000-000000000003', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which are valid PostgreSQL index types? (select all that apply)', choices: ['B-tree (default)', 'Hash', 'GIN (inverted)', 'GiST (generalized search tree)'], answer: '[0,1,2,3]', tags: ['sql', 'index-types', 'postgresql'], explanation: 'PostgreSQL index types: B-tree (equality, range, sorts), Hash (equality only, faster), GIN (arrays, JSONB, full-text), GiST (geometric, full-text, range), BRIN (large sequential tables), SP-GiST.' } },
      { id: 'f6000003-0000-4000-8001-000000000009', moduleId: 'f6000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'What is index bloat and how do you address it in PostgreSQL?', choices: ['Too many indexes', 'Dead tuples accumulate in index pages after many updates/deletes, increasing index size — VACUUM cleans table, REINDEX rebuilds indexes', 'Indexes that cover too many columns', 'Slow index creation'], answer: '1', tags: ['sql', 'index-bloat', 'vacuum', 'postgresql'], explanation: 'PostgreSQL\'s MVCC keeps dead tuple versions. VACUUM reclaims dead space. REINDEX CONCURRENTLY rebuilds bloated indexes without blocking. Monitor with pgstattuple extension.' } },
      { id: 'f6000003-0000-4000-8001-000000000010', moduleId: 'f6000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'What is CREATE INDEX CONCURRENTLY in PostgreSQL?', choices: ['Creates index in parallel', 'Creates the index without holding a lock that blocks writes — takes longer but allows DML during creation in production', 'Creates multiple indexes simultaneously', 'A faster index creation method'], answer: '1', tags: ['sql', 'index', 'concurrent', 'postgresql'], explanation: 'Regular CREATE INDEX: holds ShareLock, blocks writes. CREATE INDEX CONCURRENTLY: multiple passes, no write lock — table usable during creation. Cannot run in a transaction. Risk: fails partway, leaving invalid index.' } },
      { id: 'f6000003-0000-4000-8001-000000000011', moduleId: 'f6000000-0000-4000-8000-000000000003', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'What is a functional (expression) index?', choices: ['An index on a function result', 'An index on an expression rather than a plain column: CREATE INDEX ON users (LOWER(email)) — enables index use for LOWER(email) = $1 queries', 'A stored procedure index', 'A virtual index'], answer: '1', tags: ['sql', 'functional-index', 'expression-index'], explanation: 'Without functional index: LOWER(email) = "bob@example.com" cannot use a regular index on email. CREATE INDEX ON users (LOWER(email)) indexes the computed value, enabling fast case-insensitive lookups.' } },
      { id: 'f6000003-0000-4000-8001-000000000012', moduleId: 'f6000000-0000-4000-8000-000000000003', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which are signs that a table needs better indexing? (select all that apply)', choices: ['Seq Scan on large table in EXPLAIN ANALYZE', 'High actual time for queries on specific columns', 'Index Scan with high rows removed', 'All indexes are being used effectively'], answer: '[0,1,2]', tags: ['sql', 'index', 'performance'], explanation: 'Indicators: Seq Scan on large table (missing index), high query time for specific lookups (add index), Index Scan with many rows removed (low selectivity, consider composite index with filter columns).' } },

      // ── Module 4: Transactions & ACID ──
      { id: 'f6000004-0000-4000-8001-000000000001', moduleId: 'f6000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What does ACID stand for in database transactions?', choices: ['Atomicity, Consistency, Isolation, Durability', 'Accuracy, Completeness, Integrity, Dependency', 'Atomicity, Concurrency, Independence, Data', 'Async, Consistent, Integrated, Distributed'], answer: '0', tags: ['sql', 'acid', 'transactions'], explanation: 'ACID: Atomicity (all or nothing), Consistency (DB remains valid), Isolation (concurrent transactions don\'t see each other\'s partial work), Durability (committed data survives crashes).' } },
      { id: 'f6000004-0000-4000-8001-000000000002', moduleId: 'f6000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What is a dirty read in database transactions?', choices: ['Reading deleted data', 'Reading uncommitted data from another transaction that might be rolled back', 'Reading duplicate rows', 'Reading NULL values'], answer: '1', tags: ['sql', 'transactions', 'isolation'], explanation: 'Dirty read: Transaction A reads data modified by Transaction B before B commits. If B rolls back, A has read data that never existed. Prevented by READ COMMITTED isolation level.' } },
      { id: 'f6000004-0000-4000-8001-000000000003', moduleId: 'f6000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What are the SQL transaction isolation levels?', choices: ['Low, Medium, High, Full', 'READ UNCOMMITTED, READ COMMITTED, REPEATABLE READ, SERIALIZABLE', 'DIRTY, COMMITTED, REPEATABLE, SERIAL', 'AUTO, MANUAL, LOCKED, FULL'], answer: '1', tags: ['sql', 'isolation-levels'], explanation: 'Levels: READ UNCOMMITTED (dirty reads), READ COMMITTED (default in PostgreSQL, prevents dirty reads), REPEATABLE READ (prevents non-repeatable reads), SERIALIZABLE (full isolation, prevents phantom reads).' } },
      { id: 'f6000004-0000-4000-8001-000000000004', moduleId: 'f6000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What is a SAVEPOINT in SQL?', choices: ['A point in time for backups', 'A named point within a transaction you can ROLLBACK TO without rolling back the entire transaction', 'A performance checkpoint', 'A transaction start marker'], answer: '1', tags: ['sql', 'savepoint', 'transactions'], explanation: 'SAVEPOINT sp1; UPDATE ...; ROLLBACK TO sp1 (undoes since savepoint, transaction still active). RELEASE SAVEPOINT sp1 (just removes the savepoint). Useful for partial rollbacks.' } },
      { id: 'f6000004-0000-4000-8001-000000000005', moduleId: 'f6000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'What is a phantom read?', choices: ['Reading corrupted data', 'Transaction A queries rows matching a condition, Transaction B inserts matching rows and commits, Transaction A re-queries and sees new "phantom" rows', 'Reading NULL values', 'A non-repeatable read for single rows'], answer: '1', tags: ['sql', 'phantom-read', 'isolation'], explanation: 'Phantom reads: REPEATABLE READ prevents non-repeatable reads of existing rows but allows phantom reads (new rows from inserts). SERIALIZABLE isolation prevents phantom reads.' } },
      { id: 'f6000004-0000-4000-8001-000000000006', moduleId: 'f6000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is SELECT FOR UPDATE in PostgreSQL?', choices: ['Updates the selected rows immediately', 'Acquires a row-level exclusive lock on selected rows, preventing other transactions from modifying or locking them until COMMIT', 'A read-only SELECT', 'A version of UPDATE with a subquery'], answer: '1', tags: ['sql', 'select-for-update', 'locking'], explanation: 'SELECT * FROM inventory WHERE product_id = 1 FOR UPDATE. Locks the rows. Other transactions attempting SELECT FOR UPDATE or UPDATE on same rows will wait. Used to prevent lost updates in concurrent scenarios.' } },
      { id: 'f6000004-0000-4000-8001-000000000007', moduleId: 'f6000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'What is a deadlock in SQL and how does PostgreSQL handle it?', choices: ['A transaction that never commits', 'Two transactions each waiting for the other to release a lock — PostgreSQL detects and kills one transaction with an error', 'A full table lock', 'A timeout in a transaction'], answer: '1', tags: ['sql', 'deadlock', 'locking'], explanation: 'Deadlock: T1 locks row A, wants row B. T2 locks row B, wants row A. PostgreSQL detects cycles, picks a victim, rolls it back with ERROR: deadlock detected. Prevent by always locking in consistent order.' } },
      { id: 'f6000004-0000-4000-8001-000000000008', moduleId: 'f6000000-0000-4000-8000-000000000004', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which concurrency anomalies can occur without proper isolation? (select all that apply)', choices: ['Dirty reads', 'Non-repeatable reads', 'Phantom reads', 'Lost updates'], answer: '[0,1,2,3]', tags: ['sql', 'isolation', 'concurrency'], explanation: 'All four are concurrency anomalies: dirty reads (uncommitted data), non-repeatable reads (row changed between reads), phantom reads (new rows appear), lost updates (two writers overwrite each other).' } },
      { id: 'f6000004-0000-4000-8001-000000000009', moduleId: 'f6000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'What is PostgreSQL MVCC (Multi-Version Concurrency Control)?', choices: ['Multiple database versions', 'PostgreSQL keeps old row versions so readers never block writers — each transaction sees a snapshot of committed data at its start', 'A replication mechanism', 'A backup strategy'], answer: '1', tags: ['sql', 'mvcc', 'postgresql'], explanation: 'MVCC: UPDATE creates a new row version (xmax on old, new visible). Readers see the version active at their transaction start — no locks needed for reads. Dead tuples cleaned by VACUUM.' } },
      { id: 'f6000004-0000-4000-8001-000000000010', moduleId: 'f6000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'What is optimistic locking vs pessimistic locking?', choices: ['Speed preference', 'Pessimistic: lock rows before reading (FOR UPDATE). Optimistic: assume no conflict, check version on write, retry if changed — better for low-contention', 'Database engine options', 'Optimistic is better always'], answer: '1', tags: ['sql', 'locking', 'optimistic', 'pessimistic'], explanation: 'Optimistic: add version column; UPDATE ... WHERE id = 1 AND version = 5; if 0 rows updated, retry. Good for low contention. Pessimistic: SELECT FOR UPDATE holds lock. Good for high contention inventory-like scenarios.' } },
      { id: 'f6000004-0000-4000-8001-000000000011', moduleId: 'f6000000-0000-4000-8000-000000000004', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'What is write-ahead logging (WAL) and why is it important?', choices: ['A log of all SQL queries', 'Changes are written to WAL (durable log) before modifying data pages — enables crash recovery, point-in-time recovery, and replication', 'An application logging pattern', 'A backup log'], answer: '1', tags: ['sql', 'wal', 'durability', 'postgresql'], explanation: 'WAL ensures Durability: on crash, replay WAL from last checkpoint. Enables streaming replication (ship WAL to replicas). pg_wal directory. WAL archiving → point-in-time recovery (PITR).' } },
      { id: 'f6000004-0000-4000-8001-000000000012', moduleId: 'f6000000-0000-4000-8000-000000000004', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which are true about PostgreSQL SERIALIZABLE isolation? (select all that apply)', choices: ['Prevents all concurrency anomalies including phantom reads', 'Uses SSI (Serializable Snapshot Isolation), not traditional locking', 'Higher overhead than REPEATABLE READ', 'Automatically retries on serialization failure'], answer: '[0,1,2]', tags: ['sql', 'serializable', 'isolation'], explanation: 'SERIALIZABLE: prevents all anomalies, uses SSI (tracks read/write dependencies, no blocking). Higher overhead. Does NOT auto-retry — application must handle serialization_failure (40001) by retrying.' } },

      // ── Module 5: Window Functions ──
      { id: 'f6000005-0000-4000-8001-000000000001', moduleId: 'f6000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What are window functions in SQL?', choices: ['Popup window handlers', 'Functions that perform calculations across a "window" of related rows without collapsing them into a single row like GROUP BY', 'A type of subquery', 'Stored procedures for UI'], answer: '1', tags: ['sql', 'window-functions'], explanation: 'SELECT name, salary, AVG(salary) OVER (PARTITION BY department) FROM employees. Returns each row with the department average alongside — not collapsed like GROUP BY would be.' } },
      { id: 'f6000005-0000-4000-8001-000000000002', moduleId: 'f6000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What is PARTITION BY in a window function?', choices: ['Database partitioning', 'Divides rows into groups (partitions) for the window function to operate on independently — like GROUP BY but without collapsing rows', 'A sharding mechanism', 'An index partition'], answer: '1', tags: ['sql', 'window-functions', 'partition-by'], explanation: 'AVG(salary) OVER (PARTITION BY department ORDER BY hire_date). Each department is a separate window. Without PARTITION BY, the window covers all rows.' } },
      { id: 'f6000005-0000-4000-8001-000000000003', moduleId: 'f6000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What does ROW_NUMBER() window function do?', choices: ['Counts total rows', 'Assigns a sequential integer to each row within its partition, starting at 1 — no ties', 'Returns the rank allowing ties', 'Numbers rows in the entire table'], answer: '1', tags: ['sql', 'window-functions', 'row-number'], explanation: 'ROW_NUMBER() OVER (PARTITION BY dept ORDER BY salary DESC): 1,2,3,4... per department. No ties — if two rows have the same salary, they get different numbers (arbitrary order between them).' } },
      { id: 'f6000005-0000-4000-8001-000000000004', moduleId: 'f6000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What is the difference between RANK() and DENSE_RANK()?', choices: ['No difference', 'RANK() skips numbers after ties (1,1,3); DENSE_RANK() does not skip (1,1,2)', 'DENSE_RANK() is slower', 'RANK() does not allow ties'], answer: '1', tags: ['sql', 'window-functions', 'rank', 'dense-rank'], explanation: 'Tie in salary: RANK() → 1,1,3,4; DENSE_RANK() → 1,1,2,3. Use RANK() for "top 3 salaries" with gaps, DENSE_RANK() for "top 3 distinct salary values".' } },
      { id: 'f6000005-0000-4000-8001-000000000005', moduleId: 'f6000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'What does LAG() do in a window function?', choices: ['Returns the next row\'s value', 'Returns the value from a previous row within the partition — useful for comparing current row with previous', 'Applies a time lag filter', 'Returns the minimum value'], answer: '1', tags: ['sql', 'window-functions', 'lag'], explanation: 'LAG(salary, 1, 0) OVER (ORDER BY hire_date): returns previous row\'s salary (1 row back, default 0 if no previous). LEAD() is the forward equivalent. Calculate MoM change, running difference.' } },
      { id: 'f6000005-0000-4000-8001-000000000006', moduleId: 'f6000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is a window frame in SQL?', choices: ['A window size in pixels', 'ROWS/RANGE BETWEEN boundaries defining which rows are included in the window function calculation relative to the current row', 'A partition definition', 'A time window'], answer: '1', tags: ['sql', 'window-functions', 'window-frame'], explanation: 'SUM(amount) OVER (ORDER BY date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW): 7-day rolling sum. RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW: running total. Frames define the calculation range.' } },
      { id: 'f6000005-0000-4000-8001-000000000007', moduleId: 'f6000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'How do you select only the top N rows per group using window functions?', choices: ['LIMIT per group', 'ROW_NUMBER() OVER (PARTITION BY group ORDER BY ...) then WHERE rn <= N in an outer query', 'GROUP BY with LIMIT', 'HAVING COUNT <= N'], answer: '1', tags: ['sql', 'window-functions', 'top-n-per-group'], explanation: 'WITH ranked AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY dept ORDER BY salary DESC) AS rn FROM employees) SELECT * FROM ranked WHERE rn <= 3. Gets top 3 earners per department.' } },
      { id: 'f6000005-0000-4000-8001-000000000008', moduleId: 'f6000000-0000-4000-8000-000000000005', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which are window functions available in PostgreSQL? (select all that apply)', choices: ['ROW_NUMBER()', 'NTILE(n)', 'FIRST_VALUE()', 'PERCENT_RANK()'], answer: '[0,1,2,3]', tags: ['sql', 'window-functions'], explanation: 'All are PostgreSQL window functions: ROW_NUMBER (sequential), NTILE(4) (quartiles), FIRST_VALUE/LAST_VALUE (first/last in window), PERCENT_RANK (0-1 rank), CUME_DIST (cumulative distribution), NTH_VALUE.' } },
      { id: 'f6000005-0000-4000-8001-000000000009', moduleId: 'f6000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'What is the NTILE() window function?', choices: ['Returns the N-th row', 'Divides rows into N roughly equal buckets and returns the bucket number — useful for quartiles, deciles, percentiles', 'Returns N rows per partition', 'Sorts into N groups'], answer: '1', tags: ['sql', 'window-functions', 'ntile'], explanation: 'NTILE(4) OVER (ORDER BY salary DESC): assigns 1,2,3,4 quartile numbers. 100 rows → 25 per bucket. Uneven division: early buckets get extra row. Used for percentile-based analysis.' } },
      { id: 'f6000005-0000-4000-8001-000000000010', moduleId: 'f6000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'How do you calculate a running total with window functions?', choices: ['SUM in a subquery', 'SUM(amount) OVER (ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)', 'GROUP BY with cumulative sum', 'Use a stored procedure'], answer: '1', tags: ['sql', 'window-functions', 'running-total'], explanation: 'SUM(amount) OVER (PARTITION BY user_id ORDER BY date): running total per user. The default frame is RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW — includes all rows up to current.' } },
      { id: 'f6000005-0000-4000-8001-000000000011', moduleId: 'f6000000-0000-4000-8000-000000000005', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'Can you use window functions in WHERE clauses?', choices: ['Yes, directly', 'No — window functions are evaluated AFTER WHERE; use a subquery/CTE: WITH w AS (SELECT ..., ROW_NUMBER() OVER ...) SELECT * FROM w WHERE rn = 1', 'Yes with window references', 'Only in HAVING clause'], answer: '1', tags: ['sql', 'window-functions', 'execution-order'], explanation: 'Window functions execute in the SELECT phase, after WHERE/GROUP BY/HAVING. To filter on window function results, wrap in a CTE or subquery: SELECT * FROM (SELECT *, ROW_NUMBER() OVER... FROM t) sub WHERE rn = 1.' } },
      { id: 'f6000005-0000-4000-8001-000000000012', moduleId: 'f6000000-0000-4000-8000-000000000005', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which are valid use cases for window functions? (select all that apply)', choices: ['Top N per category', 'Running totals/averages', 'Period-over-period comparison (LAG/LEAD)', 'Replacing GROUP BY for simple aggregates'], answer: '[0,1,2]', tags: ['sql', 'window-functions', 'use-cases'], explanation: 'Window functions excel at: top-N per group (ROW_NUMBER), running aggregates (SUM OVER), period comparison (LAG/LEAD). They are NOT a replacement for GROUP BY simple aggregates — GROUP BY is clearer for those.' } },

      // ── Module 6: Query Optimization ──
      { id: 'f6000006-0000-4000-8001-000000000001', moduleId: 'f6000000-0000-4000-8000-000000000006', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What is EXPLAIN ANALYZE in PostgreSQL?', choices: ['A documentation command', 'Shows the query execution plan with actual timings — shows estimated vs actual rows, costs, and which indexes/join types were used', 'Analyzes table statistics only', 'A query syntax checker'], answer: '1', tags: ['sql', 'explain', 'query-optimization'], explanation: 'EXPLAIN ANALYZE SELECT ...: shows plan nodes (Seq Scan, Index Scan, Hash Join, etc.), estimated/actual rows, execution time. Add BUFFERS for I/O info. Essential for identifying slow queries.' } },
      { id: 'f6000006-0000-4000-8001-000000000002', moduleId: 'f6000000-0000-4000-8000-000000000006', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What does VACUUM do in PostgreSQL?', choices: ['Deletes the database', 'Reclaims storage from dead tuples (deleted/updated rows), updates statistics, prevents transaction ID wraparound', 'Analyzes query performance', 'Rebuilds all indexes'], answer: '1', tags: ['sql', 'vacuum', 'postgresql', 'maintenance'], explanation: 'VACUUM reclaims dead tuple space. VACUUM ANALYZE also updates planner statistics. VACUUM FULL rewrites the table (locks it). Autovacuum runs automatically. Monitor with pg_stat_user_tables.' } },
      { id: 'f6000006-0000-4000-8001-000000000003', moduleId: 'f6000000-0000-4000-8000-000000000006', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What is the N+1 query problem in SQL and how do you solve it?', choices: ['Fetching N extra rows', '1 query for N parents + N queries for children = N+1 total — solve with JOINs or batch loading', 'Too many nested subqueries', 'Using N indexes'], answer: '1', tags: ['sql', 'n+1', 'performance'], explanation: 'ORM: get 100 users (1 query) then load each user\'s profile (100 queries) = 101 queries. Fix: eager load with JOIN, or batch: WHERE user_id IN (id1, id2, ...). DataLoader batches automatically.' } },
      { id: 'f6000006-0000-4000-8001-000000000004', moduleId: 'f6000000-0000-4000-8000-000000000006', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What is query parameterization and why is it important?', choices: ['Setting query timeouts', 'Using $1, $2 placeholders instead of string concatenation — prevents SQL injection and enables query plan caching', 'Parameterizing stored procedures', 'A PostgreSQL-specific feature'], answer: '1', tags: ['sql', 'parameterization', 'security', 'performance'], explanation: 'Query("SELECT * FROM users WHERE id = $1", [id]) vs Query("SELECT * FROM users WHERE id = " + id). Parameterized: safe (SQL injection impossible), plan cached, reused. Never concatenate user input into SQL.' } },
      { id: 'f6000006-0000-4000-8001-000000000005', moduleId: 'f6000000-0000-4000-8000-000000000006', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'What is ANALYZE in PostgreSQL and when should you run it?', choices: ['Runs a query analysis report', 'Updates statistics used by the query planner (column distributions, row counts) — run after bulk inserts/changes when autovacuum hasn\'t caught up', 'Rebuilds indexes', 'Optimizes the storage layout'], answer: '1', tags: ['sql', 'analyze', 'statistics', 'postgresql'], explanation: 'ANALYZE table updates pg_statistic. Planner uses these to estimate row counts for query planning. After loading 10M rows, ANALYZE before running complex queries to ensure optimal plans.' } },
      { id: 'f6000006-0000-4000-8001-000000000006', moduleId: 'f6000000-0000-4000-8000-000000000006', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is the difference between a subquery and a JOIN, performance-wise?', choices: ['Subqueries are always slower', 'Modern optimizers often transform correlated subqueries to joins automatically — but JOINs are generally more predictable and often faster', 'JOINs are always faster', 'Performance is identical'], answer: '1', tags: ['sql', 'subquery', 'join', 'performance'], explanation: 'Correlated subquery: re-executes for each row (O(N*M)). JOIN: optimizer can use more efficient algorithms (hash join, merge join). Modern planners often rewrite subqueries to joins, but explicit JOINs are more readable and predictable.' } },
      { id: 'f6000006-0000-4000-8001-000000000007', moduleId: 'f6000000-0000-4000-8000-000000000007', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'What is connection pooling in PostgreSQL and why is it needed?', choices: ['A SQL connection cache', 'PostgreSQL creates a process per connection — poolers (PgBouncer) reuse connections to reduce per-connection overhead at scale', 'A PostgreSQL clustering tool', 'An SQL optimization feature'], answer: '1', tags: ['sql', 'connection-pool', 'pgbouncer'], explanation: 'Each PostgreSQL connection = a fork. At 1000 connections, overhead is huge. PgBouncer pools: clients connect to PgBouncer, which manages fewer real DB connections. Transaction mode is most efficient.' } },
      { id: 'f6000006-0000-4000-8001-000000000008', moduleId: 'f6000000-0000-4000-8000-000000000006', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which are common causes of slow PostgreSQL queries? (select all that apply)', choices: ['Missing index on WHERE/JOIN columns', 'Outdated table statistics causing bad plans', 'Returning many columns with SELECT *', 'Using parameterized queries'], answer: '[0,1,2]', tags: ['sql', 'performance', 'slow-query'], explanation: 'Slow query causes: missing indexes, stale statistics (bad plan), SELECT * (unnecessary data transfer + I/O), implicit type casts preventing index use. Parameterized queries are good practice — they help, not hurt.' } },
      { id: 'f6000006-0000-4000-8001-000000000009', moduleId: 'f6000000-0000-4000-8000-000000000006', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'What is pg_stat_statements and how does it help?', choices: ['A monitoring UI', 'A PostgreSQL extension that tracks query statistics (execution count, total time, rows, cache hits) — identifies the slowest queries by total cumulative time', 'A query logger', 'A statistics backup tool'], answer: '1', tags: ['sql', 'pg_stat_statements', 'monitoring'], explanation: 'SELECT query, total_exec_time, calls, mean_exec_time FROM pg_stat_statements ORDER BY total_exec_time DESC LIMIT 10; — shows your worst queries by cumulative time. Foundation for query optimization.' } },
      { id: 'f6000006-0000-4000-8001-000000000010', moduleId: 'f6000000-0000-4000-8000-000000000006', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'What is table partitioning in PostgreSQL and when should you use it?', choices: ['Sharding to multiple servers', 'Splitting a large table into smaller physical parts (by range, list, or hash) — improves query performance and maintenance on very large tables', 'A replication strategy', 'Schema partitioning'], answer: '1', tags: ['sql', 'partitioning', 'postgresql'], explanation: 'CREATE TABLE orders PARTITION BY RANGE (created_at). Partition pruning: WHERE created_at > "2024-01-01" scans only relevant partitions. Useful for time-series data (archive old partitions easily).' } },
      { id: 'f6000006-0000-4000-8001-000000000011', moduleId: 'f6000000-0000-4000-8000-000000000006', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'What is a materialized view and how does it differ from a regular view?', choices: ['A view that is always updated', 'Stores the query result physically on disk — must be refreshed manually (REFRESH MATERIALIZED VIEW) but provides much faster reads for expensive queries', 'A virtual table', 'A cached stored procedure'], answer: '1', tags: ['sql', 'materialized-view', 'postgresql'], explanation: 'Regular view: re-executes query on every access. Materialized view: stores result physically, very fast to read. REFRESH MATERIALIZED VIEW CONCURRENTLY updates without locking. Use for dashboards, reporting.' } },
      { id: 'f6000006-0000-4000-8001-000000000012', moduleId: 'f6000000-0000-4000-8000-000000000006', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which PostgreSQL-specific features help with performance? (select all that apply)', choices: ['Partial indexes (WHERE clause in index)', 'EXPLAIN (ANALYZE, BUFFERS) for detailed plans', 'pg_stat_statements for aggregate query stats', 'VACUUM for dead tuple cleanup'], answer: '[0,1,2,3]', tags: ['sql', 'postgresql', 'performance'], explanation: 'All are PostgreSQL performance features: partial indexes (smaller, targeted), EXPLAIN ANALYZE BUFFERS (shows I/O), pg_stat_statements (identifies slow queries), VACUUM (reclaim space, prevent bloat).' } },

      // ── Module 7: Schema Design & Normalization ──
      { id: 'f6000007-0000-4000-8001-000000000001', moduleId: 'f6000000-0000-4000-8000-000000000007', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What is database normalization?', choices: ['Scaling the database', 'The process of organizing a database to reduce data redundancy and improve data integrity through normal forms (1NF, 2NF, 3NF)', 'Performance optimization', 'Encrypting sensitive data'], answer: '1', tags: ['sql', 'normalization', 'schema-design'], explanation: 'Normalization eliminates redundancy: 1NF (atomic values, no repeating groups), 2NF (no partial dependencies), 3NF (no transitive dependencies), BCNF, 4NF, 5NF. Most practical schemas target 3NF.' } },
      { id: 'f6000007-0000-4000-8001-000000000002', moduleId: 'f6000000-0000-4000-8000-000000000007', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What is a FOREIGN KEY constraint?', choices: ['A primary key in another table', 'A column that references the PRIMARY KEY of another table, enforcing referential integrity', 'A unique constraint', 'An index on another table'], answer: '1', tags: ['sql', 'foreign-key', 'referential-integrity'], explanation: 'FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE. Prevents orphaned records. ON DELETE: CASCADE (delete children), SET NULL, RESTRICT (prevent parent delete). Enforces relational integrity.' } },
      { id: 'f6000007-0000-4000-8001-000000000003', moduleId: 'f6000000-0000-4000-8000-000000000007', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What is denormalization and when is it appropriate?', choices: ['Removing all constraints', 'Intentionally adding redundancy to improve read performance — trading data integrity for query speed in read-heavy systems', 'A database design mistake', 'Removing foreign keys'], answer: '1', tags: ['sql', 'denormalization', 'performance'], explanation: 'Denormalization: store user_name in orders table to avoid a JOIN. Pros: faster reads. Cons: update anomalies (change name in two places). Use in reporting, analytics, or when JOINs are too costly.' } },
      { id: 'f6000007-0000-4000-8001-000000000004', moduleId: 'f6000000-0000-4000-8000-000000000007', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What is the difference between CHAR, VARCHAR, and TEXT in PostgreSQL?', choices: ['No difference', 'CHAR(n) pads to n chars; VARCHAR(n) up to n chars; TEXT unlimited length — in PostgreSQL, all store similarly, TEXT/VARCHAR preferred', 'CHAR is faster always', 'TEXT cannot be indexed'], answer: '1', tags: ['sql', 'data-types', 'postgresql'], explanation: 'In PostgreSQL: CHAR(n) pads with spaces (rarely useful), VARCHAR(n) limits length, TEXT has no limit. Storage is identical for same content. TEXT is often preferred unless you need length enforcement.' } },
      { id: 'f6000007-0000-4000-8001-000000000005', moduleId: 'f6000000-0000-4000-8000-000000000007', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'What is the difference between UUID and sequential integer as a primary key?', choices: ['Only storage size differs', 'UUID: globally unique (safe for distributed systems, no central sequence), no sequence info leak, poor B-tree locality. Integer: compact, sequential, better cache locality', 'UUID is always better', 'Integers cannot be primary keys'], answer: '1', tags: ['sql', 'uuid', 'primary-key', 'schema-design'], explanation: 'UUID pros: distributed safe, no enumeration risk. Cons: 16 bytes vs 4-8, random insertion causes B-tree fragmentation (use UUIDv7 for sequential UUIDs). Integers: compact, fast index inserts.' } },
      { id: 'f6000007-0000-4000-8001-000000000006', moduleId: 'f6000000-0000-4000-8000-000000000007', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is an ENUM type in PostgreSQL and what are its trade-offs?', choices: ['A constraint on a column', 'A custom type with fixed allowed values — type-safe and compact, but hard to modify (ALTER TYPE required to add values)', 'A foreign key to a lookup table', 'A check constraint'], answer: '1', tags: ['sql', 'enum', 'postgresql'], explanation: 'CREATE TYPE status AS ENUM ("active", "inactive"). Pros: type safety, compact. Cons: hard to remove/rename values, ALTER TYPE ADD VALUE cannot be done in a transaction. Many prefer VARCHAR + CHECK or lookup table.' } },
      { id: 'f6000007-0000-4000-8001-000000000007', moduleId: 'f6000000-0000-4000-8000-000000000007', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'What is the JSONB data type in PostgreSQL?', choices: ['A JSON validation format', 'Binary JSON storage that supports indexing and efficient querying — stores parsed JSON, enables @> contains, ? exists operators', 'A text type for JSON strings', 'A deprecated JSON format'], answer: '1', tags: ['sql', 'jsonb', 'postgresql'], explanation: 'JSONB stores decomposed binary JSON. Supports GIN indexes for fast containment queries. SELECT data->>\'name\' for field access. data @> \'{"role": "admin"}\' for containment. Prefer over JSON type.' } },
      { id: 'f6000007-0000-4000-8001-000000000008', moduleId: 'f6000000-0000-4000-8000-000000000007', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which constraints can be applied to columns in PostgreSQL? (select all that apply)', choices: ['NOT NULL', 'UNIQUE', 'CHECK (condition)', 'DEFAULT value'], answer: '[0,1,2,3]', tags: ['sql', 'constraints', 'postgresql'], explanation: 'Column constraints: NOT NULL, UNIQUE, PRIMARY KEY, CHECK (price > 0), DEFAULT, REFERENCES (foreign key). Table constraints can span multiple columns. EXCLUDE for custom exclusion.' } },
      { id: 'f6000007-0000-4000-8001-000000000009', moduleId: 'f6000000-0000-4000-8000-000000000007', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'What is EAV (Entity-Attribute-Value) pattern and why is it problematic?', choices: ['An efficient JSON alternative', 'Storing arbitrary attributes as rows (entity_id, attribute_name, value) — flexible but terrible for querying, indexing, and type safety', 'An ORM design pattern', 'A normalization technique'], answer: '1', tags: ['sql', 'eav', 'schema-design'], explanation: 'EAV antipattern: hard to query (pivot required), no type checking, no NOT NULL per attribute, cannot index specific attributes efficiently. Use JSONB in PostgreSQL instead for flexible attributes.' } },
      { id: 'f6000007-0000-4000-8001-000000000010', moduleId: 'f6000000-0000-4000-8000-000000000007', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'What is the difference between soft delete and hard delete?', choices: ['Only speed differs', 'Hard delete: DELETE FROM table WHERE id = x (permanent). Soft delete: UPDATE SET deleted_at = NOW() — data preserved, filterable, supports audit trails', 'Soft delete is permanent', 'Hard delete can be undone'], answer: '1', tags: ['sql', 'soft-delete', 'schema-design'], explanation: 'Soft delete pros: audit trail, undo, foreign key integrity. Cons: all queries need WHERE deleted_at IS NULL (or use views), storage grows. Use partial index on (id) WHERE deleted_at IS NULL for undeleted data.' } },
      { id: 'f6000007-0000-4000-8001-000000000011', moduleId: 'f6000000-0000-4000-8000-000000000007', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'What is a temporal table and what problem does it solve?', choices: ['A time-series table', 'A table that tracks the full history of row changes over time, enabling point-in-time queries — supported natively in some databases', 'A table with timestamp columns', 'A partitioned table by date'], answer: '1', tags: ['sql', 'temporal-table', 'audit', 'history'], explanation: 'Temporal tables track row versions with valid_from/valid_to periods. SELECT * FROM employees FOR SYSTEM_TIME AS OF "2023-01-01". PostgreSQL: implement with trigger-based audit tables or temporal_tables extension.' } },
      { id: 'f6000007-0000-4000-8001-000000000012', moduleId: 'f6000000-0000-4000-8000-000000000007', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which are PostgreSQL-specific useful data types? (select all that apply)', choices: ['JSONB for semi-structured data', 'UUID for globally unique IDs', 'ARRAY for array values', 'BLOB for binary objects (called BYTEA in PostgreSQL)'], answer: '[0,1,2,3]', tags: ['sql', 'postgresql', 'data-types'], explanation: 'PostgreSQL unique types: JSONB (binary JSON with indexes), UUID (natively stored as 16 bytes), ARRAY (any type[]), BYTEA (binary data — PostgreSQL name for BLOB), RANGE types, INET/CIDR, tsvector, geometric types.' } },

      // ── Module 8: Stored Procedures & Functions ──
      { id: 'f6000008-0000-4000-8001-000000000001', moduleId: 'f6000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What is the difference between a stored procedure and a function in PostgreSQL?', choices: ['They are identical', 'Functions return a value and can be used in SQL expressions; procedures (CALL) are for actions, support transaction control (COMMIT/ROLLBACK)', 'Procedures are deprecated in PostgreSQL', 'Functions cannot modify data'], answer: '1', tags: ['sql', 'stored-procedure', 'function', 'postgresql'], explanation: 'Functions: return value, used in SELECT/WHERE, called with SELECT fn(). Procedures: CALL proc(), can have COMMIT/ROLLBACK inside, no return value (use INOUT params). Procedures added in PostgreSQL 11.' } },
      { id: 'f6000008-0000-4000-8001-000000000002', moduleId: 'f6000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What is PL/pgSQL in PostgreSQL?', choices: ['A programming language extension', 'PostgreSQL\'s procedural language — extends SQL with variables, loops, conditionals, exception handling for writing stored functions/procedures', 'A query optimizer', 'A NoSQL extension'], answer: '1', tags: ['sql', 'plpgsql', 'postgresql'], explanation: 'PL/pgSQL: CREATE FUNCTION fn() RETURNS void AS $$ DECLARE x INT; BEGIN SELECT id INTO x FROM ...; IF x > 0 THEN ...; END IF; END; $$ LANGUAGE plpgsql.' } },
      { id: 'f6000008-0000-4000-8001-000000000003', moduleId: 'f6000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What is a trigger in PostgreSQL?', choices: ['A scheduled job', 'A function automatically executed before/after INSERT/UPDATE/DELETE on a table — for auditing, validation, cascading changes', 'A constraint type', 'An event scheduler'], answer: '1', tags: ['sql', 'trigger', 'postgresql'], explanation: 'CREATE TRIGGER before_insert BEFORE INSERT ON users FOR EACH ROW EXECUTE FUNCTION validate_user(); Triggers: BEFORE/AFTER, INSERT/UPDATE/DELETE, ROW (per row) or STATEMENT (once per statement).' } },
      { id: 'f6000008-0000-4000-8001-000000000004', moduleId: 'f6000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What does RETURNS TABLE in a PostgreSQL function mean?', choices: ['Returns a table object', 'The function returns multiple rows with defined columns — can be queried with SELECT * FROM fn(args)', 'Returns a table name', 'Creates a new table'], answer: '1', tags: ['sql', 'function', 'returns-table'], explanation: 'CREATE FUNCTION get_users(min_age INT) RETURNS TABLE(id UUID, name TEXT) AS $$ BEGIN RETURN QUERY SELECT id, name FROM users WHERE age >= min_age; END; $$. Call: SELECT * FROM get_users(18).' } },
      { id: 'f6000008-0000-4000-8001-000000000005', moduleId: 'f6000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'What are the advantages and disadvantages of stored procedures?', choices: ['Only advantages exist', 'Pros: encapsulate complex logic, reduce network round trips, permissions model. Cons: hard to version control, test, debug; tight DB coupling', 'Only performance benefits', 'Stored procedures are always slower'], answer: '1', tags: ['sql', 'stored-procedures', 'trade-offs'], explanation: 'Pros: business logic in DB (good for complex multi-step DML), single round trip, fine-grained permissions. Cons: harder to test/debug, DB-vendor lock-in, hard to deploy with CI/CD, difficult to scale independently.' } },
      { id: 'f6000008-0000-4000-8001-000000000006', moduleId: 'f6000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is an IMMUTABLE, STABLE, or VOLATILE function in PostgreSQL?', choices: ['Security labels', 'Function volatility hints for the planner: IMMUTABLE (same args always return same result), STABLE (consistent within a transaction), VOLATILE (may change any time)', 'Access control for functions', 'Optimization flags only'], answer: '1', tags: ['sql', 'function', 'volatility', 'postgresql'], explanation: 'IMMUTABLE: planner can fold it at plan time (LOWER() is IMMUTABLE). STABLE: consistent within transaction (NOW() is STABLE). VOLATILE (default): can have side effects or change per call. Mark correctly for optimizer benefit.' } },
      { id: 'f6000008-0000-4000-8001-000000000007', moduleId: 'f6000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'What is a SECURITY DEFINER function?', choices: ['A function that only admins can call', 'A function that executes with the privileges of the function owner (not the caller) — enables controlled privilege escalation', 'A security audit function', 'A function with row-level security'], answer: '1', tags: ['sql', 'security-definer', 'function', 'security'], explanation: 'SECURITY DEFINER: useful when users need to perform actions beyond their direct permissions via a controlled function. Risk: privilege escalation if function has vulnerabilities. Use carefully with SECURITY INVOKER as default.' } },
      { id: 'f6000008-0000-4000-8001-000000000008', moduleId: 'f6000000-0000-4000-8000-000000000008', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which are valid trigger timing options in PostgreSQL? (select all that apply)', choices: ['BEFORE', 'AFTER', 'INSTEAD OF (for views)', 'DURING'], answer: '[0,1,2]', tags: ['sql', 'trigger', 'timing'], explanation: 'Trigger timing: BEFORE (can modify NEW, prevent operation), AFTER (for auditing, cascades), INSTEAD OF (only for views — implement view DML). No DURING. AFTER triggers see the committed state.' } },
      { id: 'f6000008-0000-4000-8001-000000000009', moduleId: 'f6000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'What is a table-level vs row-level trigger and when does each fire?', choices: ['No difference', 'ROW (FOR EACH ROW): fires once per affected row, has access to OLD/NEW. STATEMENT (FOR EACH STATEMENT): fires once per SQL statement, no OLD/NEW', 'Statement triggers are deprecated', 'Row triggers are faster'], answer: '1', tags: ['sql', 'trigger', 'row-level', 'statement-level'], explanation: 'FOR EACH ROW: 100 rows updated = 100 trigger calls. FOR EACH STATEMENT: 100 rows updated = 1 trigger call. Use STATEMENT for logging, counters. Use ROW when OLD/NEW values needed (validation, audit).' } },
      { id: 'f6000008-0000-4000-8001-000000000010', moduleId: 'f6000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'How do you raise and catch exceptions in PL/pgSQL?', choices: ['Use try/catch', 'RAISE EXCEPTION "message" with ERRCODE; catch with EXCEPTION WHEN unique_violation THEN ... in a BEGIN...EXCEPTION block', 'Errors cannot be caught in SQL', 'Use IF ERR_CODE THEN'], answer: '1', tags: ['sql', 'plpgsql', 'exception-handling'], explanation: 'BEGIN ... EXCEPTION WHEN unique_violation THEN RAISE NOTICE "Duplicate"; WHEN others THEN GET STACKED DIAGNOSTICS msg = MESSAGE_TEXT; END. Catches specific SQLSTATE codes.' } },
      { id: 'f6000008-0000-4000-8001-000000000011', moduleId: 'f6000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'What is pg_notify and how does it enable real-time features?', choices: ['A notification email system', 'LISTEN/NOTIFY: pg_notify(channel, payload) sends a message, clients LISTEN on the channel and receive it asynchronously — enables event-driven patterns', 'A PostgreSQL alert system', 'A monitoring notification'], answer: '1', tags: ['sql', 'postgresql', 'listen-notify', 'real-time'], explanation: 'Client: LISTEN new_orders. Trigger: PERFORM pg_notify("new_orders", row_to_json(NEW)::text). Node.js pg: client.on("notification", fn). Used for real-time dashboards, cache invalidation.' } },
      { id: 'f6000008-0000-4000-8001-000000000012', moduleId: 'f6000000-0000-4000-8000-000000000008', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which are best practices for database functions/procedures? (select all that apply)', choices: ['Use IMMUTABLE/STABLE hints where applicable', 'Version control schema with migrations', 'Write unit tests for complex functions (pgTAP)', 'Store all business logic in stored procedures'], answer: '[0,1,2]', tags: ['sql', 'stored-procedures', 'best-practices'], explanation: 'Best practices: correct volatility labels (optimizer benefit), migrate functions with the codebase (Flyway/Liquibase), test with pgTAP. Storing ALL logic in DB creates tight coupling — balance between DB and application logic.' } },
    ];

    for (const q of questions) {
      await queryRunner.query(
        `INSERT INTO "qcm_question" ("id", "moduleId", "type", "difficulty", "sortOrder", "data")
         VALUES ($1, $2, $3, $4, $5, $6)
         ON CONFLICT ("id") DO NOTHING`,
        [q.id, q.moduleId, q.type, q.difficulty, q.sortOrder, q.data]
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const ids: string[] = [];
    for (let m = 1; m <= 8; m++) {
      for (let q = 1; q <= 12; q++) {
        ids.push(`f600000${m}-0000-4000-8001-${String(q).padStart(12, '0')}`);
      }
    }
    await queryRunner.query(`DELETE FROM "qcm_question" WHERE "id" = ANY($1)`, [ids]);
  }
}
