import type { MigrationInterface, QueryRunner } from 'typeorm';

export class AddReact19Questions2_1773962201000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const questions = [
      // ── Module 8: ref as a Prop & cleanup ──
      { id: 'c3000008-0000-4000-8001-000000000001', moduleId: 'c3000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'In React 19, how do you accept a ref in a function component without forwardRef?', choices: ['function Input({ ref }) { ... }', 'const Input = forwardRef((props, ref) => { ... })', 'function Input(props, ref) { ... }', 'useRef() inside the component'], answer: '0', tags: ['react19', 'ref'], explanation: 'React 19 passes ref directly as a prop. Simply destructure it: function Input({ ref, ...props }) { return <input ref={ref} {...props} />; }. No forwardRef wrapper is needed.', docs: 'https://react.dev/blog/2024/12/05/react-19#ref-as-a-prop' } },
      { id: 'c3000008-0000-4000-8001-000000000002', moduleId: 'c3000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What does a ref callback return in React 19?', choices: ['undefined always', 'A cleanup function that runs when the element unmounts', 'The DOM element itself', 'A boolean'], answer: '1', tags: ['react19', 'ref', 'cleanup'], explanation: 'React 19 ref callbacks can return a cleanup function: ref={(el) => { setup(el); return () => cleanup(el); }}. The cleanup runs when the element is removed from DOM — mirroring useEffect cleanup.', docs: 'https://react.dev/blog/2024/12/05/react-19#cleanup-functions-for-refs' } },
      { id: 'c3000008-0000-4000-8001-000000000003', moduleId: 'c3000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What is useImperativeHandle used for?', choices: ['To create an imperative API', 'To customize the value exposed on a ref attached to a component — limiting what the parent can access', 'To bypass the virtual DOM', 'To run code imperatively in render'], answer: '1', tags: ['useImperativeHandle', 'ref'], explanation: 'useImperativeHandle(ref, () => ({ focus, reset })) exposes only specific methods on the ref. This prevents parents from accessing the full DOM node, enforcing encapsulation.', docs: 'https://react.dev/reference/react/useImperativeHandle' } },
      { id: 'c3000008-0000-4000-8001-000000000004', moduleId: 'c3000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'When does React set ref.current to the DOM element?', choices: ['Before the component renders', 'After the component mounts (after commit phase)', 'During the render phase', 'When the ref is created'], answer: '1', tags: ['ref', 'lifecycle'], explanation: 'React sets ref.current during the commit phase, after the DOM is updated. It is null during render. Access it in useEffect or event handlers — never during render.', docs: 'https://react.dev/learn/manipulating-the-dom-with-refs' } },
      { id: 'c3000008-0000-4000-8001-000000000005', moduleId: 'c3000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'What is the React 19 behavior when a ref callback doesn\'t return a cleanup function?', choices: ['React throws a warning', 'React calls the ref callback with null when the element unmounts (same as before)', 'The ref leaks memory', 'The behavior is undefined'], answer: '1', tags: ['react19', 'ref', 'callback'], explanation: 'If no cleanup function is returned, React calls the ref callback with null on unmount — same behavior as React 18. Returning a cleanup function is an opt-in improvement.', docs: 'https://react.dev/blog/2024/12/05/react-19#cleanup-functions-for-refs' } },
      { id: 'c3000008-0000-4000-8001-000000000006', moduleId: 'c3000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What is the difference between createRef() and useRef()?', choices: ['They are the same', 'createRef() creates a new ref object on every render; useRef() returns the same ref object across renders', 'useRef() only works with DOM elements', 'createRef() is for function components only'], answer: '1', tags: ['ref', 'createRef', 'useRef'], explanation: 'createRef() creates a fresh ref each render — fine for class components. useRef() persists the same ref across renders. In function components, always use useRef().', docs: 'https://react.dev/reference/react/createRef' } },
      { id: 'c3000008-0000-4000-8001-000000000007', moduleId: 'c3000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'What React 19 change affects how ref callbacks behave with React Strict Mode?', choices: ['Strict Mode no longer runs effects twice', 'Strict Mode calls ref cleanup and re-runs ref callbacks twice in development to detect issues', 'Strict Mode disables ref callbacks', 'No change — same as React 18'], answer: '1', tags: ['react19', 'ref', 'strict-mode'], explanation: 'In React 19 Strict Mode, ref callbacks are run, cleaned up, and re-run to verify that cleanup functions work correctly — consistent with how effects behave in Strict Mode.', docs: 'https://react.dev/blog/2024/12/05/react-19#cleanup-functions-for-refs' } },
      { id: 'c3000008-0000-4000-8001-000000000008', moduleId: 'c3000000-0000-4000-8000-000000000008', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which of the following are valid uses of useRef? (select all that apply)', choices: ['Storing a mutable value that doesn\'t trigger re-renders', 'Accessing a DOM element imperatively', 'Storing the previous value of a prop', 'As a replacement for useState for all values'], answer: '[0,1,2]', tags: ['useRef', 'use-cases'], explanation: 'useRef is perfect for: mutable values without re-renders (timers, flags), DOM access, and storing previous values. It should not replace useState — changing ref.current never triggers a re-render, so UI won\'t update.', docs: 'https://react.dev/reference/react/useRef' } },
      { id: 'c3000008-0000-4000-8001-000000000009', moduleId: 'c3000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'In React 19, is it still valid to use forwardRef()?', choices: ['No — it throws', 'Yes — it works but is deprecated. Migrate to ref as prop gradually.', 'Only in class components', 'Only in library code'], answer: '1', tags: ['react19', 'forwardRef', 'deprecated'], explanation: 'forwardRef() still works in React 19 but is deprecated. The React team recommends migrating to the new ref-as-prop pattern. A future major version will remove it.', docs: 'https://react.dev/blog/2024/12/05/react-19#ref-as-a-prop' } },
      { id: 'c3000008-0000-4000-8001-000000000010', moduleId: 'c3000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'What is the best practice for focus management with refs in React 19?', choices: ['Use document.getElementById()', 'Use a ref callback to programmatically focus: ref={(el) => el?.focus()}', 'Use useEffect with ref.current.focus()', 'Both ref callback and useEffect approaches are valid — choose based on timing needs'], answer: '3', tags: ['ref', 'focus', 'best-practices'], explanation: 'Ref callback focus runs synchronously during commit — good for immediate focus. useEffect focus runs after paint — useful when you need conditional logic. Both are valid approaches depending on UX requirements.', docs: 'https://react.dev/learn/manipulating-the-dom-with-refs#focusing-a-text-input' } },
      { id: 'c3000008-0000-4000-8001-000000000011', moduleId: 'c3000000-0000-4000-8000-000000000008', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'When using useImperativeHandle with React 19\'s ref-as-prop pattern, how does the signature change?', choices: ['useImperativeHandle(ref, createHandle) — same as before', 'imper(ref, handle)', 'No longer needed', 'useImperativeHandle is also deprecated'], answer: '0', tags: ['useImperativeHandle', 'react19'], explanation: 'useImperativeHandle(ref, () => ({ ... }), deps) signature is unchanged. With React 19, ref is received as a regular prop instead of via forwardRef, but useImperativeHandle usage inside the component body remains the same.', docs: 'https://react.dev/reference/react/useImperativeHandle' } },
      { id: 'c3000008-0000-4000-8001-000000000012', moduleId: 'c3000000-0000-4000-8000-000000000008', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which of the following are true about refs in React 19? (select all that apply)', choices: ['ref is now a regular prop accessible via destructuring', 'forwardRef is deprecated', 'Ref callbacks can return cleanup functions', 'Refs trigger re-renders when current changes'], answer: '[0,1,2]', tags: ['react19', 'ref'], explanation: 'React 19: ref as prop (no forwardRef), forwardRef deprecated, ref callback cleanup support. Refs do NOT trigger re-renders when .current changes — that is their key characteristic.', docs: 'https://react.dev/blog/2024/12/05/react-19#ref-as-a-prop' } },

      // ── Module 9: Document Metadata & Asset Loading ──
      { id: 'c3000009-0000-4000-8001-000000000001', moduleId: 'c3000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'In React 19, what happens when you render <title>My Page</title> inside a component?', choices: ['It renders inline in the DOM', 'React automatically hoists it to <head>', 'It is ignored', 'It needs a Portal'], answer: '1', tags: ['react19', 'metadata'], explanation: 'React 19 automatically hoists <title>, <meta>, and <link rel="stylesheet"> to the document <head> from anywhere in the component tree — no react-helmet or router integration needed.', docs: 'https://react.dev/blog/2024/12/05/react-19#support-for-document-metadata' } },
      { id: 'c3000009-0000-4000-8001-000000000002', moduleId: 'c3000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What does React 19\'s preload() API do?', choices: ['Preloads data from an API', 'Triggers a <link rel="preload"> hint to fetch a resource (font, script, CSS) early', 'Preloads a component lazily', 'Caches server responses'], answer: '1', tags: ['react19', 'resource-loading', 'preload'], explanation: 'preload(href, { as: "font" | "style" | "script" }) from react-dom emits a <link rel="preload"> hint, telling the browser to fetch the resource as soon as possible without blocking rendering.', docs: 'https://react.dev/reference/react-dom/preload' } },
      { id: 'c3000009-0000-4000-8001-000000000003', moduleId: 'c3000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What is the difference between preload() and preinit() in React 19?', choices: ['They are identical', 'preload() fetches the resource; preinit() fetches AND executes/applies it (for scripts/stylesheets)', 'preinit() is for images only', 'preload() works only in SSR'], answer: '1', tags: ['react19', 'preinit', 'preload'], explanation: 'preload() = fetch early (download only). preinit() = fetch AND initialize/execute — for stylesheets it applies the styles, for scripts it executes them. Use preinit when you need the resource immediately.', docs: 'https://react.dev/reference/react-dom/preinit' } },
      { id: 'c3000009-0000-4000-8001-000000000004', moduleId: 'c3000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What happens with duplicate <title> tags across nested components in React 19?', choices: ['All are rendered in <head>', 'React deduplicates — later/deeper instances take precedence', 'React throws a warning', 'Only the root title is used'], answer: '1', tags: ['react19', 'metadata', 'deduplication'], explanation: 'React 19 deduplicates metadata with the same key/name. For <title>, the deepest component\'s title wins (child overrides parent). For <meta name="...">, the same-name meta is deduplicated.', docs: 'https://react.dev/blog/2024/12/05/react-19#support-for-document-metadata' } },
      { id: 'c3000009-0000-4000-8001-000000000005', moduleId: 'c3000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'How do you add a stylesheet to the <head> with priority ordering in React 19?', choices: ['<link rel="stylesheet" href={css} />', '<style>{cssString}</style>', '<link rel="stylesheet" href={css} precedence="default" />', 'import styles from "./style.css"'], answer: '2', tags: ['react19', 'stylesheet', 'precedence'], explanation: 'React 19 adds a precedence prop to <link rel="stylesheet">. React orders stylesheets by precedence value and deduplicates same-href stylesheets — component re-renders don\'t add duplicate <link> tags.', docs: 'https://react.dev/blog/2024/12/05/react-19#support-for-stylesheets' } },
      { id: 'c3000009-0000-4000-8001-000000000006', moduleId: 'c3000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'What does prefetchDNS() do in React 19?', choices: ['Prefetches API data', 'Triggers a <link rel="dns-prefetch"> to resolve the DNS for a domain early', 'Caches DNS results in React state', 'Preloads fonts from a CDN'], answer: '1', tags: ['react19', 'prefetchDNS'], explanation: 'prefetchDNS(href) from react-dom emits a <link rel="dns-prefetch"> hint, triggering early DNS resolution for a domain — useful before fetching resources from a CDN or API.', docs: 'https://react.dev/reference/react-dom/prefetchDNS' } },
      { id: 'c3000009-0000-4000-8001-000000000007', moduleId: 'c3000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'How does React 19 handle async scripts added via <script async>?', choices: ['Ignores them', 'Deduplicates — same-src scripts are only added to the DOM once, even if rendered multiple times', 'Executes them multiple times', 'Requires a key prop'], answer: '1', tags: ['react19', 'scripts'], explanation: 'React 19 deduplicates async scripts. If multiple components render <script async src="/analytics.js" />, React adds the script to <head> only once. src is used as the deduplication key.', docs: 'https://react.dev/blog/2024/12/05/react-19#support-for-async-scripts' } },
      { id: 'c3000009-0000-4000-8001-000000000008', moduleId: 'c3000000-0000-4000-8000-000000000009', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which resource loading APIs are available in React 19 react-dom? (select all that apply)', choices: ['preload()', 'preinit()', 'prefetchDNS()', 'preconnect()'], answer: '[0,1,2,3]', tags: ['react19', 'resource-apis'], explanation: 'React 19 react-dom provides: preload() (<link rel="preload">), preinit() (fetch+init), prefetchDNS() (<link rel="dns-prefetch">), preconnect() (<link rel="preconnect">). All emit appropriate <link> hints.', docs: 'https://react.dev/reference/react-dom' } },
      { id: 'c3000009-0000-4000-8001-000000000009', moduleId: 'c3000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'When React 19 hoists a stylesheet <link> from inside a Suspense boundary, when is the content revealed?', choices: ['Immediately', 'After the stylesheet loads — React waits for the stylesheet to download before revealing the Suspense content', 'After 1 second timeout', 'Never — stylesheets inside Suspense are not supported'], answer: '1', tags: ['react19', 'stylesheet', 'suspense'], explanation: 'When a component inside a Suspense boundary renders a <link rel="stylesheet" precedence="...">, React waits for the stylesheet to load before revealing that boundary\'s content — preventing Flash of Unstyled Content (FOUC).', docs: 'https://react.dev/blog/2024/12/05/react-19#support-for-stylesheets' } },
      { id: 'c3000009-0000-4000-8001-000000000010', moduleId: 'c3000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'Where can preload() / preinit() be called in React 19?', choices: ['Only in useEffect', 'During render, in event handlers, or inside Server Components — wherever you have enough information to preload', 'Only in Server Components', 'Only at app initialization'], answer: '1', tags: ['react19', 'preload', 'usage'], explanation: 'preload/preinit can be called anywhere — render phase, event handlers, Server Components. Calling them early (e.g., in event handlers on hover) triggers browser resource fetch before navigation completes.', docs: 'https://react.dev/reference/react-dom/preload' } },
      { id: 'c3000009-0000-4000-8001-000000000011', moduleId: 'c3000000-0000-4000-8000-000000000009', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'What library was commonly used for document metadata before React 19?', choices: ['react-meta', 'react-document-title', 'react-helmet / react-helmet-async', 'next/head'], answer: '2', tags: ['react19', 'metadata', 'migration'], explanation: 'react-helmet (and its async variant) was the standard for managing document <head> in React. React 19\'s native metadata support makes these libraries unnecessary for most use cases.', docs: 'https://react.dev/blog/2024/12/05/react-19#support-for-document-metadata' } },
      { id: 'c3000009-0000-4000-8001-000000000012', moduleId: 'c3000000-0000-4000-8000-000000000009', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which of the following are automatically hoisted to <head> by React 19? (select all that apply)', choices: ['<title>', '<meta name="description">', '<link rel="stylesheet" precedence="...">', '<div class="header">'], answer: '[0,1,2]', tags: ['react19', 'metadata', 'hoisting'], explanation: 'React 19 hoists <title>, <meta>, and <link rel="stylesheet"> (with precedence prop) to <head>. Regular HTML elements like <div> stay where rendered — no hoisting.', docs: 'https://react.dev/blog/2024/12/05/react-19#support-for-document-metadata' } },

      // ── Module 10: Error Handling & Hydration ──
      { id: 'c3000010-0000-4000-8001-000000000001', moduleId: 'c3000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What is an Error Boundary in React?', choices: ['A try/catch block in render', 'A class component (or component using react-error-boundary library) that catches JavaScript errors in its child tree and renders a fallback UI', 'An ErrorBoundary hook', 'A browser DevTools feature'], answer: '1', tags: ['error-boundary'], explanation: 'Error Boundaries are class components implementing componentDidCatch() and static getDerivedStateFromError(). They catch errors in child components during render, lifecycle, and constructors — not event handlers.', docs: 'https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary' } },
      { id: 'c3000010-0000-4000-8001-000000000002', moduleId: 'c3000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What is a hydration error in React?', choices: ['An error when fetching data during SSR', 'A mismatch between server-rendered HTML and what React renders on the client during hydration', 'A timeout during hydration', 'A missing key prop error'], answer: '1', tags: ['hydration', 'errors'], explanation: 'Hydration errors (NG0500 equivalent in React) occur when server HTML and client render output differ. React 19 provides better diff output showing exactly what differs to help debug.', docs: 'https://react.dev/errors/418' } },
      { id: 'c3000010-0000-4000-8001-000000000003', moduleId: 'c3000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What new root option in React 19 handles errors NOT caught by Error Boundaries?', choices: ['onError', 'onUncaughtError', 'onFallback', 'onRenderError'], answer: '1', tags: ['react19', 'error-handling'], explanation: 'createRoot(container, { onUncaughtError: (err, errorInfo) => log(err) }) handles errors that propagate past all Error Boundaries. React 19 adds this for centralized error reporting.', docs: 'https://react.dev/reference/react-dom/client/createRoot' } },
      { id: 'c3000010-0000-4000-8001-000000000004', moduleId: 'c3000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What new root option in React 19 handles errors caught by Error Boundaries?', choices: ['onBoundaryError', 'onCaughtError', 'onHandledError', 'onRecoveredError'], answer: '1', tags: ['react19', 'error-handling'], explanation: 'createRoot(container, { onCaughtError: (err, errorInfo) => log(err) }) fires when an Error Boundary catches an error. Both onCaughtError and onUncaughtError allow centralized logging to services like Sentry.', docs: 'https://react.dev/reference/react-dom/client/createRoot' } },
      { id: 'c3000010-0000-4000-8001-000000000005', moduleId: 'c3000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'What common cause leads to hydration mismatches in React?', choices: ['Using too many components', 'Non-deterministic code in render: Date.now(), Math.random(), browser-only checks', 'Using CSS modules', 'Having too many props'], answer: '1', tags: ['hydration', 'errors', 'causes'], explanation: 'Hydration mismatches happen when render output differs between server and client. Common causes: Date.now() (different values), Math.random(), typeof window checks, or user-specific data in SSR.', docs: 'https://react.dev/errors/418' } },
      { id: 'c3000010-0000-4000-8001-000000000006', moduleId: 'c3000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'How does React 19 improve hydration error messages compared to React 18?', choices: ['Shorter error messages', 'Shows a diff of the server HTML vs expected client render — making it much easier to find the mismatch', 'Adds a stack trace', 'Silently recovers'], answer: '1', tags: ['react19', 'hydration', 'debugging'], explanation: 'React 19 provides a contextual diff in the console showing exactly which attributes or text differ between server and client — replacing the generic "Did not expect server HTML to contain..." message.', docs: 'https://react.dev/blog/2024/12/05/react-19#improvements-to-errors-and-diff-for-hydration-errors' } },
      { id: 'c3000010-0000-4000-8001-000000000007', moduleId: 'c3000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'What does suppressing hydration warnings with suppressHydrationWarning do?', choices: ['Disables all React warnings', 'Suppresses the warning for a specific element where intentional server/client differences exist (e.g., timestamps)', 'Disables hydration for that component', 'Fixes the mismatch automatically'], answer: '1', tags: ['hydration', 'suppressHydrationWarning'], explanation: 'suppressHydrationWarning={true} on an element tells React to ignore mismatches for that element. Only use it for intentional differences like user-specific data or browser-specific values — not to silence real bugs.', docs: 'https://react.dev/reference/react-dom/client/hydrateRoot' } },
      { id: 'c3000010-0000-4000-8001-000000000008', moduleId: 'c3000000-0000-4000-8000-000000000010', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which of the following are valid ways to handle errors in React? (select all that apply)', choices: ['Error Boundary class components', 'try/catch in async event handlers', 'onUncaughtError in createRoot', 'try/catch inside render'], answer: '[0,1,2]', tags: ['error-handling', 'react'], explanation: 'Error Boundaries catch render/lifecycle errors. try/catch works in async event handlers. onUncaughtError handles errors that escape boundaries. try/catch inside synchronous render does NOT catch errors — React owns render.', docs: 'https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary' } },
      { id: 'c3000010-0000-4000-8001-000000000009', moduleId: 'c3000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'React 19 changes how error logging works to reduce duplicate console errors. What is the new behavior?', choices: ['No change', 'React no longer logs errors to console.error twice — each error is reported once via the root handlers or re-thrown once', 'React uses console.warn instead', 'React groups errors'], answer: '1', tags: ['react19', 'error-logging'], explanation: 'React 19 fixes the duplicate error logging issue where errors were reported twice. Now errors are reported once — via onCaughtError/onUncaughtError or console.error — not duplicated.', docs: 'https://react.dev/blog/2024/12/05/react-19#error-handling' } },
      { id: 'c3000010-0000-4000-8001-000000000010', moduleId: 'c3000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'What is the react-error-boundary library and when is it useful?', choices: ['An official React package', 'A third-party library providing a functional ErrorBoundary component and useErrorBoundary hook — since React lacks a built-in functional boundary', 'A replacement for try/catch', 'An Angular-compatible error handler'], answer: '1', tags: ['error-boundary', 'react'], explanation: 'React\'s built-in Error Boundary requires a class component. react-error-boundary provides <ErrorBoundary> and useErrorBoundary() hook for functional-style error handling, reset, and retry capabilities.', docs: 'https://github.com/bvaughn/react-error-boundary' } },
      { id: 'c3000010-0000-4000-8001-000000000011', moduleId: 'c3000000-0000-4000-8000-000000000010', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'What new option in React 19 hydrateRoot() allows logging of hydration-related errors?', choices: ['onHydrationError', 'onRecoverableError', 'onHydrationMismatch', 'suppressErrors'], answer: '1', tags: ['react19', 'hydration', 'errors'], explanation: 'hydrateRoot(container, element, { onRecoverableError: (err) => log(err) }) captures recoverable errors including hydration mismatches. React 19 improves the error info passed to this callback.', docs: 'https://react.dev/reference/react-dom/client/hydrateRoot' } },
      { id: 'c3000010-0000-4000-8001-000000000012', moduleId: 'c3000000-0000-4000-8000-000000000010', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which of the following are improvements to error handling in React 19? (select all that apply)', choices: ['onCaughtError and onUncaughtError root options', 'Better hydration error diffs in console', 'No more duplicate error logging', 'Automatic error recovery without Error Boundaries'], answer: '[0,1,2]', tags: ['react19', 'error-handling', 'improvements'], explanation: 'React 19 improvements: onCaughtError/onUncaughtError options, hydration error diffs showing exact mismatches, and no more duplicate console errors. React still requires Error Boundaries for graceful error recovery — no auto-recovery.', docs: 'https://react.dev/blog/2024/12/05/react-19#error-handling' } },

      // ── Module 11: Context, Portals & Fragments ──
      { id: 'c3000011-0000-4000-8001-000000000001', moduleId: 'c3000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'In React 19, how do you render a Context provider?', choices: ['<MyContext.Provider value={val}>', '<MyContext value={val}>', 'Either — both work, but <Context> is preferred and <Context.Provider> is deprecated', 'useContextProvider(MyContext, val)'], answer: '2', tags: ['react19', 'context'], explanation: 'React 19 introduces <Context value={val}> as a shorthand. <Context.Provider> still works but is deprecated. Both render identically — migrate gradually.', docs: 'https://react.dev/blog/2024/12/05/react-19#context-as-a-provider' } },
      { id: 'c3000011-0000-4000-8001-000000000002', moduleId: 'c3000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What is a React Portal?', choices: ['A routing mechanism', 'A way to render children into a different DOM node outside the parent component\'s DOM hierarchy', 'A React Native feature', 'A Context provider shortcut'], answer: '1', tags: ['portals'], explanation: 'createPortal(children, domNode) renders children into a different DOM node — e.g., a modal rendered in document.body while logically nested in a component. React events still bubble through the component tree, not the DOM tree.', docs: 'https://react.dev/reference/react-dom/createPortal' } },
      { id: 'c3000011-0000-4000-8001-000000000003', moduleId: 'c3000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What is a React Fragment and why use it?', choices: ['A performance optimization', 'A wrapper that groups multiple elements without adding an extra DOM node', 'A code splitting boundary', 'A portal target'], answer: '1', tags: ['fragments'], explanation: '<Fragment> (or <>) lets you return multiple elements from a component without wrapping them in a div. This avoids unnecessary DOM nodes that could break CSS layout (flexbox, grid, table structures).', docs: 'https://react.dev/reference/react/Fragment' } },
      { id: 'c3000011-0000-4000-8001-000000000004', moduleId: 'c3000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'In React 19, can key be passed to a Fragment using the <> shorthand syntax?', choices: ['Yes', 'No — must use <Fragment key={k}> for keyed fragments', 'Only in class components', 'Only in lists'], answer: '1', tags: ['fragments', 'key'], explanation: '<key={k}> shorthand does not support key prop. Use <Fragment key={k}> for keyed fragments (e.g., inside map). The <> shorthand is only for non-keyed fragments.', docs: 'https://react.dev/reference/react/Fragment' } },
      { id: 'c3000011-0000-4000-8001-000000000005', moduleId: 'c3000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'medium', sortOrder: 4, data: { question: 'In React 19, what is the key prop change?', choices: ['key must now be a number', 'key can now be passed as a regular prop to any component, no longer a special React-only "reserved" prop that cannot be accessed', 'key is optional for lists', 'key is deprecated'], answer: '1', tags: ['react19', 'key'], explanation: 'React 19 allows passing key as a regular explicit prop to spread over: function Comp({ key }) {} or <Item key="1" /> where the component can read key. Previously key was reserved and inaccessible.', docs: 'https://react.dev/blog/2024/12/05/react-19#key-as-a-prop' } },
      { id: 'c3000011-0000-4000-8001-000000000006', moduleId: 'c3000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'medium', sortOrder: 5, data: { question: 'How does React event bubbling work with Portals?', choices: ['Events do not bubble through portals', 'Events bubble through the React component tree (not the DOM tree), so a portal\'s events bubble to its React parent', 'Events bubble through the DOM tree only', 'Portal events are captured only'], answer: '1', tags: ['portals', 'events'], explanation: 'Portal events bubble through the React virtual tree, not the DOM. A click in a modal portal bubbles to the React parent that renders the portal — enabling parent components to handle portal events.', docs: 'https://react.dev/reference/react-dom/createPortal#caveats' } },
      { id: 'c3000011-0000-4000-8001-000000000007', moduleId: 'c3000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'How do you avoid Context re-renders when the value changes?', choices: ['Use useMemo for the context value to only change when dependencies change', 'Use createContext with a stable default', 'Split contexts by concern (frequent vs infrequent updates)', 'Both memoizing the value and splitting contexts are valid strategies'], answer: '3', tags: ['context', 'performance'], explanation: 'Two approaches: 1) Memoize the value: const value = useMemo(() => ({ a, b }), [a, b]). 2) Split into separate contexts for different update frequencies. React re-renders all consumers when context value changes.', docs: 'https://react.dev/reference/react/createContext#optimizing-re-renders-when-passing-objects-and-functions' } },
      { id: 'c3000011-0000-4000-8001-000000000008', moduleId: 'c3000000-0000-4000-8000-000000000011', type: 'multiple', difficulty: 'medium', sortOrder: 7, data: { question: 'Which of the following are valid use cases for React Portals? (select all that apply)', choices: ['Modals and dialogs', 'Tooltips that overflow overflow:hidden containers', 'Global notifications/toasts', 'Lazy loading components'], answer: '[0,1,2]', tags: ['portals', 'use-cases'], explanation: 'Portals are ideal for UI that needs to visually escape the current DOM position: modals, tooltips (to avoid overflow clipping), and toasts. Lazy loading uses React.lazy/Suspense, not portals.', docs: 'https://react.dev/reference/react-dom/createPortal' } },
      { id: 'c3000011-0000-4000-8001-000000000009', moduleId: 'c3000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'hard', sortOrder: 8, data: { question: 'What is Context selector pattern and why is it used?', choices: ['Selecting which components receive Context', 'Using useMemo inside a consumer to derive and subscribe to only a slice of Context, reducing unnecessary re-renders', 'A Redux selector equivalent', 'A Context composition pattern'], answer: '1', tags: ['context', 'performance', 'selector'], explanation: 'Since useContext re-renders on any context value change, use: const selectedValue = useMemo(() => derive(useContext(MyContext)), [...]). Libraries like use-context-selector take this further with subscription-based approaches.', docs: 'https://react.dev/reference/react/useContext#optimizing-re-renders-when-passing-objects-and-functions' } },
      { id: 'c3000011-0000-4000-8001-000000000010', moduleId: 'c3000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'hard', sortOrder: 9, data: { question: 'What third argument does createPortal accept in React 19?', choices: ['A CSS class', 'A key prop for portal reconciliation', 'A ref', 'A priority hint'], answer: '1', tags: ['portals', 'react19', 'key'], explanation: 'createPortal(children, domNode, key) accepts an optional key as the third argument. This enables proper reconciliation when multiple portals are rendered conditionally in a list.', docs: 'https://react.dev/reference/react-dom/createPortal' } },
      { id: 'c3000011-0000-4000-8001-000000000011', moduleId: 'c3000000-0000-4000-8000-000000000011', type: 'single', difficulty: 'hard', sortOrder: 10, data: { question: 'In React 19, what replaces the legacy contextTypes / getChildContext API?', choices: ['Nothing — still valid', 'The modern createContext / useContext / Context-as-provider API which was already available since React 16.3', 'Signals', 'Redux'], answer: '1', tags: ['react19', 'context', 'legacy'], explanation: 'React 19 completely removes the legacy contextTypes and getChildContext API (deprecated since React 16.3). All code must migrate to createContext() / useContext() / <Context value={...}>.', docs: 'https://react.dev/blog/2024/12/05/react-19#removing-deprecated-react-apis' } },
      { id: 'c3000011-0000-4000-8001-000000000012', moduleId: 'c3000000-0000-4000-8000-000000000011', type: 'multiple', difficulty: 'hard', sortOrder: 11, data: { question: 'Which of the following are true about React Context in React 19? (select all that apply)', choices: ['<Context value={...}> replaces <Context.Provider value={...}>', 'All context consumers re-render when context value reference changes', 'useContext can now be called conditionally', 'Context works with Server Components'], answer: '[0,1,3]', tags: ['react19', 'context'], explanation: '<Context> as provider: yes. All consumers re-render on reference change: yes (memoize the value). useContext CANNOT be called conditionally (use use(Context) instead). Context does work in Server Components.', docs: 'https://react.dev/reference/react/useContext' } },
    ];

    for (const q of questions) {
      await queryRunner.query(
        `INSERT INTO "qcm_question" ("id", "moduleId", "type", "difficulty", "sortOrder", "data")
         VALUES ($1, $2, $3, $4, $5, $6)
         ON CONFLICT ("id") DO NOTHING`,
        [q.id, q.moduleId, q.type, q.difficulty, q.sortOrder, q.data]
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const ids: string[] = [];
    for (let m = 8; m <= 11; m++) {
      for (let q = 1; q <= 12; q++) {
        ids.push(`c300000${m}-0000-4000-8001-${String(q).padStart(12, '0')}`);
      }
    }
    await queryRunner.query(`DELETE FROM "qcm_question" WHERE "id" = ANY($1)`, [ids]);
  }
}
