import type { MigrationInterface, QueryRunner } from 'typeorm';

export class AddNodeJsDefinitionsQuestions1774200007000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const questions = [

      // ── EASY (10) ────────────────────────────────────────────────────────────

      { id: 'd4100001-0000-4000-8001-000000000001', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What is Node.js?', choices: ['A browser-based JavaScript framework for building SPAs', 'A JavaScript runtime built on Chrome\'s V8 engine that executes JavaScript code outside the browser, enabling server-side development', 'A compiled language that transpiles to C++ for performance', 'A JavaScript bundler similar to Webpack'], answer: '1', tags: ['nodejs', 'basics'], explanation: 'Node.js is a cross-platform, open-source JavaScript runtime environment built on Chrome\'s V8 engine. It allows JavaScript to run on the server, enabling building scalable network applications. Its non-blocking, event-driven architecture makes it well-suited for I/O-heavy applications like APIs, real-time apps, and CLI tools.', docs: 'https://nodejs.org/en/about' } },

      { id: 'd4100001-0000-4000-8001-000000000002', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What is the V8 engine in the context of Node.js?', choices: ['A version 8 upgrade of the Node.js standard library', 'An open-source, high-performance JavaScript and WebAssembly engine written in C++ that compiles JavaScript to native machine code', 'A garbage collector specific to Node.js servers', 'The eighth version of npm\'s dependency resolver'], answer: '1', tags: ['v8', 'internals'], explanation: 'V8 is Google\'s open-source JavaScript engine, also used in Chrome. It compiles JavaScript directly to native machine code using JIT (Just-In-Time) compilation rather than interpreting it. Node.js uses V8 to execute JavaScript on the server side, gaining V8\'s performance optimizations, garbage collection, and language feature support.', docs: 'https://nodejs.org/en/learn/getting-started/the-v8-javascript-engine' } },

      { id: 'd4100001-0000-4000-8001-000000000003', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What is non-blocking I/O in Node.js?', choices: ['I/O operations that run on a separate CPU core', 'A model where I/O operations (file reads, network requests) are initiated and then execution continues immediately without waiting for completion, using callbacks/promises for the result', 'A way to prevent JavaScript from performing any I/O operations', 'Blocking I/O that has been optimized with caching'], answer: '1', tags: ['non-blocking', 'async', 'basics'], explanation: 'In non-blocking I/O, when Node.js starts an I/O operation it registers a callback and immediately moves to the next line of code. When the I/O completes, the callback is pushed to the event queue. This means a single thread can handle thousands of concurrent I/O operations efficiently without needing one thread per connection (unlike traditional synchronous servers).', docs: 'https://nodejs.org/en/learn/asynchronous-work/overview-of-blocking-vs-non-blocking' } },

      { id: 'd4100001-0000-4000-8001-000000000004', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What is npm?', choices: ['Node Performance Monitor — a tool for profiling Node.js apps', 'Node Package Manager — the default package manager for Node.js used to install, publish, and manage JavaScript packages', 'A Node.js build tool similar to Webpack', 'The Node.js process manager for running apps in production'], answer: '1', tags: ['npm', 'basics'], explanation: 'npm (Node Package Manager) is the world\'s largest software registry and the default package manager bundled with Node.js. It lets you install third-party packages (`npm install`), run scripts (`npm run`), publish packages, and manage project dependencies via `package.json`. Alternatives include `yarn` and `pnpm`.', docs: 'https://docs.npmjs.com/' } },

      { id: 'd4100001-0000-4000-8001-000000000005', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 4, data: { question: 'What is package.json?', choices: ['A JSON file generated at runtime containing the current request metadata', 'A manifest file for a Node.js project that describes the project\'s metadata, dependencies, scripts, and configuration', 'A TypeScript configuration file for the TypeScript compiler', 'A lockfile that pins exact dependency versions'], answer: '1', tags: ['package-json', 'npm', 'basics'], explanation: '`package.json` is the manifest file at the root of a Node.js project. Key fields: `name`, `version`, `scripts` (runnable commands), `dependencies` (runtime packages), `devDependencies` (build/test-only packages), `main`/`module`/`exports` (entry points), and `type` ("module" for ESM or "commonjs"). It is the central configuration for npm.', docs: 'https://docs.npmjs.com/cli/v10/configuring-npm/package-json' } },

      { id: 'd4100001-0000-4000-8001-000000000006', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 5, data: { question: 'What is the process object in Node.js?', choices: ['A browser API polyfilled by Node.js', 'A global object providing information and control over the current Node.js process, including env vars, argv, exit codes, and standard streams', 'A child process created with child_process.fork()', 'A TypeScript type for representing OS processes'], answer: '1', tags: ['process', 'globals'], explanation: '`process` is a global Node.js object (no import needed) that provides: `process.env` (environment variables), `process.argv` (CLI arguments), `process.exit(code)` (terminate the process), `process.pid` (process ID), `process.stdin/stdout/stderr` (standard streams), and `process.cwd()` (current working directory).', docs: 'https://nodejs.org/api/process.html' } },

      { id: 'd4100001-0000-4000-8001-000000000007', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 6, data: { question: 'What is CommonJS (CJS) in Node.js?', choices: ['A web standard for shared JavaScript APIs across browsers', 'The original Node.js module system using require() and module.exports to load and export modules synchronously', 'A universal stylesheet format used in Node.js projects', 'A Node.js security standard for module sandboxing'], answer: '1', tags: ['commonjs', 'modules'], explanation: 'CommonJS is the original module system built into Node.js. Modules are loaded synchronously with `const x = require(\'./x\')` and exported via `module.exports = { ... }` or `exports.fn = fn`. CJS is well-suited for server-side code where synchronous loading is fine. It has been largely superseded by ES Modules (ESM) in modern Node.js.', docs: 'https://nodejs.org/api/modules.html' } },

      { id: 'd4100001-0000-4000-8001-000000000008', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 7, data: { question: 'What is a Buffer in Node.js?', choices: ['A temporary array for storing React component renders', 'A fixed-size chunk of memory allocated outside the V8 heap used to work with raw binary data (TCP streams, file I/O, cryptography)', 'A queue data structure provided by the Node.js standard library', 'A readline buffer for collecting user terminal input'], answer: '1', tags: ['buffer', 'binary', 'basics'], explanation: 'A `Buffer` is a global Node.js class that allocates raw memory outside V8\'s heap. It is used to handle binary data — reading files as bytes, processing TCP/UDP packets, encoding/decoding between UTF-8 and base64, and cryptographic operations. Common methods: `Buffer.from()`, `Buffer.alloc()`, `buf.toString(\'utf8\')`.', docs: 'https://nodejs.org/api/buffer.html' } },

      { id: 'd4100001-0000-4000-8001-000000000009', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 8, data: { question: 'What is the event loop in Node.js?', choices: ['A design pattern for infinite recursive function calls', 'The mechanism that allows Node.js to perform non-blocking I/O operations by offloading operations to the OS and processing their callbacks when complete', 'A for loop that continuously reads event log files', 'A libuv thread that polls the OS for file system events only'], answer: '1', tags: ['event-loop', 'internals'], explanation: 'The event loop is the heart of Node.js concurrency. It runs on the single JavaScript thread and continuously checks: are there callbacks to process? Are there timers ready? Are there I/O results waiting? The loop phases (timers, I/O, idle, poll, check, close) determine the order in which callbacks are processed, enabling non-blocking behavior on a single thread.', docs: 'https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick' } },

      { id: 'd4100001-0000-4000-8001-000000000010', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 9, data: { question: 'What is an ES Module (ESM) in Node.js?', choices: ['An older Node.js module format based on require()', 'The ECMAScript standard module system using import/export syntax, natively supported in Node.js 12+ via .mjs files or "type":"module" in package.json', 'A module bundler built into Node.js since version 18', 'A Webpack configuration option for code splitting'], answer: '1', tags: ['esm', 'modules'], explanation: 'ES Modules are the official ECMAScript standard for JavaScript modules. In Node.js they use `import x from \'./x.js\'` and `export const fn = ...`. Enabled by using `.mjs` file extension or setting `"type": "module"` in `package.json`. Unlike CJS, ESM imports are statically analyzable and loaded asynchronously. The two systems have important interop restrictions.', docs: 'https://nodejs.org/api/esm.html' } },

      // ── MEDIUM (14) ──────────────────────────────────────────────────────────

      { id: 'd4100001-0000-4000-8001-000000000011', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 10, data: { question: 'What are the phases of the Node.js event loop?', choices: ['mount → update → destroy', 'timers → pending callbacks → idle/prepare → poll → check → close callbacks', 'microtasks → macrotasks → I/O → rendering', 'queue → process → callback → flush'], answer: '1', tags: ['event-loop', 'phases', 'internals'], explanation: 'The event loop has 6 phases: (1) **timers** — executes `setTimeout`/`setInterval` callbacks; (2) **pending callbacks** — I/O callbacks deferred to next loop; (3) **idle/prepare** — internal use; (4) **poll** — retrieves new I/O events; (5) **check** — executes `setImmediate` callbacks; (6) **close callbacks** — e.g., `socket.on("close")`. `process.nextTick` and Promises (microtasks) run between each phase.', docs: 'https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick' } },

      { id: 'd4100001-0000-4000-8001-000000000012', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 11, data: { question: 'What is libuv in Node.js?', choices: ['A JavaScript parser used by Node.js to tokenize source files', 'A multi-platform C library that provides Node.js with the event loop, async I/O, a thread pool, and OS abstractions for file system, DNS, and networking', 'A built-in Node.js module for managing UV (ultraviolet) light sensor data', 'The C++ bridge between V8 and the Node.js standard library'], answer: '1', tags: ['libuv', 'internals'], explanation: 'libuv is the C library at the core of Node.js. It implements: the event loop, async TCP/UDP networking (using OS event notifications like epoll/kqueue/IOCP), a thread pool (default 4 threads) for blocking operations (file I/O, DNS, crypto), child process management, and cross-platform abstractions. Node.js uses libuv to offload work the OS can handle asynchronously.', docs: 'https://libuv.org/' } },

      { id: 'd4100001-0000-4000-8001-000000000013', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 12, data: { question: 'What is a Stream in Node.js?', choices: ['A real-time video/audio pipeline built into Node.js', 'An abstract interface for working with streaming data — reading or writing data in chunks rather than loading it all into memory at once', 'A database connection pool that streams queries', 'A logging utility that streams output to a file'], answer: '1', tags: ['streams', 'io'], explanation: 'Node.js streams are objects that let you read or write data piece-by-piece. There are four types: **Readable** (source of data, e.g., `fs.createReadStream`), **Writable** (destination, e.g., `fs.createWriteStream`), **Duplex** (both readable and writable, e.g., TCP socket), and **Transform** (duplex that modifies data as it passes through, e.g., `zlib.createGzip`). Streams are memory-efficient for large files or continuous data.', docs: 'https://nodejs.org/api/stream.html' } },

      { id: 'd4100001-0000-4000-8001-000000000014', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 13, data: { question: 'What is the EventEmitter in Node.js?', choices: ['A browser DOM event listener polyfill', 'A core Node.js class that implements the observer pattern, allowing objects to emit named events and register listener callbacks', 'A utility for emitting synthetic browser events in Node.js tests', 'A class that emits HTTP events from the Node.js HTTP server'], answer: '1', tags: ['eventemitter', 'events'], explanation: '`EventEmitter` (from the `events` module) is the foundation of Node.js\'s event-driven architecture. Objects that extend `EventEmitter` can: `emit(\'event\', data)` to broadcast an event, `on(\'event\', cb)` to subscribe, `once(\'event\', cb)` to subscribe to the first occurrence only, and `removeListener()` to unsubscribe. Many Node.js built-ins (streams, http.Server) extend EventEmitter.', docs: 'https://nodejs.org/api/events.html' } },

      { id: 'd4100001-0000-4000-8001-000000000015', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 14, data: { question: 'What is child_process in Node.js?', choices: ['A lightweight subprocess created by splitting a single-thread worker', 'A built-in Node.js module that allows spawning child OS processes, enabling parallel execution, shell commands, and IPC with the parent process', 'A type of promise that resolves when a child component renders', 'A Node.js cluster worker limited to handling child routes'], answer: '1', tags: ['child-process', 'concurrency'], explanation: 'The `child_process` module provides: `spawn()` — streams stdin/stdout of any executable; `exec()` — runs a shell command and buffers output; `execFile()` — like exec but without a shell; `fork()` — a special spawn for Node.js scripts that enables IPC (inter-process communication) via `child.send()` and `process.on(\'message\')`. Used for CPU-bound tasks and shell automation.', docs: 'https://nodejs.org/api/child_process.html' } },

      { id: 'd4100001-0000-4000-8001-000000000016', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 15, data: { question: 'What is the cluster module in Node.js?', choices: ['A built-in Node.js module that groups npm packages into install clusters', 'A module that allows a Node.js application to create multiple worker processes (one per CPU core) that share the same server port, improving throughput', 'A Redis cluster client built into Node.js', 'A module for creating grouped WebSocket connections'], answer: '1', tags: ['cluster', 'concurrency', 'performance'], explanation: 'Node.js runs on a single thread. The `cluster` module lets you fork multiple worker processes (using `cluster.fork()`) that all share the same TCP/HTTP port. The master process distributes incoming connections to workers. This utilizes multi-core CPUs to handle more concurrent requests. It is an alternative to running multiple Node.js instances behind a load balancer.', docs: 'https://nodejs.org/api/cluster.html' } },

      { id: 'd4100001-0000-4000-8001-000000000017', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 16, data: { question: 'What are Worker Threads in Node.js?', choices: ['OS threads automatically created by libuv for all async operations', 'A Node.js module that allows running JavaScript in parallel threads sharing memory, suitable for CPU-intensive tasks without blocking the event loop', 'Aliases for child processes created with child_process.fork()', 'Browser Web Workers ported to Node.js for DOM manipulation'], answer: '1', tags: ['worker-threads', 'concurrency'], explanation: '`worker_threads` (stable since Node 12) allows running JavaScript in true parallel threads within the same process, sharing memory via `SharedArrayBuffer` and `Atomics`. Unlike `child_process`, worker threads share the V8 heap partially and communicate via message passing (`postMessage`). Best for CPU-intensive tasks (image processing, ML inference, compression) that would otherwise block the event loop.', docs: 'https://nodejs.org/api/worker_threads.html' } },

      { id: 'd4100001-0000-4000-8001-000000000018', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 17, data: { question: 'What is process.nextTick() in Node.js?', choices: ['A function that delays execution by one event loop tick (one millisecond)', 'A function that schedules a callback to run at the end of the current operation, before the event loop moves to the next phase — before any I/O callbacks', 'An alias for setImmediate() with higher priority', 'A way to schedule a microtask that runs after all Promise callbacks'], answer: '1', tags: ['nextTick', 'event-loop', 'async'], explanation: '`process.nextTick(cb)` queues a callback to run immediately after the current synchronous code completes, before the event loop moves to its next phase. It has higher priority than Promise microtasks and `setImmediate`. Overusing it can starve I/O. `queueMicrotask(cb)` (from the Promises spec) and `setImmediate(cb)` (runs in the check phase) are alternatives.', docs: 'https://nodejs.org/en/learn/asynchronous-work/understanding-process-nexttick' } },

      { id: 'd4100001-0000-4000-8001-000000000019', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 18, data: { question: 'What is the difference between setImmediate() and setTimeout() in Node.js?', choices: ['setImmediate runs after the current event loop cycle in the check phase; setTimeout runs after at least the specified delay in the timers phase', 'setImmediate is a Promise-based version of setTimeout(0)', 'setTimeout runs synchronously; setImmediate runs asynchronously', 'They are identical but setImmediate is deprecated'], answer: '0', tags: ['setImmediate', 'setTimeout', 'event-loop'], explanation: '`setTimeout(fn, 0)` schedules `fn` in the **timers phase** after at least 0ms (but often slightly later due to OS granularity). `setImmediate(fn)` schedules `fn` in the **check phase** — after I/O events in the current loop cycle. In an I/O callback, `setImmediate` will always fire before `setTimeout(fn, 0)`. Outside I/O context, the order is non-deterministic.', docs: 'https://nodejs.org/en/learn/asynchronous-work/understanding-setimmediate' } },

      { id: 'd4100001-0000-4000-8001-000000000020', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 19, data: { question: 'What is the fs module in Node.js?', choices: ['A file system browser polyfill for Node.js', 'The built-in Node.js module for interacting with the file system — reading, writing, deleting, renaming files and directories', 'A front-end state management library for Node.js', 'A fast stream compression module bundled with Node.js'], answer: '1', tags: ['fs', 'file-system'], explanation: 'The `fs` (file system) module provides APIs to interact with the OS file system. Key methods: `fs.readFile()` / `fs.writeFile()` (async with callbacks), `fs.promises.readFile()` (Promise-based), `fs.readFileSync()` (sync, blocks event loop), `fs.createReadStream()` / `fs.createWriteStream()` (streaming). Always prefer async or stream APIs for production code.', docs: 'https://nodejs.org/api/fs.html' } },

      { id: 'd4100001-0000-4000-8001-000000000021', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 20, data: { question: 'What is the http module in Node.js?', choices: ['A third-party HTTP client library equivalent to fetch', 'The built-in Node.js module for creating HTTP servers and making HTTP requests without external dependencies', 'A module that polyfills the browser fetch API in Node.js', 'A compression middleware for HTTP responses'], answer: '1', tags: ['http', 'networking'], explanation: 'The `http` module lets you create HTTP servers with `http.createServer((req, res) => { ... }).listen(3000)`. The `req` is an `IncomingMessage` (readable stream with headers/method/url); `res` is a `ServerResponse` (writable stream). For outgoing requests: `http.request(options, callback)`. For production, most developers use Express/Fastify which wrap `http` with a better API.', docs: 'https://nodejs.org/api/http.html' } },

      { id: 'd4100001-0000-4000-8001-000000000022', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 21, data: { question: 'What is the path module in Node.js?', choices: ['A module for routing HTTP requests in Node.js', 'A built-in module providing utilities for working with file and directory paths in a cross-platform way', 'A module for resolving npm package paths', 'A Node.js module for reading the system PATH environment variable'], answer: '1', tags: ['path', 'file-system'], explanation: 'The `path` module provides cross-platform path utilities: `path.join(...segments)` builds a path correctly for the OS, `path.resolve()` gives an absolute path, `path.dirname()` / `path.basename()` / `path.extname()` parse components, and `path.sep` gives the OS separator (`/` or `\\`). Always use `path.join` instead of string concatenation to avoid Windows/Linux incompatibilities.', docs: 'https://nodejs.org/api/path.html' } },

      { id: 'd4100001-0000-4000-8001-000000000023', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 22, data: { question: 'What is the __dirname variable in Node.js (CJS)?', choices: ['A global variable always pointing to the current user\'s home directory', 'A CommonJS-only variable containing the absolute path of the directory in which the current module file is located', 'A Node.js variable for the root directory of the project', 'An ESM global containing the path to the node_modules folder'], answer: '1', tags: ['dirname', 'globals', 'commonjs'], explanation: '`__dirname` (and `__filename`) are available automatically in CommonJS modules. `__dirname` is the absolute path of the folder containing the current file. Combined with `path.join(__dirname, \'../config.json\')` it gives you reliable paths regardless of where the process was started. In ESM, use `import.meta.url` and `new URL(\'./file\', import.meta.url)` instead.', docs: 'https://nodejs.org/api/modules.html#__dirname' } },

      { id: 'd4100001-0000-4000-8001-000000000024', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 23, data: { question: 'What is error-first callback pattern in Node.js?', choices: ['A pattern where the first argument of a callback is reserved for an error object (null if success), and subsequent arguments hold the result', 'A pattern where errors are always thrown synchronously before any async work begins', 'A convention where errors are returned as the last argument of callbacks', 'A Node.js-specific try/catch pattern for async functions'], answer: '0', tags: ['error-first', 'callback', 'patterns'], explanation: 'The error-first (errback) convention is: `callback(err, result)` where the first argument is `null` on success or an `Error` instance on failure. Example: `fs.readFile(path, (err, data) => { if (err) return handleError(err); use(data); })`. This pattern predates Promises and is the standard async convention for Node.js core APIs. Promises and async/await have largely replaced it in modern code.', docs: 'https://nodejs.org/en/learn/asynchronous-work/javascript-asynchronous-programming-and-callbacks' } },

      // ── HARD (12) ────────────────────────────────────────────────────────────

      { id: 'd4100001-0000-4000-8001-000000000025', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 24, data: { question: 'What is backpressure in Node.js streams?', choices: ['The CPU pressure caused by too many active event listeners', 'A flow control mechanism where a writable stream signals a readable stream to pause sending data when its internal buffer is full', 'An OS-level TCP backpressure signal forwarded to Node.js', 'The memory pressure from storing large Buffers in the V8 heap'], answer: '1', tags: ['backpressure', 'streams', 'advanced'], explanation: 'Backpressure occurs when a writable stream\'s buffer fills faster than it can drain. The `write()` method returns `false` when the highWaterMark is exceeded — the readable source should stop calling `read()` until the writable emits `\'drain\'`. Stream `pipe()` handles this automatically. Ignoring backpressure causes unbounded memory growth (the full source is buffered in memory).', docs: 'https://nodejs.org/en/learn/modules/backpressuring-in-streams' } },

      { id: 'd4100001-0000-4000-8001-000000000026', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 25, data: { question: 'What is the libuv thread pool used for in Node.js?', choices: ['Executing all JavaScript code in parallel across CPU cores', 'Performing blocking operations (file I/O, DNS lookups, crypto, zlib) that cannot be made truly async at the OS level', 'Running garbage collection concurrently with the event loop', 'Executing setTimeout and setInterval callbacks off the main thread'], answer: '1', tags: ['libuv', 'thread-pool', 'internals'], explanation: 'libuv maintains a default thread pool of 4 threads (configurable via `UV_THREADPOOL_SIZE`). It handles: file system operations, DNS resolution (`dns.lookup`), `crypto` (blocking hashing), and `zlib` operations. Network I/O (TCP/UDP) does NOT use the thread pool — it uses OS async mechanisms (epoll/kqueue/IOCP). Increasing thread pool size helps when many concurrent file/crypto operations queue up.', docs: 'https://docs.libuv.org/en/v1.x/threadpool.html' } },

      { id: 'd4100001-0000-4000-8001-000000000027', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 26, data: { question: 'What is the difference between microtasks and macrotasks in Node.js?', choices: ['Microtasks are smaller async operations; macrotasks are operations on large data sets', 'Microtasks (Promise callbacks, process.nextTick) run between each event loop phase; macrotasks (setTimeout, setImmediate, I/O) are scheduled in specific event loop phases', 'Macrotasks run in the thread pool; microtasks run on the main thread', 'They are identical — the distinction is a browser concept not applicable to Node.js'], answer: '1', tags: ['microtasks', 'macrotasks', 'event-loop', 'advanced'], explanation: 'After each event loop phase (and after each macrotask), Node.js drains the **microtask queue** — which includes `process.nextTick` callbacks (highest priority) and Promise `.then` callbacks. Only after the microtask queue is empty does the event loop advance to the next phase. This means `nextTick` and resolved Promises always run before `setImmediate` or the next I/O callback.', docs: 'https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick' } },

      { id: 'd4100001-0000-4000-8001-000000000028', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 27, data: { question: 'What is module caching in Node.js CJS?', choices: ['A Redis-backed cache for npm module imports', 'The behavior where require() returns the same exported object on subsequent calls — the module is executed once and its exports are cached in require.cache', 'A V8 optimization that compiles frequently used modules to machine code', 'An npm feature that caches downloaded packages on disk'], answer: '1', tags: ['module-cache', 'commonjs', 'internals'], explanation: 'In CJS, the first time you `require(\'./foo\')`, Node.js executes `foo.js` and stores the resulting `module.exports` in `require.cache` keyed by the resolved filename. All subsequent `require` calls for the same path return the cached export without re-executing the file. This means modules are effectively singletons. You can delete an entry from `require.cache` to force a re-load (useful in testing).', docs: 'https://nodejs.org/api/modules.html#caching' } },

      { id: 'd4100001-0000-4000-8001-000000000029', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 28, data: { question: 'What are the key differences between cluster module and worker_threads?', choices: ['cluster uses shared memory; worker_threads use separate processes', 'cluster creates separate OS processes (each with its own event loop and V8 heap) sharing a port; worker_threads run in the same process sharing memory via SharedArrayBuffer', 'worker_threads are for CPU tasks; cluster is for GPU tasks', 'They are identical — cluster is just a higher-level API over worker_threads'], answer: '1', tags: ['cluster', 'worker-threads', 'concurrency', 'advanced'], explanation: '`cluster` forks separate Node.js processes — each has its own V8 heap, event loop, and memory space. Communication is via IPC (slower but isolated). `worker_threads` run inside the same process and can share memory via `SharedArrayBuffer` (faster). Use cluster for scaling HTTP servers across CPU cores; use worker_threads for CPU-intensive computations that need to share data efficiently.', docs: 'https://nodejs.org/api/worker_threads.html' } },

      { id: 'd4100001-0000-4000-8001-000000000030', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 29, data: { question: 'What is the crypto module in Node.js?', choices: ['A third-party library for blockchain development in Node.js', 'The built-in Node.js module providing cryptographic functionality including hashing, HMAC, ciphers, key generation, and digital signatures', 'A module for encrypting environment variables only', 'A Node.js implementation of the Web Crypto API (browser standard)'], answer: '1', tags: ['crypto', 'security'], explanation: 'Node.js\'s built-in `crypto` module wraps OpenSSL. Key APIs: `crypto.createHash(\'sha256\').update(data).digest(\'hex\')` (hashing), `crypto.createHmac()` (HMAC), `crypto.randomBytes(n)` (secure random), `crypto.createCipher/Decipher()` (symmetric encryption), and `crypto.generateKeyPair()` (asymmetric). For browser-compatible crypto, `globalThis.crypto` (WebCrypto API) is also available in Node.js 19+.', docs: 'https://nodejs.org/api/crypto.html' } },

      { id: 'd4100001-0000-4000-8001-000000000031', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 30, data: { question: 'What is CJS/ESM interoperability in Node.js?', choices: ['CJS and ESM modules are fully compatible and can be mixed freely', 'CJS can require() ESM modules asynchronously in Node.js 22+; ESM can import CJS modules but only gets the default export (module.exports); named CJS exports are not individually importable via static ESM import', 'ESM cannot import CJS modules at all', 'CJS and ESM are identical in Node.js — "type":"module" is a cosmetic flag'], answer: '1', tags: ['esm', 'commonjs', 'interop', 'advanced'], explanation: 'CJS → ESM: use dynamic `await import(\'esm-pkg\')` (the only option in Node.js < 22; synchronous `require()` of ESM throws). ESM → CJS: `import cjsMod from \'./cjs.cjs\'` works but you only get `module.exports` as the default — individual named exports must be destructured from default. This asymmetry is a common source of "package is ESM only" errors when consuming modern packages.', docs: 'https://nodejs.org/api/esm.html#interoperability-with-commonjs' } },

      { id: 'd4100001-0000-4000-8001-000000000032', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 31, data: { question: 'What is the util module in Node.js?', choices: ['A utility belt module for building Express middleware', 'A built-in Node.js module with helper functions including util.promisify(), util.inspect(), util.format(), and util.types', 'A module for building CLI utilities with readline', 'A third-party lodash-style utility library built into Node.js'], answer: '1', tags: ['util', 'stdlib'], explanation: 'Key `util` utilities: `util.promisify(fn)` converts an error-first callback function into a Promise-returning function; `util.inspect(obj, opts)` converts any object to a string (used by `console.log` internally); `util.format(fmt, ...args)` does printf-style string formatting; `util.types` provides type-checking helpers; `util.deprecate()` wraps a function to emit deprecation warnings.', docs: 'https://nodejs.org/api/util.html' } },

      { id: 'd4100001-0000-4000-8001-000000000033', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 32, data: { question: 'What is the os module in Node.js?', choices: ['A module that provides access to the underlying operating system shell', 'A built-in module providing OS-related utility methods: platform, CPU info, memory, hostname, home directory, and network interfaces', 'A module for creating OS-level daemons', 'An abstraction layer for running Docker containers from Node.js'], answer: '1', tags: ['os', 'stdlib'], explanation: 'The `os` module provides OS information: `os.platform()` (\'linux\', \'darwin\', \'win32\'), `os.cpus()` (array of CPU core info), `os.totalmem()` / `os.freemem()` (bytes), `os.hostname()`, `os.homedir()`, `os.tmpdir()`, `os.networkInterfaces()`, and `os.EOL` (line ending). Used for diagnostics, to set thread pool size based on CPU count, or to build cross-platform CLI tools.', docs: 'https://nodejs.org/api/os.html' } },

      { id: 'd4100001-0000-4000-8001-000000000034', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 33, data: { question: 'What is a Transform stream in Node.js?', choices: ['A stream that only reads data and transforms it in place', 'A duplex stream that modifies or transforms data as it is written to it, making transformed data available to be read', 'A readable stream that emits transformed events instead of data events', 'A writable stream with built-in compression'], answer: '1', tags: ['transform-stream', 'streams', 'advanced'], explanation: 'A Transform stream implements both the Readable and Writable interfaces. You write data in, it processes it, and you read the transformed result out. To create one, extend `Transform` and implement `_transform(chunk, encoding, callback)`. Examples: `zlib.createGzip()` compresses chunks; `crypto.createCipheriv()` encrypts chunks. Transform streams are chainable with `pipe()` for processing pipelines.', docs: 'https://nodejs.org/api/stream.html#implementing-a-transform-stream' } },

      { id: 'd4100001-0000-4000-8001-000000000035', moduleId: 'd4100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 34, data: { question: 'What is graceful shutdown in a Node.js HTTP server?', choices: ['Shutting down the server by sending a SIGTERM from a separate process', 'The pattern of listening for SIGTERM/SIGINT signals, stopping the server from accepting new connections, waiting for in-flight requests to complete, then exiting cleanly', 'Calling process.exit(0) immediately on receiving a shutdown signal', 'Using cluster.fork() to restart workers without downtime'], answer: '1', tags: ['graceful-shutdown', 'production', 'advanced'], explanation: 'Graceful shutdown ensures in-flight requests are not abruptly terminated when the process receives a shutdown signal (e.g., `SIGTERM` from Kubernetes). The pattern: `process.on(\'SIGTERM\', () => { server.close(() => { db.disconnect(); process.exit(0); }); })`. `server.close()` stops accepting new connections but lets existing ones finish. Connection draining may need a timeout to force-exit if requests take too long.', docs: 'https://nodejs.org/api/http.html#serverclose' } },
    ];

    for (const q of questions) {
      await queryRunner.query(
        `INSERT INTO "qcm_question" ("id", "moduleId", "type", "difficulty", "sortOrder", "data")
         VALUES ($1, $2, $3, $4, $5, $6)
         ON CONFLICT ("id") DO NOTHING`,
        [q.id, q.moduleId, q.type, q.difficulty, q.sortOrder, JSON.stringify(q.data)]
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const ids = Array.from({ length: 35 }, (_, i) =>
      `d4100001-0000-4000-8001-${String(i + 1).padStart(12, '0')}`
    );
    await queryRunner.query(
      `DELETE FROM "qcm_question" WHERE "id" = ANY($1)`,
      [ids]
    );
  }
}
