import type { MigrationInterface, QueryRunner } from 'typeorm';

export class AddTypescriptDefinitionsQuestions1774200001000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const questions = [
      // ── EASY (6) ────────────────────────────────────────────────────────────
      { id: '07000001-0000-4000-8001-000000000001', moduleId: '07000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What is TypeScript?', choices: ['A superset of JavaScript that adds optional static typing and compiles to JavaScript', 'A JavaScript runtime built on V8', 'A CSS preprocessor for typed stylesheets', 'A JavaScript framework for building UIs'], answer: '0', tags: ['typescript', 'basics'], explanation: 'TypeScript is a statically typed superset of JavaScript developed by Microsoft. It adds optional type annotations, interfaces, generics, and other features that compile down to plain JavaScript, catching errors at compile time rather than runtime.', docs: 'https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html' } },
      { id: '07000001-0000-4000-8001-000000000002', moduleId: '07000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What is a type alias in TypeScript?', choices: ['A way to rename an existing variable at runtime', 'A name given to any type using the `type` keyword', 'A TypeScript class decorator', 'An alias for a JavaScript prototype'], answer: '1', tags: ['type-alias', 'basics'], explanation: 'A type alias creates a new name for any type using the `type` keyword. Example: `type StringOrNumber = string | number`. Unlike interfaces, type aliases can represent primitives, unions, intersections, tuples, and any other type.', docs: 'https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-aliases' } },
      { id: '07000001-0000-4000-8001-000000000003', moduleId: '07000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What is an interface in TypeScript?', choices: ['A TypeScript class with only abstract methods', 'A named description of the shape (structure) of an object', 'A function declaration without implementation', 'A module boundary'], answer: '1', tags: ['interface', 'basics'], explanation: 'An interface defines the shape of an object — its required properties and their types. Interfaces support extension (`extends`), declaration merging, and are erased at runtime. They are ideal for describing object contracts.', docs: 'https://www.typescriptlang.org/docs/handbook/2/objects.html' } },
      { id: '07000001-0000-4000-8001-000000000004', moduleId: '07000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What is a union type in TypeScript?', choices: ['A type that requires all specified types at once', 'A type that allows a value to be one of several specified types', 'A combined class declaration', 'A way to merge two modules'], answer: '1', tags: ['union', 'basics'], explanation: 'A union type (written with `|`) means a value can be type A OR type B. Example: `string | number` accepts both strings and numbers. TypeScript uses type guards to narrow the type within conditional blocks.', docs: 'https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#union-types' } },
      { id: '07000001-0000-4000-8001-000000000005', moduleId: '07000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 4, data: { question: 'What is a tuple in TypeScript?', choices: ['An array of any number of elements of the same type', 'A fixed-length array where each position has a known, specific type', 'A key-value pair structure', 'A union of array types'], answer: '1', tags: ['tuple', 'basics'], explanation: 'A tuple is an array with a fixed number of elements whose types are known at each position. Example: `[string, number]` means the first element must be a string and the second a number. Length and types are enforced at compile time.', docs: 'https://www.typescriptlang.org/docs/handbook/2/objects.html#tuple-types' } },
      { id: '07000001-0000-4000-8001-000000000006', moduleId: '07000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 5, data: { question: 'What is an enum in TypeScript?', choices: ['A function that returns a numeric value', 'A set of named constants grouped under a single name', 'A type that only accepts string values', 'A collection of optional properties'], answer: '1', tags: ['enum', 'basics'], explanation: 'An enum defines a set of named numeric or string constants. Example: `enum Direction { Up, Down, Left, Right }`. Enums improve readability and make intent clearer when working with a fixed set of related values. They exist at runtime (unlike most TypeScript types).', docs: 'https://www.typescriptlang.org/docs/handbook/enums.html' } },

      // ── MEDIUM (8) ────────────────────────────────────────────────────────────
      { id: '07000001-0000-4000-8001-000000000007', moduleId: '07000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 6, data: { question: 'What is a generic in TypeScript?', choices: ['A type that applies only to primitive values', 'A reusable type placeholder that lets you write type-safe code working with multiple types', 'A type assertion keyword', 'A built-in utility type'], answer: '1', tags: ['generics', 'types'], explanation: 'Generics allow you to write functions, classes, and interfaces that work with any type while preserving type safety. Example: `function identity<T>(x: T): T` works with any type T. The concrete type is inferred or provided at the call site.', docs: 'https://www.typescriptlang.org/docs/handbook/2/generics.html' } },
      { id: '07000001-0000-4000-8001-000000000008', moduleId: '07000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 7, data: { question: 'What is an intersection type in TypeScript?', choices: ['A type that can be either A or B', 'A type that combines multiple types into one, requiring all properties from each type simultaneously', 'A type used only inside class declarations', 'The result of type narrowing'], answer: '1', tags: ['intersection', 'types'], explanation: 'An intersection type (written with `&`) combines multiple types into one. A value of an intersection type must satisfy ALL combined types at once. Example: `type AB = A & B` — a value must have all properties of both A and B.', docs: 'https://www.typescriptlang.org/docs/handbook/2/objects.html#intersection-types' } },
      { id: '07000001-0000-4000-8001-000000000009', moduleId: '07000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 8, data: { question: 'What is `Record<K, V>` in TypeScript?', choices: ['A class for storing key-value pairs at runtime', 'A utility type that constructs an object type with keys of type K and values of type V', 'A decorator for recording method calls', 'A type alias for Map<K, V>'], answer: '1', tags: ['record', 'utility-types'], explanation: '`Record<K, V>` is a built-in utility type that creates an object type where all keys are of type K and all values are of type V. Example: `Record<string, number>` is equivalent to `{ [key: string]: number }`. It is often used to type dictionaries and lookup tables.', docs: 'https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeys-type' } },
      { id: '07000001-0000-4000-8001-000000000010', moduleId: '07000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 9, data: { question: 'What is `Partial<T>` in TypeScript?', choices: ['A type that makes all properties of T required', 'A utility type that makes all properties of T optional', 'A type that removes all methods from T', 'A type that picks only primitive properties from T'], answer: '1', tags: ['partial', 'utility-types'], explanation: '`Partial<T>` constructs a type with all properties of T set to optional by adding `?` to each property. It is useful for update/patch functions where only some fields need to be passed.', docs: 'https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype' } },
      { id: '07000001-0000-4000-8001-000000000011', moduleId: '07000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 10, data: { question: 'What is `Readonly<T>` in TypeScript?', choices: ['A type that prevents reassignment of the variable itself', 'A utility type that makes all properties of T read-only so they cannot be reassigned', 'A decorator that locks a class from being extended', 'A type that replaces mutable arrays with frozen ones at runtime'], answer: '1', tags: ['readonly', 'utility-types'], explanation: '`Readonly<T>` constructs a type where all properties of T are marked `readonly`, preventing them from being reassigned after initialization. This constraint is enforced at compile time only — it does not freeze the object at runtime.', docs: 'https://www.typescriptlang.org/docs/handbook/utility-types.html#readonlytype' } },
      { id: '07000001-0000-4000-8001-000000000012', moduleId: '07000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 11, data: { question: 'What is `Pick<T, K>` in TypeScript?', choices: ['A utility type that removes properties K from type T', 'A utility type that constructs a type by selecting only the properties K from type T', 'A runtime function to extract properties from an object', 'A way to choose between union type members'], answer: '1', tags: ['pick', 'utility-types'], explanation: '`Pick<T, K>` creates a new type by including only the properties whose keys are in K (a union of string literals). Example: `Pick<User, "id" | "name">` creates a type with only the `id` and `name` properties of User.', docs: 'https://www.typescriptlang.org/docs/handbook/utility-types.html#picktype-keys' } },
      { id: '07000001-0000-4000-8001-000000000013', moduleId: '07000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 12, data: { question: 'What is `Omit<T, K>` in TypeScript?', choices: ['A utility type that includes only properties K from T', 'A utility type that constructs a type by removing properties K from type T', 'A way to skip type checking on certain properties', 'A utility that removes optional modifiers from T'], answer: '1', tags: ['omit', 'utility-types'], explanation: '`Omit<T, K>` is the opposite of `Pick`. It creates a new type from T excluding the properties whose keys are in K. Example: `Omit<User, "password">` gives all User properties except `password`. Internally it is implemented as `Pick<T, Exclude<keyof T, K>>`.', docs: 'https://www.typescriptlang.org/docs/handbook/utility-types.html#omittype-keys' } },
      { id: '07000001-0000-4000-8001-000000000014', moduleId: '07000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 13, data: { question: 'What is a type guard in TypeScript?', choices: ['A keyword that protects class members from external access', 'A runtime check that narrows the type of a value to a more specific type within a conditional block', 'A compiler option that enforces strict null checks', 'A decorator that validates function arguments at runtime'], answer: '1', tags: ['type-guard', 'narrowing'], explanation: 'A type guard is an expression that performs a runtime check and narrows a union type inside a conditional branch. Common patterns: `typeof x === "string"`, `x instanceof Date`, `"key" in obj`, and user-defined predicates using `value is Type` return type syntax.', docs: 'https://www.typescriptlang.org/docs/handbook/2/narrowing.html' } },

      // ── HARD (6) ────────────────────────────────────────────────────────────
      { id: '07000001-0000-4000-8001-000000000015', moduleId: '07000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 14, data: { question: 'What is the `never` type in TypeScript?', choices: ['The type of variables that have not been initialized', 'The bottom type — a type with no values, used for exhaustive checks and functions that never return', 'An alias for `void` indicating no return value', 'The type of `null` and `undefined` combined'], answer: '1', tags: ['never', 'types'], explanation: '`never` is the bottom type in TypeScript — no value can be of type `never`. A function that always throws an error or loops infinitely returns `never`. It is also used for exhaustive checks: if a union variable has type `never` in a branch, TypeScript ensures all cases were handled.', docs: 'https://www.typescriptlang.org/docs/handbook/2/functions.html#never' } },
      { id: '07000001-0000-4000-8001-000000000016', moduleId: '07000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 15, data: { question: 'What is the `unknown` type in TypeScript?', choices: ['A type alias for `any` with stricter assignment rules', 'The type-safe counterpart to `any` — you must narrow its type before performing operations on it', 'A type representing variables that have not yet been declared', 'A placeholder type used only inside generic constraints'], answer: '1', tags: ['unknown', 'types'], explanation: '`unknown` is the type-safe alternative to `any`. Any value can be assigned to `unknown`, but you cannot use it until you narrow its type (e.g., with `typeof`, `instanceof`, or a type guard). This forces explicit type checking and prevents unsafe operations.', docs: 'https://www.typescriptlang.org/docs/handbook/2/functions.html#unknown' } },
      { id: '07000001-0000-4000-8001-000000000017', moduleId: '07000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 16, data: { question: 'What is a mapped type in TypeScript?', choices: ['A type that transforms arrays using `.map()`', 'A type created by iterating over the keys of an existing type to produce a new type', 'A type that maps union members to numeric indices', 'A runtime object that stores type metadata'], answer: '1', tags: ['mapped-types', 'advanced'], explanation: 'A mapped type transforms each property of an existing type using the syntax `{ [K in keyof T]: ... }`. You can add/remove `readonly` and `?` modifiers. Built-in utility types like `Partial<T>`, `Readonly<T>`, and `Record<K, V>` are all implemented as mapped types internally.', docs: 'https://www.typescriptlang.org/docs/handbook/2/mapped-types.html' } },
      { id: '07000001-0000-4000-8001-000000000018', moduleId: '07000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 17, data: { question: 'What is a conditional type in TypeScript?', choices: ['A type that changes based on runtime values', 'A compile-time type expression that selects one of two types based on whether a type condition is satisfied', 'A special syntax for optional chaining in types', 'A type that is only evaluated inside if/else blocks'], answer: '1', tags: ['conditional-types', 'advanced'], explanation: 'Conditional types use the syntax `T extends U ? X : Y`. If T is assignable to U at compile time, the type resolves to X; otherwise Y. They power utility types like `NonNullable<T>` (`T extends null | undefined ? never : T`) and `Exclude<T, U>`.', docs: 'https://www.typescriptlang.org/docs/handbook/2/conditional-types.html' } },
      { id: '07000001-0000-4000-8001-000000000019', moduleId: '07000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 18, data: { question: 'What is `ReturnType<T>` in TypeScript?', choices: ['A decorator that infers the return value of a function at runtime', 'A utility type that extracts the return type of a function type T', 'A type that wraps a function\'s return value in a Promise', 'A runtime function that returns the type name as a string'], answer: '1', tags: ['return-type', 'utility-types', 'advanced'], explanation: '`ReturnType<T>` is a built-in utility type that extracts the type that a function returns. Example: if `T = () => string`, then `ReturnType<T>` is `string`. It is useful when you need to reference a function\'s return type without duplicating it. Internally it uses conditional types.', docs: 'https://www.typescriptlang.org/docs/handbook/utility-types.html#returntypetype' } },
      { id: '07000001-0000-4000-8001-000000000020', moduleId: '07000000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 19, data: { question: 'What is a discriminated union in TypeScript?', choices: ['A union of primitive types such as `string | number`', 'A union of object types that share a common literal property (the discriminant) used to narrow the type safely', 'A union type that automatically excludes `null` and `undefined`', 'A union created using the `Exclude` utility type'], answer: '1', tags: ['discriminated-union', 'advanced', 'narrowing'], explanation: 'A discriminated union (also called a tagged union) is a union of object types each having a common field with a unique literal value (the discriminant). TypeScript uses this field to narrow the type in switch/if statements. Example: `type Shape = { kind: "circle"; radius: number } | { kind: "square"; side: number }` — checking `shape.kind` narrows to the correct variant.', docs: 'https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions' } },
    ];

    for (const q of questions) {
      await queryRunner.query(
        `INSERT INTO "qcm_question" ("id", "moduleId", "type", "difficulty", "sortOrder", "data")
         VALUES ($1, $2, $3, $4, $5, $6)
         ON CONFLICT ("id") DO NOTHING`,
        [q.id, q.moduleId, q.type, q.difficulty, q.sortOrder, JSON.stringify(q.data)]
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const ids = Array.from({ length: 20 }, (_, i) =>
      `07000001-0000-4000-8001-${String(i + 1).padStart(12, '0')}`
    );
    await queryRunner.query(
      `DELETE FROM "qcm_question" WHERE "id" = ANY($1)`,
      [ids]
    );
  }
}
