import type { MigrationInterface, QueryRunner } from 'typeorm';

export class AddGraphQLDefinitionsQuestions1774200009000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const questions = [

      // ── EASY (10) ────────────────────────────────────────────────────────────

      { id: '08100001-0000-4000-8001-000000000001', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What is GraphQL?', choices: ['A graph database query language similar to Cypher', 'A query language for APIs and a runtime for executing those queries, allowing clients to request exactly the data they need', 'A JSON serialization format developed by Facebook', 'A REST framework with automatic graph-based endpoint generation'], answer: '1', tags: ['graphql', 'basics'], explanation: 'GraphQL is a query language for APIs (not databases) and a server-side runtime developed by Facebook (Meta). Unlike REST where endpoints dictate the response shape, GraphQL lets clients request exactly the fields they need — no over-fetching, no under-fetching. The schema acts as a contract between client and server, and a single endpoint handles all operations.', docs: 'https://graphql.org/learn/' } },

      { id: '08100001-0000-4000-8001-000000000002', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What is a GraphQL Schema?', choices: ['A JSON file describing REST API endpoints', 'A strongly-typed description of the data graph — defining all types, queries, mutations, and subscriptions available in a GraphQL API', 'A database schema generated from GraphQL queries', 'A configuration file for the Apollo Client'], answer: '1', tags: ['schema', 'basics'], explanation: 'The GraphQL schema is the contract between the client and server. Written in SDL (Schema Definition Language), it defines all available types, their fields, and the root operation types (`Query`, `Mutation`, `Subscription`). Every valid GraphQL request must conform to the schema, which is validated at parse time.', docs: 'https://graphql.org/learn/schema/' } },

      { id: '08100001-0000-4000-8001-000000000003', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What is a GraphQL Query?', choices: ['A mutation that reads and writes data simultaneously', 'A read-only operation in GraphQL that fetches data from the server, analogous to a GET request in REST', 'A string sent in the request body of a REST endpoint', 'A type definition in the GraphQL schema'], answer: '1', tags: ['query', 'basics'], explanation: 'A `query` is one of the three GraphQL operation types (alongside `mutation` and `subscription`). It is a read-only operation for fetching data. The client specifies the exact fields it needs, and the server returns only those fields. Query fields are resolved in parallel by default.', docs: 'https://graphql.org/learn/queries/' } },

      { id: '08100001-0000-4000-8001-000000000004', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What is a GraphQL Mutation?', choices: ['An operation that only reads data and mutates the local cache', 'An operation type used to write (create, update, delete) data on the server, analogous to POST/PUT/DELETE in REST', 'A subscription that updates data in real time', 'A schema directive that modifies type definitions at build time'], answer: '1', tags: ['mutation', 'basics'], explanation: 'A `mutation` is a GraphQL operation that modifies server-side data (create, update, delete). Like queries, mutations return data — you specify which fields you want back after the mutation completes. Unlike query fields (resolved in parallel), mutation fields are resolved sequentially to prevent race conditions.', docs: 'https://graphql.org/learn/queries/#mutations' } },

      { id: '08100001-0000-4000-8001-000000000005', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 4, data: { question: 'What is a GraphQL Subscription?', choices: ['An HTTP polling mechanism built into GraphQL', 'A long-lived operation that sends real-time data updates from the server to the client when specific events occur, typically over WebSockets', 'A way to subscribe to a REST API from a GraphQL client', 'A schema type that defines optional fields'], answer: '1', tags: ['subscription', 'real-time'], explanation: 'Subscriptions are the third GraphQL operation type. They maintain a persistent connection (usually WebSocket) between client and server. When a subscribed event occurs on the server (e.g., a new message is created), the server pushes an update to all subscribed clients. Used for real-time features: chat, live feeds, dashboards, notifications.', docs: 'https://graphql.org/blog/subscriptions-in-graphql-and-relay/' } },

      { id: '08100001-0000-4000-8001-000000000006', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 5, data: { question: 'What is a Resolver in GraphQL?', choices: ['A function that validates the GraphQL schema at startup', 'A function that implements how to fetch the data for a specific field or type in the schema', 'A middleware that resolves naming conflicts between schema types', 'A built-in function that automatically resolves scalar types'], answer: '1', tags: ['resolver', 'basics'], explanation: 'Resolvers are the functions that actually fetch data for each field in a GraphQL schema. Each field can have a resolver: `(parent, args, context, info) => value`. If a field has no resolver, GraphQL uses a default resolver that returns `parent[fieldName]`. Resolvers can return values, Promises, or async values. The resolver map mirrors the schema\'s type/field hierarchy.', docs: 'https://graphql.org/learn/execution/' } },

      { id: '08100001-0000-4000-8001-000000000007', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 6, data: { question: 'What are scalar types in GraphQL?', choices: ['Complex types composed of multiple fields', 'Primitive leaf types that resolve to a single value — the built-in ones are String, Int, Float, Boolean, and ID', 'Types that can only be used as input to mutations', 'Types that map to database column types'], answer: '1', tags: ['scalar', 'types'], explanation: 'GraphQL has 5 built-in scalar types: `String` (UTF-8 string), `Int` (32-bit integer), `Float` (double-precision float), `Boolean` (true/false), and `ID` (unique identifier, serialized as String). Scalars are the leaf nodes of a query — they resolve to a concrete value, not another object. You can also define custom scalars (e.g., `Date`, `JSON`, `URL`).', docs: 'https://graphql.org/learn/schema/#scalar-types' } },

      { id: '08100001-0000-4000-8001-000000000008', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 7, data: { question: 'What is an Object Type in GraphQL?', choices: ['A JavaScript class that maps to a GraphQL resolver', 'A named type in the schema with a set of fields, each with its own type — the most common building block of a GraphQL schema', 'A type that can only be used as a mutation input', 'A union of scalar types'], answer: '1', tags: ['object-type', 'schema', 'basics'], explanation: 'An Object Type is defined in SDL as: `type User { id: ID! name: String! email: String posts: [Post!] }`. Each field has a name and a type (scalar or another object type). Non-null fields use `!`. Object types form the nodes of the data graph. The root `Query`, `Mutation`, and `Subscription` types are also object types.', docs: 'https://graphql.org/learn/schema/#object-types-and-fields' } },

      { id: '08100001-0000-4000-8001-000000000009', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 8, data: { question: 'What is an Input Type in GraphQL?', choices: ['Any type used as an argument to a field', 'A special object type used exclusively as arguments to mutations and queries — defined with the `input` keyword', 'A type that maps to an HTML form input element', 'An object type that only accepts primitive field values'], answer: '1', tags: ['input-type', 'schema'], explanation: 'Input types are defined with `input` keyword instead of `type`. Example: `input CreateUserInput { name: String! email: String! }`. They are used as argument types for mutations and queries. Unlike regular Object Types, input types cannot have circular references or fields that return Object Types — they only accept scalars and other input types.', docs: 'https://graphql.org/learn/schema/#input-types' } },

      { id: '08100001-0000-4000-8001-000000000010', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 9, data: { question: 'What is a GraphQL Enum type?', choices: ['A list of numeric constants automatically assigned sequential values', 'A special scalar type restricted to a specific set of allowed string values defined in the schema', 'A type that enumerates all available queries in the schema', 'A TypeScript enum compiled into the GraphQL schema'], answer: '1', tags: ['enum', 'types'], explanation: 'Enum types define a set of allowed values for a field. Example: `enum Status { ACTIVE INACTIVE PENDING }`. The field will only accept or return one of those values. GraphQL enums are serialized as strings. They are useful for fields that have a fixed, finite set of states (order status, user role, direction).', docs: 'https://graphql.org/learn/schema/#enumeration-types' } },

      // ── MEDIUM (12) ──────────────────────────────────────────────────────────

      { id: '08100001-0000-4000-8001-000000000011', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 10, data: { question: 'What is a GraphQL Fragment?', choices: ['A code-split piece of a GraphQL schema', 'A reusable set of fields on a specific type that can be spread into multiple queries to avoid repeating field selections', 'A partial query sent as a batch with other queries', 'A directive that marks a field as optional in a query'], answer: '1', tags: ['fragment', 'queries'], explanation: 'Fragments let you define reusable field selections: `fragment UserFields on User { id name email }`. They are spread into queries with `...UserFields`. Fragments reduce duplication in complex queries and ensure consistent field selections across different operations. Inline fragments (`... on Type { }`) are used for conditional field selection on union/interface types.', docs: 'https://graphql.org/learn/queries/#fragments' } },

      { id: '08100001-0000-4000-8001-000000000012', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 11, data: { question: 'What are GraphQL Variables?', choices: ['JavaScript variables used inside resolver functions', 'Dynamic values passed to a GraphQL operation separately from the query string, enabling parameterized and reusable queries', 'Server-side environment variables exposed through the schema', 'Named fragments stored in the GraphQL cache'], answer: '1', tags: ['variables', 'queries'], explanation: 'Variables externalize dynamic values from query strings. Instead of `query { user(id: "123") { name } }`, you write `query GetUser($id: ID!) { user(id: $id) { name } }` and pass `{ "id": "123" }` as the variables JSON object. This allows the same query document to be reused with different inputs, enables query whitelisting, and prevents injection attacks.', docs: 'https://graphql.org/learn/queries/#variables' } },

      { id: '08100001-0000-4000-8001-000000000013', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 12, data: { question: 'What are GraphQL Directives?', choices: ['Compiler instructions that modify how the schema is generated at build time only', 'Special annotations (prefixed with @) that can modify execution behavior of queries or schema definitions', 'HTTP headers required for GraphQL requests', 'Decorators used in code-first schema approaches'], answer: '1', tags: ['directives', 'schema'], explanation: 'Directives customize GraphQL execution. Built-in: `@skip(if: Boolean)` omits a field if true; `@include(if: Boolean)` includes a field if true; `@deprecated(reason: String)` marks a schema field as deprecated. Custom directives extend this: `@auth`, `@cacheControl`, `@upper`. Schema directives run at build time; query directives run at execution time.', docs: 'https://graphql.org/learn/queries/#directives' } },

      { id: '08100001-0000-4000-8001-000000000014', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 13, data: { question: 'What is the N+1 problem in GraphQL?', choices: ['A schema validation error when more than N types reference each other', 'A performance problem where fetching a list of N items triggers N additional database queries (one per item) for a nested field, instead of one batched query', 'A versioning issue that arises when N clients use different schema versions', 'The problem of having more than N resolvers for a single type'], answer: '1', tags: ['n+1', 'performance', 'dataloader'], explanation: 'The N+1 problem: querying 10 posts where each post\'s author is fetched individually = 1 query for posts + 10 queries for authors = 11 total. This occurs because GraphQL resolves each field independently. The standard solution is DataLoader — it batches and deduplicates all author ID lookups within a single tick into one database query.', docs: 'https://shopify.engineering/solving-the-n-1-problem-for-graphql-through-batching' } },

      { id: '08100001-0000-4000-8001-000000000015', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 14, data: { question: 'What is DataLoader in GraphQL?', choices: ['A tool for loading GraphQL schema from a file', 'A batching and caching utility that collects all data-load calls within a single tick and fires a single batched request, solving the N+1 problem', 'A pagination helper for loading data in pages', 'An Apollo Client feature that preloads data before rendering'], answer: '1', tags: ['dataloader', 'performance', 'n+1'], explanation: 'DataLoader (by Meta) collects individual `load(id)` calls made within the same event loop tick and batches them into a single `batchLoadFn([id1, id2, ...])` call. It also caches results within a request (per-request DataLoader instances are the standard). Result: 10 individual author loads → 1 `SELECT * FROM users WHERE id IN (...)` query.', docs: 'https://github.com/graphql/dataloader' } },

      { id: '08100001-0000-4000-8001-000000000016', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 15, data: { question: 'What is the difference between code-first and schema-first GraphQL approaches?', choices: ['Code-first generates REST endpoints first; schema-first generates GraphQL first', 'Schema-first: SDL is written first and resolvers implement it; Code-first: TypeScript classes/decorators generate the schema automatically', 'Code-first uses JavaScript; schema-first uses TypeScript', 'They produce different output — code-first generates a faster schema'], answer: '1', tags: ['code-first', 'schema-first', 'patterns'], explanation: '**Schema-first**: write SDL (`type Query { user(id: ID!): User }`) first, then implement resolver functions. The SDL is the single source of truth. **Code-first**: use decorators on TypeScript classes (`@ObjectType()`, `@Resolver()`, `@Query()`) and a library (NestJS/type-graphql) auto-generates the SDL. Code-first has better TypeScript integration and avoids SDL/resolver drift; schema-first is more explicit and portable.', docs: 'https://docs.nestjs.com/graphql/quick-start' } },

      { id: '08100001-0000-4000-8001-000000000017', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 16, data: { question: 'What is a GraphQL Interface type?', choices: ['A TypeScript interface compiled into the GraphQL schema', 'An abstract type that defines a set of fields that multiple object types must implement, enabling polymorphic queries', 'A type used to describe the shape of resolver arguments', 'An object type that acts as the base class for all other types'], answer: '1', tags: ['interface', 'schema', 'types'], explanation: 'An interface type defines fields that implementing types must include. Example: `interface Node { id: ID! }`. Both `User` and `Post` can `implements Node`. This enables queries like `{ node(id: "1") { id ... on User { name } ... on Post { title } } }`. Resolvers must implement `__resolveType` to tell GraphQL which concrete type a value represents.', docs: 'https://graphql.org/learn/schema/#interfaces' } },

      { id: '08100001-0000-4000-8001-000000000018', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 17, data: { question: 'What is a GraphQL Union type?', choices: ['A type that combines two scalars into one field', 'A type that represents a value that can be one of several object types, without requiring shared fields between them', 'A type created by merging two schemas with the same type names', 'A field modifier indicating the field can be null or a specific type'], answer: '1', tags: ['union', 'types', 'schema'], explanation: 'Union types allow a field to return one of multiple object types that share no required fields. Example: `union SearchResult = User | Post | Comment`. When querying a union, you use inline fragments to select fields per type: `... on User { name }`. Like interfaces, unions require `__resolveType` to identify the concrete type at runtime.', docs: 'https://graphql.org/learn/schema/#union-types' } },

      { id: '08100001-0000-4000-8001-000000000019', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 18, data: { question: 'What is the context object in a GraphQL resolver?', choices: ['The parent object passed down from the root resolver', 'A shared object passed to every resolver in an operation, used to store per-request data like the authenticated user, database connection, and DataLoader instances', 'A built-in GraphQL object for managing schema context', 'The fourth argument `info` of a resolver function'], answer: '1', tags: ['context', 'resolver', 'patterns'], explanation: 'The `context` object is the third argument of every resolver: `(parent, args, context, info)`. It is created once per request and shared across all resolvers in that operation. Standard contents: `context.user` (from auth middleware), `context.db` (database client/connection pool), and `context.loaders` (DataLoader instances). Injecting DataLoaders here ensures they are scoped per-request for proper batching.', docs: 'https://www.apollographql.com/docs/apollo-server/data/context' } },

      { id: '08100001-0000-4000-8001-000000000020', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 19, data: { question: 'What is GraphQL Introspection?', choices: ['The ability of a GraphQL client to inspect the server\'s network traffic', 'A built-in GraphQL capability where clients can query the schema itself to discover available types, fields, queries, and mutations', 'A debugging mode that logs all resolver calls', 'A security feature that audits all incoming queries for potential risks'], answer: '1', tags: ['introspection', 'schema'], explanation: 'Introspection allows querying the schema using special `__` fields: `__schema { types { name } }`, `__type(name: "User") { fields { name type { name } } }`. It powers GraphiQL, Apollo Sandbox, and code generation tools. In production, introspection is often disabled to prevent schema leakage — instead, use persisted queries or schema registries for clients.', docs: 'https://graphql.org/learn/introspection/' } },

      { id: '08100001-0000-4000-8001-000000000021', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 20, data: { question: 'What is Apollo Server?', choices: ['A client library for sending GraphQL queries from React applications', 'An open-source, spec-compliant GraphQL server that works with any Node.js framework, providing schema building, resolver execution, and plugin ecosystem', 'A GraphQL IDE for testing queries in the browser', 'A query planning service for distributed GraphQL schemas'], answer: '1', tags: ['apollo-server', 'server'], explanation: 'Apollo Server is the most widely used GraphQL server for Node.js. It accepts a schema (typeDefs + resolvers), handles parsing, validation, execution, and error formatting of GraphQL requests. It supports REST data sources, caching (RESTDataSource), persisted queries, plugins (tracing, reporting), and integrates with Express, Fastify, Lambda, and NestJS.', docs: 'https://www.apollographql.com/docs/apollo-server' } },

      { id: '08100001-0000-4000-8001-000000000022', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 21, data: { question: 'What is Apollo Client?', choices: ['A GraphQL server built on top of Express', 'A state management and data-fetching library for JavaScript applications that manages sending GraphQL queries and caching their results', 'A CLI tool for generating GraphQL client code', 'A browser extension for testing GraphQL APIs'], answer: '1', tags: ['apollo-client', 'client'], explanation: 'Apollo Client is a comprehensive state management library for JavaScript. It: sends GraphQL queries/mutations to the server, normalizes and caches the response in a local InMemoryCache (by `id` + `__typename`), provides React hooks (`useQuery`, `useMutation`, `useSubscription`), and enables optimistic UI updates. The normalized cache means fetching the same object in two queries shares the same cache entry.', docs: 'https://www.apollographql.com/docs/react' } },

      // ── HARD (10) ────────────────────────────────────────────────────────────

      { id: '08100001-0000-4000-8001-000000000023', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 22, data: { question: 'What is cursor-based pagination in GraphQL?', choices: ['Pagination using LIMIT/OFFSET SQL clauses surfaced in GraphQL', 'A pagination pattern using an opaque cursor (position marker) to fetch the next/previous page, providing stable pagination even when items are added or removed', 'A pattern that loads all data and paginates client-side', 'A server-sent events mechanism for streaming paginated results'], answer: '1', tags: ['pagination', 'cursor', 'patterns'], explanation: 'Cursor-based (keyset) pagination uses a cursor — an encoded reference to the last seen item — instead of a page number. The Relay Connections spec standardizes this: `{ edges { node { id title } cursor } pageInfo { hasNextPage endCursor } }`. Pass `after: cursor` for the next page. It is stable under insertions/deletions (unlike offset-based which can skip or repeat items).', docs: 'https://relay.dev/graphql/connections.htm' } },

      { id: '08100001-0000-4000-8001-000000000024', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 23, data: { question: 'What is GraphQL Federation?', choices: ['A way to federate authentication across multiple GraphQL clients', 'An architecture for splitting a single GraphQL schema across multiple independently deployable subgraph services, composed into a unified supergraph by a gateway', 'A method of federating GraphQL subscriptions across data centers', 'A plugin for Apollo Server that enables schema stitching'], answer: '1', tags: ['federation', 'architecture', 'advanced'], explanation: 'Apollo Federation (v2) lets teams own separate GraphQL subgraphs (e.g., Users service, Products service). A Router/Gateway composes them into a single unified supergraph. Subgraphs extend each other\'s types using `@key` (entity references), `@external`, and `@shareable` directives. Clients query the gateway as if it were a single schema. Enables micro-frontend-style architecture for APIs.', docs: 'https://www.apollographql.com/docs/federation' } },

      { id: '08100001-0000-4000-8001-000000000025', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 24, data: { question: 'What is schema stitching in GraphQL?', choices: ['The process of merging SDL files at build time', 'A technique for combining and delegating between multiple separate GraphQL schemas into one merged schema at the gateway level', 'A code-first pattern for building schemas programmatically', 'A way to stitch REST API responses into a GraphQL response'], answer: '1', tags: ['schema-stitching', 'advanced', 'architecture'], explanation: 'Schema stitching (via `@graphql-tools/stitch`) merges multiple GraphQL schemas into one, with remote schema delegation. Unlike Federation, it does not require a specific spec — schemas can be any GraphQL API. The gateway wraps remote schemas and can add transforms. Federation has largely replaced stitching for new projects, but stitching is still used for legacy or non-Federation-compliant services.', docs: 'https://the-guild.dev/graphql/stitching/docs' } },

      { id: '08100001-0000-4000-8001-000000000026', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 25, data: { question: 'What are Persisted Queries in GraphQL?', choices: ['Queries stored in the database for audit logging', 'A technique where a client sends only a hash of a pre-registered query instead of the full query string, reducing payload size and preventing arbitrary query execution', 'Queries cached indefinitely in the Apollo Client cache', 'A server-side query cache that persists across deployments'], answer: '1', tags: ['persisted-queries', 'performance', 'security'], explanation: 'With Automatic Persisted Queries (APQ): the client first sends a SHA-256 hash of the query. If the server recognizes it, it executes it. If not, the client resends with the full query, and the server saves the hash. Benefits: (1) smaller HTTP payloads (hashes are short), (2) enables GET requests (cacheable by CDN), (3) security — production servers can reject queries not in the persisted registry.', docs: 'https://www.apollographql.com/docs/apollo-server/performance/apq' } },

      { id: '08100001-0000-4000-8001-000000000027', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 26, data: { question: 'How is authentication typically implemented in a GraphQL API?', choices: ['By adding @auth directive to every field in the schema', 'By verifying tokens in HTTP middleware before the request reaches GraphQL, attaching the user to context, then checking context.user inside resolvers or using a @auth directive', 'By using the built-in GraphQL @authenticated directive', 'By wrapping every resolver in a try/catch that validates the JWT'], answer: '1', tags: ['authentication', 'security', 'patterns'], explanation: 'The standard pattern: (1) HTTP middleware (e.g., Express) reads the `Authorization` header, verifies the JWT, and sets `req.user`; (2) Apollo Server\'s `context` function attaches `{ user: req.user }` to context; (3) resolvers or a custom `@auth` schema directive check `context.user` and throw `AuthenticationError` / `ForbiddenError` if unauthorized. This keeps auth logic out of individual resolvers.', docs: 'https://www.apollographql.com/docs/apollo-server/security/authentication' } },

      { id: '08100001-0000-4000-8001-000000000028', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 27, data: { question: 'What is the Apollo Client InMemoryCache normalization strategy?', choices: ['Apollo Client stores all responses as raw JSON keyed by the full query string', 'Apollo Client normalizes each object by __typename + id, storing each entity once in a flat table so that updates from any query automatically update all components referencing the same entity', 'Apollo Client uses a LRU cache keyed by resolver name', 'Apollo Client stores only the most recent response for each query operation'], answer: '1', tags: ['apollo-client', 'cache', 'advanced'], explanation: 'InMemoryCache normalizes responses into a flat, entity-based store. Each object is stored at key `TypeName:id`. When any query updates a `User:123`, all components that have that user in their query result re-render automatically — without a manual cache update. `cache.modify()`, `cache.writeQuery()`, and `update` in mutations let you imperatively update the cache after mutations.', docs: 'https://www.apollographql.com/docs/react/caching/cache-configuration' } },

      { id: '08100001-0000-4000-8001-000000000029', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 28, data: { question: 'What is a custom scalar type in GraphQL?', choices: ['A scalar that is defined by extending the built-in String scalar', 'A user-defined scalar type that specifies how a custom value (e.g., Date, JSON, URL) is serialized, parsed, and validated', 'A scalar that is resolved by a custom resolver function', 'A scalar provided by third-party GraphQL libraries'], answer: '1', tags: ['custom-scalar', 'types', 'advanced'], explanation: 'Custom scalars (e.g., `scalar Date`) require implementing three methods: `serialize(value)` — output (resolver → response), `parseValue(value)` — input from variable, `parseLiteral(ast)` — input from inline query literal. Libraries like `graphql-scalars` provide production-ready implementations of `Date`, `DateTime`, `JSON`, `UUID`, `URL`, `PositiveInt`, etc.', docs: 'https://www.apollographql.com/docs/apollo-server/schema/custom-scalars' } },

      { id: '08100001-0000-4000-8001-000000000030', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 29, data: { question: 'What is the `info` argument in a GraphQL resolver?', choices: ['A metadata object providing information about the current request\'s HTTP headers', 'The fourth resolver argument containing information about the execution state: field name, return type, parent type, schema, and the parsed query AST', 'A logging object automatically injected by Apollo Server', 'An object containing the variables passed to the current operation'], answer: '1', tags: ['resolver', 'info', 'advanced'], explanation: '`info` is the fourth resolver argument: `(parent, args, context, info)`. It contains: `info.fieldName` (current field), `info.parentType` (parent type), `info.returnType` (field\'s return type), `info.schema` (the full schema), and `info.fieldNodes` (AST nodes for the field selection). Advanced use cases: look-ahead (reading child field selections from the AST to optimize the database query and avoid fetching unused columns).', docs: 'https://graphql.org/graphql-js/type/#graphqlobjecttype' } },

      { id: '08100001-0000-4000-8001-000000000031', moduleId: '08100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 30, data: { question: 'What is query complexity / depth limiting in GraphQL and why is it important?', choices: ['A technique for measuring resolver performance and flagging slow queries', 'A security mechanism that assigns cost scores to fields or limits query depth to prevent abusively expensive nested queries from exhausting server resources', 'A caching strategy that limits the number of cached queries', 'A schema directive that prevents clients from querying deprecated fields'], answer: '1', tags: ['security', 'performance', 'advanced'], explanation: 'GraphQL\'s flexibility means a single maliciously crafted deeply-nested query can cause exponential database load (query depth attacks). Solutions: (1) **Depth limiting** — reject queries deeper than N levels (e.g., `graphql-depth-limit`); (2) **Query complexity** — assign cost scores to fields and reject queries above a threshold (e.g., `graphql-query-complexity`). Both are critical for public-facing APIs.', docs: 'https://www.apollographql.com/docs/apollo-server/security/dos-dos-prevention' } },
    ];

    for (const q of questions) {
      await queryRunner.query(
        `INSERT INTO "qcm_question" ("id", "moduleId", "type", "difficulty", "sortOrder", "data")
         VALUES ($1, $2, $3, $4, $5, $6)
         ON CONFLICT ("id") DO NOTHING`,
        [q.id, q.moduleId, q.type, q.difficulty, q.sortOrder, JSON.stringify(q.data)]
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const ids = Array.from({ length: 31 }, (_, i) =>
      `08100001-0000-4000-8001-${String(i + 1).padStart(12, '0')}`
    );
    await queryRunner.query(
      `DELETE FROM "qcm_question" WHERE "id" = ANY($1)`,
      [ids]
    );
  }
}
