import type { MigrationInterface, QueryRunner } from 'typeorm';

export class AddReactDefinitionsQuestions1774200003000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const questions = [

      // ── EASY (12) ────────────────────────────────────────────────────────────

      { id: 'c3100001-0000-4000-8001-000000000001', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 0, data: { question: 'What is React?', choices: ['A relational database library for JavaScript', 'A declarative, component-based JavaScript library for building user interfaces', 'A JavaScript runtime built on Node.js', 'A CSS-in-JS framework developed by Facebook'], answer: '1', tags: ['react', 'basics'], explanation: 'React is an open-source JavaScript library developed by Meta (Facebook) for building user interfaces. It is declarative (you describe what the UI should look like, not how to update it), component-based (UIs are built from isolated, reusable pieces), and uses a virtual DOM to efficiently update the real DOM.', docs: 'https://react.dev/learn' } },

      { id: 'c3100001-0000-4000-8001-000000000002', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 1, data: { question: 'What is JSX?', choices: ['A new JavaScript engine', 'A syntax extension for JavaScript that looks like HTML and is transformed into React.createElement() calls', 'A CSS preprocessor bundled with React', 'A JSON schema format used by React'], answer: '1', tags: ['jsx', 'basics'], explanation: 'JSX (JavaScript XML) is a syntax extension that lets you write HTML-like markup inside JavaScript. It is not valid JS on its own — tools like Babel transform it into `React.createElement()` calls. JSX makes component templates more readable while remaining fully powered by JavaScript.', docs: 'https://react.dev/learn/writing-markup-with-jsx' } },

      { id: 'c3100001-0000-4000-8001-000000000003', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 2, data: { question: 'What is a React component?', choices: ['A standalone HTML file with JavaScript inside', 'A reusable, self-contained piece of UI that can accept inputs and returns JSX describing what should appear on screen', 'A class that extends HTMLElement', 'A Redux action creator'], answer: '1', tags: ['component', 'basics'], explanation: 'A React component is a JavaScript function (or class) that accepts props as input and returns JSX. Components can be composed together to build complex UIs. They encapsulate their own markup, logic, and style, making them reusable and independently testable.', docs: 'https://react.dev/learn/your-first-component' } },

      { id: 'c3100001-0000-4000-8001-000000000004', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 3, data: { question: 'What are props in React?', choices: ['Internal mutable state of a component', 'Read-only data passed from a parent component to a child component', 'CSS properties applied to a component', 'A browser API for handling events'], answer: '1', tags: ['props', 'basics'], explanation: 'Props (short for properties) are the mechanism for passing data from parent to child components. Props are read-only — a child must never modify its props. This makes data flow predictable and one-directional (top-down). A child communicates back to its parent by calling callback functions passed as props.', docs: 'https://react.dev/learn/passing-props-to-a-component' } },

      { id: 'c3100001-0000-4000-8001-000000000005', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 4, data: { question: 'What is state in React?', choices: ['Data that is shared between all components globally', 'A component\'s private, mutable data that, when changed, causes the component to re-render', 'The browser URL stored in the component', 'Static data passed via props that cannot change'], answer: '1', tags: ['state', 'basics'], explanation: 'State is data that is local and private to a component. Unlike props, state is managed within the component and can change over time. When state changes, React schedules a re-render of that component and its children so the UI stays in sync with the data.', docs: 'https://react.dev/learn/state-a-components-memory' } },

      { id: 'c3100001-0000-4000-8001-000000000006', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 5, data: { question: 'What is `useState`?', choices: ['A lifecycle method for class components', 'A React hook that lets you add a state variable to a functional component and returns the current value and a setter function', 'A global state manager similar to Redux', 'A hook that subscribes a component to context changes'], answer: '1', tags: ['useState', 'hooks'], explanation: '`useState(initialValue)` is a React hook that adds state to a functional component. It returns a tuple `[value, setValue]` where `value` is the current state and `setValue` is a function to update it. Calling `setValue` triggers a re-render with the new value.', docs: 'https://react.dev/reference/react/useState' } },

      { id: 'c3100001-0000-4000-8001-000000000007', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 6, data: { question: 'What is `useEffect`?', choices: ['A hook that memoizes expensive computations', 'A hook that lets you synchronize a component with an external system by running side effects after rendering', 'A hook that manages form submissions', 'A lifecycle method that runs before the component mounts'], answer: '1', tags: ['useEffect', 'hooks'], explanation: '`useEffect(setup, deps?)` runs a side effect (data fetching, subscriptions, DOM manipulation) after the component renders. The optional dependency array controls when it re-runs: empty array = once on mount; omitted = every render; with deps = when deps change. The returned cleanup function runs before the next effect or on unmount.', docs: 'https://react.dev/reference/react/useEffect' } },

      { id: 'c3100001-0000-4000-8001-000000000008', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 7, data: { question: 'What is the virtual DOM in React?', choices: ['A browser API that lets JavaScript manipulate the DOM faster', 'A lightweight in-memory representation of the real DOM that React uses to compute minimal updates', 'A separate DOM tree used for server-side rendering', 'The shadow DOM used by Web Components'], answer: '1', tags: ['virtual-dom', 'internals'], explanation: 'The virtual DOM (VDOM) is a plain JavaScript object tree that mirrors the real DOM. When state or props change, React creates a new VDOM tree and diffs it against the previous one (reconciliation) to identify the minimal set of real DOM operations needed. This batching of updates is more efficient than direct DOM manipulation.', docs: 'https://react.dev/learn/preserving-and-resetting-state' } },

      { id: 'c3100001-0000-4000-8001-000000000009', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 8, data: { question: 'What is a functional component in React?', choices: ['A component that can only render static HTML with no logic', 'A plain JavaScript function that accepts props and returns JSX, and can use hooks for state and lifecycle', 'A component that extends React.PureComponent', 'A component that renders only when a condition is true'], answer: '1', tags: ['functional-component', 'basics'], explanation: 'A functional component is a JavaScript function (regular or arrow function) whose name starts with a capital letter, accepts a props object, and returns JSX. Since the introduction of hooks in React 16.8, functional components can manage state, side effects, and context — making class components largely obsolete.', docs: 'https://react.dev/learn/your-first-component' } },

      { id: 'c3100001-0000-4000-8001-000000000010', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 9, data: { question: 'What is a React Fragment?', choices: ['A component that lazily loads its children', 'A wrapper that lets you group multiple JSX elements without adding an extra DOM node', 'A special comment syntax in JSX', 'A placeholder rendered while a component is suspended'], answer: '1', tags: ['fragment', 'jsx'], explanation: 'A Fragment (`<React.Fragment>` or the shorthand `<>...</>`) lets you group multiple elements into a single JSX expression without introducing an extra DOM element. This is important when a parent requires a single child element (e.g., `<td>` inside `<tr>`) but you need to return several elements.', docs: 'https://react.dev/reference/react/Fragment' } },

      { id: 'c3100001-0000-4000-8001-000000000011', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 10, data: { question: 'What is the `key` prop in React?', choices: ['A prop that encrypts component data for security', 'A special string attribute that helps React identify which items in a list have changed, been added, or removed', 'A prop used to forward a ref to a child element', 'An index-based identifier automatically added to every element'], answer: '1', tags: ['key', 'lists', 'reconciliation'], explanation: 'The `key` prop is a special attribute React uses during reconciliation to track list items across re-renders. Keys must be stable and unique among siblings. Using an item\'s unique ID (not its array index) prevents bugs when items are reordered or removed, and ensures React reuses the right DOM nodes.', docs: 'https://react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key' } },

      { id: 'c3100001-0000-4000-8001-000000000012', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'easy', sortOrder: 11, data: { question: 'What is the children prop in React?', choices: ['An array of all sibling components', 'A special prop that contains the JSX elements placed between a component\'s opening and closing tags', 'A prop that holds a component\'s internal state', 'A list of lifecycle method callbacks'], answer: '1', tags: ['children', 'composition'], explanation: '`props.children` contains whatever JSX is placed between a component\'s opening and closing tags when it is used. It enables composition patterns: wrapper or layout components can render their children without knowing what those children are. The `children` prop can be a string, a single element, an array, or `undefined`.', docs: 'https://react.dev/learn/passing-props-to-a-component#passing-jsx-as-children' } },

      // ── MEDIUM (14) ──────────────────────────────────────────────────────────

      { id: 'c3100001-0000-4000-8001-000000000013', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 12, data: { question: 'What is `useContext`?', choices: ['A hook that creates a new context', 'A hook that reads and subscribes a component to a React context, avoiding prop drilling', 'A hook that memoizes a context value', 'A hook that provides context to child components'], answer: '1', tags: ['useContext', 'hooks', 'context'], explanation: '`useContext(MyContext)` reads the current value of a context provided by the nearest `<MyContext.Provider>` above in the tree. The component re-renders automatically when the context value changes. It replaces the older `<Context.Consumer>` render-prop pattern and eliminates prop drilling for global data like theme or auth.', docs: 'https://react.dev/reference/react/useContext' } },

      { id: 'c3100001-0000-4000-8001-000000000014', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 13, data: { question: 'What is `useRef`?', choices: ['A hook that creates a reactive state variable', 'A hook that returns a mutable ref object whose `.current` property persists across renders without causing re-renders', 'A hook that subscribes to browser resize events', 'A hook that forwards a ref to a parent component'], answer: '1', tags: ['useRef', 'hooks'], explanation: '`useRef(initialValue)` returns `{ current: initialValue }`. Unlike state, mutating `.current` does NOT trigger a re-render. It has two main uses: (1) accessing DOM nodes directly via `ref={myRef}` on an element, and (2) storing mutable values that need to persist across renders (e.g., interval IDs, previous values).', docs: 'https://react.dev/reference/react/useRef' } },

      { id: 'c3100001-0000-4000-8001-000000000015', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 14, data: { question: 'What is `useMemo`?', choices: ['A hook that memoizes a callback function between renders', 'A hook that caches the result of an expensive calculation, recomputing it only when its dependencies change', 'A hook that prevents a component from re-rendering', 'A hook that batches multiple state updates together'], answer: '1', tags: ['useMemo', 'hooks', 'performance'], explanation: '`useMemo(() => expensiveCalc(), deps)` caches (memoizes) the return value of a function. The cached value is reused on re-renders unless a dependency changes. It is used to avoid expensive recalculations on every render. Do not use it for everything — the overhead is only worth it for genuinely expensive computations.', docs: 'https://react.dev/reference/react/useMemo' } },

      { id: 'c3100001-0000-4000-8001-000000000016', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 15, data: { question: 'What is `useCallback`?', choices: ['A hook that calls a function immediately on mount', 'A hook that caches a function reference between renders so that it does not change unless its dependencies change', 'A hook that debounces event handler calls', 'A hook that memoizes the return value of a function'], answer: '1', tags: ['useCallback', 'hooks', 'performance'], explanation: '`useCallback(fn, deps)` returns a memoized version of a function that only changes when deps change. Without it, a new function reference is created on every render. This is important when passing callbacks to memoized children (`React.memo`) to prevent unnecessary re-renders. It is essentially `useMemo(() => fn, deps)`.', docs: 'https://react.dev/reference/react/useCallback' } },

      { id: 'c3100001-0000-4000-8001-000000000017', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 16, data: { question: 'What is `useReducer`?', choices: ['A hook that connects a component to a Redux store', 'A hook that manages complex state transitions via a reducer function, returning the current state and a dispatch function', 'A hook that reduces an array of children to a single value', 'A hook that replaces useEffect for data fetching'], answer: '1', tags: ['useReducer', 'hooks', 'state'], explanation: '`useReducer(reducer, initialState)` is an alternative to `useState` for complex state logic. It accepts a `reducer(state, action) => newState` function and an initial state, returning `[state, dispatch]`. Dispatching actions makes state transitions explicit and testable. It mirrors the Redux pattern at the component level.', docs: 'https://react.dev/reference/react/useReducer' } },

      { id: 'c3100001-0000-4000-8001-000000000018', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 17, data: { question: 'What is the Context API in React?', choices: ['An API for making HTTP requests without prop drilling', 'A built-in mechanism for sharing data across the component tree without passing props at every level', 'A global store similar to Redux but built into React', 'An API for persisting component state to localStorage'], answer: '1', tags: ['context', 'context-api'], explanation: 'The Context API (`React.createContext`, `Provider`, `useContext`) lets you share values (theme, user, locale) across the component tree without manually threading props through every intermediate component. A `Provider` wraps a subtree and supplies a value; any descendant using `useContext` receives that value.', docs: 'https://react.dev/learn/passing-data-deeply-with-context' } },

      { id: 'c3100001-0000-4000-8001-000000000019', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 18, data: { question: 'What is `React.memo`?', choices: ['A hook that memoizes a computed value inside a component', 'A higher-order component that prevents a functional component from re-rendering when its props have not changed', 'A React 19 replacement for useMemo', 'A way to cache the result of an API call'], answer: '1', tags: ['memo', 'performance', 'hoc'], explanation: '`React.memo(Component)` wraps a functional component and performs a shallow comparison of props. If the props are the same as the previous render, React skips re-rendering and reuses the last result. This is a performance optimisation — use it for components that render the same output for the same props and re-render frequently.', docs: 'https://react.dev/reference/react/memo' } },

      { id: 'c3100001-0000-4000-8001-000000000020', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 19, data: { question: 'What is a controlled component in React?', choices: ['A component managed by a parent through refs', 'A form element whose value is driven by React state and updated only via a state setter', 'A component that cannot be unmounted', 'A component wrapped with React.memo'], answer: '1', tags: ['controlled-component', 'forms'], explanation: 'A controlled component is a form element (input, textarea, select) whose displayed value is always in sync with React state. The state is the single source of truth. Every keystroke calls `setState`, and the element\'s `value` prop reflects the current state. This makes reading, validating, and transforming user input straightforward.', docs: 'https://react.dev/reference/react-dom/components/input#controlling-an-input-with-a-state-variable' } },

      { id: 'c3100001-0000-4000-8001-000000000021', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 20, data: { question: 'What is an uncontrolled component in React?', choices: ['A component whose state is not accessible by its parent', 'A form element that manages its own value internally via the DOM, accessed through a ref', 'A component with no props or state', 'A component rendered outside the React tree'], answer: '1', tags: ['uncontrolled-component', 'forms'], explanation: 'An uncontrolled component stores its form value internally in the DOM rather than in React state. You access the value via `useRef` and the `.current.value` property, typically on submit. Uncontrolled components are simpler for basic forms and useful when integrating with non-React code, but are harder to validate or transform on the fly.', docs: 'https://react.dev/learn/sharing-state-between-components#controlled-and-uncontrolled-components' } },

      { id: 'c3100001-0000-4000-8001-000000000022', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 21, data: { question: 'What is a Higher-Order Component (HOC) in React?', choices: ['A component that appears at the top of the page layout', 'A function that takes a component and returns a new component with added behavior', 'A class component that extends React.PureComponent', 'A component that renders multiple children at once'], answer: '1', tags: ['hoc', 'patterns'], explanation: 'A Higher-Order Component is a pattern where a function accepts a component and returns a new, enhanced component. HOCs add reusable logic (auth checks, logging, theming) without modifying the original component. Examples: `withRouter`, `connect`. They have largely been replaced by hooks, which are simpler and avoid wrapper hell.', docs: 'https://react.dev/reference/react/Component#usage' } },

      { id: 'c3100001-0000-4000-8001-000000000023', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 22, data: { question: 'What is a React Portal?', choices: ['A routing component that teleports the user to a different page', 'A way to render a child component into a different DOM node outside its parent\'s DOM hierarchy', 'A special context that passes data across browser tabs', 'A React API for streaming components from the server'], answer: '1', tags: ['portal', 'dom'], explanation: '`ReactDOM.createPortal(children, domNode)` renders children into a different part of the DOM (e.g., `document.body`) while keeping them logically inside the React tree for event bubbling and context. Portals are essential for modals, tooltips, and dropdowns that must visually escape an `overflow: hidden` or `z-index` stacking context.', docs: 'https://react.dev/reference/react-dom/createPortal' } },

      { id: 'c3100001-0000-4000-8001-000000000024', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 23, data: { question: 'What is `React.Suspense`?', choices: ['A component that delays all renders until all data is fetched globally', 'A component that lets you display a fallback UI while its children are loading (code-splitting or async data)', 'A hook that pauses execution of useEffect until a condition is met', 'A component that catches rendering errors in its subtree'], answer: '1', tags: ['suspense', 'async', 'lazy'], explanation: '`<Suspense fallback={<Spinner />}>` wraps components that are not yet ready to render. It shows the `fallback` UI until all suspended children are ready. It works with `React.lazy` for code splitting and with data fetching libraries that use the Suspense protocol (like Relay or React 19\'s `use()` hook).', docs: 'https://react.dev/reference/react/Suspense' } },

      { id: 'c3100001-0000-4000-8001-000000000025', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 24, data: { question: 'What is `React.lazy`?', choices: ['A hook that defers rendering a component until it is visible in the viewport', 'A function that lets you dynamically import a component so it is only loaded when first rendered (code splitting)', 'A utility that batches lazy state updates', 'A React compiler optimization flag'], answer: '1', tags: ['lazy', 'code-splitting'], explanation: '`React.lazy(() => import("./MyComponent"))` creates a component that is loaded dynamically on first render. The module containing the component is split into a separate bundle downloaded only when needed. `React.lazy` must be used inside a `<Suspense>` boundary that provides the loading fallback.', docs: 'https://react.dev/reference/react/lazy' } },

      { id: 'c3100001-0000-4000-8001-000000000026', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'medium', sortOrder: 25, data: { question: 'What is reconciliation in React?', choices: ['The process of merging two Redux stores', 'The algorithm React uses to diff the previous and new virtual DOM trees to determine the minimum set of real DOM changes needed', 'A hook that reconciles conflicting state updates', 'The process of hydrating a server-rendered page'], answer: '1', tags: ['reconciliation', 'virtual-dom', 'internals'], explanation: 'Reconciliation is React\'s diffing algorithm. When state or props change, React renders a new virtual DOM tree and compares it to the previous one. React assumes components of different types produce different trees (replacing them entirely) and uses the `key` prop to match list items across renders. Only the computed differences are applied to the real DOM.', docs: 'https://react.dev/learn/preserving-and-resetting-state' } },

      // ── HARD (12) ────────────────────────────────────────────────────────────

      { id: 'c3100001-0000-4000-8001-000000000027', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 26, data: { question: 'What is the React Fiber architecture?', choices: ['A network layer for server components', 'A complete rewrite of React\'s reconciliation engine that enables incremental rendering, prioritization, and pausing/resuming work', 'A CSS-in-JS engine used by React Native', 'A data-fetching layer introduced in React 19'], answer: '1', tags: ['fiber', 'internals', 'concurrency'], explanation: 'React Fiber (introduced in React 16) is a reimplementation of the reconciler as a linked-list of work units called "fibers". Unlike the old synchronous stack reconciler, Fiber can pause, prioritize, reuse, and abort rendering work. This enables Concurrent React features: time slicing, Suspense, transitions, and deferred updates.', docs: 'https://react.dev/blog/2022/03/29/react-v18#what-is-concurrent-react' } },

      { id: 'c3100001-0000-4000-8001-000000000028', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 27, data: { question: 'What is an Error Boundary in React?', choices: ['A try/catch block inside useEffect', 'A class component that catches JavaScript errors in its child component tree, logs them, and displays a fallback UI instead of crashing', 'A higher-order component that validates prop types at runtime', 'A TypeScript utility type for narrowing error values'], answer: '1', tags: ['error-boundary', 'error-handling'], explanation: 'An Error Boundary is a class component that implements `static getDerivedStateFromError()` and/or `componentDidCatch()`. It catches rendering errors in its subtree during render, in lifecycle methods, and in constructors. Functional components cannot be error boundaries. Libraries like `react-error-boundary` provide a hook-friendly API on top.', docs: 'https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary' } },

      { id: 'c3100001-0000-4000-8001-000000000029', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 28, data: { question: 'What is `useLayoutEffect` and how does it differ from `useEffect`?', choices: ['useLayoutEffect runs asynchronously after paint; useEffect runs synchronously before paint', 'useLayoutEffect runs synchronously after DOM mutations but before the browser paints; useEffect runs asynchronously after paint', 'They are identical — useLayoutEffect is just an alias for useEffect', 'useLayoutEffect only runs on mount; useEffect runs on every render'], answer: '1', tags: ['useLayoutEffect', 'hooks', 'performance'], explanation: '`useLayoutEffect` fires synchronously after React has applied DOM mutations but before the browser paints. This makes it suitable for reading layout (e.g., element dimensions) and making DOM changes that must be visible before the first paint to avoid flicker. For most side effects (data fetching, logging), prefer `useEffect` which is asynchronous and does not block the browser.', docs: 'https://react.dev/reference/react/useLayoutEffect' } },

      { id: 'c3100001-0000-4000-8001-000000000030', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 29, data: { question: 'What is a custom hook in React?', choices: ['A component that exposes a public API via the DOM', 'A JavaScript function whose name starts with "use" that calls other hooks to encapsulate and share stateful logic between components', 'A class method that overrides a React lifecycle', 'A hook provided by third-party libraries only'], answer: '1', tags: ['custom-hook', 'hooks', 'patterns'], explanation: 'A custom hook is a function named with `use` prefix that internally calls React hooks (`useState`, `useEffect`, etc.) to encapsulate reusable stateful logic. Unlike HOCs or render props, custom hooks share logic without affecting the component tree. Examples: `useFetch`, `useDebounce`, `useLocalStorage`. Each component using the hook gets its own independent state.', docs: 'https://react.dev/learn/reusing-logic-with-custom-hooks' } },

      { id: 'c3100001-0000-4000-8001-000000000031', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 30, data: { question: 'What is "lifting state up" in React?', choices: ['Moving local state into a Redux store', 'Moving state to the closest common ancestor of components that need to share it, so they can receive it via props', 'Using React.memo to prevent state from propagating downward', 'Persisting component state to sessionStorage on unmount'], answer: '1', tags: ['lifting-state', 'patterns', 'state'], explanation: '"Lifting state up" means moving shared state to the lowest common ancestor component. When two sibling components need to share or synchronize state, the state is moved to their parent, which passes it down as props and provides setter callbacks. This preserves single-source-of-truth and avoids state sync bugs.', docs: 'https://react.dev/learn/sharing-state-between-components' } },

      { id: 'c3100001-0000-4000-8001-000000000032', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 31, data: { question: 'What is `forwardRef` in React?', choices: ['A function that creates a ref and automatically attaches it to the first DOM node rendered', 'A higher-order function that lets a component expose a DOM node or imperative handle to its parent via a ref', 'A hook that watches a ref and re-renders when it changes', 'A utility that copies props to a child component'], answer: '1', tags: ['forwardRef', 'refs', 'advanced'], explanation: '`React.forwardRef((props, ref) => <jsx ref={ref} />)` lets a component accept a `ref` from its parent and forward it to a DOM element or child component. Without it, refs on custom components point to `null`. In React 19, refs are passed as a regular prop and `forwardRef` is no longer needed.', docs: 'https://react.dev/reference/react/forwardRef' } },

      { id: 'c3100001-0000-4000-8001-000000000033', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 32, data: { question: 'What is `useImperativeHandle`?', choices: ['A hook that gives a component imperative control over its own animation lifecycle', 'A hook used with forwardRef to customize the value exposed on a ref to a parent component', 'A hook that replaces useRef for accessing DOM nodes', 'A hook that subscribes to imperative browser APIs like IntersectionObserver'], answer: '1', tags: ['useImperativeHandle', 'refs', 'advanced'], explanation: '`useImperativeHandle(ref, () => ({ focus, reset }), deps)` customizes the value seen by the parent through a forwarded ref. Instead of exposing the entire DOM node, you expose only specific methods. This is useful for component libraries where you want to provide a controlled imperative API (e.g., `inputRef.current.focus()`).', docs: 'https://react.dev/reference/react/useImperativeHandle' } },

      { id: 'c3100001-0000-4000-8001-000000000034', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 33, data: { question: 'What is hydration in React?', choices: ['A process of adding water-like animations to a UI', 'The process where React attaches event listeners and makes a server-rendered HTML page interactive without re-generating the DOM', 'A way to persist state between page navigations', 'A technique for loading data before a component mounts'], answer: '1', tags: ['hydration', 'ssr', 'performance'], explanation: 'Hydration is the client-side process following SSR (Server-Side Rendering). The server sends fully-rendered HTML to the browser for fast initial paint. React then "hydrates" that HTML by traversing the DOM and attaching event listeners — making the page interactive without discarding and rebuilding the DOM nodes. React 18 introduced selective/partial hydration for streaming SSR.', docs: 'https://react.dev/reference/react-dom/client/hydrateRoot' } },

      { id: 'c3100001-0000-4000-8001-000000000035', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 34, data: { question: 'What is `useTransition` in React?', choices: ['A hook that animates state changes using CSS transitions', 'A hook that lets you mark a state update as non-urgent so it can be interrupted by higher-priority updates', 'A hook that wraps async functions to auto-show a loading spinner', 'A hook from React Router for route transitions'], answer: '1', tags: ['useTransition', 'concurrency', 'performance'], explanation: '`const [isPending, startTransition] = useTransition()` marks a state update as a non-urgent "transition". React can interrupt it to process urgent updates (like typing). `isPending` is `true` while the transition is in progress. This keeps the UI responsive during expensive re-renders (e.g., filtering a large list) without showing a full loading state.', docs: 'https://react.dev/reference/react/useTransition' } },

      { id: 'c3100001-0000-4000-8001-000000000036', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 35, data: { question: 'What is `useDeferredValue` in React?', choices: ['A hook that debounces a state value by a fixed timeout', 'A hook that lets you defer updating a part of the UI by providing a stale copy of a value that React will update when the browser is idle', 'A hook that returns a Promise for an async value', 'A hook that memoizes a value until a server response arrives'], answer: '1', tags: ['useDeferredValue', 'concurrency', 'performance'], explanation: '`useDeferredValue(value)` returns a "deferred" copy of the value that lags behind the latest one during concurrent rendering. React renders with the old value first (to keep the UI interactive), then re-renders with the new value when capacity allows. It is useful for deferring expensive child renders (e.g., a filtered search results list) while the input stays snappy.', docs: 'https://react.dev/reference/react/useDeferredValue' } },

      { id: 'c3100001-0000-4000-8001-000000000037', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 36, data: { question: 'What is `useActionState` in React 19?', choices: ['A hook for managing Redux action creators', 'A hook that manages state from a form action function, handling pending state and the returned result automatically', 'A hook that tracks which Redux actions have been dispatched', 'A hook that replaces useReducer with server-side state'], answer: '1', tags: ['useActionState', 'react-19', 'forms'], explanation: '`useActionState(actionFn, initialState)` (React 19) takes an async action function and returns `[state, dispatch, isPending]`. When `dispatch` is called (e.g., from a form), React calls `actionFn(prevState, formData)`, sets `isPending` to `true` during execution, and updates `state` with the resolved value. It replaces the older `useFormState` from react-dom.', docs: 'https://react.dev/reference/react/useActionState' } },

      { id: 'c3100001-0000-4000-8001-000000000038', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 37, data: { question: 'What is `useOptimistic` in React 19?', choices: ['A hook that automatically retries failed network requests', 'A hook that lets you show an optimistic (predicted) state immediately while an async operation is in progress, then reverts if it fails', 'A hook that prefetches data before a component mounts', 'A hook that replaces useMemo with automatic optimization'], answer: '1', tags: ['useOptimistic', 'react-19', 'async'], explanation: '`useOptimistic(state, updateFn)` returns `[optimisticState, addOptimistic]`. When `addOptimistic(optimisticValue)` is called, `optimisticState` immediately reflects the update via `updateFn`. Once the underlying async action settles, `optimisticState` reverts to the real `state`. This creates instant, non-jarring feedback for server mutations (e.g., likes, sends).', docs: 'https://react.dev/reference/react/useOptimistic' } },

      { id: 'c3100001-0000-4000-8001-000000000039', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 38, data: { question: 'What is the `use()` hook in React 19?', choices: ['A replacement for all existing hooks', 'A hook that can read the value of a Promise or Context inside a component, integrating with Suspense and error boundaries', 'A hook that creates a new React context', 'A hook that lazy-loads a module on demand'], answer: '1', tags: ['use', 'react-19', 'async', 'suspense'], explanation: '`use(resource)` is a new React 19 hook that can unwrap a Promise or read a Context anywhere in a component — including inside loops and conditionals (unlike other hooks). If the Promise is pending, the component suspends (showing the nearest `<Suspense>` fallback). If it rejects, the nearest error boundary catches it.', docs: 'https://react.dev/reference/react/use' } },

      { id: 'c3100001-0000-4000-8001-000000000040', moduleId: 'c3100000-0000-4000-8000-000000000001', type: 'single', difficulty: 'hard', sortOrder: 39, data: { question: 'What is `useFormStatus` in React 19?', choices: ['A hook that validates all form fields and returns errors', 'A hook used inside a form\'s child component to read the pending state and data of the parent form\'s submission', 'A hook that tracks how many times a form has been submitted', 'A hook that replaces controlled inputs with automatic form state'], answer: '1', tags: ['useFormStatus', 'react-19', 'forms'], explanation: '`useFormStatus()` (from `react-dom`) must be called inside a component rendered inside a `<form>`. It returns `{ pending, data, method, action }` reflecting the parent form\'s current submission state. The `pending` boolean is `true` while the form action is executing. This lets child components like submit buttons react to form state without prop drilling.', docs: 'https://react.dev/reference/react-dom/hooks/useFormStatus' } },

    ];

    for (const q of questions) {
      await queryRunner.query(
        `INSERT INTO "qcm_question" ("id", "moduleId", "type", "difficulty", "sortOrder", "data")
         VALUES ($1, $2, $3, $4, $5, $6)
         ON CONFLICT ("id") DO NOTHING`,
        [q.id, q.moduleId, q.type, q.difficulty, q.sortOrder, JSON.stringify(q.data)]
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const ids = Array.from({ length: 40 }, (_, i) =>
      `c3100001-0000-4000-8001-${String(i + 1).padStart(12, '0')}`
    );
    await queryRunner.query(
      `DELETE FROM "qcm_question" WHERE "id" = ANY($1)`,
      [ids]
    );
  }
}
