import fs from 'fs';
import path from 'path';
import { spawn } from 'child_process';
import { fileURLToPath } from 'url';

// ─── colors ─────────────────────────────────────────────────────────────────
const c = {
  reset:  '\x1b[0m',
  bold:   '\x1b[1m',
  dim:    '\x1b[2m',
  cyan:   '\x1b[36m',
  green:  '\x1b[32m',
  yellow: '\x1b[33m',
  blue:   '\x1b[34m',
  magenta:'\x1b[35m',
  gray:   '\x1b[90m',
};
const clr = (color, text) => `${color}${text}${c.reset}`;

const STORYBOOK_NATIVE_DIR = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '../../storybook-native',
);

const STORYBOOK_DIR = path.join(STORYBOOK_NATIVE_DIR, '.storybook');
const CONFIGS_DIR = path.join(STORYBOOK_NATIVE_DIR, 'configs');

// ─── helpers ────────────────────────────────────────────────────────────────

/** Turn a package name like @mas/rn-ui into a safe folder name: mas__rn-ui */
function sanitizeName(name) {
  return name.replace(/^@/, '').replace(/\//g, '__');
}

/** Return the per-lib config dir, creating it if it doesn't exist. */
function getConfigDir(libName) {
  const dir = path.join(CONFIGS_DIR, sanitizeName(libName));
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
    console.log(`  📁 ${clr(c.blue, 'created')} config folder for ${clr(c.cyan, libName)}`);
  }
  return dir;
}

/**
 * Write content to filePath only when it actually differs.
 * Returns true if the file was written, false if it was already up-to-date.
 */
function writeIfChanged(filePath, content) {
  if (fs.existsSync(filePath) && fs.readFileSync(filePath, 'utf-8') === content) {
    return false;
  }
  fs.writeFileSync(filePath, content, 'utf-8');
  return true;
}

/** Copy a file to dst only when content differs. Returns true if written. */
function copyIfChanged(src, dst) {
  if (!fs.existsSync(src)) return false;
  const content = fs.readFileSync(src, 'utf-8');
  return writeIfChanged(dst, content);
}

// ─── config generators ──────────────────────────────────────────────────────

function buildMainTs(storiesGlob) {
  return `// AUTO-GENERATED by storybook-launcher — do not edit manually
import type { StorybookConfig } from '@storybook/react-native';

const main: StorybookConfig = {
  stories: ['${storiesGlob}'],
  addons: [
    '@storybook/addon-ondevice-controls',
    '@storybook/addon-ondevice-actions',
  ],
};

export default main;
`;
}

function buildPreviewTsx(libRoot) {
  const previewTsx = path.join(libRoot, '.storybook', 'preview.tsx');
  const previewTs = path.join(libRoot, '.storybook', 'preview.ts');
  const hasPreview = fs.existsSync(previewTsx) || fs.existsSync(previewTs);

  if (hasPreview) {
    const relPath = path
      .relative(STORYBOOK_DIR, path.join(libRoot, '.storybook', 'preview'))
      .replace(/\\/g, '/');
    const importPath = relPath.startsWith('.') ? relPath : `./${relPath}`;
    return `// AUTO-GENERATED by storybook-launcher — do not edit manually
export { default } from '${importPath}';
export * from '${importPath}';
`;
  }

  return `// AUTO-GENERATED by storybook-launcher — do not edit manually
// No .storybook/preview found in the selected lib.
import type { Preview } from '@storybook/react-native';

const preview: Preview = {};

export default preview;
`;
}

// ─── per-lib config management ───────────────────────────────────────────────

/**
 * Ensure the per-lib config folder exists and its files are up-to-date.
 * When main.ts changes, the cached storybook.requires.ts is invalidated.
 * Returns { mainChanged, previewChanged, configDir }.
 */
function syncConfigFolder(target, storiesGlob) {
  const configDir = getConfigDir(target.name);

  const mainContent = buildMainTs(storiesGlob);
  const previewContent = buildPreviewTsx(target.root);

  const mainChanged = writeIfChanged(path.join(configDir, 'main.ts'), mainContent);
  const previewChanged = writeIfChanged(path.join(configDir, 'preview.tsx'), previewContent);

  // Invalidate cached requires when main.ts changes — stories glob changed.
  if (mainChanged) {
    const cachedRequires = path.join(configDir, 'storybook.requires.ts');
    if (fs.existsSync(cachedRequires)) {
      fs.rmSync(cachedRequires);
      console.log(`  🗑️  ${clr(c.yellow, 'invalidated')} cached storybook.requires.ts`);
    }
  }

  if (mainChanged) console.log(`  ✏️  ${clr(c.yellow, 'updated')}  main.ts`);
  if (previewChanged) console.log(`  ✏️  ${clr(c.yellow, 'updated')}  preview.tsx`);
  if (!mainChanged && !previewChanged) console.log(`  ✅ ${clr(c.green, 'config up-to-date')} for ${clr(c.cyan, target.name)}`);

  return { mainChanged, previewChanged, configDir };
}

/**
 * Activate a lib's config by copying its files into .storybook/.
 * Also restores storybook.requires.ts from the per-lib cache if available.
 * Returns { mainActivated, requiresRestored }.
 */
function activateConfig(configDir) {
  const mainActivated = copyIfChanged(
    path.join(configDir, 'main.ts'),
    path.join(STORYBOOK_DIR, 'main.ts'),
  );
  copyIfChanged(
    path.join(configDir, 'preview.tsx'),
    path.join(STORYBOOK_DIR, 'preview.tsx'),
  );

  // Restore cached storybook.requires.ts (may not exist yet on first run for this lib)
  const requiresRestored = copyIfChanged(
    path.join(configDir, 'storybook.requires.ts'),
    path.join(STORYBOOK_DIR, 'storybook.requires.ts'),
  );

  return { mainActivated, requiresRestored };
}

// ─── storybook.requires.ts ───────────────────────────────────────────────────

/**
 * Generate storybook.requires.ts content from a stories glob.
 *
 * The storiesGlob is relative to storybook-native/ (e.g. "../rn-pic-swipe-wipe/app/**").
 * require.context paths must be relative to the output file (.storybook/), so we
 * prepend an extra "../" to shift one level deeper.
 */
function buildStorybookRequires(storiesGlob) {
  const baseDir = storiesGlob.split('/**/')[0]; // dir before "/**/"
  const requireCtxDir = `../${baseDir}`;        // shift relative to .storybook/

  // Standard Metro/webpack importPathMatcher for *.stories.(ts|tsx) files
  const regex = String.raw`/^\.(?:(?:^|[\\/]|(?:(?:(?!(?:^|[\\/])\.).)*?)[\\/])(?!\.)(?=.)[^\\/]*?\.stories\.tsx?)$/`;

  return `/* do not change this file, it is managed by storybook-launcher. */
import { start, updateView, View } from '@storybook/react-native';

import '@storybook/addon-ondevice-controls/register';
import '@storybook/addon-ondevice-actions/register';

const normalizedStories = [
  {
    titlePrefix: '',
    directory: '${requireCtxDir}',
    files: '**/*.stories.?(ts|tsx)',
    importPathMatcher:
      ${regex},
    // @ts-ignore
    req: require.context(
      '${requireCtxDir}',
      true,
      ${regex},
    ),
  },
];

declare global {
  var view: View;
  var STORIES: typeof normalizedStories;
  var STORYBOOK_WEBSOCKET: { host: string; port: number } | undefined;
}

const annotations = [require('./preview'), require('@storybook/react-native/preview')];

globalThis.STORIES = normalizedStories;

// @ts-ignore
module?.hot?.accept?.();

if (!globalThis.view) {
  globalThis.view = start({
    annotations,
    storyEntries: normalizedStories,
  });
} else {
  updateView(globalThis.view, annotations, normalizedStories);
}

export const view: View = globalThis.view;
`;
}

function generateStorybookRequires(storiesGlob) {
  console.log(`  ⚙️  ${clr(c.magenta, 'generating')} storybook.requires.ts...`);
  const content = buildStorybookRequires(storiesGlob);
  fs.writeFileSync(path.join(STORYBOOK_DIR, 'storybook.requires.ts'), content, 'utf-8');
}

// ─── main export ─────────────────────────────────────────────────────────────

/**
 * Derive the stories glob from the actual story file paths.
 * If all stories share the same top-level dir (e.g. "src" or "app"), use that.
 * Otherwise fall back to a root-level glob.
 */
function buildStoriesGlob(relRoot, targetRoot, stories) {
  const topDirs = new Set(
    stories.map((s) => path.relative(targetRoot, s).split(path.sep)[0]),
  );
  const [firstDir] = topDirs;
  const subGlob = topDirs.size === 1 ? `${firstDir}/**` : '**';
  return `${relRoot}/${subGlob}/*.stories.?(ts|tsx)`;
}

export async function runReactNative(target, _monorepoRoot) {
  const relRoot = path.relative(STORYBOOK_NATIVE_DIR, target.root).replace(/\\/g, '/');
  const storiesGlob = buildStoriesGlob(relRoot, target.root, target.stories ?? []);

  console.log(`\n📚 ${clr(c.bold + c.cyan, 'Configuring storybook-native')} for ${clr(c.bold + c.magenta, target.name)}...`);
  console.log(`  🔍 ${clr(c.gray, 'glob   ')} ${clr(c.blue, storiesGlob)}`);
  const storyList = target.stories ?? [];
  console.log(`  📄 ${clr(c.gray, 'stories')} ${clr(c.green, `${storyList.length} found`)}`);
  for (const s of storyList) {
    console.log(`        ${clr(c.dim, path.relative(STORYBOOK_NATIVE_DIR, s).replace(/\\/g, '/'))}`);
  }

  // 1. Ensure per-lib config folder exists and files are current.
  //    Invalidates cached requires if main.ts changed.
  const { configDir } = syncConfigFolder(target, storiesGlob);

  // 2. Activate the config into .storybook/ (only writes if content changed).
  //    Also restores storybook.requires.ts from per-lib cache.
  const { mainActivated, requiresRestored } = activateConfig(configDir);

  // 3. Regenerate storybook.requires.ts if:
  //    - main.ts just changed (new glob), OR
  //    - no cached requires existed for this lib (first time selecting it)
  const requiresPath = path.join(STORYBOOK_DIR, 'storybook.requires.ts');
  const needsRegen = mainActivated || !requiresRestored;
  if (needsRegen) {
    generateStorybookRequires(storiesGlob);
    // Save the freshly-generated file into the per-lib cache for next time.
    if (fs.existsSync(requiresPath)) {
      fs.copyFileSync(requiresPath, path.join(configDir, 'storybook.requires.ts'));
      console.log(`  💾 ${clr(c.green, 'cached')} storybook.requires.ts for next run`);
    }
  } else {
    console.log(`  ♻️  ${clr(c.green, 'restored')} storybook.requires.ts from cache`);
  }

  console.log(`\n🚀 ${clr(c.bold + c.green, 'Launching')} Expo Storybook for ${clr(c.bold + c.magenta, target.name)}...\n`);

  const child = spawn('npx', ['expo', 'start', '-c'], {
    cwd: STORYBOOK_NATIVE_DIR,
    stdio: 'inherit',
    shell: true,
  });

  child.on('exit', (code) => process.exit(code ?? 0));
}
