import nx from '@nx/eslint-plugin';
import baseConfig from '../../eslint.config.mjs';

export default [
  ...baseConfig,
  ...nx.configs['flat/react'],
  {
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      'react/self-closing-comp': 'warn',
      'react/no-unstable-nested-components': 'warn',
    },
  },
  {
    // Auto-generated by storybook-launcher — cross-project relative imports are intentional
    ignores: ['**/.storybook/preview.tsx', '**/configs/**/preview.tsx', '**/storybook.requires.ts'],
  },
];
